-- ============================================================================
-- EvaluaOS — Fase 1: Prontuário & Prescrição (núcleo)
-- Branch: Nutricionista
-- ============================================================================
--
-- ANTES DE RODAR ESTA MIGRATION, rode o diagnóstico abaixo no SQL Editor do
-- Supabase e guarde o resultado — ele não bloqueia esta migration, mas diz
-- se as tabelas atuais (pacientes/avaliacoes/dados_calculados) já têm RLS
-- ativo ou se o isolamento entre nutricionistas hoje depende só do filtro
-- .eq('id_avaliador', ...) no client:
--
--   select tablename, rowsecurity
--   from pg_tables
--   where schemaname = 'public'
--     and tablename in ('pacientes', 'avaliacoes', 'dados_calculados', 'avaliadores', 'configuracoes_avaliador');
--
--   select tablename, policyname, cmd, qual
--   from pg_policies
--   where schemaname = 'public';
--
-- Esta migration cobre só o núcleo que a Fase 2 (Prontuário/Linha do Tempo)
-- e o início da Fase 3 (Prescrição) precisam. Anamnese, Exames, Bioimpedância,
-- Gestante/Pediátrico, Fotos e Grupos de Alimentos ficam para quando a tela
-- de cada um for construída — schema não cresce antes da feature existir.
--
-- Toda tabela nova carrega id_avaliador denormalizado (mesmo em tabelas que
-- penduram de id_paciente/id_plano) para que a política de RLS seja uma
-- comparação direta (id_avaliador = auth.uid()) em vez de subquery — mais
-- barato pro Postgres avaliar em toda leitura, relevante no plano gratuito.
--
-- TIPOS: confirmado via information_schema que este projeto usa bigint
-- identity como PK em todas as tabelas existentes (pacientes.id,
-- avaliacoes.id, dados_calculados.id, avaliadores.id) — só a ligação com o
-- nutricionista é uuid (pacientes.id_avaliador / avaliadores.auth_id, que
-- apontam pra auth.users.id). As tabelas novas seguem exatamente esse
-- padrão: PK bigint identity, id_avaliador uuid.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. PRONTUÁRIOS — histórico clínico de consultas
-- ----------------------------------------------------------------------------
create table if not exists public.prontuarios (
  id                    bigint generated by default as identity primary key,
  id_paciente           bigint not null references public.pacientes(id) on delete cascade,
  id_avaliador          uuid not null references auth.users(id) on delete cascade,
  data_consulta         date not null default current_date,
  queixa_principal      text,
  historico_doencas     text,
  historico_familiar    text,
  medicamentos          text,
  suplementos_em_uso    text,
  observacoes           text,
  created_at            timestamptz not null default now()
);

create index if not exists idx_prontuarios_paciente on public.prontuarios(id_paciente);
create index if not exists idx_prontuarios_avaliador on public.prontuarios(id_avaliador);

alter table public.prontuarios enable row level security;

create policy "prontuarios_isolamento_avaliador" on public.prontuarios
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());


-- ----------------------------------------------------------------------------
-- 2. LINHA DO TEMPO — agregação cronológica de eventos do paciente
-- ----------------------------------------------------------------------------
-- referencia_id é polimórfico (aponta pra prontuarios/avaliacoes/planos_
-- alimentares dependendo de tipo_evento) — sem FK real por isso, só índice.
-- Funciona porque as 3 tabelas-alvo usam bigint identity como PK.
create table if not exists public.linha_do_tempo (
  id                bigint generated by default as identity primary key,
  id_paciente       bigint not null references public.pacientes(id) on delete cascade,
  id_avaliador      uuid not null references auth.users(id) on delete cascade,
  tipo_evento       text not null check (tipo_evento in ('consulta', 'avaliacao', 'plano_alimentar')),
  referencia_id     bigint not null,
  titulo            text not null,
  created_at        timestamptz not null default now()
);

create index if not exists idx_linha_tempo_paciente_data on public.linha_do_tempo(id_paciente, created_at desc);
create index if not exists idx_linha_tempo_avaliador on public.linha_do_tempo(id_avaliador);

alter table public.linha_do_tempo enable row level security;

create policy "linha_tempo_isolamento_avaliador" on public.linha_do_tempo
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());


-- ----------------------------------------------------------------------------
-- 3. TABELA DE ALIMENTOS — acervo ÚNICO e GLOBAL (não replicado por avaliador)
-- ----------------------------------------------------------------------------
-- id_avaliador nulo = alimento oficial (TACO/IBGE/USDA), visível a todos.
-- id_avaliador preenchido = alimento customizado, visível só ao dono.
-- Isso evita multiplicar ~600-2000 linhas de TACO/IBGE por N nutricionistas
-- no plano gratuito do Supabase — é o maior risco de espaço do módulo.
create table if not exists public.tabela_alimentos (
  id                      bigint generated by default as identity primary key,
  id_avaliador            uuid references auth.users(id) on delete cascade,
  nome                    text not null,
  categoria               text,
  fonte                   text not null default 'Customizado' check (fonte in ('TACO', 'IBGE', 'USDA', 'Customizado')),
  unidade_padrao          text default 'g',
  medida_caseira_desc     text,
  medida_caseira_g        numeric(8,2),
  -- valores por 100g:
  energia_kcal            numeric(10,3),
  proteina_g              numeric(10,3),
  lipidios_g              numeric(10,3),
  carboidrato_g           numeric(10,3),
  fibra_g                 numeric(10,3),
  acucares_g              numeric(10,3),
  gorduras_saturadas_g    numeric(10,3),
  gorduras_trans_g        numeric(10,3),
  colesterol_mg           numeric(10,3),
  calcio_mg               numeric(10,3),
  ferro_mg                numeric(10,3),
  sodio_mg                numeric(10,3),
  zinco_mg                numeric(10,3),
  vitamina_a_mcg          numeric(10,3),
  vitamina_c_mg           numeric(10,3),
  vitamina_d_mcg          numeric(10,3),
  tiamina_mg              numeric(10,3),
  riboflavina_mg          numeric(10,3),
  niacina_mg              numeric(10,3),
  vitamina_b6_mg          numeric(10,3),
  vitamina_b12_mcg        numeric(10,3),
  created_at              timestamptz not null default now()
);

create index if not exists idx_alimentos_avaliador on public.tabela_alimentos(id_avaliador);
create index if not exists idx_alimentos_nome on public.tabela_alimentos(lower(nome));
-- Se a busca precisar de "contém" (ilike '%termo%') em vez de só prefixo,
-- trocar pelo índice trigram abaixo (precisa da extensão pg_trgm, já vem
-- habilitada por padrão em projetos Supabase):
--   create extension if not exists pg_trgm;
--   create index idx_alimentos_nome_trgm on public.tabela_alimentos using gin (nome gin_trgm_ops);

alter table public.tabela_alimentos enable row level security;

create policy "alimentos_leitura_oficial_ou_proprio" on public.tabela_alimentos
  for select using (id_avaliador is null or id_avaliador = auth.uid());

create policy "alimentos_escrita_somente_proprio" on public.tabela_alimentos
  for insert with check (id_avaliador = auth.uid());

create policy "alimentos_update_somente_proprio" on public.tabela_alimentos
  for update using (id_avaliador = auth.uid()) with check (id_avaliador = auth.uid());

create policy "alimentos_delete_somente_proprio" on public.tabela_alimentos
  for delete using (id_avaliador = auth.uid());


-- ----------------------------------------------------------------------------
-- 4. PLANOS ALIMENTARES — prescrição
-- ----------------------------------------------------------------------------
create table if not exists public.planos_alimentares (
  id                        bigint generated by default as identity primary key,
  id_paciente               bigint not null references public.pacientes(id) on delete cascade,
  id_avaliador              uuid not null references auth.users(id) on delete cascade,
  id_avaliacao              bigint references public.avaliacoes(id) on delete set null,
  titulo                    text not null default 'Plano Alimentar',
  vet_target                numeric(10,2),
  proteina_target_g_kg      numeric(6,2),
  carbo_target_g_kg         numeric(6,2),
  lipidio_target_g_kg       numeric(6,2),
  ativo                     boolean not null default true,
  created_at                timestamptz not null default now()
);

create index if not exists idx_planos_paciente on public.planos_alimentares(id_paciente);
create index if not exists idx_planos_avaliador on public.planos_alimentares(id_avaliador);

-- No máximo um plano ativo por paciente por vez — evita o app deixar dois
-- planos "ativo=true" coexistindo por engano.
create unique index if not exists idx_planos_um_ativo_por_paciente
  on public.planos_alimentares(id_paciente)
  where ativo = true;

alter table public.planos_alimentares enable row level security;

create policy "planos_isolamento_avaliador" on public.planos_alimentares
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());


-- ----------------------------------------------------------------------------
-- 5. REFEIÇÕES PRESCRITAS
-- ----------------------------------------------------------------------------
create table if not exists public.refeicoes_prescritas (
  id              bigint generated by default as identity primary key,
  id_plano        bigint not null references public.planos_alimentares(id) on delete cascade,
  horario         time,
  nome_refeicao   text not null default 'Refeição',
  ordem           integer not null default 0
);

create index if not exists idx_refeicoes_plano on public.refeicoes_prescritas(id_plano);

alter table public.refeicoes_prescritas enable row level security;

-- Sem id_avaliador direto aqui — a política verifica dono via o plano pai.
-- É a única subquery de RLS desta fase (tabela filha de granularidade fina,
-- sem necessidade de duplicar id_avaliador em mais um nível).
create policy "refeicoes_isolamento_via_plano" on public.refeicoes_prescritas
  for all using (
    exists (
      select 1 from public.planos_alimentares p
      where p.id = refeicoes_prescritas.id_plano
        and p.id_avaliador = auth.uid()
    )
  );


-- ----------------------------------------------------------------------------
-- 6. ITENS DA REFEIÇÃO
-- ----------------------------------------------------------------------------
create table if not exists public.itens_refeicao (
  id                      bigint generated by default as identity primary key,
  id_refeicao             bigint not null references public.refeicoes_prescritas(id) on delete cascade,
  id_alimento             bigint not null references public.tabela_alimentos(id) on delete restrict,
  quantidade_g            numeric(8,2) not null,
  opcao_numero            integer not null default 1,
  ignorar_nos_calculos    boolean not null default false
);

create index if not exists idx_itens_refeicao_refeicao on public.itens_refeicao(id_refeicao);
create index if not exists idx_itens_refeicao_alimento on public.itens_refeicao(id_alimento);

alter table public.itens_refeicao enable row level security;

create policy "itens_isolamento_via_refeicao" on public.itens_refeicao
  for all using (
    exists (
      select 1 from public.refeicoes_prescritas r
      join public.planos_alimentares p on p.id = r.id_plano
      where r.id = itens_refeicao.id_refeicao
        and p.id_avaliador = auth.uid()
    )
  );
