-- Fase 3b — Substitutos de alimento, nome customizado por item e faixa de
-- referência (min/max) das metas de macro.
--
-- Não mexe em política de RLS de tabelas existentes, só acrescenta.


-- ----------------------------------------------------------------------------
-- 1. SUBSTITUTOS DO ITEM — alternativas para um item específico de uma
-- refeição prescrita (diferente de "Opção" em itens_refeicao, que é uma
-- alternativa pra REFEIÇÃO inteira; substituto é alternativa pra UM item).
-- ----------------------------------------------------------------------------
create table if not exists public.substitutos_item (
  id                  bigint generated by default as identity primary key,
  id_item_original    bigint not null references public.itens_refeicao(id) on delete cascade,
  id_alimento         bigint not null references public.tabela_alimentos(id) on delete restrict,
  quantidade_g        numeric(8,2) not null,
  ordem               integer not null default 0
);

create index if not exists idx_substitutos_item_original on public.substitutos_item(id_item_original);
create index if not exists idx_substitutos_item_alimento on public.substitutos_item(id_alimento);

alter table public.substitutos_item enable row level security;

-- Sem id_avaliador direto — dono verificado subindo item -> refeição -> plano,
-- mesmo padrão já usado em itens_refeicao/refeicoes_prescritas.
-- drop+create (em vez de "if not exists", que não existe pra policy) deixa
-- o arquivo seguro pra rodar de novo se uma tentativa anterior parou no meio.
drop policy if exists "substitutos_isolamento_via_item" on public.substitutos_item;

create policy "substitutos_isolamento_via_item" on public.substitutos_item
  for all using (
    exists (
      select 1
      from public.itens_refeicao i
      join public.refeicoes_prescritas r on r.id = i.id_refeicao
      join public.planos_alimentares p on p.id = r.id_plano
      where i.id = substitutos_item.id_item_original
        and p.id_avaliador = auth.uid()
    )
  );


-- ----------------------------------------------------------------------------
-- 2. NOME CUSTOMIZADO POR ITEM — sobrescreve tabela_alimentos.nome só na
-- exibição daquele item específico (ex: "Ovo Cru" -> "Ovo" só nesta
-- refeição/plano). Null = usa o nome do alimento normalmente.
-- ----------------------------------------------------------------------------
alter table public.itens_refeicao
  add column if not exists nome_customizado text;


-- ----------------------------------------------------------------------------
-- 3. FAIXA DE REFERÊNCIA (g/kg) — meta/prescrição em formato de intervalo
-- (ex: "0,8 a 2,0 g/kg"), puramente informativa: exibida como texto de apoio
-- junto do macro, não participa de nenhum cálculo nem gera alerta.
-- ----------------------------------------------------------------------------
alter table public.planos_alimentares
  add column if not exists proteina_target_g_kg_min numeric(6,2),
  add column if not exists proteina_target_g_kg_max numeric(6,2),
  add column if not exists carbo_target_g_kg_min    numeric(6,2),
  add column if not exists carbo_target_g_kg_max    numeric(6,2),
  add column if not exists lipidio_target_g_kg_min  numeric(6,2),
  add column if not exists lipidio_target_g_kg_max  numeric(6,2);
