-- Fase 4 — Anamnese: um registro de texto livre por paciente (sem IA por
-- enquanto — fica registrado como possível evolução futura, mas custo/
-- complexidade não compensam agora).
--
-- Diferente de prontuarios (histórico de CONSULTAS, um registro por data),
-- anamnese aqui é um documento único por paciente que o avaliador edita e
-- reescreve ao longo do tempo — por isso id_paciente é UNIQUE (upsert).

create table if not exists public.anamneses (
  id            bigint generated by default as identity primary key,
  id_paciente   bigint not null references public.pacientes(id) on delete cascade,
  id_avaliador  uuid not null references auth.users(id) on delete cascade,
  conteudo      text,
  updated_at    timestamptz not null default now()
);

create unique index if not exists idx_anamneses_paciente_unico on public.anamneses(id_paciente);
create index if not exists idx_anamneses_avaliador on public.anamneses(id_avaliador);

alter table public.anamneses enable row level security;

drop policy if exists "anamneses_isolamento_avaliador" on public.anamneses;

create policy "anamneses_isolamento_avaliador" on public.anamneses
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());
