-- Orientações Nutricionais — um ou mais documentos de texto livre por
-- paciente (título + texto), pensados pra depois virarem aba do paciente ou
-- PDF (fora de escopo por enquanto — só o builder aqui).
--
-- Separado em duas tabelas: os documentos do paciente (orientacoes_
-- nutricionais) e os modelos reutilizáveis do avaliador (modelos_
-- orientacoes) — usar um modelo só PRÉ-PREENCHE um documento novo, não
-- mantém vínculo com o modelo original (editar um não afeta o outro).

create table if not exists public.orientacoes_nutricionais (
  id            bigint generated by default as identity primary key,
  id_paciente   bigint not null references public.pacientes(id) on delete cascade,
  id_avaliador  uuid not null references auth.users(id) on delete cascade,
  titulo        text not null default 'Orientação',
  conteudo      text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists idx_orientacoes_paciente on public.orientacoes_nutricionais(id_paciente);
create index if not exists idx_orientacoes_avaliador on public.orientacoes_nutricionais(id_avaliador);

alter table public.orientacoes_nutricionais enable row level security;

drop policy if exists "orientacoes_isolamento_avaliador" on public.orientacoes_nutricionais;
create policy "orientacoes_isolamento_avaliador" on public.orientacoes_nutricionais
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());


create table if not exists public.modelos_orientacoes (
  id            bigint generated by default as identity primary key,
  id_avaliador  uuid not null references auth.users(id) on delete cascade,
  titulo        text not null default 'Modelo',
  conteudo      text,
  created_at    timestamptz not null default now()
);

create index if not exists idx_modelos_orientacoes_avaliador on public.modelos_orientacoes(id_avaliador);

alter table public.modelos_orientacoes enable row level security;

drop policy if exists "modelos_orientacoes_isolamento_avaliador" on public.modelos_orientacoes;
create policy "modelos_orientacoes_isolamento_avaliador" on public.modelos_orientacoes
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());
