-- Modelos reutilizáveis de Anamnese (por avaliador) — mesmo padrão já usado
-- em modelos_orientacoes (migration 0009): usar um modelo só PRÉ-PREENCHE
-- uma anamnese nova, sem manter vínculo com o modelo original.

create table if not exists public.modelos_anamneses (
  id            bigint generated by default as identity primary key,
  id_avaliador  uuid not null references auth.users(id) on delete cascade,
  titulo        text not null default 'Modelo',
  conteudo      text,
  created_at    timestamptz not null default now()
);

create index if not exists idx_modelos_anamneses_avaliador on public.modelos_anamneses(id_avaliador);

alter table public.modelos_anamneses enable row level security;

drop policy if exists "modelos_anamneses_isolamento_avaliador" on public.modelos_anamneses;
create policy "modelos_anamneses_isolamento_avaliador" on public.modelos_anamneses
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());
