-- Listas de Recomendações — mesmo padrão de Orientações Nutricionais
-- (migration 0009): um ou mais documentos de texto por paciente, com
-- modelos reutilizáveis por avaliador. Tabela separada (não reaproveita
-- orientacoes_nutricionais) porque são conceitos distintos no menu do
-- paciente, e podem evoluir de formas diferentes mais pra frente.

create table if not exists public.listas_recomendacoes (
  id            bigint generated by default as identity primary key,
  id_paciente   bigint not null references public.pacientes(id) on delete cascade,
  id_avaliador  uuid not null references auth.users(id) on delete cascade,
  titulo        text not null default 'Lista',
  conteudo      text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists idx_listas_recomendacoes_paciente on public.listas_recomendacoes(id_paciente);
create index if not exists idx_listas_recomendacoes_avaliador on public.listas_recomendacoes(id_avaliador);

alter table public.listas_recomendacoes enable row level security;

drop policy if exists "listas_recomendacoes_isolamento_avaliador" on public.listas_recomendacoes;
create policy "listas_recomendacoes_isolamento_avaliador" on public.listas_recomendacoes
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());


create table if not exists public.modelos_listas_recomendacoes (
  id            bigint generated by default as identity primary key,
  id_avaliador  uuid not null references auth.users(id) on delete cascade,
  titulo        text not null default 'Modelo',
  conteudo      text,
  created_at    timestamptz not null default now()
);

create index if not exists idx_modelos_listas_recomendacoes_avaliador on public.modelos_listas_recomendacoes(id_avaliador);

alter table public.modelos_listas_recomendacoes enable row level security;

drop policy if exists "modelos_listas_recomendacoes_isolamento_avaliador" on public.modelos_listas_recomendacoes;
create policy "modelos_listas_recomendacoes_isolamento_avaliador" on public.modelos_listas_recomendacoes
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());
