-- Votação de prioridade no Roadmap (like/dislike por item, 1 voto por
-- avaliador por item — reforçado pelo índice único abaixo, que o upsert do
-- app usa como onConflict). Leitura liberada pra todo autenticado porque o
-- app precisa somar o voto de TODOS os avaliadores pra ordenar a tela por
-- pontuação (não é dado sensível, só preferência sobre funcionalidades).

create table if not exists public.roadmap_votos (
  id            bigint generated by default as identity primary key,
  item_chave    text not null,
  id_avaliador  uuid not null references auth.users(id) on delete cascade,
  voto          smallint not null check (voto in (1, -1)),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create unique index if not exists idx_roadmap_votos_item_avaliador
  on public.roadmap_votos(item_chave, id_avaliador);
create index if not exists idx_roadmap_votos_item on public.roadmap_votos(item_chave);

alter table public.roadmap_votos enable row level security;

drop policy if exists "roadmap_votos_leitura_agregada" on public.roadmap_votos;
create policy "roadmap_votos_leitura_agregada" on public.roadmap_votos
  for select using (auth.uid() is not null);

drop policy if exists "roadmap_votos_escrita_propria" on public.roadmap_votos;
create policy "roadmap_votos_escrita_propria" on public.roadmap_votos
  for insert with check (id_avaliador = auth.uid());

drop policy if exists "roadmap_votos_update_propria" on public.roadmap_votos;
create policy "roadmap_votos_update_propria" on public.roadmap_votos
  for update using (id_avaliador = auth.uid()) with check (id_avaliador = auth.uid());

drop policy if exists "roadmap_votos_delete_propria" on public.roadmap_votos;
create policy "roadmap_votos_delete_propria" on public.roadmap_votos
  for delete using (id_avaliador = auth.uid());
