-- Modelos reutilizáveis de Refeição e de Plano Alimentar (mesmo espírito de
-- modelos_orientacoes/modelos_anamneses — usar um modelo só PRÉ-PREENCHE uma
-- refeição/plano novo, sem manter vínculo com o modelo original). Diferente
-- daqueles dois, aqui o "conteúdo" é estruturado (itens de alimento, não
-- texto livre), então cada modelo precisa de tabela(s) filha própria, no
-- mesmo padrão de refeicoes_prescritas/itens_refeicao (RLS via join até o
-- dono, sem duplicar id_avaliador em cada nível).


-- ----------------------------------------------------------------------------
-- 1. MODELO DE REFEIÇÃO — uma refeição (com itens, inclusive múltiplas
-- opções de substituição) salva pra reusar em qualquer paciente.
-- ----------------------------------------------------------------------------
create table if not exists public.modelos_refeicoes (
  id            bigint generated by default as identity primary key,
  id_avaliador  uuid not null references auth.users(id) on delete cascade,
  titulo        text not null default 'Modelo',
  created_at    timestamptz not null default now()
);

create index if not exists idx_modelos_refeicoes_avaliador on public.modelos_refeicoes(id_avaliador);

alter table public.modelos_refeicoes enable row level security;

drop policy if exists "modelos_refeicoes_isolamento_avaliador" on public.modelos_refeicoes;
create policy "modelos_refeicoes_isolamento_avaliador" on public.modelos_refeicoes
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());


create table if not exists public.modelos_refeicoes_itens (
  id                  bigint generated by default as identity primary key,
  id_modelo           bigint not null references public.modelos_refeicoes(id) on delete cascade,
  id_alimento         bigint not null references public.tabela_alimentos(id) on delete restrict,
  quantidade_g        numeric(8,2) not null,
  opcao_numero        integer not null default 1,
  nome_customizado    text,
  unidade_medida      text,
  quantidade_medida   numeric(8,2)
);

create index if not exists idx_modelos_refeicoes_itens_modelo on public.modelos_refeicoes_itens(id_modelo);
create index if not exists idx_modelos_refeicoes_itens_alimento on public.modelos_refeicoes_itens(id_alimento);

alter table public.modelos_refeicoes_itens enable row level security;

drop policy if exists "modelos_refeicoes_itens_isolamento_via_modelo" on public.modelos_refeicoes_itens;
create policy "modelos_refeicoes_itens_isolamento_via_modelo" on public.modelos_refeicoes_itens
  for all using (
    exists (
      select 1 from public.modelos_refeicoes m
      where m.id = modelos_refeicoes_itens.id_modelo
        and m.id_avaliador = auth.uid()
    )
  );


-- ----------------------------------------------------------------------------
-- 2. MODELO DE PLANO ALIMENTAR — um plano inteiro (metas + todas as
-- refeições e itens dele) salvo pra reusar como ponto de partida em
-- qualquer paciente.
-- ----------------------------------------------------------------------------
create table if not exists public.modelos_planos (
  id                        bigint generated by default as identity primary key,
  id_avaliador              uuid not null references auth.users(id) on delete cascade,
  titulo                    text not null default 'Modelo',
  vet_target                numeric(10,2),
  proteina_target_g_kg      numeric(6,2),
  carbo_target_g_kg         numeric(6,2),
  lipidio_target_g_kg       numeric(6,2),
  proteina_target_pct       numeric(6,2),
  carbo_target_pct          numeric(6,2),
  lipidio_target_pct        numeric(6,2),
  created_at                timestamptz not null default now()
);

create index if not exists idx_modelos_planos_avaliador on public.modelos_planos(id_avaliador);

alter table public.modelos_planos enable row level security;

drop policy if exists "modelos_planos_isolamento_avaliador" on public.modelos_planos;
create policy "modelos_planos_isolamento_avaliador" on public.modelos_planos
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());


create table if not exists public.modelos_planos_refeicoes (
  id                bigint generated by default as identity primary key,
  id_modelo_plano   bigint not null references public.modelos_planos(id) on delete cascade,
  horario           time,
  nome_refeicao     text not null default 'Refeição',
  ordem             integer not null default 0
);

create index if not exists idx_modelos_planos_refeicoes_plano on public.modelos_planos_refeicoes(id_modelo_plano);

alter table public.modelos_planos_refeicoes enable row level security;

drop policy if exists "modelos_planos_refeicoes_isolamento_via_plano" on public.modelos_planos_refeicoes;
create policy "modelos_planos_refeicoes_isolamento_via_plano" on public.modelos_planos_refeicoes
  for all using (
    exists (
      select 1 from public.modelos_planos p
      where p.id = modelos_planos_refeicoes.id_modelo_plano
        and p.id_avaliador = auth.uid()
    )
  );


create table if not exists public.modelos_planos_itens (
  id                    bigint generated by default as identity primary key,
  id_modelo_refeicao    bigint not null references public.modelos_planos_refeicoes(id) on delete cascade,
  id_alimento           bigint not null references public.tabela_alimentos(id) on delete restrict,
  quantidade_g          numeric(8,2) not null,
  opcao_numero          integer not null default 1,
  nome_customizado      text,
  unidade_medida        text,
  quantidade_medida     numeric(8,2)
);

create index if not exists idx_modelos_planos_itens_refeicao on public.modelos_planos_itens(id_modelo_refeicao);
create index if not exists idx_modelos_planos_itens_alimento on public.modelos_planos_itens(id_alimento);

alter table public.modelos_planos_itens enable row level security;

drop policy if exists "modelos_planos_itens_isolamento_via_refeicao" on public.modelos_planos_itens;
create policy "modelos_planos_itens_isolamento_via_refeicao" on public.modelos_planos_itens
  for all using (
    exists (
      select 1 from public.modelos_planos_refeicoes r
      join public.modelos_planos p on p.id = r.id_modelo_plano
      where r.id = modelos_planos_itens.id_modelo_refeicao
        and p.id_avaliador = auth.uid()
    )
  );
