-- Questionários reutilizáveis: o avaliador monta um questionário (etapas +
-- perguntas), gera um "envio" (link com token público, opcionalmente ligado a
-- um paciente) e manda pro paciente responder SEM login. É o primeiro recurso
-- deste projeto com ESCRITA anônima via Supabase — as policies extras pro
-- role anon estão comentadas linha a linha por isso.

-- ----------------------------------------------------------------------------
-- 1. QUESTIONÁRIOS (template reutilizável)
-- ----------------------------------------------------------------------------
create table if not exists public.questionarios (
  id            bigint generated by default as identity primary key,
  id_avaliador  uuid not null references auth.users(id) on delete cascade,
  titulo        text not null default 'Questionário sem título',
  created_at    timestamptz not null default now()
);

create index if not exists idx_questionarios_avaliador on public.questionarios(id_avaliador);

alter table public.questionarios enable row level security;

drop policy if exists "questionarios_isolamento_avaliador" on public.questionarios;
create policy "questionarios_isolamento_avaliador" on public.questionarios
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());

-- (a policy de leitura pública desta tabela via token de envio está lá no
-- final do arquivo, seção 6 — ela referencia questionario_envios, que só é
-- criada mais adiante, e "create policy" já valida a query na hora)


-- ----------------------------------------------------------------------------
-- 2. ETAPAS
-- ----------------------------------------------------------------------------
create table if not exists public.questionario_etapas (
  id                bigint generated by default as identity primary key,
  id_questionario   bigint not null references public.questionarios(id) on delete cascade,
  titulo            text not null default 'Etapa',
  ordem             integer not null default 0
);

create index if not exists idx_questionario_etapas_questionario on public.questionario_etapas(id_questionario);

alter table public.questionario_etapas enable row level security;

drop policy if exists "questionario_etapas_isolamento_via_questionario" on public.questionario_etapas;
create policy "questionario_etapas_isolamento_via_questionario" on public.questionario_etapas
  for all using (
    exists (
      select 1 from public.questionarios q
      where q.id = questionario_etapas.id_questionario
        and q.id_avaliador = auth.uid()
    )
  );

-- (idem — policy de leitura pública desta tabela também fica na seção 6)


-- ----------------------------------------------------------------------------
-- 3. PERGUNTAS
-- ----------------------------------------------------------------------------
create table if not exists public.questionario_perguntas (
  id                  bigint generated by default as identity primary key,
  id_etapa            bigint not null references public.questionario_etapas(id) on delete cascade,
  tipo                text not null check (tipo in (
                        'resposta_curta', 'resposta_longa', 'numero',
                        'multipla_escolha', 'caixas_selecao', 'escala_linear'
                      )),
  texto               text not null default '',
  opcoes              jsonb,
  escala_min          integer,
  escala_max          integer,
  escala_label_min    text,
  escala_label_max    text,
  obrigatoria         boolean not null default false,
  ordem               integer not null default 0
);

create index if not exists idx_questionario_perguntas_etapa on public.questionario_perguntas(id_etapa);

alter table public.questionario_perguntas enable row level security;

drop policy if exists "questionario_perguntas_isolamento_via_etapa" on public.questionario_perguntas;
create policy "questionario_perguntas_isolamento_via_etapa" on public.questionario_perguntas
  for all using (
    exists (
      select 1 from public.questionario_etapas et
      join public.questionarios q on q.id = et.id_questionario
      where et.id = questionario_perguntas.id_etapa
        and q.id_avaliador = auth.uid()
    )
  );

-- (idem — policy de leitura pública desta tabela também fica na seção 6)


-- ----------------------------------------------------------------------------
-- 4. ENVIOS — uma instância enviada (com ou sem paciente vinculado ainda).
-- ----------------------------------------------------------------------------
create table if not exists public.questionario_envios (
  id                bigint generated by default as identity primary key,
  id_questionario   bigint not null references public.questionarios(id) on delete cascade,
  id_avaliador      uuid not null references auth.users(id) on delete cascade,
  id_paciente       bigint references public.pacientes(id) on delete set null,
  token_publico     uuid not null default gen_random_uuid() unique,
  status            text not null default 'aguardando' check (status in ('aguardando', 'respondido', 'revisado')),
  created_at        timestamptz not null default now(),
  respondido_em     timestamptz,
  revisado_em       timestamptz
);

create index if not exists idx_questionario_envios_avaliador on public.questionario_envios(id_avaliador);
create index if not exists idx_questionario_envios_questionario on public.questionario_envios(id_questionario);
create index if not exists idx_questionario_envios_paciente on public.questionario_envios(id_paciente);
create index if not exists idx_questionario_envios_token on public.questionario_envios(token_publico);

alter table public.questionario_envios enable row level security;

drop policy if exists "questionario_envios_isolamento_avaliador" on public.questionario_envios;
create policy "questionario_envios_isolamento_avaliador" on public.questionario_envios
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());

-- Leitura pública: mesmo modelo de confiança do token_publico já usado em
-- pacientes/avaliacoes (laudo/evolução) — o segredo é o token em si (uuid
-- imprevisível), não uma checagem extra de RLS. É sempre buscado com
-- .eq('token_publico', tokenDaUrl), então "using (true)" aqui não abre uma
-- listagem geral, só permite que a linha específica passe pelo filtro.
drop policy if exists "questionario_envios_leitura_publica" on public.questionario_envios;
create policy "questionario_envios_leitura_publica" on public.questionario_envios
  for select to anon using (true);

-- Escrita pública: só permite marcar como respondido (nunca reabrir depois de
-- já respondido/revisado, nunca virar outro status).
drop policy if exists "questionario_envios_resposta_publica" on public.questionario_envios;
create policy "questionario_envios_resposta_publica" on public.questionario_envios
  for update to anon
  using (status = 'aguardando')
  with check (status = 'respondido');


-- ----------------------------------------------------------------------------
-- 5. RESPOSTAS
-- ----------------------------------------------------------------------------
create table if not exists public.questionario_respostas (
  id                    bigint generated by default as identity primary key,
  id_envio              bigint not null references public.questionario_envios(id) on delete cascade,
  id_pergunta           bigint not null references public.questionario_perguntas(id) on delete cascade,
  resposta              text,
  resposta_multipla     jsonb
);

create index if not exists idx_questionario_respostas_envio on public.questionario_respostas(id_envio);
create index if not exists idx_questionario_respostas_pergunta on public.questionario_respostas(id_pergunta);

alter table public.questionario_respostas enable row level security;

drop policy if exists "questionario_respostas_leitura_avaliador" on public.questionario_respostas;
create policy "questionario_respostas_leitura_avaliador" on public.questionario_respostas
  for all using (
    exists (
      select 1 from public.questionario_envios e
      where e.id = questionario_respostas.id_envio
        and e.id_avaliador = auth.uid()
    )
  );

-- Escrita pública: só insere resposta enquanto o envio ainda não foi
-- respondido (mesma trava usada na policy de update de questionario_envios
-- acima). Sem select/update/delete pra anon aqui — o paciente não precisa
-- reler o que já mandou.
drop policy if exists "questionario_respostas_insercao_publica" on public.questionario_respostas;
create policy "questionario_respostas_insercao_publica" on public.questionario_respostas
  for insert to anon
  with check (
    exists (
      select 1 from public.questionario_envios e
      where e.id = questionario_respostas.id_envio
        and e.status = 'aguardando'
    )
  );


-- ----------------------------------------------------------------------------
-- 6. LEITURA PÚBLICA DE questionarios / questionario_etapas /
-- questionario_perguntas — em bloco separado aqui no final porque as 3
-- referenciam questionario_envios (tabela 4) num "exists (...)", e o Postgres
-- já valida essa subquery no momento do CREATE POLICY, então a tabela
-- referenciada precisa existir antes. Mesmo raciocínio de "só enxerga a
-- estrutura de um questionário se souber o token de algum envio dele" das
-- seções 1-3.
-- ----------------------------------------------------------------------------
drop policy if exists "questionarios_leitura_publica_via_envio" on public.questionarios;
create policy "questionarios_leitura_publica_via_envio" on public.questionarios
  for select to anon using (
    exists (
      select 1 from public.questionario_envios e
      where e.id_questionario = questionarios.id
    )
  );

drop policy if exists "questionario_etapas_leitura_publica_via_envio" on public.questionario_etapas;
create policy "questionario_etapas_leitura_publica_via_envio" on public.questionario_etapas
  for select to anon using (
    exists (
      select 1 from public.questionario_envios e
      where e.id_questionario = questionario_etapas.id_questionario
    )
  );

drop policy if exists "questionario_perguntas_leitura_publica_via_envio" on public.questionario_perguntas;
create policy "questionario_perguntas_leitura_publica_via_envio" on public.questionario_perguntas
  for select to anon using (
    exists (
      select 1 from public.questionario_etapas et
      join public.questionario_envios e on e.id_questionario = et.id_questionario
      where et.id = questionario_perguntas.id_etapa
    )
  );
