-- CORREÇÃO DE BUG CRÍTICO: cadastro de novo avaliador estava quebrado pra
-- TODO MUNDO desde que a trigger public.trigger_verificar_promocao (função
-- verificar_promocao_novo_avaliador(), criada direto no Supabase, fora das
-- migrations) começou a rodar em cada insert de public.avaliadores — ela
-- consulta a tabela public.promocoes, que nunca existiu neste banco. Toda
-- tentativa de auth.signUp() falhava com "Database error saving new user".
--
-- Esta migration só recria a tabela com as colunas que a função já espera
-- (email, utilizado, meses_gratuitos, id p/ o UPDATE de resgate, data_resgate).
-- Fica vazia — não muda nada pra quem já tem conta, só destrava o cadastro.
-- Sem policy de RLS por enquanto: só a função SECURITY DEFINER acessa; se um
-- dia o Marco quiser gerenciar promoções pela tela, adiciona policy depois.

create table if not exists public.promocoes (
  id                bigint generated by default as identity primary key,
  email             text not null,
  meses_gratuitos   integer not null,
  utilizado         boolean not null default false,
  data_resgate      timestamptz,
  created_at        timestamptz not null default now()
);

create index if not exists idx_promocoes_email on public.promocoes(lower(email));

alter table public.promocoes enable row level security;
