-- Bug: salvar uma refeição/plano como modelo (favorito) não levava os
-- substitutos de cada item — modelos_refeicoes_itens e modelos_planos_itens
-- (migration 0014) nunca ganharam uma tabela filha equivalente a
-- substitutos_item (migration 0005). O comentário original da 0014 já
-- previa "múltiplas opções de substituição" nos modelos, mas só o
-- opcao_numero (Opção 1/2/3 dentro da própria refeição) foi implementado —
-- isso aqui completa a peça que faltou.

create table if not exists public.modelos_refeicoes_itens_substitutos (
  id                  bigint generated by default as identity primary key,
  id_item_modelo      bigint not null references public.modelos_refeicoes_itens(id) on delete cascade,
  id_alimento         bigint not null references public.tabela_alimentos(id) on delete restrict,
  quantidade_g        numeric(8,2) not null,
  ordem               integer not null default 0
);

create index if not exists idx_modelos_refeicoes_itens_subs_item on public.modelos_refeicoes_itens_substitutos(id_item_modelo);
create index if not exists idx_modelos_refeicoes_itens_subs_alimento on public.modelos_refeicoes_itens_substitutos(id_alimento);

alter table public.modelos_refeicoes_itens_substitutos enable row level security;

drop policy if exists "modelos_refeicoes_itens_subs_isolamento_via_item" on public.modelos_refeicoes_itens_substitutos;
create policy "modelos_refeicoes_itens_subs_isolamento_via_item" on public.modelos_refeicoes_itens_substitutos
  for all using (
    exists (
      select 1
      from public.modelos_refeicoes_itens i
      join public.modelos_refeicoes m on m.id = i.id_modelo
      where i.id = modelos_refeicoes_itens_substitutos.id_item_modelo
        and m.id_avaliador = auth.uid()
    )
  );


create table if not exists public.modelos_planos_itens_substitutos (
  id                  bigint generated by default as identity primary key,
  id_item_modelo      bigint not null references public.modelos_planos_itens(id) on delete cascade,
  id_alimento         bigint not null references public.tabela_alimentos(id) on delete restrict,
  quantidade_g        numeric(8,2) not null,
  ordem               integer not null default 0
);

create index if not exists idx_modelos_planos_itens_subs_item on public.modelos_planos_itens_substitutos(id_item_modelo);
create index if not exists idx_modelos_planos_itens_subs_alimento on public.modelos_planos_itens_substitutos(id_alimento);

alter table public.modelos_planos_itens_substitutos enable row level security;

drop policy if exists "modelos_planos_itens_subs_isolamento_via_item" on public.modelos_planos_itens_substitutos;
create policy "modelos_planos_itens_subs_isolamento_via_item" on public.modelos_planos_itens_substitutos
  for all using (
    exists (
      select 1
      from public.modelos_planos_itens i
      join public.modelos_planos_refeicoes r on r.id = i.id_modelo_refeicao
      join public.modelos_planos p on p.id = r.id_modelo_plano
      where i.id = modelos_planos_itens_substitutos.id_item_modelo
        and p.id_avaliador = auth.uid()
    )
  );
