-- Medida caseira pessoal em alimentos oficiais (TACO/IBGE/Fabricante) —
-- hoje esses alimentos não podem ser editados por ninguém (a RLS de
-- tabela_alimentos só libera update pra quem é dono, e alimentos oficiais
-- não têm dono). O nutricionista pediu pra poder cadastrar a medida
-- caseira (ex: "1 unidade ≈ 90g" pra banana) SEM alterar o valor
-- nutricional compartilhado por todo mundo — por isso isso vira uma
-- tabela separada de "anotação pessoal", nunca um update em
-- tabela_alimentos.

create table if not exists public.alimentos_medida_caseira_pessoal (
  id                    bigint generated by default as identity primary key,
  id_avaliador          uuid not null references auth.users(id) on delete cascade,
  id_alimento           bigint not null references public.tabela_alimentos(id) on delete cascade,
  medida_caseira_desc   text,
  medida_caseira_g      numeric(8,2),
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  unique (id_avaliador, id_alimento)
);

create index if not exists idx_alimentos_medida_pessoal_avaliador on public.alimentos_medida_caseira_pessoal(id_avaliador);
create index if not exists idx_alimentos_medida_pessoal_alimento on public.alimentos_medida_caseira_pessoal(id_alimento);

alter table public.alimentos_medida_caseira_pessoal enable row level security;

drop policy if exists "alimentos_medida_pessoal_isolamento_avaliador" on public.alimentos_medida_caseira_pessoal;
create policy "alimentos_medida_pessoal_isolamento_avaliador" on public.alimentos_medida_caseira_pessoal
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());
