-- Módulo de Exames Laboratoriais: duas frentes independentes.
--
-- 1) Solicitações — documento de texto livre (pedido de exames), mesmo
--    padrão de listas_recomendacoes/orientacoes_nutricionais (migrations
--    0009/0011), com modelos reutilizáveis. Diferença: cada solicitação
--    tem um token_publico próprio (não reaproveita o token do paciente)
--    porque o PDF carrega um QR Code que aponta pra ELA especificamente
--    — é um documento médico, precisa validar sozinho.
--
-- 2) Registros — resultados de exames organizados em grupos (Hemograma,
--    Perfil Lipídico etc), cada exame com valor obtido, unidade e
--    intervalo de referência próprios (preenchidos olhando o laudo em
--    mãos — o catálogo do app só sugere um prefill genérico, referências
--    variam bastante entre laboratórios). valor_obtido é texto, não
--    numérico, porque vários exames têm resultado qualitativo
--    ("Não Reagente", "Indetectável", "Negativo").

-- ============================================================
-- SOLICITAÇÕES
-- ============================================================
create table if not exists public.exames_solicitacoes (
  id            bigint generated by default as identity primary key,
  id_paciente   bigint not null references public.pacientes(id) on delete cascade,
  id_avaliador  uuid not null references auth.users(id) on delete cascade,
  titulo        text not null default '1ª Solicitação de exames',
  conteudo      text,
  token_publico uuid not null default gen_random_uuid() unique,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists idx_exames_solicitacoes_paciente on public.exames_solicitacoes(id_paciente);
create index if not exists idx_exames_solicitacoes_avaliador on public.exames_solicitacoes(id_avaliador);

alter table public.exames_solicitacoes enable row level security;

drop policy if exists "exames_solicitacoes_isolamento_avaliador" on public.exames_solicitacoes;
create policy "exames_solicitacoes_isolamento_avaliador" on public.exames_solicitacoes
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());

-- Leitura pública via token — mesmo padrão (e mesmo nível de confiança)
-- já usado pra avaliações/planos/orientações em
-- 0018_area_paciente_leitura_publica.sql: a tabela toda fica legível pro
-- anônimo, mas o app só busca por token_publico específico (aleatório,
-- não listável).
drop policy if exists "exames_solicitacoes_leitura_publica_via_token" on public.exames_solicitacoes;
create policy "exames_solicitacoes_leitura_publica_via_token" on public.exames_solicitacoes
  for select to anon using (true);


create table if not exists public.modelos_exames_solicitacoes (
  id            bigint generated by default as identity primary key,
  id_avaliador  uuid references auth.users(id) on delete cascade,
  titulo        text not null default 'Modelo',
  conteudo      text,
  created_at    timestamptz not null default now()
);

-- id_avaliador nullable de propósito: linhas com id_avaliador is null são
-- modelos do SISTEMA (os dois perfis prontos abaixo), visíveis pra todo
-- nutricionista — não só quem os criou.
create index if not exists idx_modelos_exames_solicitacoes_avaliador on public.modelos_exames_solicitacoes(id_avaliador);

alter table public.modelos_exames_solicitacoes enable row level security;

drop policy if exists "modelos_exames_solicitacoes_leitura" on public.modelos_exames_solicitacoes;
create policy "modelos_exames_solicitacoes_leitura" on public.modelos_exames_solicitacoes
  for select using (id_avaliador is null or id_avaliador = auth.uid());

drop policy if exists "modelos_exames_solicitacoes_escrita" on public.modelos_exames_solicitacoes;
create policy "modelos_exames_solicitacoes_escrita" on public.modelos_exames_solicitacoes
  for insert with check (id_avaliador = auth.uid());

drop policy if exists "modelos_exames_solicitacoes_update" on public.modelos_exames_solicitacoes;
create policy "modelos_exames_solicitacoes_update" on public.modelos_exames_solicitacoes
  for update using (id_avaliador = auth.uid()) with check (id_avaliador = auth.uid());

drop policy if exists "modelos_exames_solicitacoes_delete" on public.modelos_exames_solicitacoes;
create policy "modelos_exames_solicitacoes_delete" on public.modelos_exames_solicitacoes
  for delete using (id_avaliador = auth.uid());

-- Dois modelos prontos do sistema (mesmo conteúdo usado no
-- fluxo real do consultório).
insert into public.modelos_exames_solicitacoes (id_avaliador, titulo, conteudo)
select null, 'Perfil de exames básico', '<p>Solicito os seguintes exames laboratoriais (SANGUE):</p><p><br></p><p>Glicemia de jejum</p><p>Hemoglobina glicada</p><p><br></p><p>Colesterol total e frações</p><p>Triglicerídeos</p><p><br></p><p>TGO</p><p>TGP</p><p>GGT</p><p><br></p><p>Ureia</p><p>Creatinina</p><p><br></p><p>Ferritina</p><p>Índice de saturação da transferrina</p><p>Proteína C-reativa ultrassensível (PCR-US)</p><p><br></p><p>Vitamina B12</p><p>Vitamina D (25-OH-VIT D)</p><p><br></p><p>TSH</p><p>T4 Livre</p>'
where not exists (select 1 from public.modelos_exames_solicitacoes where id_avaliador is null and titulo = 'Perfil de exames básico');

insert into public.modelos_exames_solicitacoes (id_avaliador, titulo, conteudo)
select null, 'Perfil de exames completo', '<p>Solicito os seguintes exames laboratoriais (SANGUE):</p><p><br></p><p>Glicemia de jejum</p><p>Hemoglobina glicada</p><p>Insulina</p><p>HOMA-IR</p><p><br></p><p>Colesterol total e frações</p><p>Triglicerídeos</p><p>Lp(a)</p><p><br></p><p>TGO</p><p>TGP</p><p>GGT</p><p>FOSFATASE ALCALINA</p><p><br></p><p>Ureia</p><p>Creatinina</p><p>Ácido úrico</p><p>Cistatina C</p><p>Microalbuminúria</p><p><br></p><p>Ferro sérico</p><p>Ferritina</p><p>Índice de saturação da transferrina</p><p>Capacidade total de ligação do ferro</p><p>Proteína C-reativa ultrassensível (PCR-US)</p><p><br></p><p>PTH</p><p>Cálcio iônico</p><p><br></p><p>Ácido fólico</p><p>Vitamina B12</p><p>Vitamina D (25-OH-VIT D)</p><p>Magnésio</p><p>Zinco</p><p><br></p><p>TSH</p><p>T4 Livre</p>'
where not exists (select 1 from public.modelos_exames_solicitacoes where id_avaliador is null and titulo = 'Perfil de exames completo');


-- ============================================================
-- REGISTROS (resultados)
-- ============================================================
create table if not exists public.exames_registros (
  id            bigint generated by default as identity primary key,
  id_paciente   bigint not null references public.pacientes(id) on delete cascade,
  id_avaliador  uuid not null references auth.users(id) on delete cascade,
  titulo        text not null default '1º Registro de exames',
  data_coleta   date not null default current_date,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists idx_exames_registros_paciente on public.exames_registros(id_paciente);
create index if not exists idx_exames_registros_avaliador on public.exames_registros(id_avaliador);

alter table public.exames_registros enable row level security;

drop policy if exists "exames_registros_isolamento_avaliador" on public.exames_registros;
create policy "exames_registros_isolamento_avaliador" on public.exames_registros
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());


create table if not exists public.exames_registros_grupos (
  id           bigint generated by default as identity primary key,
  id_registro  bigint not null references public.exames_registros(id) on delete cascade,
  nome         text not null default 'Grupo',
  ordem        integer not null default 0
);

create index if not exists idx_exames_registros_grupos_registro on public.exames_registros_grupos(id_registro);

alter table public.exames_registros_grupos enable row level security;

drop policy if exists "exames_registros_grupos_via_registro" on public.exames_registros_grupos;
create policy "exames_registros_grupos_via_registro" on public.exames_registros_grupos
  for all using (
    exists (select 1 from public.exames_registros r where r.id = exames_registros_grupos.id_registro and r.id_avaliador = auth.uid())
  )
  with check (
    exists (select 1 from public.exames_registros r where r.id = exames_registros_grupos.id_registro and r.id_avaliador = auth.uid())
  );


create table if not exists public.exames_registros_itens (
  id             bigint generated by default as identity primary key,
  id_grupo       bigint references public.exames_registros_grupos(id) on delete cascade,
  id_registro    bigint not null references public.exames_registros(id) on delete cascade,
  nome_exame     text not null,
  valor_obtido   text,
  unidade        text,
  intervalo_min  numeric,
  intervalo_max  numeric,
  ordem          integer not null default 0
);

-- id_registro duplicado aqui (além de id_grupo) pra permitir "exame
-- avulso" sem grupo (id_grupo null) e ainda assim escopar a RLS
-- diretamente pelo registro, sem depender de um grupo existir.
create index if not exists idx_exames_registros_itens_grupo on public.exames_registros_itens(id_grupo);
create index if not exists idx_exames_registros_itens_registro on public.exames_registros_itens(id_registro);

alter table public.exames_registros_itens enable row level security;

drop policy if exists "exames_registros_itens_via_registro" on public.exames_registros_itens;
create policy "exames_registros_itens_via_registro" on public.exames_registros_itens
  for all using (
    exists (select 1 from public.exames_registros r where r.id = exames_registros_itens.id_registro and r.id_avaliador = auth.uid())
  )
  with check (
    exists (select 1 from public.exames_registros r where r.id = exames_registros_itens.id_registro and r.id_avaliador = auth.uid())
  );
