-- Módulo de Agenda: compromissos entre nutricionista e paciente,
-- opcionalmente sincronizados com um evento no Google Calendar do
-- próprio nutricionista (google_event_id/google_meet_link, preenchidos
-- pela função serverless api/google/create-event.js — nunca pelo
-- client) e com avisos por WhatsApp (whatsapp_confirmacao_enviada_em/
-- whatsapp_lembrete_enviado_em são guardas contra reenvio, gravados
-- pelas funções serverless de WhatsApp).
--
-- visivel_paciente aqui tem default TRUE (diferente de exames, que é
-- dado sensível) — um horário marcado é informação que o próprio
-- paciente já sabe (combinou a hora), então não faz sentido esconder
-- por padrão.

create table if not exists public.agendamentos (
  id                                bigint generated by default as identity primary key,
  id_paciente                       bigint not null references public.pacientes(id) on delete cascade,
  id_avaliador                      uuid not null references auth.users(id) on delete cascade,
  titulo                            text,
  data_inicio                       timestamptz not null,
  data_fim                          timestamptz not null,
  fuso_horario                      text not null default 'America/Sao_Paulo',
  local                             text,
  status                            text not null default 'confirmado',
  google_event_id                   text,
  google_meet_link                  text,
  whatsapp_confirmacao_enviada_em   timestamptz,
  whatsapp_lembrete_enviado_em      timestamptz,
  visivel_paciente                  boolean not null default true,
  created_at                        timestamptz not null default now(),
  updated_at                        timestamptz not null default now()
);

create index if not exists idx_agendamentos_paciente on public.agendamentos(id_paciente);
create index if not exists idx_agendamentos_avaliador on public.agendamentos(id_avaliador);
create index if not exists idx_agendamentos_data_inicio on public.agendamentos(data_inicio);

alter table public.agendamentos enable row level security;

drop policy if exists "agendamentos_isolamento_avaliador" on public.agendamentos;
create policy "agendamentos_isolamento_avaliador" on public.agendamentos
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());

-- Leitura pública pro portal do paciente — mesmo padrão de
-- exames_registros (0034), condicionada a visivel_paciente = true.
drop policy if exists "agendamentos_leitura_publica_via_paciente" on public.agendamentos;
create policy "agendamentos_leitura_publica_via_paciente" on public.agendamentos
  for select to anon using (
    visivel_paciente = true
    and exists (select 1 from public.pacientes p where p.id = agendamentos.id_paciente)
  );
