-- Suporte a imagens: R2 (upload próprio do nutricionista) + banco de
-- imagens (Pexels, salva só a URL, sem re-hospedar nada). Tabela de
-- registro pra listar/buscar "Minhas Imagens" na tela de seleção — o
-- arquivo em si mora no R2, aqui só guardamos a referência.

create table if not exists public.imagens_nutricionista (
  id            bigint generated by default as identity primary key,
  id_avaliador  uuid not null references auth.users(id) on delete cascade,
  url           text not null,
  chave_r2      text not null,
  nome_arquivo  text not null,
  created_at    timestamptz not null default now()
);

create index if not exists idx_imagens_nutricionista_avaliador on public.imagens_nutricionista(id_avaliador);

alter table public.imagens_nutricionista enable row level security;

drop policy if exists "imagens_nutricionista_isolamento_avaliador" on public.imagens_nutricionista;
create policy "imagens_nutricionista_isolamento_avaliador" on public.imagens_nutricionista
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());

-- Campo de imagem nos 5 lugares da Fase 1 (URL só — do R2 ou da Pexels,
-- o sistema não precisa saber a origem).
alter table public.refeicoes_prescritas add column if not exists imagem_url text;
alter table public.orientacoes_nutricionais add column if not exists imagem_url text;
alter table public.listas_recomendacoes add column if not exists imagem_url text;
alter table public.questionario_perguntas add column if not exists imagem_url text;
alter table public.anamneses add column if not exists imagem_url text;
