-- Permite mais de um Check-in Semanal ativo por paciente ao mesmo tempo
-- (ex: "Check-in Semanal" básico de peso + um questionário mais profundo
-- que o nutricionista construiu). Troca a coluna única
-- pacientes.id_questionario_semanal por uma tabela de relação, já que um
-- FK simples só permitia um ativo por vez.

create table if not exists public.checkins_semanais_pacientes (
  id                        bigint generated by default as identity primary key,
  id_paciente               bigint not null references public.pacientes(id) on delete cascade,
  id_questionario           bigint not null references public.questionarios(id) on delete cascade,
  id_avaliador              uuid not null references auth.users(id) on delete cascade,
  mostrar_grafico_paciente  boolean not null default false,
  created_at                timestamptz not null default now(),
  unique (id_paciente, id_questionario)
);

create index if not exists idx_checkins_semanais_paciente on public.checkins_semanais_pacientes(id_paciente);
create index if not exists idx_checkins_semanais_questionario on public.checkins_semanais_pacientes(id_questionario);
create index if not exists idx_checkins_semanais_avaliador on public.checkins_semanais_pacientes(id_avaliador);

alter table public.checkins_semanais_pacientes enable row level security;

drop policy if exists "checkins_semanais_pacientes_isolamento_avaliador" on public.checkins_semanais_pacientes;
create policy "checkins_semanais_pacientes_isolamento_avaliador" on public.checkins_semanais_pacientes
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());

-- Leitura pública (mesmo modelo de confiança via token_publico do
-- paciente já usado em toda a Área do Paciente) — o Portal do Paciente
-- precisa saber quais check-ins têm mostrar_grafico_paciente=true.
drop policy if exists "checkins_semanais_pacientes_leitura_publica" on public.checkins_semanais_pacientes;
create policy "checkins_semanais_pacientes_leitura_publica" on public.checkins_semanais_pacientes
  for select to anon using (
    exists (select 1 from public.pacientes p where p.id = checkins_semanais_pacientes.id_paciente)
  );

-- Migra os dados existentes de pacientes.id_questionario_semanal (coluna
-- antiga, 0044) pra tabela nova antes de remover a coluna.
insert into public.checkins_semanais_pacientes (id_paciente, id_questionario, id_avaliador, mostrar_grafico_paciente)
select p.id, p.id_questionario_semanal, p.id_avaliador, coalesce(p.mostrar_grafico_peso_paciente, false)
from public.pacientes p
where p.id_questionario_semanal is not null
on conflict (id_paciente, id_questionario) do nothing;

alter table public.pacientes drop column if exists id_questionario_semanal;
alter table public.pacientes drop column if exists mostrar_grafico_peso_paciente;

-- ----------------------------------------------------------------------------
-- Check-in básico sem a pergunta de "refeições livres" — só Peso (+ Altura
-- condicional). Redefine a função de seed (usada pelo trigger em novos
-- avaliadores) e limpa a pergunta dos questionários já criados por ela.
-- ----------------------------------------------------------------------------
create or replace function public.criar_checkin_semanal_padrao(p_id_avaliador uuid)
returns void as $$
declare
  v_questionario_id bigint;
  v_etapa_id bigint;
begin
  if exists (
    select 1 from public.questionarios
    where id_avaliador = p_id_avaliador and recorrente_semanal = true
  ) then
    return;
  end if;

  insert into public.questionarios (id_avaliador, titulo, recorrente_semanal)
  values (p_id_avaliador, 'Check-in Semanal', true)
  returning id into v_questionario_id;

  insert into public.questionario_etapas (id_questionario, titulo, ordem)
  values (v_questionario_id, 'Check-in', 0)
  returning id into v_etapa_id;

  insert into public.questionario_perguntas (id_etapa, tipo, texto, campo_especial, obrigatoria, ordem)
  values
    (v_etapa_id, 'numero', 'Qual foi seu peso hoje? (medido em jejum, pela manhã)', 'peso', true, 0),
    (v_etapa_id, 'numero', 'Qual sua altura? (em cm)', 'altura', false, 1);
end;
$$ language plpgsql security definer;

delete from public.questionario_perguntas qp
using public.questionario_etapas qe, public.questionarios q
where qp.id_etapa = qe.id
  and qe.id_questionario = q.id
  and q.titulo = 'Check-in Semanal'
  and q.recorrente_semanal = true
  and qp.texto = 'Quantas refeições livres você fez na última semana?';
