-- Controle Financeiro (MVP): receitas e despesas do consultório, com
-- vínculo opcional a um paciente. Fica de fora por enquanto: parcelamento,
-- nota fiscal, despesa recorrente e fluxo de caixa — entram depois,
-- iterando em cima disso, igual foi feito com o Check-in Semanal.
--
-- Sem policy de leitura pública: dado financeiro é só do nutricionista, o
-- paciente nunca vê nada daqui.
create table if not exists public.movimentacoes_financeiras (
  id            bigint generated by default as identity primary key,
  id_avaliador  uuid not null references auth.users(id) on delete cascade,
  id_paciente   bigint references public.pacientes(id) on delete set null,
  tipo          text not null check (tipo in ('receita', 'despesa')),
  descricao     text not null,
  categoria     text not null default 'Outro',
  valor         numeric(10,2) not null,
  data          date not null default current_date,
  pago          boolean not null default false,
  created_at    timestamptz not null default now()
);

create index if not exists idx_movimentacoes_avaliador on public.movimentacoes_financeiras(id_avaliador);
create index if not exists idx_movimentacoes_paciente on public.movimentacoes_financeiras(id_paciente);
create index if not exists idx_movimentacoes_data on public.movimentacoes_financeiras(data);

alter table public.movimentacoes_financeiras enable row level security;

drop policy if exists "movimentacoes_isolamento_avaliador" on public.movimentacoes_financeiras;
create policy "movimentacoes_isolamento_avaliador" on public.movimentacoes_financeiras
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());
