-- Metas de vitaminas/minerais (Dietary Reference Intakes — Institute of
-- Medicine / National Academies) pra comparar contra o plano alimentar.
-- Dado de referência público (facts, não protegidos por copyright),
-- extraído de uma fonte limpa e verificável — NCBI Bookshelf, resumo
-- oficial dos relatórios do Institute of Medicine:
-- https://www.ncbi.nlm.nih.gov/books/NBK545442/table/appJ_tab2/ (vitaminas)
-- https://www.ncbi.nlm.nih.gov/books/NBK545442/table/appJ_tab3/ (minerais)
--
-- Escopo v1: só adultos (19+), M/F, sem gestante/lactante/criança — a
-- grande maioria dos pacientes de uma prática de nutrição. Dá pra expandir
-- depois. "chave" bate com o nome da coluna em tabela_alimentos (ver 0054)
-- pra facilitar o join na hora de somar o plano. eh_ai marca quando o
-- valor é Adequate Intake (menos estabelecido) em vez de RDA.
create table if not exists public.dri_referencias (
  id            bigint generated by default as identity primary key,
  chave         text not null,
  nutriente     text not null,
  unidade       text not null,
  sexo          text not null check (sexo in ('M', 'F')),
  idade_min     integer not null,
  idade_max     integer not null,
  valor         numeric(10,3) not null,
  eh_ai         boolean not null default false,
  created_at    timestamptz not null default now()
);

create index if not exists idx_dri_chave on public.dri_referencias(chave);
create index if not exists idx_dri_sexo_idade on public.dri_referencias(sexo, idade_min, idade_max);

alter table public.dri_referencias enable row level security;

-- Referência pública/estática, igual não tem dono — todo nutricionista
-- logado lê a mesma tabela. Sem policy de insert/update/delete: só é
-- alterada por migration.
drop policy if exists "dri_referencias_leitura" on public.dri_referencias;
create policy "dri_referencias_leitura" on public.dri_referencias
  for select to authenticated using (true);

insert into public.dri_referencias (chave, nutriente, unidade, sexo, idade_min, idade_max, valor, eh_ai) values
  -- Vitamina A (mcg RAE)
  ('vitamina_a_mcg', 'Vitamina A', 'µg', 'M', 19, 30, 900, false),
  ('vitamina_a_mcg', 'Vitamina A', 'µg', 'M', 31, 50, 900, false),
  ('vitamina_a_mcg', 'Vitamina A', 'µg', 'M', 51, 70, 900, false),
  ('vitamina_a_mcg', 'Vitamina A', 'µg', 'M', 71, 120, 900, false),
  ('vitamina_a_mcg', 'Vitamina A', 'µg', 'F', 19, 30, 700, false),
  ('vitamina_a_mcg', 'Vitamina A', 'µg', 'F', 31, 50, 700, false),
  ('vitamina_a_mcg', 'Vitamina A', 'µg', 'F', 51, 70, 700, false),
  ('vitamina_a_mcg', 'Vitamina A', 'µg', 'F', 71, 120, 700, false),
  -- Vitamina C
  ('vitamina_c_mg', 'Vitamina C', 'mg', 'M', 19, 30, 90, false),
  ('vitamina_c_mg', 'Vitamina C', 'mg', 'M', 31, 50, 90, false),
  ('vitamina_c_mg', 'Vitamina C', 'mg', 'M', 51, 70, 90, false),
  ('vitamina_c_mg', 'Vitamina C', 'mg', 'M', 71, 120, 90, false),
  ('vitamina_c_mg', 'Vitamina C', 'mg', 'F', 19, 30, 75, false),
  ('vitamina_c_mg', 'Vitamina C', 'mg', 'F', 31, 50, 75, false),
  ('vitamina_c_mg', 'Vitamina C', 'mg', 'F', 51, 70, 75, false),
  ('vitamina_c_mg', 'Vitamina C', 'mg', 'F', 71, 120, 75, false),
  -- Vitamina D
  ('vitamina_d_mcg', 'Vitamina D', 'µg', 'M', 19, 30, 15, false),
  ('vitamina_d_mcg', 'Vitamina D', 'µg', 'M', 31, 50, 15, false),
  ('vitamina_d_mcg', 'Vitamina D', 'µg', 'M', 51, 70, 15, false),
  ('vitamina_d_mcg', 'Vitamina D', 'µg', 'M', 71, 120, 20, false),
  ('vitamina_d_mcg', 'Vitamina D', 'µg', 'F', 19, 30, 15, false),
  ('vitamina_d_mcg', 'Vitamina D', 'µg', 'F', 31, 50, 15, false),
  ('vitamina_d_mcg', 'Vitamina D', 'µg', 'F', 51, 70, 15, false),
  ('vitamina_d_mcg', 'Vitamina D', 'µg', 'F', 71, 120, 20, false),
  -- Vitamina E
  ('vitamina_e_mg', 'Vitamina E', 'mg', 'M', 19, 30, 15, false),
  ('vitamina_e_mg', 'Vitamina E', 'mg', 'M', 31, 50, 15, false),
  ('vitamina_e_mg', 'Vitamina E', 'mg', 'M', 51, 70, 15, false),
  ('vitamina_e_mg', 'Vitamina E', 'mg', 'M', 71, 120, 15, false),
  ('vitamina_e_mg', 'Vitamina E', 'mg', 'F', 19, 30, 15, false),
  ('vitamina_e_mg', 'Vitamina E', 'mg', 'F', 31, 50, 15, false),
  ('vitamina_e_mg', 'Vitamina E', 'mg', 'F', 51, 70, 15, false),
  ('vitamina_e_mg', 'Vitamina E', 'mg', 'F', 71, 120, 15, false),
  -- Vitamina K (AI)
  ('vitamina_k_mcg', 'Vitamina K', 'µg', 'M', 19, 30, 120, true),
  ('vitamina_k_mcg', 'Vitamina K', 'µg', 'M', 31, 50, 120, true),
  ('vitamina_k_mcg', 'Vitamina K', 'µg', 'M', 51, 70, 120, true),
  ('vitamina_k_mcg', 'Vitamina K', 'µg', 'M', 71, 120, 120, true),
  ('vitamina_k_mcg', 'Vitamina K', 'µg', 'F', 19, 30, 90, true),
  ('vitamina_k_mcg', 'Vitamina K', 'µg', 'F', 31, 50, 90, true),
  ('vitamina_k_mcg', 'Vitamina K', 'µg', 'F', 51, 70, 90, true),
  ('vitamina_k_mcg', 'Vitamina K', 'µg', 'F', 71, 120, 90, true),
  -- Tiamina (B1)
  ('tiamina_mg', 'Tiamina (B1)', 'mg', 'M', 19, 30, 1.2, false),
  ('tiamina_mg', 'Tiamina (B1)', 'mg', 'M', 31, 50, 1.2, false),
  ('tiamina_mg', 'Tiamina (B1)', 'mg', 'M', 51, 70, 1.2, false),
  ('tiamina_mg', 'Tiamina (B1)', 'mg', 'M', 71, 120, 1.2, false),
  ('tiamina_mg', 'Tiamina (B1)', 'mg', 'F', 19, 30, 1.1, false),
  ('tiamina_mg', 'Tiamina (B1)', 'mg', 'F', 31, 50, 1.1, false),
  ('tiamina_mg', 'Tiamina (B1)', 'mg', 'F', 51, 70, 1.1, false),
  ('tiamina_mg', 'Tiamina (B1)', 'mg', 'F', 71, 120, 1.1, false),
  -- Riboflavina (B2)
  ('riboflavina_mg', 'Riboflavina (B2)', 'mg', 'M', 19, 30, 1.3, false),
  ('riboflavina_mg', 'Riboflavina (B2)', 'mg', 'M', 31, 50, 1.3, false),
  ('riboflavina_mg', 'Riboflavina (B2)', 'mg', 'M', 51, 70, 1.3, false),
  ('riboflavina_mg', 'Riboflavina (B2)', 'mg', 'M', 71, 120, 1.3, false),
  ('riboflavina_mg', 'Riboflavina (B2)', 'mg', 'F', 19, 30, 1.1, false),
  ('riboflavina_mg', 'Riboflavina (B2)', 'mg', 'F', 31, 50, 1.1, false),
  ('riboflavina_mg', 'Riboflavina (B2)', 'mg', 'F', 51, 70, 1.1, false),
  ('riboflavina_mg', 'Riboflavina (B2)', 'mg', 'F', 71, 120, 1.1, false),
  -- Niacina (B3)
  ('niacina_mg', 'Niacina (B3)', 'mg', 'M', 19, 30, 16, false),
  ('niacina_mg', 'Niacina (B3)', 'mg', 'M', 31, 50, 16, false),
  ('niacina_mg', 'Niacina (B3)', 'mg', 'M', 51, 70, 16, false),
  ('niacina_mg', 'Niacina (B3)', 'mg', 'M', 71, 120, 16, false),
  ('niacina_mg', 'Niacina (B3)', 'mg', 'F', 19, 30, 14, false),
  ('niacina_mg', 'Niacina (B3)', 'mg', 'F', 31, 50, 14, false),
  ('niacina_mg', 'Niacina (B3)', 'mg', 'F', 51, 70, 14, false),
  ('niacina_mg', 'Niacina (B3)', 'mg', 'F', 71, 120, 14, false),
  -- Vitamina B6
  ('vitamina_b6_mg', 'Vitamina B6', 'mg', 'M', 19, 30, 1.3, false),
  ('vitamina_b6_mg', 'Vitamina B6', 'mg', 'M', 31, 50, 1.3, false),
  ('vitamina_b6_mg', 'Vitamina B6', 'mg', 'M', 51, 70, 1.7, false),
  ('vitamina_b6_mg', 'Vitamina B6', 'mg', 'M', 71, 120, 1.7, false),
  ('vitamina_b6_mg', 'Vitamina B6', 'mg', 'F', 19, 30, 1.3, false),
  ('vitamina_b6_mg', 'Vitamina B6', 'mg', 'F', 31, 50, 1.3, false),
  ('vitamina_b6_mg', 'Vitamina B6', 'mg', 'F', 51, 70, 1.5, false),
  ('vitamina_b6_mg', 'Vitamina B6', 'mg', 'F', 71, 120, 1.5, false),
  -- Folato
  ('folato_mcg', 'Folato', 'µg', 'M', 19, 30, 400, false),
  ('folato_mcg', 'Folato', 'µg', 'M', 31, 50, 400, false),
  ('folato_mcg', 'Folato', 'µg', 'M', 51, 70, 400, false),
  ('folato_mcg', 'Folato', 'µg', 'M', 71, 120, 400, false),
  ('folato_mcg', 'Folato', 'µg', 'F', 19, 30, 400, false),
  ('folato_mcg', 'Folato', 'µg', 'F', 31, 50, 400, false),
  ('folato_mcg', 'Folato', 'µg', 'F', 51, 70, 400, false),
  ('folato_mcg', 'Folato', 'µg', 'F', 71, 120, 400, false),
  -- Vitamina B12
  ('vitamina_b12_mcg', 'Vitamina B12', 'µg', 'M', 19, 30, 2.4, false),
  ('vitamina_b12_mcg', 'Vitamina B12', 'µg', 'M', 31, 50, 2.4, false),
  ('vitamina_b12_mcg', 'Vitamina B12', 'µg', 'M', 51, 70, 2.4, false),
  ('vitamina_b12_mcg', 'Vitamina B12', 'µg', 'M', 71, 120, 2.4, false),
  ('vitamina_b12_mcg', 'Vitamina B12', 'µg', 'F', 19, 30, 2.4, false),
  ('vitamina_b12_mcg', 'Vitamina B12', 'µg', 'F', 31, 50, 2.4, false),
  ('vitamina_b12_mcg', 'Vitamina B12', 'µg', 'F', 51, 70, 2.4, false),
  ('vitamina_b12_mcg', 'Vitamina B12', 'µg', 'F', 71, 120, 2.4, false),
  -- Ácido Pantotênico (B5, AI)
  ('acido_pantotenico_mg', 'Ácido Pantotênico (B5)', 'mg', 'M', 19, 30, 5, true),
  ('acido_pantotenico_mg', 'Ácido Pantotênico (B5)', 'mg', 'M', 31, 50, 5, true),
  ('acido_pantotenico_mg', 'Ácido Pantotênico (B5)', 'mg', 'M', 51, 70, 5, true),
  ('acido_pantotenico_mg', 'Ácido Pantotênico (B5)', 'mg', 'M', 71, 120, 5, true),
  ('acido_pantotenico_mg', 'Ácido Pantotênico (B5)', 'mg', 'F', 19, 30, 5, true),
  ('acido_pantotenico_mg', 'Ácido Pantotênico (B5)', 'mg', 'F', 31, 50, 5, true),
  ('acido_pantotenico_mg', 'Ácido Pantotênico (B5)', 'mg', 'F', 51, 70, 5, true),
  ('acido_pantotenico_mg', 'Ácido Pantotênico (B5)', 'mg', 'F', 71, 120, 5, true),
  -- Biotina (B7, AI)
  ('biotina_mcg', 'Biotina (B7)', 'µg', 'M', 19, 30, 30, true),
  ('biotina_mcg', 'Biotina (B7)', 'µg', 'M', 31, 50, 30, true),
  ('biotina_mcg', 'Biotina (B7)', 'µg', 'M', 51, 70, 30, true),
  ('biotina_mcg', 'Biotina (B7)', 'µg', 'M', 71, 120, 30, true),
  ('biotina_mcg', 'Biotina (B7)', 'µg', 'F', 19, 30, 30, true),
  ('biotina_mcg', 'Biotina (B7)', 'µg', 'F', 31, 50, 30, true),
  ('biotina_mcg', 'Biotina (B7)', 'µg', 'F', 51, 70, 30, true),
  ('biotina_mcg', 'Biotina (B7)', 'µg', 'F', 71, 120, 30, true),
  -- Colina (AI)
  ('colina_mg', 'Colina', 'mg', 'M', 19, 30, 550, true),
  ('colina_mg', 'Colina', 'mg', 'M', 31, 50, 550, true),
  ('colina_mg', 'Colina', 'mg', 'M', 51, 70, 550, true),
  ('colina_mg', 'Colina', 'mg', 'M', 71, 120, 550, true),
  ('colina_mg', 'Colina', 'mg', 'F', 19, 30, 425, true),
  ('colina_mg', 'Colina', 'mg', 'F', 31, 50, 425, true),
  ('colina_mg', 'Colina', 'mg', 'F', 51, 70, 425, true),
  ('colina_mg', 'Colina', 'mg', 'F', 71, 120, 425, true),
  -- Cálcio
  ('calcio_mg', 'Cálcio', 'mg', 'M', 19, 30, 1000, false),
  ('calcio_mg', 'Cálcio', 'mg', 'M', 31, 50, 1000, false),
  ('calcio_mg', 'Cálcio', 'mg', 'M', 51, 70, 1000, false),
  ('calcio_mg', 'Cálcio', 'mg', 'M', 71, 120, 1200, false),
  ('calcio_mg', 'Cálcio', 'mg', 'F', 19, 30, 1000, false),
  ('calcio_mg', 'Cálcio', 'mg', 'F', 31, 50, 1000, false),
  ('calcio_mg', 'Cálcio', 'mg', 'F', 51, 70, 1200, false),
  ('calcio_mg', 'Cálcio', 'mg', 'F', 71, 120, 1200, false),
  -- Cromo (AI)
  ('cromo_mcg', 'Cromo', 'µg', 'M', 19, 30, 35, true),
  ('cromo_mcg', 'Cromo', 'µg', 'M', 31, 50, 35, true),
  ('cromo_mcg', 'Cromo', 'µg', 'M', 51, 70, 30, true),
  ('cromo_mcg', 'Cromo', 'µg', 'M', 71, 120, 30, true),
  ('cromo_mcg', 'Cromo', 'µg', 'F', 19, 30, 25, true),
  ('cromo_mcg', 'Cromo', 'µg', 'F', 31, 50, 25, true),
  ('cromo_mcg', 'Cromo', 'µg', 'F', 51, 70, 20, true),
  ('cromo_mcg', 'Cromo', 'µg', 'F', 71, 120, 20, true),
  -- Cobre
  ('cobre_mcg', 'Cobre', 'µg', 'M', 19, 30, 900, false),
  ('cobre_mcg', 'Cobre', 'µg', 'M', 31, 50, 900, false),
  ('cobre_mcg', 'Cobre', 'µg', 'M', 51, 70, 900, false),
  ('cobre_mcg', 'Cobre', 'µg', 'M', 71, 120, 900, false),
  ('cobre_mcg', 'Cobre', 'µg', 'F', 19, 30, 900, false),
  ('cobre_mcg', 'Cobre', 'µg', 'F', 31, 50, 900, false),
  ('cobre_mcg', 'Cobre', 'µg', 'F', 51, 70, 900, false),
  ('cobre_mcg', 'Cobre', 'µg', 'F', 71, 120, 900, false),
  -- Iodo
  ('iodo_mcg', 'Iodo', 'µg', 'M', 19, 30, 150, false),
  ('iodo_mcg', 'Iodo', 'µg', 'M', 31, 50, 150, false),
  ('iodo_mcg', 'Iodo', 'µg', 'M', 51, 70, 150, false),
  ('iodo_mcg', 'Iodo', 'µg', 'M', 71, 120, 150, false),
  ('iodo_mcg', 'Iodo', 'µg', 'F', 19, 30, 150, false),
  ('iodo_mcg', 'Iodo', 'µg', 'F', 31, 50, 150, false),
  ('iodo_mcg', 'Iodo', 'µg', 'F', 51, 70, 150, false),
  ('iodo_mcg', 'Iodo', 'µg', 'F', 71, 120, 150, false),
  -- Ferro
  ('ferro_mg', 'Ferro', 'mg', 'M', 19, 30, 8, false),
  ('ferro_mg', 'Ferro', 'mg', 'M', 31, 50, 8, false),
  ('ferro_mg', 'Ferro', 'mg', 'M', 51, 70, 8, false),
  ('ferro_mg', 'Ferro', 'mg', 'M', 71, 120, 8, false),
  ('ferro_mg', 'Ferro', 'mg', 'F', 19, 30, 18, false),
  ('ferro_mg', 'Ferro', 'mg', 'F', 31, 50, 18, false),
  ('ferro_mg', 'Ferro', 'mg', 'F', 51, 70, 8, false),
  ('ferro_mg', 'Ferro', 'mg', 'F', 71, 120, 8, false),
  -- Magnésio
  ('magnesio_mg', 'Magnésio', 'mg', 'M', 19, 30, 400, false),
  ('magnesio_mg', 'Magnésio', 'mg', 'M', 31, 50, 420, false),
  ('magnesio_mg', 'Magnésio', 'mg', 'M', 51, 70, 420, false),
  ('magnesio_mg', 'Magnésio', 'mg', 'M', 71, 120, 420, false),
  ('magnesio_mg', 'Magnésio', 'mg', 'F', 19, 30, 310, false),
  ('magnesio_mg', 'Magnésio', 'mg', 'F', 31, 50, 320, false),
  ('magnesio_mg', 'Magnésio', 'mg', 'F', 51, 70, 320, false),
  ('magnesio_mg', 'Magnésio', 'mg', 'F', 71, 120, 320, false),
  -- Manganês (AI)
  ('manganes_mg', 'Manganês', 'mg', 'M', 19, 30, 2.3, true),
  ('manganes_mg', 'Manganês', 'mg', 'M', 31, 50, 2.3, true),
  ('manganes_mg', 'Manganês', 'mg', 'M', 51, 70, 2.3, true),
  ('manganes_mg', 'Manganês', 'mg', 'M', 71, 120, 2.3, true),
  ('manganes_mg', 'Manganês', 'mg', 'F', 19, 30, 1.8, true),
  ('manganes_mg', 'Manganês', 'mg', 'F', 31, 50, 1.8, true),
  ('manganes_mg', 'Manganês', 'mg', 'F', 51, 70, 1.8, true),
  ('manganes_mg', 'Manganês', 'mg', 'F', 71, 120, 1.8, true),
  -- Molibdênio
  ('molibdenio_mcg', 'Molibdênio', 'µg', 'M', 19, 30, 45, false),
  ('molibdenio_mcg', 'Molibdênio', 'µg', 'M', 31, 50, 45, false),
  ('molibdenio_mcg', 'Molibdênio', 'µg', 'M', 51, 70, 45, false),
  ('molibdenio_mcg', 'Molibdênio', 'µg', 'M', 71, 120, 45, false),
  ('molibdenio_mcg', 'Molibdênio', 'µg', 'F', 19, 30, 45, false),
  ('molibdenio_mcg', 'Molibdênio', 'µg', 'F', 31, 50, 45, false),
  ('molibdenio_mcg', 'Molibdênio', 'µg', 'F', 51, 70, 45, false),
  ('molibdenio_mcg', 'Molibdênio', 'µg', 'F', 71, 120, 45, false),
  -- Fósforo
  ('fosforo_mg', 'Fósforo', 'mg', 'M', 19, 30, 700, false),
  ('fosforo_mg', 'Fósforo', 'mg', 'M', 31, 50, 700, false),
  ('fosforo_mg', 'Fósforo', 'mg', 'M', 51, 70, 700, false),
  ('fosforo_mg', 'Fósforo', 'mg', 'M', 71, 120, 700, false),
  ('fosforo_mg', 'Fósforo', 'mg', 'F', 19, 30, 700, false),
  ('fosforo_mg', 'Fósforo', 'mg', 'F', 31, 50, 700, false),
  ('fosforo_mg', 'Fósforo', 'mg', 'F', 51, 70, 700, false),
  ('fosforo_mg', 'Fósforo', 'mg', 'F', 71, 120, 700, false),
  -- Selênio
  ('selenio_mcg', 'Selênio', 'µg', 'M', 19, 30, 55, false),
  ('selenio_mcg', 'Selênio', 'µg', 'M', 31, 50, 55, false),
  ('selenio_mcg', 'Selênio', 'µg', 'M', 51, 70, 55, false),
  ('selenio_mcg', 'Selênio', 'µg', 'M', 71, 120, 55, false),
  ('selenio_mcg', 'Selênio', 'µg', 'F', 19, 30, 55, false),
  ('selenio_mcg', 'Selênio', 'µg', 'F', 31, 50, 55, false),
  ('selenio_mcg', 'Selênio', 'µg', 'F', 51, 70, 55, false),
  ('selenio_mcg', 'Selênio', 'µg', 'F', 71, 120, 55, false),
  -- Zinco
  ('zinco_mg', 'Zinco', 'mg', 'M', 19, 30, 11, false),
  ('zinco_mg', 'Zinco', 'mg', 'M', 31, 50, 11, false),
  ('zinco_mg', 'Zinco', 'mg', 'M', 51, 70, 11, false),
  ('zinco_mg', 'Zinco', 'mg', 'M', 71, 120, 11, false),
  ('zinco_mg', 'Zinco', 'mg', 'F', 19, 30, 8, false),
  ('zinco_mg', 'Zinco', 'mg', 'F', 31, 50, 8, false),
  ('zinco_mg', 'Zinco', 'mg', 'F', 51, 70, 8, false),
  ('zinco_mg', 'Zinco', 'mg', 'F', 71, 120, 8, false),
  -- Potássio (AI)
  ('potassio_mg', 'Potássio', 'mg', 'M', 19, 30, 3400, true),
  ('potassio_mg', 'Potássio', 'mg', 'M', 31, 50, 3400, true),
  ('potassio_mg', 'Potássio', 'mg', 'M', 51, 70, 3400, true),
  ('potassio_mg', 'Potássio', 'mg', 'M', 71, 120, 3400, true),
  ('potassio_mg', 'Potássio', 'mg', 'F', 19, 30, 2600, true),
  ('potassio_mg', 'Potássio', 'mg', 'F', 31, 50, 2600, true),
  ('potassio_mg', 'Potássio', 'mg', 'F', 51, 70, 2600, true),
  ('potassio_mg', 'Potássio', 'mg', 'F', 71, 120, 2600, true),
  -- Sódio (AI — meta de adequação, não confundir com limite de excesso)
  ('sodio_mg', 'Sódio', 'mg', 'M', 19, 30, 1500, true),
  ('sodio_mg', 'Sódio', 'mg', 'M', 31, 50, 1500, true),
  ('sodio_mg', 'Sódio', 'mg', 'M', 51, 70, 1500, true),
  ('sodio_mg', 'Sódio', 'mg', 'M', 71, 120, 1500, true),
  ('sodio_mg', 'Sódio', 'mg', 'F', 19, 30, 1500, true),
  ('sodio_mg', 'Sódio', 'mg', 'F', 31, 50, 1500, true),
  ('sodio_mg', 'Sódio', 'mg', 'F', 51, 70, 1500, true),
  ('sodio_mg', 'Sódio', 'mg', 'F', 71, 120, 1500, true);
