-- Segunda leva de micronutrientes pra "Frutas e derivados" — recuperação dos
-- itens que ficaram sem match na 0056 (44/96 aprovados na 1ª leva).
--
-- Duas fontes, com dois níveis de confiança diferentes:
--
-- 1) USDA FoodData Central (18 itens) — mesma fonte/metodologia da 0056.
--    Esses itens tinham um bom equivalente na USDA que o algoritmo de
--    match automático simplesmente não encontrou/pontuou bem na 1ª
--    rodada; revisei manualmente e confirmei o fdc_id certo pra cada um
--    (ex.: maçã Fuji/Argentina -> "Apples, raw, with skin"; suco de
--    laranja/limão/tangerina -> os sucos correspondentes da USDA; jaca,
--    fruta-pão, pinha, carambola, romã, tamarindo, nêspera, caqui ->
--    entradas específicas da USDA). Confiança alta, igual à 0056.
--
-- 2) Pesquisa na internet (22 itens) — frutas brasileiras/tropicais sem
--    NENHUM equivalente razoável na USDA (jabuticaba, cupuaçu, pequi,
--    açaí, tucumã, jambo, jamelão, ciriguela, cajá, umbu, atemóia, abiu,
--    caju, graviola, goiabada). A pedido explícito do usuário ("mesmo
--    que o dado não seja 100% confiável"), usei dados agregados de sites
--    que espelham a Tabela TACO 4ª edição (tabelanutricional.com.br,
--    tabelatacoonline.com.br) pra preencher só as 5 colunas mais
--    comumente reportadas: magnesio_mg, fosforo_mg, potassio_mg,
--    manganes_mg e cobre_mcg. Não preenchi selênio, iodo, vitamina E/K,
--    folato, colina, ácido pantotênico, biotina, cromo ou molibdênio
--    pra esses itens — não achei fonte confiável pra esses números
--    nessas frutas específicas (prefiro coluna vazia a dado errado,
--    mesmo com a barra mais baixa pedida aqui). "Cobre" nessas fontes
--    aparece rotulado como µg mas os valores batem com miligramas (igual
--    a USDA) — apliquei o mesmo fator ×1000 usado no resto do projeto.
--    Ficaram de fora (sem fonte confiável nem aproximada): Caju suco
--    concentrado, Maracujá suco concentrado, Mamão doce em calda (é
--    comida de bebê goiaba+mamão, não mamão puro), Acerola polpa
--    congelada, Pitanga polpa congelada, Cacau cru e Macaúba.
--
-- Itens ainda sem nenhum dado novo depois desta leva: seguem exatamente
-- como estavam (colunas antigas da TACO preservadas, novas colunas null).

-- ============================================================
-- 1) Recuperados via USDA (alta confiança)
-- ============================================================
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 0.12), magnesio_mg = 5, fosforo_mg = 11, potassio_mg = 107, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.04), cobre_mcg = 27, manganes_mg = 0.035, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.18, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4.6), tiamina_mg = coalesce(tiamina_mg, 0.017), riboflavina_mg = coalesce(riboflavina_mg, 0.026), niacina_mg = coalesce(niacina_mg, 0.091), acido_pantotenico_mg = 0.061, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.041), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 3.4, vitamina_k_mcg = 2.2, folato_mcg = 3 where nome = 'Maçã, Argentina, com casca, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7), ferro_mg = coalesce(ferro_mg, 0.1), magnesio_mg = 5, fosforo_mg = 13, potassio_mg = 109, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.04), cobre_mcg = 25, manganes_mg = 0.031, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.18, tiamina_mg = coalesce(tiamina_mg, 0.013), riboflavina_mg = coalesce(riboflavina_mg, 0.026), niacina_mg = coalesce(niacina_mg, 0.07), acido_pantotenico_mg = 0.051, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.045), colina_mg = 3.4, vitamina_k_mcg = 1 where nome = 'Maçã, Fuji, com casca, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 10), ferro_mg = coalesce(ferro_mg, 0.3), magnesio_mg = 12, fosforo_mg = 36, potassio_mg = 236, sodio_mg = coalesce(sodio_mg, 3), zinco_mg = coalesce(zinco_mg, 0.35), cobre_mcg = 158, manganes_mg = 0.119, selenio_mcg = 0.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.6, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 10.2), tiamina_mg = coalesce(tiamina_mg, 0.067), riboflavina_mg = coalesce(riboflavina_mg, 0.053), niacina_mg = coalesce(niacina_mg, 0.293), acido_pantotenico_mg = 0.377, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.075), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 7.6, vitamina_k_mcg = 16.4, folato_mcg = 38 where nome = 'Romã, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 74), ferro_mg = coalesce(ferro_mg, 2.8), magnesio_mg = 92, fosforo_mg = 113, potassio_mg = 628, sodio_mg = coalesce(sodio_mg, 28), zinco_mg = coalesce(zinco_mg, 0.1), cobre_mcg = 86, selenio_mcg = 1.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.1, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 3.5), tiamina_mg = coalesce(tiamina_mg, 0.428), riboflavina_mg = coalesce(riboflavina_mg, 0.152), niacina_mg = coalesce(niacina_mg, 1.938), acido_pantotenico_mg = 0.143, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.066), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 8.6, vitamina_k_mcg = 2.8, folato_mcg = 14 where nome = 'Tamarindo, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 0.2), magnesio_mg = 11, fosforo_mg = 17, potassio_mg = 200, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.05), cobre_mcg = 44, manganes_mg = 0.014, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 10), vitamina_e_mg = 0.04, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 50), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.03), niacina_mg = coalesce(niacina_mg, 0.4), acido_pantotenico_mg = 0.19, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.04), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.2, vitamina_k_mcg = 0.1, folato_mcg = 30 where nome = 'Laranja, baía, suco' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 0.2), magnesio_mg = 11, fosforo_mg = 17, potassio_mg = 200, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.05), cobre_mcg = 44, manganes_mg = 0.014, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 10), vitamina_e_mg = 0.04, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 50), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.03), niacina_mg = coalesce(niacina_mg, 0.4), acido_pantotenico_mg = 0.19, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.04), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.2, vitamina_k_mcg = 0.1, folato_mcg = 30 where nome = 'Laranja, da terra, suco' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 0.2), magnesio_mg = 11, fosforo_mg = 17, potassio_mg = 200, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.05), cobre_mcg = 44, manganes_mg = 0.014, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 10), vitamina_e_mg = 0.04, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 50), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.03), niacina_mg = coalesce(niacina_mg, 0.4), acido_pantotenico_mg = 0.19, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.04), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.2, vitamina_k_mcg = 0.1, folato_mcg = 30 where nome = 'Laranja, lima, suco' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 0.2), magnesio_mg = 11, fosforo_mg = 17, potassio_mg = 200, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.05), cobre_mcg = 44, manganes_mg = 0.014, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 10), vitamina_e_mg = 0.04, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 50), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.03), niacina_mg = coalesce(niacina_mg, 0.4), acido_pantotenico_mg = 0.19, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.04), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.2, vitamina_k_mcg = 0.1, folato_mcg = 30 where nome = 'Laranja, pêra, suco' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 0.2), magnesio_mg = 11, fosforo_mg = 17, potassio_mg = 200, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.05), cobre_mcg = 44, manganes_mg = 0.014, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 10), vitamina_e_mg = 0.04, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 50), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.03), niacina_mg = coalesce(niacina_mg, 0.4), acido_pantotenico_mg = 0.19, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.04), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.2, vitamina_k_mcg = 0.1, folato_mcg = 30 where nome = 'Laranja, valência, suco' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 14), ferro_mg = coalesce(ferro_mg, 0.09), magnesio_mg = 8, fosforo_mg = 14, potassio_mg = 117, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 0.08), cobre_mcg = 27, manganes_mg = 0.018, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.22, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 30), tiamina_mg = coalesce(tiamina_mg, 0.025), riboflavina_mg = coalesce(riboflavina_mg, 0.015), niacina_mg = coalesce(niacina_mg, 0.142), acido_pantotenico_mg = 0.123, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.038), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 5.1, vitamina_k_mcg = 0.6, folato_mcg = 10 where nome = 'Limão, cravo, suco' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 14), ferro_mg = coalesce(ferro_mg, 0.09), magnesio_mg = 8, fosforo_mg = 14, potassio_mg = 117, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 0.08), cobre_mcg = 27, manganes_mg = 0.018, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.22, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 30), tiamina_mg = coalesce(tiamina_mg, 0.025), riboflavina_mg = coalesce(riboflavina_mg, 0.015), niacina_mg = coalesce(niacina_mg, 0.142), acido_pantotenico_mg = 0.123, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.038), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 5.1, vitamina_k_mcg = 0.6, folato_mcg = 10 where nome = 'Limão, galego, suco' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 0.54), magnesio_mg = 25, fosforo_mg = 30, potassio_mg = 490, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 0.12), cobre_mcg = 84, manganes_mg = 0.06, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.1, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 29), tiamina_mg = coalesce(tiamina_mg, 0.11), riboflavina_mg = coalesce(riboflavina_mg, 0.03), niacina_mg = coalesce(niacina_mg, 0.9), acido_pantotenico_mg = 0.457, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.1), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 9.8, vitamina_k_mcg = 0.5, folato_mcg = 14 where nome = 'Fruta-pão, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 24), ferro_mg = coalesce(ferro_mg, 0.23), magnesio_mg = 29, fosforo_mg = 21, potassio_mg = 448, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 0.13), cobre_mcg = 76, manganes_mg = 0.043, vitamina_a_mcg = coalesce(vitamina_a_mcg, 5), vitamina_e_mg = 0.34, vitamina_c_mg = coalesce(vitamina_c_mg, 13.7), tiamina_mg = coalesce(tiamina_mg, 0.105), riboflavina_mg = coalesce(riboflavina_mg, 0.055), niacina_mg = coalesce(niacina_mg, 0.92), acido_pantotenico_mg = 0.235, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.329), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 24 where nome = 'Jaca, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 24), ferro_mg = coalesce(ferro_mg, 0.6), magnesio_mg = 21, fosforo_mg = 32, potassio_mg = 247, sodio_mg = coalesce(sodio_mg, 9), zinco_mg = coalesce(zinco_mg, 0.1), cobre_mcg = 86, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 36.3), tiamina_mg = coalesce(tiamina_mg, 0.11), riboflavina_mg = coalesce(riboflavina_mg, 0.113), niacina_mg = coalesce(niacina_mg, 0.883), acido_pantotenico_mg = 0.226, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.2), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 14 where nome = 'Pinha, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 16), ferro_mg = coalesce(ferro_mg, 0.28), magnesio_mg = 13, fosforo_mg = 27, potassio_mg = 266, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.05), cobre_mcg = 40, manganes_mg = 0.148, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 76), vitamina_c_mg = coalesce(vitamina_c_mg, 1), tiamina_mg = coalesce(tiamina_mg, 0.019), riboflavina_mg = coalesce(riboflavina_mg, 0.024), niacina_mg = coalesce(niacina_mg, 0.18), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.1), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 14 where nome = 'Nêspera, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 3), ferro_mg = coalesce(ferro_mg, 0.08), magnesio_mg = 10, fosforo_mg = 12, potassio_mg = 133, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 0.12), cobre_mcg = 137, manganes_mg = 0.037, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.15, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 34.4), tiamina_mg = coalesce(tiamina_mg, 0.014), riboflavina_mg = coalesce(riboflavina_mg, 0.016), niacina_mg = coalesce(niacina_mg, 0.367), acido_pantotenico_mg = 0.391, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.017), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 7.6, vitamina_k_mcg = 0, folato_mcg = 12 where nome = 'Carambola, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 8), ferro_mg = coalesce(ferro_mg, 0.15), magnesio_mg = 9, fosforo_mg = 17, potassio_mg = 161, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.11), cobre_mcg = 113, manganes_mg = 0.355, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 81), vitamina_e_mg = 0.73, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 7.5), tiamina_mg = coalesce(tiamina_mg, 0.03), riboflavina_mg = coalesce(riboflavina_mg, 0.02), niacina_mg = coalesce(niacina_mg, 0.1), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.1), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 7.6, vitamina_k_mcg = 2.6, folato_mcg = 8 where nome = 'Caqui, chocolate, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 18), ferro_mg = coalesce(ferro_mg, 0.2), magnesio_mg = 8, fosforo_mg = 14, potassio_mg = 178, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.03), cobre_mcg = 25, manganes_mg = 0.037, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 13), vitamina_e_mg = 0.13, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 31), tiamina_mg = coalesce(tiamina_mg, 0.06), riboflavina_mg = coalesce(riboflavina_mg, 0.02), niacina_mg = coalesce(niacina_mg, 0.1), acido_pantotenico_mg = 0.125, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.042), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.2, vitamina_k_mcg = 0, folato_mcg = 5 where nome = 'Tangerina, Poncã, suco' and fonte = 'TACO' and id_avaliador is null;

-- ============================================================
-- 2) Pesquisa na internet (TACO 4ª edição via sites-espelho) — só
--    magnesio_mg, fosforo_mg, potassio_mg, manganes_mg, cobre_mcg.
--    Confiança mais baixa, aceita explicitamente pelo usuário pra
--    fechar essas frutas exclusivamente brasileiras.
-- ============================================================
update public.tabela_alimentos set magnesio_mg = 10.11, fosforo_mg = 15.64, potassio_mg = 123.86, manganes_mg = 0.12, cobre_mcg = 70 where nome = 'Caju, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 7.07, fosforo_mg = 9.77, potassio_mg = 87.66, manganes_mg = 0.05, cobre_mcg = 70 where nome = 'Caju, polpa, congelada' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 9.49, fosforo_mg = 9.11, potassio_mg = 131.37, manganes_mg = 0.12, cobre_mcg = 60 where nome = 'Manga, polpa, congelada' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 9.7, fosforo_mg = 15.26, potassio_mg = 227.91, manganes_mg = 0.07, cobre_mcg = 50 where nome = 'Maracujá, polpa, congelada' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 6.49, fosforo_mg = 53.57, potassio_mg = 164.81, manganes_mg = 0.11, cobre_mcg = 60 where nome = 'Goiaba, doce em pasta' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 9.67, fosforo_mg = 28.2, potassio_mg = 250.72, manganes_mg = 0.16, cobre_mcg = 80 where nome = 'Goiaba, doce, cascão' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 11.35, fosforo_mg = 13.38, potassio_mg = 151.83, manganes_mg = 0.03, cobre_mcg = 40 where nome = 'Umbu, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 11.35, fosforo_mg = 13.38, potassio_mg = 151.83, manganes_mg = 0.03, cobre_mcg = 40 where nome = 'Umbu, polpa, congelada' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 9.3, fosforo_mg = 20.29, potassio_mg = 128.34, manganes_mg = 0.08, cobre_mcg = 90 where nome = 'Abiu, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 17.04, fosforo_mg = 16.43, potassio_mg = 123.62, manganes_mg = 6.16, cobre_mcg = 180 where nome = 'Açaí, polpa, congelada' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 24.84, fosforo_mg = 23.36, potassio_mg = 300.01, manganes_mg = 0.16, cobre_mcg = 170 where nome = 'Atemóia, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 11.3, fosforo_mg = 24.1, potassio_mg = 119.4, manganes_mg = 0.1, cobre_mcg = 100 where nome = 'Cajá-Manga, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 7.17, fosforo_mg = 25.66, potassio_mg = 148.08, manganes_mg = 0.07, cobre_mcg = 100 where nome = 'Cajá, polpa, congelada' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 17.96, fosforo_mg = 48.6, potassio_mg = 248.01, manganes_mg = 0.06, cobre_mcg = 120 where nome = 'Ciriguela, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 13.91, fosforo_mg = 14.2, potassio_mg = 291.09, manganes_mg = 0.17, cobre_mcg = 140 where nome = 'Cupuaçu, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 13.91, fosforo_mg = 14.2, potassio_mg = 291.09, manganes_mg = 0.17, cobre_mcg = 140 where nome = 'Cupuaçu, polpa, congelada' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 9.76, fosforo_mg = 16.59, potassio_mg = 169.96, manganes_mg = 0.06, cobre_mcg = 60 where nome = 'Graviola, polpa, congelada' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 17.78, fosforo_mg = 14.55, potassio_mg = 129.72, manganes_mg = 0.3, cobre_mcg = 70 where nome = 'Jabuticaba, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 14.18, fosforo_mg = 18.36, potassio_mg = 134.87, manganes_mg = 0.05, cobre_mcg = 20 where nome = 'Jambo, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 2.16, fosforo_mg = 4.12, potassio_mg = 394.34, cobre_mcg = 30 where nome = 'Jamelão, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 29.77, fosforo_mg = 33.75, potassio_mg = 297.79, manganes_mg = 0.64, cobre_mcg = 210 where nome = 'Pequi, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set magnesio_mg = 121.01, fosforo_mg = 52.55, potassio_mg = 401.17, manganes_mg = 0.55, cobre_mcg = 390 where nome = 'Tucumã, cru' and fonte = 'TACO' and id_avaliador is null;
