-- Micronutrientes pra "Cereais e derivados" (63 itens) — mesma
-- metodologia da Frutas/Carnes/Verduras (0054-0061), fonte USDA
-- FoodData Central (SR Legacy + Foundation Foods).
--
-- Erro mais grave: o matching automático INVERTEU arroz integral e
-- arroz tipo 1 — "Arroz, integral" (integral = arroz castanho/brown
-- rice) tinha sido casado com arroz BRANCO, e "Arroz, tipo 1" (arroz
-- branco comum) tinha sido casado com arroz INTEGRAL. Outros erros
-- corrigidos manualmente: farinha de centeio casada com farinha de
-- TRIGO (espécie errada); farinha de rosca e farinha láctea casadas com
-- farinha "00" italiana crua (produtos completamente diferentes);
-- canjica/fubá/amido de milho casados com milho verde fresco in natura
-- (água/densidade de nutrientes bem diferente de produto seco/
-- processado); macarrão instantâneo casado com macarrão de arroz (é de
-- trigo); pão francês casado com pão de trigo integral (pão francês
-- brasileiro é de farinha branca); pão de soja casado com "shortening"
-- (gordura vegetal, nem é pão); polenta casada com fubá de milho AZUL
-- (variedade Navajo, cor/composição diferente da polenta amarela
-- comum); cereal infantil de milho casado com corn flakes de adulto
-- (fortificação vitamínica muito diferente).
--
-- 39 de 63 itens aprovados. Ficaram de fora (prefiro coluna vazia a
-- dado errado): biscoitos/bolos com recheio ou mistura industrializada
-- muito específica (maisena, recheados de morango, wafer, mistura pra
-- bolo, bolo pronto de aipim/coco/milho), sobremesas de milho (canjica
-- com leite, curau), farinha de rosca, farinha láctea, creme de milho
-- em pó, mingau tradicional em pó, pamonha, pão de soja, e o pastel
-- brasileiro em todas as variações (carne/queijo, cru/frito, só a
-- massa) — prato frito com recheio, sem equivalente USDA razoável.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 3), ferro_mg = coalesce(ferro_mg, 0.56), magnesio_mg = 39, fosforo_mg = 103, potassio_mg = 86, sodio_mg = coalesce(sodio_mg, 4), zinco_mg = coalesce(zinco_mg, 0.71), cobre_mcg = 106, manganes_mg = 0.974, selenio_mcg = 5.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.17, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.178), riboflavina_mg = coalesce(riboflavina_mg, 0.069), niacina_mg = coalesce(niacina_mg, 2.561), acido_pantotenico_mg = 0.38, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.123), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 9.2, vitamina_k_mcg = 0.2, folato_mcg = 9 where nome = 'Arroz, integral, cozido' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 8.058), ferro_mg = coalesce(ferro_mg, 1.242), magnesio_mg = 115, fosforo_mg = 302.8, potassio_mg = 250.1, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 1.854), cobre_mcg = 265.9, manganes_mg = 2.696, molibdenio_mcg = 63.94, selenio_mcg = 14.8, tiamina_mg = coalesce(tiamina_mg, 0.326), riboflavina_mg = coalesce(riboflavina_mg, 0.103), niacina_mg = coalesce(niacina_mg, 6.271), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.161), biotina_mcg = 4.988 where nome = 'Arroz, integral, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 10), ferro_mg = coalesce(ferro_mg, 1.2), magnesio_mg = 12, fosforo_mg = 43, potassio_mg = 35, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.49), cobre_mcg = 69, manganes_mg = 0.472, selenio_mcg = 7.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.04, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.163), riboflavina_mg = coalesce(riboflavina_mg, 0.013), niacina_mg = coalesce(niacina_mg, 1.476), acido_pantotenico_mg = 0.39, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.093), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 2.1, vitamina_k_mcg = 0, folato_mcg = 97 where nome = 'Arroz, tipo 1, cozido' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 28), ferro_mg = coalesce(ferro_mg, 4.31), magnesio_mg = 25, fosforo_mg = 115, potassio_mg = 115, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 1.09), cobre_mcg = 220, manganes_mg = 1.088, selenio_mcg = 15.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.576), riboflavina_mg = coalesce(riboflavina_mg, 0.049), niacina_mg = coalesce(niacina_mg, 4.192), acido_pantotenico_mg = 1.014, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.164), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 5.8, vitamina_k_mcg = 0.1, folato_mcg = 387 where nome = 'Arroz, tipo 1, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 3), ferro_mg = coalesce(ferro_mg, 1.49), magnesio_mg = 13, fosforo_mg = 37, potassio_mg = 29, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 0.42), cobre_mcg = 38, manganes_mg = 0.377, selenio_mcg = 7.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.167), riboflavina_mg = coalesce(riboflavina_mg, 0.016), niacina_mg = coalesce(niacina_mg, 1.835), acido_pantotenico_mg = 0.411, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.05), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 97 where nome = 'Arroz, tipo 2, cozido' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 9), ferro_mg = coalesce(ferro_mg, 4.36), magnesio_mg = 35, fosforo_mg = 108, potassio_mg = 86, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 1.16), cobre_mcg = 110, manganes_mg = 1.1, selenio_mcg = 15.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.578), riboflavina_mg = coalesce(riboflavina_mg, 0.048), niacina_mg = coalesce(niacina_mg, 5.093), acido_pantotenico_mg = 1.342, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.145), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 386 where nome = 'Arroz, tipo 2, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 52), ferro_mg = coalesce(ferro_mg, 4.25), magnesio_mg = 138, fosforo_mg = 410, potassio_mg = 362, sodio_mg = coalesce(sodio_mg, 6), zinco_mg = coalesce(zinco_mg, 3.64), cobre_mcg = 391, manganes_mg = 3.63, selenio_mcg = 28.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.42, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.46), riboflavina_mg = coalesce(riboflavina_mg, 0.155), niacina_mg = coalesce(niacina_mg, 1.125), acido_pantotenico_mg = 1.12, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.1), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 40.4, vitamina_k_mcg = 2, folato_mcg = 32 where nome = 'Aveia, flocos, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 15), ferro_mg = coalesce(ferro_mg, 3), magnesio_mg = 25, fosforo_mg = 75, potassio_mg = 95, sodio_mg = coalesce(sodio_mg, 380), zinco_mg = coalesce(zinco_mg, 0.3), cobre_mcg = 267, selenio_mcg = 11.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 2.79, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.29), riboflavina_mg = coalesce(riboflavina_mg, 0.19), niacina_mg = coalesce(niacina_mg, 2.5), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.023), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.02), colina_mg = 7, vitamina_k_mcg = 6.9, folato_mcg = 92 where nome = 'Biscoito, doce, recheado com chocolate' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 19), ferro_mg = coalesce(ferro_mg, 5.57), magnesio_mg = 23, fosforo_mg = 102, potassio_mg = 152, sodio_mg = coalesce(sodio_mg, 941), zinco_mg = coalesce(zinco_mg, 0.69), cobre_mcg = 139, manganes_mg = 0.686, selenio_mcg = 10.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 1.15, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.702), riboflavina_mg = coalesce(riboflavina_mg, 0.487), niacina_mg = coalesce(niacina_mg, 6.442), acido_pantotenico_mg = 0.536, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.086), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.09), colina_mg = 16.7, vitamina_k_mcg = 25.4, folato_mcg = 216 where nome = 'Biscoito, salgado, cream cracker' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 60), ferro_mg = coalesce(ferro_mg, 1.61), magnesio_mg = 32, fosforo_mg = 106, potassio_mg = 140, sodio_mg = coalesce(sodio_mg, 315), zinco_mg = coalesce(zinco_mg, 0.69), cobre_mcg = 207, manganes_mg = 0.28, selenio_mcg = 11.9, vitamina_c_mg = coalesce(vitamina_c_mg, 0.2), tiamina_mg = coalesce(tiamina_mg, 0.141), riboflavina_mg = coalesce(riboflavina_mg, 0.213), niacina_mg = coalesce(niacina_mg, 1.137), acido_pantotenico_mg = 0.304, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.041), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.16), colina_mg = 128.4, folato_mcg = 39 where nome = 'Bolo, pronto, chocolate' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 10), ferro_mg = coalesce(ferro_mg, 0.62), magnesio_mg = 16, fosforo_mg = 35, potassio_mg = 9, sodio_mg = coalesce(sodio_mg, 267), zinco_mg = coalesce(zinco_mg, 1.05), cobre_mcg = 30, manganes_mg = 0.07, selenio_mcg = 3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.05, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.3), tiamina_mg = coalesce(tiamina_mg, 0.003), riboflavina_mg = coalesce(riboflavina_mg, 0.006), niacina_mg = coalesce(niacina_mg, 0.033), acido_pantotenico_mg = 0.154, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.005), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 3.1, vitamina_k_mcg = 0.2, folato_mcg = 1 where nome = 'Canjica, branca, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 2), ferro_mg = coalesce(ferro_mg, 19.4), magnesio_mg = 7, fosforo_mg = 33, potassio_mg = 107, sodio_mg = coalesce(sodio_mg, 571), zinco_mg = coalesce(zinco_mg, 0.2), cobre_mcg = 75, manganes_mg = 0.095, selenio_mcg = 2.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 981), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 7.1), vitamina_c_mg = coalesce(vitamina_c_mg, 65), tiamina_mg = coalesce(tiamina_mg, 4.483), riboflavina_mg = coalesce(riboflavina_mg, 1.74), niacina_mg = coalesce(niacina_mg, 21.033), acido_pantotenico_mg = 0.099, vitamina_b6_mg = coalesce(vitamina_b6_mg, 1.907), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 5.36), colina_mg = 2.2, vitamina_k_mcg = 0 where nome = 'Cereais, milho, flocos, com sal' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 2), ferro_mg = coalesce(ferro_mg, 19.4), magnesio_mg = 7, fosforo_mg = 33, potassio_mg = 107, sodio_mg = coalesce(sodio_mg, 571), zinco_mg = coalesce(zinco_mg, 0.2), cobre_mcg = 75, manganes_mg = 0.095, selenio_mcg = 2.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 981), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 7.1), vitamina_c_mg = coalesce(vitamina_c_mg, 65), tiamina_mg = coalesce(tiamina_mg, 4.483), riboflavina_mg = coalesce(riboflavina_mg, 1.74), niacina_mg = coalesce(niacina_mg, 21.033), acido_pantotenico_mg = 0.099, vitamina_b6_mg = coalesce(vitamina_b6_mg, 1.907), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 5.36), colina_mg = 2.2, vitamina_k_mcg = 0 where nome = 'Cereais, milho, flocos, sem sal' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 109), ferro_mg = coalesce(ferro_mg, 2.81), magnesio_mg = 121, fosforo_mg = 392, potassio_mg = 483, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 2.95), cobre_mcg = 312, selenio_mcg = 17.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 1.3, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.2), tiamina_mg = coalesce(tiamina_mg, 0.411), riboflavina_mg = coalesce(riboflavina_mg, 0.289), niacina_mg = coalesce(niacina_mg, 2.308), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.231), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.17), colina_mg = 35, vitamina_k_mcg = 7, folato_mcg = 37 where nome = 'Cereais, mistura para vitamina, trigo, cevada e aveia' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 2), ferro_mg = coalesce(ferro_mg, 19.4), magnesio_mg = 7, fosforo_mg = 33, potassio_mg = 107, sodio_mg = coalesce(sodio_mg, 571), zinco_mg = coalesce(zinco_mg, 0.2), cobre_mcg = 75, manganes_mg = 0.095, selenio_mcg = 2.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 981), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 7.1), vitamina_c_mg = coalesce(vitamina_c_mg, 65), tiamina_mg = coalesce(tiamina_mg, 4.483), riboflavina_mg = coalesce(riboflavina_mg, 1.74), niacina_mg = coalesce(niacina_mg, 21.033), acido_pantotenico_mg = 0.099, vitamina_b6_mg = coalesce(vitamina_b6_mg, 1.907), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 5.36), colina_mg = 2.2, vitamina_k_mcg = 0 where nome = 'Cereal matinal, milho' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 2), ferro_mg = coalesce(ferro_mg, 19.4), magnesio_mg = 7, fosforo_mg = 33, potassio_mg = 107, sodio_mg = coalesce(sodio_mg, 571), zinco_mg = coalesce(zinco_mg, 0.2), cobre_mcg = 75, manganes_mg = 0.095, selenio_mcg = 2.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 981), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 7.1), vitamina_c_mg = coalesce(vitamina_c_mg, 65), tiamina_mg = coalesce(tiamina_mg, 4.483), riboflavina_mg = coalesce(riboflavina_mg, 1.74), niacina_mg = coalesce(niacina_mg, 21.033), acido_pantotenico_mg = 0.099, vitamina_b6_mg = coalesce(vitamina_b6_mg, 1.907), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 5.36), colina_mg = 2.2, vitamina_k_mcg = 0 where nome = 'Cereal matinal, milho, açúcar' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 5), ferro_mg = coalesce(ferro_mg, 28.44), magnesio_mg = 23, fosforo_mg = 124, potassio_mg = 143, sodio_mg = coalesce(sodio_mg, 6), zinco_mg = coalesce(zinco_mg, 1.12), cobre_mcg = 244, manganes_mg = 1.033, selenio_mcg = 19, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.51), riboflavina_mg = coalesce(riboflavina_mg, 0.13), niacina_mg = coalesce(niacina_mg, 7.46), acido_pantotenico_mg = 0.55, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.195), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 5.9, vitamina_k_mcg = 0.1, folato_mcg = 29 where nome = 'Creme de arroz, pó' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 10), ferro_mg = coalesce(ferro_mg, 0.35), magnesio_mg = 35, fosforo_mg = 98, potassio_mg = 76, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 0.8), cobre_mcg = 130, manganes_mg = 1.2, selenio_mcg = 15.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.138), riboflavina_mg = coalesce(riboflavina_mg, 0.021), niacina_mg = coalesce(niacina_mg, 2.59), acido_pantotenico_mg = 0.819, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.436), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 5.8, vitamina_k_mcg = 0, folato_mcg = 4 where nome = 'Farinha, de arroz, enriquecida' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 37), ferro_mg = coalesce(ferro_mg, 4.97), magnesio_mg = 160, fosforo_mg = 499, potassio_mg = 717, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 5.04), cobre_mcg = 560, manganes_mg = 6.062, selenio_mcg = 18, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 2.73, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.316), riboflavina_mg = coalesce(riboflavina_mg, 0.251), niacina_mg = coalesce(niacina_mg, 4.27), acido_pantotenico_mg = 1.456, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.443), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 30.4, vitamina_k_mcg = 5.9, folato_mcg = 33 where nome = 'Farinha, de centeio, integral' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7), ferro_mg = coalesce(ferro_mg, 2.38), magnesio_mg = 93, fosforo_mg = 272, potassio_mg = 315, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 1.73), cobre_mcg = 230, manganes_mg = 0.46, selenio_mcg = 15.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 11), vitamina_e_mg = 0.42, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.246), riboflavina_mg = coalesce(riboflavina_mg, 0.08), niacina_mg = coalesce(niacina_mg, 1.9), acido_pantotenico_mg = 0.658, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.37), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 21.6, vitamina_k_mcg = 0.3, folato_mcg = 25 where nome = 'Farinha, de milho, amarela' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 15), ferro_mg = coalesce(ferro_mg, 4.64), magnesio_mg = 22, fosforo_mg = 108, potassio_mg = 107, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 0.7), cobre_mcg = 144, manganes_mg = 0.682, selenio_mcg = 33.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.23, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.785), riboflavina_mg = coalesce(riboflavina_mg, 0.494), niacina_mg = coalesce(niacina_mg, 5.904), acido_pantotenico_mg = 0.438, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.044), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), vitamina_k_mcg = 0.3, folato_mcg = 291 where nome = 'Farinha, de trigo' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 1.14), magnesio_mg = 18, fosforo_mg = 63, potassio_mg = 24, sodio_mg = coalesce(sodio_mg, 6), zinco_mg = coalesce(zinco_mg, 0.56), cobre_mcg = 93, manganes_mg = 0.224, vitamina_a_mcg = coalesce(vitamina_a_mcg, 6), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.209), riboflavina_mg = coalesce(riboflavina_mg, 0.15), niacina_mg = coalesce(niacina_mg, 0.992), acido_pantotenico_mg = 0.183, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.034), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.14), folato_mcg = 104 where nome = 'Lasanha, massa fresca, cozida' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 15), ferro_mg = coalesce(ferro_mg, 3.35), magnesio_mg = 46, fosforo_mg = 163, potassio_mg = 179, sodio_mg = coalesce(sodio_mg, 26), zinco_mg = coalesce(zinco_mg, 1.22), cobre_mcg = 228, manganes_mg = 0.547, vitamina_a_mcg = coalesce(vitamina_a_mcg, 14), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.705), riboflavina_mg = coalesce(riboflavina_mg, 0.439), niacina_mg = coalesce(niacina_mg, 3.35), acido_pantotenico_mg = 0.535, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.093), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.31), folato_mcg = 284 where nome = 'Lasanha, massa fresca, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 21), ferro_mg = coalesce(ferro_mg, 4.11), magnesio_mg = 25, fosforo_mg = 115, potassio_mg = 181, sodio_mg = coalesce(sodio_mg, 1855), zinco_mg = coalesce(zinco_mg, 0.6), cobre_mcg = 126, manganes_mg = 0.63, selenio_mcg = 23.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 2.44, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.3), tiamina_mg = coalesce(tiamina_mg, 0.448), riboflavina_mg = coalesce(riboflavina_mg, 0.255), niacina_mg = coalesce(niacina_mg, 5.401), acido_pantotenico_mg = 0.438, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.038), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.25), colina_mg = 5.5, vitamina_k_mcg = 8.9, folato_mcg = 165 where nome = 'Macarrão, instantâneo' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 21), ferro_mg = coalesce(ferro_mg, 1.3), magnesio_mg = 53, fosforo_mg = 189, potassio_mg = 223, sodio_mg = coalesce(sodio_mg, 6), zinco_mg = coalesce(zinco_mg, 1.41), cobre_mcg = 289, manganes_mg = 0.917, selenio_mcg = 63.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.06), niacina_mg = coalesce(niacina_mg, 1.7), acido_pantotenico_mg = 0.431, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.142), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), vitamina_k_mcg = 0.1, folato_mcg = 18 where nome = 'Macarrão, trigo, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 35), ferro_mg = coalesce(ferro_mg, 4.01), magnesio_mg = 58, fosforo_mg = 241, potassio_mg = 244, sodio_mg = coalesce(sodio_mg, 21), zinco_mg = coalesce(zinco_mg, 1.92), cobre_mcg = 297, manganes_mg = 0.855, selenio_mcg = 78.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 17), vitamina_e_mg = 0.37, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 1.133), riboflavina_mg = coalesce(riboflavina_mg, 0.426), niacina_mg = coalesce(niacina_mg, 8.387), acido_pantotenico_mg = 0.912, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.216), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.29), colina_mg = 78.7, vitamina_k_mcg = 0.5, folato_mcg = 370 where nome = 'Macarrão, trigo, cru, com ovos' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 2), ferro_mg = coalesce(ferro_mg, 0.47), magnesio_mg = 3, fosforo_mg = 13, potassio_mg = 3, sodio_mg = coalesce(sodio_mg, 9), zinco_mg = coalesce(zinco_mg, 0.06), cobre_mcg = 50, manganes_mg = 0.053, selenio_mcg = 2.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0.4, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Milho, amido, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 3.45), magnesio_mg = 127, fosforo_mg = 241, potassio_mg = 287, sodio_mg = coalesce(sodio_mg, 35), zinco_mg = coalesce(zinco_mg, 1.82), cobre_mcg = 193, manganes_mg = 0.498, selenio_mcg = 15.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 11), vitamina_e_mg = 0.42, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.385), riboflavina_mg = coalesce(riboflavina_mg, 0.201), niacina_mg = coalesce(niacina_mg, 3.632), acido_pantotenico_mg = 0.425, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.304), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 21.6, vitamina_k_mcg = 0.3, folato_mcg = 25 where nome = 'Milho, fubá, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 2), ferro_mg = coalesce(ferro_mg, 0.52), magnesio_mg = 37, fosforo_mg = 89, potassio_mg = 270, sodio_mg = coalesce(sodio_mg, 15), zinco_mg = coalesce(zinco_mg, 0.45), cobre_mcg = 54, manganes_mg = 0.161, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.07, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 6.8), tiamina_mg = coalesce(tiamina_mg, 0.2), riboflavina_mg = coalesce(riboflavina_mg, 0.06), niacina_mg = coalesce(niacina_mg, 1.7), acido_pantotenico_mg = 0.76, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.055), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), vitamina_k_mcg = 0.3, folato_mcg = 46 where nome = 'Milho, verde, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 3), ferro_mg = coalesce(ferro_mg, 0.27), magnesio_mg = 13, fosforo_mg = 46, potassio_mg = 132, sodio_mg = coalesce(sodio_mg, 205), zinco_mg = coalesce(zinco_mg, 0.32), cobre_mcg = 33, manganes_mg = 0.067, selenio_mcg = 0.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.09, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.8), tiamina_mg = coalesce(tiamina_mg, 0.039), riboflavina_mg = coalesce(riboflavina_mg, 0.089), niacina_mg = coalesce(niacina_mg, 1.005), acido_pantotenico_mg = 0.209, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.037), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 17.8, vitamina_k_mcg = 0, folato_mcg = 39 where nome = 'Milho, verde, enlatado, drenado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 65), ferro_mg = coalesce(ferro_mg, 3.12), magnesio_mg = 35, fosforo_mg = 141, potassio_mg = 147, sodio_mg = coalesce(sodio_mg, 353), zinco_mg = coalesce(zinco_mg, 0.89), cobre_mcg = 135, manganes_mg = 0.779, selenio_mcg = 30, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.44, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.504), riboflavina_mg = coalesce(riboflavina_mg, 0.346), niacina_mg = coalesce(niacina_mg, 4.831), acido_pantotenico_mg = 0.581, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.073), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 18.7, vitamina_k_mcg = 1.2, folato_mcg = 120 where nome = 'Pão, aveia, forma' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 124), ferro_mg = coalesce(ferro_mg, 4.15), magnesio_mg = 65, fosforo_mg = 185, potassio_mg = 322, sodio_mg = coalesce(sodio_mg, 404), zinco_mg = coalesce(zinco_mg, 1.82), cobre_mcg = 417, manganes_mg = 1.472, selenio_mcg = 32.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.36, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.36), riboflavina_mg = coalesce(riboflavina_mg, 0.394), niacina_mg = coalesce(niacina_mg, 4.289), acido_pantotenico_mg = 0.42, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.071), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 18.7, vitamina_k_mcg = 1.3, folato_mcg = 173 where nome = 'Pão, glúten, forma' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 249), ferro_mg = coalesce(ferro_mg, 2.5), magnesio_mg = 25, fosforo_mg = 169, potassio_mg = 147, sodio_mg = coalesce(sodio_mg, 658), zinco_mg = coalesce(zinco_mg, 0.6), cobre_mcg = 51, manganes_mg = 0.118, selenio_mcg = 10.1, vitamina_c_mg = coalesce(vitamina_c_mg, 0.3), tiamina_mg = coalesce(tiamina_mg, 0.291), riboflavina_mg = coalesce(riboflavina_mg, 0.294), niacina_mg = coalesce(niacina_mg, 2.254), acido_pantotenico_mg = 0.339, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.113), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.15), folato_mcg = 118 where nome = 'Pão, milho, forma' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 161), ferro_mg = coalesce(ferro_mg, 2.47), magnesio_mg = 75, fosforo_mg = 212, potassio_mg = 254, sodio_mg = coalesce(sodio_mg, 455), zinco_mg = coalesce(zinco_mg, 1.77), cobre_mcg = 227, manganes_mg = 2.174, selenio_mcg = 25.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 2.66, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.394), riboflavina_mg = coalesce(riboflavina_mg, 0.167), niacina_mg = coalesce(niacina_mg, 4.438), acido_pantotenico_mg = 0.646, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.215), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 27.2, vitamina_k_mcg = 7.8, folato_mcg = 42 where nome = 'Pão, trigo, forma, integral' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 52), ferro_mg = coalesce(ferro_mg, 3.91), magnesio_mg = 32, fosforo_mg = 105, potassio_mg = 117, sodio_mg = coalesce(sodio_mg, 602), zinco_mg = coalesce(zinco_mg, 1.04), cobre_mcg = 152, manganes_mg = 0.577, selenio_mcg = 28.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.71), riboflavina_mg = coalesce(riboflavina_mg, 0.427), niacina_mg = coalesce(niacina_mg, 4.817), acido_pantotenico_mg = 0.455, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.107), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 8, vitamina_k_mcg = 0.7, folato_mcg = 170 where nome = 'Pão, trigo, francês' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 684), ferro_mg = coalesce(ferro_mg, 4.89), magnesio_mg = 26, fosforo_mg = 103, potassio_mg = 127, sodio_mg = coalesce(sodio_mg, 478), zinco_mg = coalesce(zinco_mg, 0.95), cobre_mcg = 149, manganes_mg = 0.634, selenio_mcg = 16.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.38, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.51), riboflavina_mg = coalesce(riboflavina_mg, 0.255), niacina_mg = coalesce(niacina_mg, 4.455), acido_pantotenico_mg = 0.455, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.08), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 8.1, vitamina_k_mcg = 7.7, folato_mcg = 162 where nome = 'Pão, trigo, sovado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 10), ferro_mg = coalesce(ferro_mg, 2.78), magnesio_mg = 108, fosforo_mg = 250, potassio_mg = 225, sodio_mg = coalesce(sodio_mg, 3), zinco_mg = coalesce(zinco_mg, 2.64), cobre_mcg = 221, selenio_mcg = 7.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 8), vitamina_e_mg = 2.43, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.3), tiamina_mg = coalesce(tiamina_mg, 0.13), riboflavina_mg = coalesce(riboflavina_mg, 0.14), niacina_mg = coalesce(niacina_mg, 1.55), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.21), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 16, vitamina_k_mcg = 4.3, folato_mcg = 17 where nome = 'Pipoca, com óleo de soja, sem sal' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 3), ferro_mg = coalesce(ferro_mg, 4.36), magnesio_mg = 32, fosforo_mg = 99, potassio_mg = 142, sodio_mg = coalesce(sodio_mg, 7), zinco_mg = coalesce(zinco_mg, 0.66), cobre_mcg = 76, manganes_mg = 0.174, selenio_mcg = 10.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 11), vitamina_e_mg = 0.12, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.551), riboflavina_mg = coalesce(riboflavina_mg, 0.382), niacina_mg = coalesce(niacina_mg, 4.968), acido_pantotenico_mg = 0.24, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.182), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 8.6, vitamina_k_mcg = 0, folato_mcg = 335 where nome = 'Polenta, pré-cozida' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 47), ferro_mg = coalesce(ferro_mg, 3.87), magnesio_mg = 31, fosforo_mg = 126, potassio_mg = 140, sodio_mg = coalesce(sodio_mg, 720), zinco_mg = coalesce(zinco_mg, 1.05), cobre_mcg = 150, manganes_mg = 0.573, selenio_mcg = 29.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.19, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.2), tiamina_mg = coalesce(tiamina_mg, 0.427), riboflavina_mg = coalesce(riboflavina_mg, 0.37), niacina_mg = coalesce(niacina_mg, 5.38), acido_pantotenico_mg = 0.616, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.096), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 17.5, vitamina_k_mcg = 0.5, folato_mcg = 217 where nome = 'Torrada, pão francês' and fonte = 'TACO' and id_avaliador is null;
