-- Micronutrientes pra "Gorduras e óleos" (14 itens) — mesma metodologia
-- da Frutas/Carnes/Verduras/Cereais (0054-0062), fonte USDA FoodData
-- Central.
--
-- Erros corrigidos: "Azeite, de dendê" (óleo de palma) tinha sido
-- casado com azeite de OLIVA — perfil de gordura completamente
-- diferente; "Óleo, de babaçu/canola" tinham sido casados com "óleo de
-- aveia" (a USDA tem uma única entrada isolada de oat oil que o
-- algoritmo usou de curinga sempre que não achava nada melhor); as
-- margarinas de 65% de lipídeos tinham sido casadas com um "vegetable
-- oil spread" de 20% de gordura (categoria de produto errada — creme
-- vegetal light, não margarina).
--
-- 9 de 14 itens aprovados. Ficaram de fora: as 3 margarinas de 65% de
-- lipídeos (só achei margarina 80% na USDA, e 23% a mais de gordura por
-- 100g distorceria vitamina E/K demais pra aceitar como aproximação);
-- óleo de pequi (fruta nativa brasileira, sem equivalente USDA); azeite
-- de oliva extra virgem (o registro da USDA pro tipo certo de azeite
-- não tinha os valores de vitamina E/K carregados na nossa extração).

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 0), ferro_mg = coalesce(ferro_mg, 0.01), magnesio_mg = 0, fosforo_mg = 0, potassio_mg = 0, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 0), cobre_mcg = 0, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 15.94, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0.3, vitamina_k_mcg = 8, folato_mcg = 0 where nome = 'Azeite, de dendê' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 24), ferro_mg = coalesce(ferro_mg, 0.02), magnesio_mg = 2, fosforo_mg = 24, potassio_mg = 24, sodio_mg = coalesce(sodio_mg, 643), zinco_mg = coalesce(zinco_mg, 0.09), cobre_mcg = 0, manganes_mg = 0, selenio_mcg = 1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 684), vitamina_e_mg = 2.32, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.005), riboflavina_mg = coalesce(riboflavina_mg, 0.034), niacina_mg = coalesce(niacina_mg, 0.042), acido_pantotenico_mg = 0.11, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.003), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.17), colina_mg = 18.8, vitamina_k_mcg = 7, folato_mcg = 3 where nome = 'Manteiga, com sal' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 24), ferro_mg = coalesce(ferro_mg, 0.02), magnesio_mg = 2, fosforo_mg = 24, potassio_mg = 24, sodio_mg = coalesce(sodio_mg, 11), zinco_mg = coalesce(zinco_mg, 0.09), cobre_mcg = 16, manganes_mg = 0.004, selenio_mcg = 1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 684), vitamina_e_mg = 2.32, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.005), riboflavina_mg = coalesce(riboflavina_mg, 0.034), niacina_mg = coalesce(niacina_mg, 0.042), acido_pantotenico_mg = 0.11, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.003), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.17), colina_mg = 18.8, vitamina_k_mcg = 7, folato_mcg = 3 where nome = 'Manteiga, sem sal' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 3), ferro_mg = coalesce(ferro_mg, 0.06), magnesio_mg = 3, fosforo_mg = 5, potassio_mg = 18, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 0), cobre_mcg = 0, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 819), vitamina_e_mg = 9, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.2), tiamina_mg = coalesce(tiamina_mg, 0.01), riboflavina_mg = coalesce(riboflavina_mg, 0.037), niacina_mg = coalesce(niacina_mg, 0.023), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.009), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.1), colina_mg = 12.4, vitamina_k_mcg = 93, folato_mcg = 1 where nome = 'Margarina, com óleo hidrogenado, sem sal (80% de lipídeos)' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 0), ferro_mg = coalesce(ferro_mg, 0), magnesio_mg = 0, fosforo_mg = 0, potassio_mg = 0, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 0), selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 19.1, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 0 where nome = 'Óleo, de babaçu' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set vitamina_e_mg = 17.3 where nome = 'Óleo, de canola' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set vitamina_e_mg = 68.48, vitamina_k_mcg = 6.925 where nome = 'Óleo, de girassol' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 0), ferro_mg = coalesce(ferro_mg, 0), magnesio_mg = 0, fosforo_mg = 0, potassio_mg = 0, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 0), cobre_mcg = 0, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 14.3, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0.2, vitamina_k_mcg = 1.9, folato_mcg = 0 where nome = 'Óleo, de milho' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 0), ferro_mg = coalesce(ferro_mg, 0.05), magnesio_mg = 0, fosforo_mg = 0, potassio_mg = 0, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 0.01), cobre_mcg = 0, manganes_mg = 0, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 8.18, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0.2, vitamina_k_mcg = 183.9, folato_mcg = 0 where nome = 'Óleo, de soja' and fonte = 'TACO' and id_avaliador is null;
