-- Micronutrientes pra "Leite e derivados" (24 itens) — mesma
-- metodologia da Frutas/Carnes/Verduras/Cereais/Gorduras (0054-0063),
-- fonte USDA FoodData Central.
--
-- Erro sistemático grave: quase todo queijo (mussarela, parmesão,
-- pasteurizado, prato, ricota) tinha sido casado com uma entrada
-- genérica "Cheese" sem tipo definido — provavelmente um registro de
-- baixa qualidade da USDA que virou curinga do algoritmo sempre que não
-- achava nada melhor. Cada tipo de queijo tem composição mineral muito
-- diferente (cálcio do parmesão é o triplo do da mussarela, por
-- exemplo), então troquei cada um pelo tipo específico da USDA mais
-- parecido. Outros erros: leite condensado/de cabra/fermentado tinham
-- sido casados com leite de vaca comum (2%); achocolatado casado com
-- milkshake; leite em pó integral casado com uma bebida substituta de
-- café à base de cereal (nada a ver); iogurtes de fruta casados com
-- iogurte de SOJA (Silk brand) — espécie de matéria-prima errada.
--
-- 22 de 24 itens aprovados. Ficaram de fora: "Queijo, petit suisse,
-- morango" (sobremesa láctea cremosa açucarada, só achei comida de bebê
-- como candidato na USDA) e "Bebida láctea, pêssego" (bebida à base de
-- soro de leite, sem equivalente USDA razoável).

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 69), ferro_mg = coalesce(ferro_mg, 0.03), magnesio_mg = 7, fosforo_mg = 61, potassio_mg = 97, sodio_mg = coalesce(sodio_mg, 34), zinco_mg = coalesce(zinco_mg, 0.25), cobre_mcg = 7, manganes_mg = 0.001, selenio_mcg = 0.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 279), vitamina_e_mg = 0.88, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.6), vitamina_c_mg = coalesce(vitamina_c_mg, 0.6), tiamina_mg = coalesce(tiamina_mg, 0.024), riboflavina_mg = coalesce(riboflavina_mg, 0.125), niacina_mg = coalesce(niacina_mg, 0.042), acido_pantotenico_mg = 0.259, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.028), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.2), colina_mg = 16.8, vitamina_k_mcg = 2.7, folato_mcg = 4 where nome = 'Creme de Leite' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 121), ferro_mg = coalesce(ferro_mg, 0.05), magnesio_mg = 12, fosforo_mg = 95, potassio_mg = 155, sodio_mg = coalesce(sodio_mg, 46), zinco_mg = coalesce(zinco_mg, 0.59), cobre_mcg = 9, manganes_mg = 0.004, selenio_mcg = 2.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 27), vitamina_e_mg = 0.06, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0.5), tiamina_mg = coalesce(tiamina_mg, 0.029), riboflavina_mg = coalesce(riboflavina_mg, 0.142), niacina_mg = coalesce(niacina_mg, 0.075), acido_pantotenico_mg = 0.389, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.032), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.37), colina_mg = 15.2, vitamina_k_mcg = 0.2, folato_mcg = 7 where nome = 'Iogurte, natural' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 199), ferro_mg = coalesce(ferro_mg, 0.09), magnesio_mg = 19, fosforo_mg = 157, potassio_mg = 255, sodio_mg = coalesce(sodio_mg, 77), zinco_mg = coalesce(zinco_mg, 0.97), cobre_mcg = 15, manganes_mg = 0.005, selenio_mcg = 3.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.9), tiamina_mg = coalesce(tiamina_mg, 0.048), riboflavina_mg = coalesce(riboflavina_mg, 0.234), niacina_mg = coalesce(niacina_mg, 0.124), acido_pantotenico_mg = 0.641, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.053), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.61), colina_mg = 15.2, vitamina_k_mcg = 0.2, folato_mcg = 12 where nome = 'Iogurte, natural, desnatado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 92), ferro_mg = coalesce(ferro_mg, 0.03), sodio_mg = coalesce(sodio_mg, 33), vitamina_a_mcg = coalesce(vitamina_a_mcg, 21), vitamina_c_mg = coalesce(vitamina_c_mg, 2.2) where nome = 'Iogurte, sabor abacaxi' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 152), ferro_mg = coalesce(ferro_mg, 0.07), magnesio_mg = 15, fosforo_mg = 119, potassio_mg = 195, sodio_mg = coalesce(sodio_mg, 58), zinco_mg = coalesce(zinco_mg, 0.74), cobre_mcg = 80, manganes_mg = 0.065, selenio_mcg = 3.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 10), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.7), tiamina_mg = coalesce(tiamina_mg, 0.037), riboflavina_mg = coalesce(riboflavina_mg, 0.178), niacina_mg = coalesce(niacina_mg, 0.095), acido_pantotenico_mg = 0.489, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.04), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.47), colina_mg = 14, vitamina_k_mcg = 0.1, folato_mcg = 9 where nome = 'Iogurte, sabor morango' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 152), ferro_mg = coalesce(ferro_mg, 0.07), magnesio_mg = 15, fosforo_mg = 119, potassio_mg = 195, sodio_mg = coalesce(sodio_mg, 58), zinco_mg = coalesce(zinco_mg, 0.74), cobre_mcg = 80, manganes_mg = 0.065, selenio_mcg = 3.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 10), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.7), tiamina_mg = coalesce(tiamina_mg, 0.037), riboflavina_mg = coalesce(riboflavina_mg, 0.178), niacina_mg = coalesce(niacina_mg, 0.095), acido_pantotenico_mg = 0.489, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.04), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.47), colina_mg = 14, vitamina_k_mcg = 0.1, folato_mcg = 9 where nome = 'Iogurte, sabor pêssego' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 284), ferro_mg = coalesce(ferro_mg, 0.19), magnesio_mg = 26, fosforo_mg = 253, potassio_mg = 371, sodio_mg = coalesce(sodio_mg, 127), zinco_mg = coalesce(zinco_mg, 0.94), cobre_mcg = 15, manganes_mg = 0.006, selenio_mcg = 14.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 74), vitamina_e_mg = 0.16, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.2), vitamina_c_mg = coalesce(vitamina_c_mg, 2.6), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.416), niacina_mg = coalesce(niacina_mg, 0.21), acido_pantotenico_mg = 0.75, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.051), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.44), colina_mg = 89.1, vitamina_k_mcg = 0.6, folato_mcg = 11 where nome = 'Leite, condensado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 134), ferro_mg = coalesce(ferro_mg, 0.05), magnesio_mg = 14, fosforo_mg = 111, potassio_mg = 204, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 0.3), cobre_mcg = 46, manganes_mg = 0.018, selenio_mcg = 1.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 57), vitamina_e_mg = 0.07, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.3), vitamina_c_mg = coalesce(vitamina_c_mg, 1.3), tiamina_mg = coalesce(tiamina_mg, 0.048), riboflavina_mg = coalesce(riboflavina_mg, 0.138), niacina_mg = coalesce(niacina_mg, 0.277), acido_pantotenico_mg = 0.31, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.046), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.07), colina_mg = 16, vitamina_k_mcg = 0.3, folato_mcg = 1 where nome = 'Leite, de cabra' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 112), ferro_mg = coalesce(ferro_mg, 0.24), magnesio_mg = 13, fosforo_mg = 101, potassio_mg = 167, sodio_mg = coalesce(sodio_mg, 60), zinco_mg = coalesce(zinco_mg, 0.41), cobre_mcg = 65, manganes_mg = 0.077, selenio_mcg = 1.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 27), vitamina_e_mg = 0.07, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0.9), tiamina_mg = coalesce(tiamina_mg, 0.037), riboflavina_mg = coalesce(riboflavina_mg, 0.162), niacina_mg = coalesce(niacina_mg, 0.125), acido_pantotenico_mg = 0.295, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.04), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.33), colina_mg = 17, vitamina_k_mcg = 0.3, folato_mcg = 5 where nome = 'Leite, de vaca, achocolatado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 204), ferro_mg = coalesce(ferro_mg, 0.04), magnesio_mg = 11, fosforo_mg = 101, potassio_mg = 166, sodio_mg = coalesce(sodio_mg, 52), zinco_mg = coalesce(zinco_mg, 0.4), cobre_mcg = 11, selenio_mcg = 2.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 137), vitamina_e_mg = 0.01, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.2), vitamina_c_mg = coalesce(vitamina_c_mg, 1), tiamina_mg = coalesce(tiamina_mg, 0.036), riboflavina_mg = coalesce(riboflavina_mg, 0.14), niacina_mg = coalesce(niacina_mg, 0.088), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.04), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.38), colina_mg = 16, vitamina_k_mcg = 0, folato_mcg = 5 where nome = 'Leite, de vaca, desnatado, pó' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 204), ferro_mg = coalesce(ferro_mg, 0.04), magnesio_mg = 11, fosforo_mg = 101, potassio_mg = 166, sodio_mg = coalesce(sodio_mg, 52), zinco_mg = coalesce(zinco_mg, 0.4), cobre_mcg = 11, selenio_mcg = 2.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 137), vitamina_e_mg = 0.01, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.2), vitamina_c_mg = coalesce(vitamina_c_mg, 1), tiamina_mg = coalesce(tiamina_mg, 0.036), riboflavina_mg = coalesce(riboflavina_mg, 0.14), niacina_mg = coalesce(niacina_mg, 0.088), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.04), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.38), colina_mg = 16, vitamina_k_mcg = 0, folato_mcg = 5 where nome = 'Leite, de vaca, desnatado, UHT' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 113), ferro_mg = coalesce(ferro_mg, 0.03), magnesio_mg = 10, fosforo_mg = 84, potassio_mg = 132, sodio_mg = coalesce(sodio_mg, 43), zinco_mg = coalesce(zinco_mg, 0.37), cobre_mcg = 25, manganes_mg = 0.004, selenio_mcg = 3.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 46), vitamina_e_mg = 0.07, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.046), riboflavina_mg = coalesce(riboflavina_mg, 0.169), niacina_mg = coalesce(niacina_mg, 0.089), acido_pantotenico_mg = 0.373, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.45), colina_mg = 14.3, vitamina_k_mcg = 0.3, folato_mcg = 5 where nome = 'Leite, de vaca, integral' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 912), ferro_mg = coalesce(ferro_mg, 0.47), magnesio_mg = 85, fosforo_mg = 776, potassio_mg = 1330, sodio_mg = coalesce(sodio_mg, 371), zinco_mg = coalesce(zinco_mg, 3.34), cobre_mcg = 80, manganes_mg = 0.04, selenio_mcg = 16.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 258), vitamina_e_mg = 0.58, vitamina_d_mcg = coalesce(vitamina_d_mcg, 10.5), vitamina_c_mg = coalesce(vitamina_c_mg, 8.6), tiamina_mg = coalesce(tiamina_mg, 0.283), riboflavina_mg = coalesce(riboflavina_mg, 1.205), niacina_mg = coalesce(niacina_mg, 0.646), acido_pantotenico_mg = 2.271, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.302), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.25), colina_mg = 119.3, vitamina_k_mcg = 2.2, folato_mcg = 37 where nome = 'Leite, de vaca, integral, pó' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 130), ferro_mg = coalesce(ferro_mg, 0.04), magnesio_mg = 12, fosforo_mg = 105, potassio_mg = 164, sodio_mg = coalesce(sodio_mg, 40), zinco_mg = coalesce(zinco_mg, 0.46), cobre_mcg = 9, manganes_mg = 0.005, selenio_mcg = 3.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 171), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1), vitamina_c_mg = coalesce(vitamina_c_mg, 0.2), tiamina_mg = coalesce(tiamina_mg, 0.03), riboflavina_mg = coalesce(riboflavina_mg, 0.135), niacina_mg = coalesce(niacina_mg, 0.15), acido_pantotenico_mg = 0.385, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.058), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.29), colina_mg = 15.2, vitamina_k_mcg = 0.1, folato_mcg = 13 where nome = 'Leite, fermentado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 566), ferro_mg = coalesce(ferro_mg, 0.2), magnesio_mg = 24, fosforo_mg = 385, potassio_mg = 129, sodio_mg = coalesce(sodio_mg, 751), zinco_mg = coalesce(zinco_mg, 2.58), cobre_mcg = 33, manganes_mg = 0.014, selenio_mcg = 19.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 224), vitamina_e_mg = 0.37, vitamina_d_mcg = coalesce(vitamina_d_mcg, 2.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.042), riboflavina_mg = coalesce(riboflavina_mg, 0.173), niacina_mg = coalesce(niacina_mg, 0.027), acido_pantotenico_mg = 0.358, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.076), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.68), colina_mg = 12.5, vitamina_k_mcg = 1, folato_mcg = 7 where nome = 'Queijo, minas, frescal' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 566), ferro_mg = coalesce(ferro_mg, 0.2), magnesio_mg = 24, fosforo_mg = 385, potassio_mg = 129, sodio_mg = coalesce(sodio_mg, 751), zinco_mg = coalesce(zinco_mg, 2.58), cobre_mcg = 33, manganes_mg = 0.014, selenio_mcg = 19.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 224), vitamina_e_mg = 0.37, vitamina_d_mcg = coalesce(vitamina_d_mcg, 2.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.042), riboflavina_mg = coalesce(riboflavina_mg, 0.173), niacina_mg = coalesce(niacina_mg, 0.027), acido_pantotenico_mg = 0.358, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.076), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.68), colina_mg = 12.5, vitamina_k_mcg = 1, folato_mcg = 7 where nome = 'Queijo, minas, meia cura' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 575), ferro_mg = coalesce(ferro_mg, 0.2), magnesio_mg = 21, fosforo_mg = 412, potassio_mg = 75, sodio_mg = coalesce(sodio_mg, 710), zinco_mg = coalesce(zinco_mg, 2.46), cobre_mcg = 22, manganes_mg = 0.009, selenio_mcg = 16.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 197), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.016), riboflavina_mg = coalesce(riboflavina_mg, 0.27), niacina_mg = coalesce(niacina_mg, 0.094), acido_pantotenico_mg = 0.071, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.062), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.73), colina_mg = 15, vitamina_k_mcg = 2.5, folato_mcg = 8 where nome = 'Queijo, mozarela' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1184), ferro_mg = coalesce(ferro_mg, 0.82), magnesio_mg = 44, fosforo_mg = 694, potassio_mg = 92, sodio_mg = coalesce(sodio_mg, 1175), zinco_mg = coalesce(zinco_mg, 2.75), cobre_mcg = 32, manganes_mg = 0.02, selenio_mcg = 22.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 207), vitamina_e_mg = 0.22, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.039), riboflavina_mg = coalesce(riboflavina_mg, 0.332), niacina_mg = coalesce(niacina_mg, 0.271), acido_pantotenico_mg = 0.453, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.091), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.2), colina_mg = 15.4, vitamina_k_mcg = 1.7, folato_mcg = 7 where nome = 'Queijo, parmesão' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 575), ferro_mg = coalesce(ferro_mg, 0.2), magnesio_mg = 21, fosforo_mg = 412, potassio_mg = 75, sodio_mg = coalesce(sodio_mg, 710), zinco_mg = coalesce(zinco_mg, 2.46), cobre_mcg = 22, manganes_mg = 0.009, selenio_mcg = 16.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 197), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.016), riboflavina_mg = coalesce(riboflavina_mg, 0.27), niacina_mg = coalesce(niacina_mg, 0.094), acido_pantotenico_mg = 0.071, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.062), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.73), colina_mg = 15, vitamina_k_mcg = 2.5, folato_mcg = 8 where nome = 'Queijo, pasteurizado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 685), ferro_mg = coalesce(ferro_mg, 0.76), magnesio_mg = 26, fosforo_mg = 457, potassio_mg = 127, sodio_mg = coalesce(sodio_mg, 604), zinco_mg = coalesce(zinco_mg, 3.07), cobre_mcg = 42, manganes_mg = 0.012, selenio_mcg = 14.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 264), vitamina_e_mg = 0.28, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.6), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.015), riboflavina_mg = coalesce(riboflavina_mg, 0.375), niacina_mg = coalesce(niacina_mg, 0.093), acido_pantotenico_mg = 0.21, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.079), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.83), colina_mg = 15.4, vitamina_k_mcg = 2.7, folato_mcg = 18 where nome = 'Queijo, prato' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 97), ferro_mg = coalesce(ferro_mg, 0.11), magnesio_mg = 9, fosforo_mg = 107, potassio_mg = 132, sodio_mg = coalesce(sodio_mg, 314), zinco_mg = coalesce(zinco_mg, 0.5), cobre_mcg = 18, manganes_mg = 0.011, selenio_mcg = 8.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 308), vitamina_e_mg = 0.86, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.023), riboflavina_mg = coalesce(riboflavina_mg, 0.23), niacina_mg = coalesce(niacina_mg, 0.091), acido_pantotenico_mg = 0.517, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.056), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.22), colina_mg = 26.8, vitamina_k_mcg = 2.1, folato_mcg = 9 where nome = 'Queijo, requeijão, cremoso' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 206), ferro_mg = coalesce(ferro_mg, 0.13), magnesio_mg = 20, fosforo_mg = 154, potassio_mg = 219, sodio_mg = coalesce(sodio_mg, 110), zinco_mg = coalesce(zinco_mg, 0.53), cobre_mcg = 18, manganes_mg = 0.011, selenio_mcg = 5.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 120), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.013), riboflavina_mg = coalesce(riboflavina_mg, 0.298), niacina_mg = coalesce(niacina_mg, 0.137), acido_pantotenico_mg = 0.461, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.097), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.85), colina_mg = 17.5, vitamina_k_mcg = 1.1, folato_mcg = 4 where nome = 'Queijo, ricota' and fonte = 'TACO' and id_avaliador is null;
