-- Micronutrientes pra "Bebidas (alcoólicas e não alcoólicas)" (14
-- itens) — mesma metodologia das categorias anteriores (0054-0064),
-- fonte USDA FoodData Central.
--
-- Erros corrigidos: café coado tinha sido casado com "SILK Coffee"
-- (bebida de soja com sabor café, não é café puro); os 3 chás
-- (erva-doce, mate, preto) tinham sido casados com um chá de erva
-- nativa norte-americana obscura (Hohoysi/Hopi), sem relação com
-- nenhum dos três; água de coco tinha sido casada com ÓLEO de coco
-- (produtos opostos — um é líquido aquoso, outro é gordura pura);
-- refrigerantes de cola/água tônica tinham sido casados com "cream
-- soda" genérico.
--
-- 11 de 14 itens aprovados. Ficaram de fora: chá de erva-doce e chá
-- mate (sem equivalente USDA — erva-mate é exclusivamente sul-
-- americana) e caldo de cana (sem equivalente USDA).

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1), ferro_mg = coalesce(ferro_mg, 0.05), magnesio_mg = 0, fosforo_mg = 10, potassio_mg = 15, sodio_mg = coalesce(sodio_mg, 39), zinco_mg = coalesce(zinco_mg, 0.01), cobre_mcg = 6, manganes_mg = 0.013, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.4), tiamina_mg = coalesce(tiamina_mg, 0.011), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0.22), acido_pantotenico_mg = 0.055, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.022), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0, vitamina_k_mcg = 0.2, folato_mcg = 0 where nome = 'Bebida isotônica, sabores variados' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 2), ferro_mg = coalesce(ferro_mg, 0.01), magnesio_mg = 3, fosforo_mg = 3, potassio_mg = 49, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 0.02), cobre_mcg = 2, manganes_mg = 0.023, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.01, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.014), riboflavina_mg = coalesce(riboflavina_mg, 0.076), niacina_mg = coalesce(niacina_mg, 0.191), acido_pantotenico_mg = 0.254, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.001), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 2.6, vitamina_k_mcg = 0.1, folato_mcg = 2 where nome = 'Café, infusão 10%' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 0), ferro_mg = coalesce(ferro_mg, 0.04), magnesio_mg = 0, fosforo_mg = 4, potassio_mg = 2, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.04), cobre_mcg = 21, manganes_mg = 0.018, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.006), riboflavina_mg = coalesce(riboflavina_mg, 0.004), niacina_mg = coalesce(niacina_mg, 0.013), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.001), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Cana, aguardente 1' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 4), ferro_mg = coalesce(ferro_mg, 0.02), magnesio_mg = 6, fosforo_mg = 14, potassio_mg = 27, sodio_mg = coalesce(sodio_mg, 4), zinco_mg = coalesce(zinco_mg, 0.01), cobre_mcg = 5, manganes_mg = 0.008, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.005), riboflavina_mg = coalesce(riboflavina_mg, 0.025), niacina_mg = coalesce(niacina_mg, 0.513), acido_pantotenico_mg = 0.041, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.046), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.02), colina_mg = 10.1, vitamina_k_mcg = 0, folato_mcg = 6 where nome = 'Cerveja, pilsen 2' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 0), ferro_mg = coalesce(ferro_mg, 0.02), magnesio_mg = 3, fosforo_mg = 1, potassio_mg = 37, sodio_mg = coalesce(sodio_mg, 3), zinco_mg = coalesce(zinco_mg, 0.02), cobre_mcg = 10, manganes_mg = 0.219, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0.014), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0.011, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0.4, vitamina_k_mcg = 0, folato_mcg = 5 where nome = 'Chá, preto, infusão 5%' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7), ferro_mg = coalesce(ferro_mg, 0.03), magnesio_mg = 6, fosforo_mg = 5, potassio_mg = 165, sodio_mg = coalesce(sodio_mg, 26), zinco_mg = coalesce(zinco_mg, 0.02), cobre_mcg = 8, manganes_mg = 0.221, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 9.9), tiamina_mg = coalesce(tiamina_mg, 0.03), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Coco, água de' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1), ferro_mg = coalesce(ferro_mg, 0.01), magnesio_mg = 0, fosforo_mg = 0, potassio_mg = 0, sodio_mg = coalesce(sodio_mg, 12), zinco_mg = coalesce(zinco_mg, 0.1), cobre_mcg = 6, manganes_mg = 0.001, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Refrigerante, tipo água tônica' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1), ferro_mg = coalesce(ferro_mg, 0.02), magnesio_mg = 0, fosforo_mg = 9, potassio_mg = 5, sodio_mg = coalesce(sodio_mg, 3), zinco_mg = coalesce(zinco_mg, 0.09), cobre_mcg = 7, manganes_mg = 0.003, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0.3, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Refrigerante, tipo cola' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1), ferro_mg = coalesce(ferro_mg, 0.02), magnesio_mg = 0, fosforo_mg = 9, potassio_mg = 5, sodio_mg = coalesce(sodio_mg, 3), zinco_mg = coalesce(zinco_mg, 0.09), cobre_mcg = 7, manganes_mg = 0.003, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0.3, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Refrigerante, tipo guaraná' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 5), ferro_mg = coalesce(ferro_mg, 0.06), magnesio_mg = 1, fosforo_mg = 1, potassio_mg = 2, sodio_mg = coalesce(sodio_mg, 12), zinco_mg = coalesce(zinco_mg, 0.1), cobre_mcg = 15, manganes_mg = 0.013, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0.6, folato_mcg = 0 where nome = 'Refrigerante, tipo laranja' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 2), ferro_mg = coalesce(ferro_mg, 0.02), magnesio_mg = 1, fosforo_mg = 0, potassio_mg = 1, sodio_mg = coalesce(sodio_mg, 10), zinco_mg = coalesce(zinco_mg, 0.01), cobre_mcg = 0, manganes_mg = 0, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0.015), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0.4, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Refrigerante, tipo limão' and fonte = 'TACO' and id_avaliador is null;
