-- Micronutrientes pra "Ovos e derivados" (7 itens) — mesma metodologia
-- das categorias anteriores (0054-0065), fonte USDA FoodData Central.
--
-- Erro corrigido: "Ovo, de codorna" (ovo de codorna) tinha sido casado
-- com ovo de GALINHA — espécie errada, e ovo de codorna tem densidade
-- de micronutrientes bem maior (ferro quase o dobro, por exemplo).
-- "Ovo, de galinha, inteiro, frito" e "Omelete, de queijo" não tinham
-- match algum, resolvidos com busca direta.
--
-- Todos os 7 itens aprovados. Nota: os fdc_ids originais pra clara/
-- gema/inteiro cozidos (10 min) eram amostras da USDA sem nutrientes
-- carregados — usei o correspondente cru (clara/gema) ou a versão
-- "hard-boiled" (ovo inteiro), já que cozer não muda os minerais de
-- forma relevante. "Omelete, de queijo" usa a base de ovo cozido em
-- omelete simples — sem o acréscimo específico do queijo, por não
-- achar uma entrada USDA de omelete de queijo pronta.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 48), ferro_mg = coalesce(ferro_mg, 1.48), magnesio_mg = 11, fosforo_mg = 167, potassio_mg = 117, sodio_mg = coalesce(sodio_mg, 155), zinco_mg = coalesce(zinco_mg, 1.09), cobre_mcg = 63, manganes_mg = 0.024, selenio_mcg = 25.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 172), vitamina_e_mg = 1.29, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.034), riboflavina_mg = coalesce(riboflavina_mg, 0.386), niacina_mg = coalesce(niacina_mg, 0.064), acido_pantotenico_mg = 1.289, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.143), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.76), colina_mg = 247.6, vitamina_k_mcg = 4.5, folato_mcg = 39 where nome = 'Omelete, de queijo' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 64), ferro_mg = coalesce(ferro_mg, 3.65), magnesio_mg = 13, fosforo_mg = 226, potassio_mg = 132, sodio_mg = coalesce(sodio_mg, 141), zinco_mg = coalesce(zinco_mg, 1.47), cobre_mcg = 62, manganes_mg = 0.038, selenio_mcg = 32, vitamina_a_mcg = coalesce(vitamina_a_mcg, 156), vitamina_e_mg = 1.08, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.4), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.13), riboflavina_mg = coalesce(riboflavina_mg, 0.79), niacina_mg = coalesce(niacina_mg, 0.15), acido_pantotenico_mg = 1.761, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.15), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.58), colina_mg = 263.4, vitamina_k_mcg = 0.3, folato_mcg = 66 where nome = 'Ovo, de codorna, inteiro, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7), ferro_mg = coalesce(ferro_mg, 0.08), magnesio_mg = 11, fosforo_mg = 15, potassio_mg = 163, sodio_mg = coalesce(sodio_mg, 166), zinco_mg = coalesce(zinco_mg, 0.03), cobre_mcg = 23, manganes_mg = 0.011, selenio_mcg = 20, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.004), riboflavina_mg = coalesce(riboflavina_mg, 0.439), niacina_mg = coalesce(niacina_mg, 0.105), acido_pantotenico_mg = 0.19, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.005), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.09), colina_mg = 1.1, vitamina_k_mcg = 0, folato_mcg = 4 where nome = 'Ovo, de galinha, clara, cozida/10minutos' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 129), ferro_mg = coalesce(ferro_mg, 2.73), magnesio_mg = 5, fosforo_mg = 390, potassio_mg = 109, sodio_mg = coalesce(sodio_mg, 48), zinco_mg = coalesce(zinco_mg, 2.3), cobre_mcg = 77, manganes_mg = 0.055, selenio_mcg = 56, vitamina_a_mcg = coalesce(vitamina_a_mcg, 381), vitamina_e_mg = 2.58, vitamina_d_mcg = coalesce(vitamina_d_mcg, 5.4), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.176), riboflavina_mg = coalesce(riboflavina_mg, 0.528), niacina_mg = coalesce(niacina_mg, 0.024), acido_pantotenico_mg = 2.99, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.35), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.95), colina_mg = 820.2, vitamina_k_mcg = 0.7, folato_mcg = 146 where nome = 'Ovo, de galinha, gema, cozida/10minutos' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 50), ferro_mg = coalesce(ferro_mg, 1.19), magnesio_mg = 10, fosforo_mg = 172, potassio_mg = 126, sodio_mg = coalesce(sodio_mg, 124), zinco_mg = coalesce(zinco_mg, 1.05), cobre_mcg = 13, manganes_mg = 0.026, selenio_mcg = 30.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 149), vitamina_e_mg = 1.03, vitamina_d_mcg = coalesce(vitamina_d_mcg, 2.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.066), riboflavina_mg = coalesce(riboflavina_mg, 0.513), niacina_mg = coalesce(niacina_mg, 0.064), acido_pantotenico_mg = 1.398, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.121), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.11), colina_mg = 293.8, vitamina_k_mcg = 0.3, folato_mcg = 44 where nome = 'Ovo, de galinha, inteiro, cozido/10minutos' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 56), ferro_mg = coalesce(ferro_mg, 1.75), magnesio_mg = 12, fosforo_mg = 198, potassio_mg = 138, sodio_mg = coalesce(sodio_mg, 142), zinco_mg = coalesce(zinco_mg, 1.29), cobre_mcg = 72, manganes_mg = 0.028, selenio_mcg = 30.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 160), vitamina_e_mg = 1.05, vitamina_d_mcg = coalesce(vitamina_d_mcg, 2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.04), riboflavina_mg = coalesce(riboflavina_mg, 0.457), niacina_mg = coalesce(niacina_mg, 0.075), acido_pantotenico_mg = 1.533, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.17), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.89), colina_mg = 293.8, vitamina_k_mcg = 0.3, folato_mcg = 47 where nome = 'Ovo, de galinha, inteiro, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 62), ferro_mg = coalesce(ferro_mg, 1.89), magnesio_mg = 13, fosforo_mg = 215, potassio_mg = 152, sodio_mg = coalesce(sodio_mg, 207), zinco_mg = coalesce(zinco_mg, 1.39), cobre_mcg = 78, manganes_mg = 0.03, selenio_mcg = 33.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 219), vitamina_e_mg = 1.31, vitamina_d_mcg = coalesce(vitamina_d_mcg, 2.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.044), riboflavina_mg = coalesce(riboflavina_mg, 0.495), niacina_mg = coalesce(niacina_mg, 0.082), acido_pantotenico_mg = 1.66, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.184), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.97), colina_mg = 317.1, vitamina_k_mcg = 5.6, folato_mcg = 51 where nome = 'Ovo, de galinha, inteiro, frito' and fonte = 'TACO' and id_avaliador is null;
