-- Micronutrientes pra "Produtos açucarados" (20 itens) — mesma
-- metodologia das categorias anteriores (0054-0066), fonte USDA
-- FoodData Central.
--
-- Erros corrigidos: açúcar cristal/refinado (branco) tinham sido
-- casados com açúcar MASCAVO (marrom, com melaço — mineral bem
-- diferente); chocolate meio amargo tinha sido casado com bebida de
-- soja sabor chocolate; doce de leite cremoso tinha sido casado com
-- bala de chocolate ao leite (achei "Dulce de Leche" direto na USDA,
-- produto certo).
--
-- 13 de 20 itens aprovados. Ficaram de fora: chocolate dietético (sem
-- equivalente USDA de chocolate diet/sem açúcar — usar um chocolate
-- comum distorceria o teor de açúcar), cocada branca, doce de abóbora,
-- geleia de mocotó, marmelada, melado e quindim (doces/preparos
-- caseiros brasileiros específicos sem equivalente USDA razoável).

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 60), ferro_mg = coalesce(ferro_mg, 2.28), magnesio_mg = 70, fosforo_mg = 175, potassio_mg = 618, sodio_mg = coalesce(sodio_mg, 190), zinco_mg = coalesce(zinco_mg, 0.8), cobre_mcg = 200, selenio_mcg = 6.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 33), vitamina_e_mg = 0.17, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.5), tiamina_mg = coalesce(tiamina_mg, 0.173), riboflavina_mg = coalesce(riboflavina_mg, 0.2), niacina_mg = coalesce(niacina_mg, 2.003), acido_pantotenico_mg = 0.316, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.156), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.42), colina_mg = 27.2, vitamina_k_mcg = 2.5, folato_mcg = 50 where nome = 'Achocolatado, pó' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1), ferro_mg = coalesce(ferro_mg, 0.05), magnesio_mg = 0, fosforo_mg = 0, potassio_mg = 2, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.01), cobre_mcg = 7, manganes_mg = 0.004, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0.019), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Açúcar, cristal' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 83), ferro_mg = coalesce(ferro_mg, 0.71), magnesio_mg = 9, fosforo_mg = 4, potassio_mg = 133, sodio_mg = coalesce(sodio_mg, 28), zinco_mg = coalesce(zinco_mg, 0.03), cobre_mcg = 47, manganes_mg = 0.064, selenio_mcg = 1.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0.11), acido_pantotenico_mg = 0.132, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.041), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 2.3, vitamina_k_mcg = 0, folato_mcg = 1 where nome = 'Açúcar, mascavo' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1), ferro_mg = coalesce(ferro_mg, 0.05), magnesio_mg = 0, fosforo_mg = 0, potassio_mg = 2, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.01), cobre_mcg = 7, manganes_mg = 0.004, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0.019), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Açúcar, refinado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 116), ferro_mg = coalesce(ferro_mg, 1.23), sodio_mg = coalesce(sodio_mg, 68), vitamina_c_mg = coalesce(vitamina_c_mg, 0.6) where nome = 'Chocolate, ao leite' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 116), ferro_mg = coalesce(ferro_mg, 1.23), sodio_mg = coalesce(sodio_mg, 68), vitamina_c_mg = coalesce(vitamina_c_mg, 0.6) where nome = 'Chocolate, ao leite, com castanha do Pará' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 62), ferro_mg = coalesce(ferro_mg, 6.32), magnesio_mg = 176, fosforo_mg = 260, potassio_mg = 567, sodio_mg = coalesce(sodio_mg, 10), zinco_mg = coalesce(zinco_mg, 2.65), cobre_mcg = 1248, manganes_mg = 1.325, selenio_mcg = 8.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.59, tiamina_mg = coalesce(tiamina_mg, 0.032), riboflavina_mg = coalesce(riboflavina_mg, 0.049), niacina_mg = coalesce(niacina_mg, 0.838), acido_pantotenico_mg = 0.3, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.034), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.18), vitamina_k_mcg = 7.2 where nome = 'Chocolate, meio amargo' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 251), ferro_mg = coalesce(ferro_mg, 0.17), magnesio_mg = 22, fosforo_mg = 193, potassio_mg = 350, sodio_mg = coalesce(sodio_mg, 129), zinco_mg = coalesce(zinco_mg, 0.79), cobre_mcg = 4, manganes_mg = 0.002, selenio_mcg = 2.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 74), vitamina_e_mg = 0.2, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.2), vitamina_c_mg = coalesce(vitamina_c_mg, 2.6), tiamina_mg = coalesce(tiamina_mg, 0.016), riboflavina_mg = coalesce(riboflavina_mg, 0.405), niacina_mg = coalesce(niacina_mg, 0.21), acido_pantotenico_mg = 0.835, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.016), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.31), colina_mg = 89.1, vitamina_k_mcg = 1.3, folato_mcg = 11 where nome = 'Doce, de leite, cremoso' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 13), ferro_mg = coalesce(ferro_mg, 0), magnesio_mg = 1, fosforo_mg = 0, potassio_mg = 1, sodio_mg = coalesce(sodio_mg, 62), zinco_mg = coalesce(zinco_mg, 0.44), cobre_mcg = 0, manganes_mg = 0, selenio_mcg = 0.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.059), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Glicose de milho' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 3), ferro_mg = coalesce(ferro_mg, 0.23), magnesio_mg = 2, fosforo_mg = 8, potassio_mg = 5, sodio_mg = coalesce(sodio_mg, 80), zinco_mg = coalesce(zinco_mg, 0.04), cobre_mcg = 97, manganes_mg = 0.008, selenio_mcg = 1.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.001), riboflavina_mg = coalesce(riboflavina_mg, 0.001), niacina_mg = coalesce(niacina_mg, 0.078), acido_pantotenico_mg = 0.005, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.003), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0.1, vitamina_k_mcg = 0, folato_mcg = 1 where nome = 'Maria mole' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 3), ferro_mg = coalesce(ferro_mg, 0.23), magnesio_mg = 2, fosforo_mg = 8, potassio_mg = 5, sodio_mg = coalesce(sodio_mg, 80), zinco_mg = coalesce(zinco_mg, 0.04), cobre_mcg = 97, manganes_mg = 0.008, selenio_mcg = 1.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.001), riboflavina_mg = coalesce(riboflavina_mg, 0.001), niacina_mg = coalesce(niacina_mg, 0.078), acido_pantotenico_mg = 0.005, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.003), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0.1, vitamina_k_mcg = 0, folato_mcg = 1 where nome = 'Maria mole, coco queimado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 0.42), magnesio_mg = 2, fosforo_mg = 4, potassio_mg = 52, sodio_mg = coalesce(sodio_mg, 4), zinco_mg = coalesce(zinco_mg, 0.22), cobre_mcg = 36, manganes_mg = 0.08, selenio_mcg = 0.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.5), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0.038), niacina_mg = coalesce(niacina_mg, 0.121), acido_pantotenico_mg = 0.068, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.024), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 2.2, vitamina_k_mcg = 0, folato_mcg = 2 where nome = 'Mel, de abelha' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 12), ferro_mg = coalesce(ferro_mg, 0.37), magnesio_mg = 2, fosforo_mg = 1, potassio_mg = 29, sodio_mg = coalesce(sodio_mg, 3), zinco_mg = coalesce(zinco_mg, 0.03), cobre_mcg = 9, manganes_mg = 0.046 where nome = 'Rapadura' and fonte = 'TACO' and id_avaliador is null;
