-- Micronutrientes pra "Miscelâneas" (9 itens) — mesma metodologia das
-- categorias anteriores (0054-0067), fonte USDA FoodData Central.
--
-- Sem erros graves nessa categoria — a maioria simplesmente não tinha
-- match algum. Resolvido com busca direta: fermento em pó (baking
-- powder), fermento biológico em tablete (levedura compressa), gelatina
-- em pó sem sabor, e "Shoyu" que por coincidência tem uma entrada da
-- USDA com esse nome exato ("Soy sauce made from soy and wheat
-- (shoyu)"). Os valores de fermento em pó parecem altos à primeira
-- vista (cálcio/fósforo na casa dos milhares de mg por 100g), mas isso
-- é esperado — é um produto concentrado usado em quantidades pequenas
-- (1 colher de chá ~ 4g), não um alimento consumido em porções de
-- 100g.
--
-- 6 de 9 itens aprovados. Ficaram de fora: cappuccino em pó (sem
-- equivalente USDA), sal dietético (substituto de sódio por potássio —
-- perfil mineral oposto ao sal comum, sem equivalente USDA) e tempero à
-- base de sal (mistura industrializada variável demais).

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 141), ferro_mg = coalesce(ferro_mg, 4.41), magnesio_mg = 327, fosforo_mg = 303, potassio_mg = 3535, sodio_mg = coalesce(sodio_mg, 37), zinco_mg = coalesce(zinco_mg, 0.35), cobre_mcg = 139, manganes_mg = 1.712, selenio_mcg = 12.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.008), riboflavina_mg = coalesce(riboflavina_mg, 0.074), niacina_mg = coalesce(niacina_mg, 28.173), acido_pantotenico_mg = 0.097, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.029), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 101.9, vitamina_k_mcg = 1.9, folato_mcg = 0 where nome = 'Café, pó, torrado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7364), ferro_mg = coalesce(ferro_mg, 11.27), magnesio_mg = 39, fosforo_mg = 9918, potassio_mg = 5, sodio_mg = coalesce(sodio_mg, 7893), zinco_mg = coalesce(zinco_mg, 0.02), cobre_mcg = 13, manganes_mg = 0.014, selenio_mcg = 0.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Fermento em pó, químico' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 19), ferro_mg = coalesce(ferro_mg, 3.25), magnesio_mg = 40, fosforo_mg = 336, potassio_mg = 601, sodio_mg = coalesce(sodio_mg, 30), zinco_mg = coalesce(zinco_mg, 9.97), cobre_mcg = 148, manganes_mg = 0.2, selenio_mcg = 8.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.1), tiamina_mg = coalesce(tiamina_mg, 1.88), riboflavina_mg = coalesce(riboflavina_mg, 1.13), niacina_mg = coalesce(niacina_mg, 12.3), acido_pantotenico_mg = 4.9, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.43), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.01), colina_mg = 32, vitamina_k_mcg = 0, folato_mcg = 785 where nome = 'Fermento, biológico, levedura, tablete' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 55), ferro_mg = coalesce(ferro_mg, 1.11), magnesio_mg = 22, fosforo_mg = 39, potassio_mg = 16, sodio_mg = coalesce(sodio_mg, 196), zinco_mg = coalesce(zinco_mg, 0.14), cobre_mcg = 2161, manganes_mg = 0.105, selenio_mcg = 39.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.025), riboflavina_mg = coalesce(riboflavina_mg, 0.23), niacina_mg = coalesce(niacina_mg, 0.085), acido_pantotenico_mg = 0.125, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.007), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 38.5, vitamina_k_mcg = 0, folato_mcg = 30 where nome = 'Gelatina, sabores variados, pó' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 24), ferro_mg = coalesce(ferro_mg, 0.33), magnesio_mg = 1, fosforo_mg = 0, potassio_mg = 8, sodio_mg = coalesce(sodio_mg, 38758), zinco_mg = coalesce(zinco_mg, 0.1), cobre_mcg = 30, manganes_mg = 0.1, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Sal, grosso' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 33), ferro_mg = coalesce(ferro_mg, 1.45), magnesio_mg = 74, fosforo_mg = 166, potassio_mg = 435, sodio_mg = coalesce(sodio_mg, 5493), zinco_mg = coalesce(zinco_mg, 0.87), cobre_mcg = 43, manganes_mg = 1.018, selenio_mcg = 0.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.033), riboflavina_mg = coalesce(riboflavina_mg, 0.165), niacina_mg = coalesce(niacina_mg, 2.196), acido_pantotenico_mg = 0.297, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.148), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 18.3, vitamina_k_mcg = 0, folato_mcg = 14 where nome = 'Shoyu' and fonte = 'TACO' and id_avaliador is null;
