-- Micronutrientes pra "Outros alimentos industrializados" (5 itens) —
-- mesma metodologia das categorias anteriores (0054-0068), fonte USDA
-- FoodData Central.
--
-- Erro corrigido: "Leite, de coco" (leite de coco, produto vegetal)
-- tinha sido casado com leite de vaca 2% — categoria de produto errada
-- (vegetal vs laticínio, composição completamente diferente). Os outros
-- 4 itens simplesmente não tinham match algum, resolvidos com busca
-- direta.
--
-- Todos os 5 itens aprovados.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 88), ferro_mg = coalesce(ferro_mg, 6.28), magnesio_mg = 4, fosforo_mg = 3, potassio_mg = 8, sodio_mg = coalesce(sodio_mg, 735), zinco_mg = coalesce(zinco_mg, 0.22), cobre_mcg = 251, manganes_mg = 0.02, selenio_mcg = 0.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 17), vitamina_e_mg = 1.65, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.9), tiamina_mg = coalesce(tiamina_mg, 0.003), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0.037), acido_pantotenico_mg = 0.015, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.009), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 10.3, vitamina_k_mcg = 1.4, folato_mcg = 0 where nome = 'Azeitona, preta, conserva' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 52), ferro_mg = coalesce(ferro_mg, 0.49), magnesio_mg = 11, fosforo_mg = 4, potassio_mg = 42, sodio_mg = coalesce(sodio_mg, 1556), zinco_mg = coalesce(zinco_mg, 0.04), cobre_mcg = 120, selenio_mcg = 0.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 20), vitamina_e_mg = 3.81, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.021), riboflavina_mg = coalesce(riboflavina_mg, 0.007), niacina_mg = coalesce(niacina_mg, 0.237), acido_pantotenico_mg = 0.023, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.031), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 14.2, vitamina_k_mcg = 1.4, folato_mcg = 3 where nome = 'Azeitona, verde, conserva' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 101), ferro_mg = coalesce(ferro_mg, 0.05), magnesio_mg = 11, fosforo_mg = 89, potassio_mg = 147, sodio_mg = coalesce(sodio_mg, 8), zinco_mg = coalesce(zinco_mg, 0.37), cobre_mcg = 10, manganes_mg = 0.001, selenio_mcg = 1.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 188), vitamina_e_mg = 0.64, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.4), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.037), riboflavina_mg = coalesce(riboflavina_mg, 0.065), niacina_mg = coalesce(niacina_mg, 0.07), acido_pantotenico_mg = 0.305, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.041), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.29), colina_mg = 16.8, vitamina_k_mcg = 1.9, folato_mcg = 3 where nome = 'Chantilly, spray, com gordura vegetal' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 18), ferro_mg = coalesce(ferro_mg, 3.3), magnesio_mg = 46, fosforo_mg = 96, potassio_mg = 220, sodio_mg = coalesce(sodio_mg, 13), zinco_mg = coalesce(zinco_mg, 0.56), cobre_mcg = 223, manganes_mg = 0.768, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1), tiamina_mg = coalesce(tiamina_mg, 0.022), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0.637), acido_pantotenico_mg = 0.153, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.028), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 8.5, folato_mcg = 14 where nome = 'Leite, de coco' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 8), ferro_mg = coalesce(ferro_mg, 0.21), magnesio_mg = 1, fosforo_mg = 21, potassio_mg = 20, sodio_mg = coalesce(sodio_mg, 635), zinco_mg = coalesce(zinco_mg, 0.15), cobre_mcg = 19, manganes_mg = 0.007, selenio_mcg = 2.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 16), vitamina_e_mg = 3.28, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.01), riboflavina_mg = coalesce(riboflavina_mg, 0.019), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0.172, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.008), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.12), colina_mg = 34.2, vitamina_k_mcg = 163, folato_mcg = 5 where nome = 'Maionese, tradicional com ovos' and fonte = 'TACO' and id_avaliador is null;
