-- Micronutrientes pra "Nozes e sementes" (11 itens) — mesma
-- metodologia das categorias anteriores (0054-0069), fonte USDA
-- FoodData Central.
--
-- Erros corrigidos: farinha de mesocarpo de babaçu (palmeira
-- brasileira) tinha sido casada com farinha de SOJA (planta totalmente
-- diferente); gergelim em semente tinha sido casado com pasta/manteiga
-- de gergelim (forma de produto errada). Castanha-do-Brasil ficou com
-- selênio de 280,4 mcg/100g — batendo com o que se sabe sobre a
-- castanha-do-Brasil ser a principal fonte alimentar de selênio que
-- existe.
--
-- 9 de 11 itens aprovados. Ficaram de fora: pupunha cozida (fruto de
-- palmeira amazônica, sem equivalente USDA) e pinhão cozido (semente de
-- araucária brasileira — rica em amido, pouca gordura; o "pine nut"
-- americano da USDA é de outra família botânica e tem perfil oposto,
-- rico em lipídeos, então não usei como aproximação).

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 268), ferro_mg = coalesce(ferro_mg, 3.73), magnesio_mg = 279, fosforo_mg = 471, potassio_mg = 713, sodio_mg = coalesce(sodio_mg, 234), zinco_mg = coalesce(zinco_mg, 3.31), cobre_mcg = 1099, manganes_mg = 2.232, selenio_mcg = 2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 23.9, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.077), riboflavina_mg = coalesce(riboflavina_mg, 1.197), niacina_mg = coalesce(niacina_mg, 3.637), acido_pantotenico_mg = 0.321, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.136), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 52.1, vitamina_k_mcg = 0, folato_mcg = 55 where nome = 'Amêndoa, torrada, salgada' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 45), ferro_mg = coalesce(ferro_mg, 6), magnesio_mg = 260, fosforo_mg = 490, potassio_mg = 565, sodio_mg = coalesce(sodio_mg, 640), zinco_mg = coalesce(zinco_mg, 5.6), cobre_mcg = 2220, manganes_mg = 0.826, selenio_mcg = 11.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.92, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.2), riboflavina_mg = coalesce(riboflavina_mg, 0.2), niacina_mg = coalesce(niacina_mg, 1.4), acido_pantotenico_mg = 1.217, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.256), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 61, vitamina_k_mcg = 34.7, folato_mcg = 69 where nome = 'Castanha-de-caju, torrada, salgada' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 167.8), ferro_mg = coalesce(ferro_mg, 2.474), magnesio_mg = 351.3, fosforo_mg = 706.9, potassio_mg = 592.5, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 3.824), cobre_mcg = 1739, manganes_mg = 1.26, selenio_mcg = 280.4 where nome = 'Castanha-do-Brasil, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 14), ferro_mg = coalesce(ferro_mg, 2.43), magnesio_mg = 32, fosforo_mg = 113, potassio_mg = 356, sodio_mg = coalesce(sodio_mg, 20), zinco_mg = coalesce(zinco_mg, 1.1), cobre_mcg = 435, manganes_mg = 1.5, selenio_mcg = 10.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.24, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 3.3), tiamina_mg = coalesce(tiamina_mg, 0.066), riboflavina_mg = coalesce(riboflavina_mg, 0.02), niacina_mg = coalesce(niacina_mg, 0.54), acido_pantotenico_mg = 0.3, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.054), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 12.1, vitamina_k_mcg = 0.2, folato_mcg = 26 where nome = 'Coco, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 14), ferro_mg = coalesce(ferro_mg, 2.43), magnesio_mg = 32, fosforo_mg = 113, potassio_mg = 356, sodio_mg = coalesce(sodio_mg, 20), zinco_mg = coalesce(zinco_mg, 1.1), cobre_mcg = 435, manganes_mg = 1.5, selenio_mcg = 10.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.24, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 3.3), tiamina_mg = coalesce(tiamina_mg, 0.066), riboflavina_mg = coalesce(riboflavina_mg, 0.02), niacina_mg = coalesce(niacina_mg, 0.54), acido_pantotenico_mg = 0.3, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.054), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 12.1, vitamina_k_mcg = 0.2, folato_mcg = 26 where nome = 'Coco,  verde, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 206), ferro_mg = coalesce(ferro_mg, 6.37), magnesio_mg = 429, fosforo_mg = 494, potassio_mg = 2515, sodio_mg = coalesce(sodio_mg, 13), zinco_mg = coalesce(zinco_mg, 3.92), cobre_mcg = 2920, manganes_mg = 2.275, selenio_mcg = 7.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 6), vitamina_e_mg = 1.95, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.581), riboflavina_mg = coalesce(riboflavina_mg, 1.16), niacina_mg = coalesce(niacina_mg, 4.32), acido_pantotenico_mg = 1.59, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.461), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 190.6, vitamina_k_mcg = 70, folato_mcg = 345 where nome = 'Farinha, de mesocarpo de babaçu, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 975), ferro_mg = coalesce(ferro_mg, 14.55), magnesio_mg = 351, fosforo_mg = 629, potassio_mg = 468, sodio_mg = coalesce(sodio_mg, 11), zinco_mg = coalesce(zinco_mg, 7.75), cobre_mcg = 4082, manganes_mg = 2.46, selenio_mcg = 34.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.25, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.791), riboflavina_mg = coalesce(riboflavina_mg, 0.247), niacina_mg = coalesce(niacina_mg, 4.515), acido_pantotenico_mg = 0.05, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.79), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 25.6, vitamina_k_mcg = 0, folato_mcg = 97 where nome = 'Gergelim, semente' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 255), ferro_mg = coalesce(ferro_mg, 5.73), magnesio_mg = 392, fosforo_mg = 642, potassio_mg = 813, sodio_mg = coalesce(sodio_mg, 30), zinco_mg = coalesce(zinco_mg, 4.34), cobre_mcg = 1220, manganes_mg = 2.482, selenio_mcg = 25.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.31, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.6), tiamina_mg = coalesce(tiamina_mg, 1.644), riboflavina_mg = coalesce(riboflavina_mg, 0.161), niacina_mg = coalesce(niacina_mg, 3.08), acido_pantotenico_mg = 0.985, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.473), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 78.7, vitamina_k_mcg = 4.3, folato_mcg = 87 where nome = 'Linhaça, semente' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 88.26), ferro_mg = coalesce(ferro_mg, 2.235), magnesio_mg = 142.4, fosforo_mg = 365.1, potassio_mg = 423.5, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 2.76), cobre_mcg = 1206, manganes_mg = 2.995, molibdenio_mcg = 21, tiamina_mg = coalesce(tiamina_mg, 0.23), niacina_mg = coalesce(niacina_mg, 1.218), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.66), biotina_mcg = 17.28, vitamina_k_mcg = 1.7 where nome = 'Noz, crua' and fonte = 'TACO' and id_avaliador is null;
