-- Micronutrientes pra "Leguminosas e derivados" (30 itens) — mesma
-- metodologia das categorias anteriores (0054-0070), fonte USDA
-- FoodData Central.
--
-- Erro SISTEMÁTICO gigantesco: os 7 tipos de feijão brasileiro (carioca,
-- fradinho, jalo, preto, rajado, rosinha, roxo) tinham TODOS os 14
-- itens (cru + cozido de cada um) casados errado — os crus com "Green
-- beans, raw" (a VAGEM verde comestível, não o grão seco!) e os
-- cozidos com "Yardlong bean" (feijão-corda asiático de vagem
-- comprida). Em nenhum dos 14 casos o algoritmo pegou um grão seco de
-- verdade — a composição de vagem fresca (muita água, pouca proteína)
-- é radicalmente diferente de grão seco cozido (proteína/ferro/fibra/
-- folato muito mais concentrados). Remapeei cada variedade brasileira
-- pro tipo de feijão americano botanicamente mais parecido: carioca →
-- pinto, fradinho → cowpea/black-eyed pea (mesma espécie), jalo → great
-- northern, preto → black, rajado → cranberry/roman, rosinha → pink,
-- roxo → red kidney. Também corrigido: ervilha em vagem (vagem fresca)
-- estava casada com ervilha SECA; extrato de soja fluido (bebida)
-- estava casado com soja verde crua em GRÃO; tremoço cru estava casado
-- com vagem; amendoim torrado salgado estava casado com pasta de
-- amendoim.
--
-- 26 de 30 itens aprovados. Ficaram de fora: paçoca e pé-de-moleque de
-- amendoim (doces brasileiros sem equivalente USDA), extrato de soja em
-- pó (a única entrada USDA é "soy protein isolate", proteína quase
-- pura — muito diferente do extrato em pó, que retém carboidratos/
-- fibra) e tremoço em conserva (salmoura muda o sódio radicalmente,
-- sem entrada específica na USDA).

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 49.13), ferro_mg = coalesce(ferro_mg, 1.554), magnesio_mg = 179.7, fosforo_mg = 380.4, potassio_mg = 635.6, sodio_mg = coalesce(sodio_mg, 1.493), zinco_mg = coalesce(zinco_mg, 2.78), cobre_mcg = 459.5, manganes_mg = 1.68, selenio_mcg = 17.81 where nome = 'Amendoim, grão, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 58), ferro_mg = coalesce(ferro_mg, 1.58), magnesio_mg = 178, fosforo_mg = 363, potassio_mg = 634, sodio_mg = coalesce(sodio_mg, 410), zinco_mg = coalesce(zinco_mg, 2.77), cobre_mcg = 428, manganes_mg = 1.786, selenio_mcg = 9.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 4.93, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.152), riboflavina_mg = coalesce(riboflavina_mg, 0.197), niacina_mg = coalesce(niacina_mg, 14.355), acido_pantotenico_mg = 1.011, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.466), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 64.6, vitamina_k_mcg = 0, folato_mcg = 97 where nome = 'Amendoim, torrado, salgado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 43), ferro_mg = coalesce(ferro_mg, 2.08), magnesio_mg = 24, fosforo_mg = 53, potassio_mg = 200, sodio_mg = coalesce(sodio_mg, 4), zinco_mg = coalesce(zinco_mg, 0.27), cobre_mcg = 79, manganes_mg = 0.244, selenio_mcg = 0.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 54), vitamina_e_mg = 0.39, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 60), tiamina_mg = coalesce(tiamina_mg, 0.15), riboflavina_mg = coalesce(riboflavina_mg, 0.08), niacina_mg = coalesce(niacina_mg, 0.6), acido_pantotenico_mg = 0.75, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.16), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 17.4, vitamina_k_mcg = 25, folato_mcg = 42 where nome = 'Ervilha, em vagem' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 20), ferro_mg = coalesce(ferro_mg, 0.95), magnesio_mg = 17, fosforo_mg = 67, potassio_mg = 173, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 0.71), cobre_mcg = 82, manganes_mg = 0.303, selenio_mcg = 1.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 27), vitamina_e_mg = 0.03, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 9.6), tiamina_mg = coalesce(tiamina_mg, 0.121), riboflavina_mg = coalesce(riboflavina_mg, 0.078), niacina_mg = coalesce(niacina_mg, 0.732), acido_pantotenico_mg = 0.128, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.064), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), vitamina_k_mcg = 21.4, folato_mcg = 44 where nome = 'Ervilha, enlatada, drenada' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 46), ferro_mg = coalesce(ferro_mg, 2.09), magnesio_mg = 50, fosforo_mg = 147, potassio_mg = 436, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.98), cobre_mcg = 219, manganes_mg = 0.453, selenio_mcg = 6.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.94, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.8), tiamina_mg = coalesce(tiamina_mg, 0.193), riboflavina_mg = coalesce(riboflavina_mg, 0.062), niacina_mg = coalesce(niacina_mg, 0.318), acido_pantotenico_mg = 0.21, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.229), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 35.3, vitamina_k_mcg = 3.5, folato_mcg = 172 where nome = 'Feijão, carioca, cozido' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 113), ferro_mg = coalesce(ferro_mg, 5.07), magnesio_mg = 176, fosforo_mg = 411, potassio_mg = 1393, sodio_mg = coalesce(sodio_mg, 12), zinco_mg = coalesce(zinco_mg, 2.28), cobre_mcg = 893, manganes_mg = 1.148, selenio_mcg = 27.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 6.3), tiamina_mg = coalesce(tiamina_mg, 0.713), riboflavina_mg = coalesce(riboflavina_mg, 0.212), niacina_mg = coalesce(niacina_mg, 1.174), acido_pantotenico_mg = 0.785, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.474), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 66.2, vitamina_k_mcg = 5.6, folato_mcg = 525 where nome = 'Feijão, carioca, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 24), ferro_mg = coalesce(ferro_mg, 2.51), magnesio_mg = 53, fosforo_mg = 156, potassio_mg = 278, sodio_mg = coalesce(sodio_mg, 4), zinco_mg = coalesce(zinco_mg, 1.29), cobre_mcg = 268, manganes_mg = 0.475, selenio_mcg = 2.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 0.28, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.4), tiamina_mg = coalesce(tiamina_mg, 0.202), riboflavina_mg = coalesce(riboflavina_mg, 0.055), niacina_mg = coalesce(niacina_mg, 0.495), acido_pantotenico_mg = 0.411, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.1), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 32.2, vitamina_k_mcg = 1.7, folato_mcg = 208 where nome = 'Feijão, fradinho, cozido' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 110), ferro_mg = coalesce(ferro_mg, 8.27), magnesio_mg = 184, fosforo_mg = 424, potassio_mg = 1112, sodio_mg = coalesce(sodio_mg, 16), zinco_mg = coalesce(zinco_mg, 3.37), cobre_mcg = 845, manganes_mg = 1.528, selenio_mcg = 9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.39, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.5), tiamina_mg = coalesce(tiamina_mg, 0.853), riboflavina_mg = coalesce(riboflavina_mg, 0.226), niacina_mg = coalesce(niacina_mg, 2.075), acido_pantotenico_mg = 1.496, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.357), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 94.7, vitamina_k_mcg = 5, folato_mcg = 633 where nome = 'Feijão, fradinho, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 68), ferro_mg = coalesce(ferro_mg, 2.13), magnesio_mg = 50, fosforo_mg = 165, potassio_mg = 391, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 0.88), cobre_mcg = 247, manganes_mg = 0.518, selenio_mcg = 4.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.3), tiamina_mg = coalesce(tiamina_mg, 0.158), riboflavina_mg = coalesce(riboflavina_mg, 0.059), niacina_mg = coalesce(niacina_mg, 0.681), acido_pantotenico_mg = 0.266, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.117), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 102 where nome = 'Feijão, jalo, cozido' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 175), ferro_mg = coalesce(ferro_mg, 5.47), magnesio_mg = 189, fosforo_mg = 447, potassio_mg = 1387, sodio_mg = coalesce(sodio_mg, 14), zinco_mg = coalesce(zinco_mg, 2.31), cobre_mcg = 837, manganes_mg = 1.423, selenio_mcg = 12.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.22, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 5.3), tiamina_mg = coalesce(tiamina_mg, 0.653), riboflavina_mg = coalesce(riboflavina_mg, 0.237), niacina_mg = coalesce(niacina_mg, 1.955), acido_pantotenico_mg = 1.098, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.447), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), vitamina_k_mcg = 6, folato_mcg = 482 where nome = 'Feijão, jalo, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 27), ferro_mg = coalesce(ferro_mg, 2.1), magnesio_mg = 70, fosforo_mg = 140, potassio_mg = 355, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 1.12), cobre_mcg = 209, manganes_mg = 0.444, selenio_mcg = 1.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.87, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.244), riboflavina_mg = coalesce(riboflavina_mg, 0.059), niacina_mg = coalesce(niacina_mg, 0.505), acido_pantotenico_mg = 0.242, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.069), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 32.6, vitamina_k_mcg = 3.3, folato_mcg = 149 where nome = 'Feijão, preto, cozido' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 123), ferro_mg = coalesce(ferro_mg, 5.02), magnesio_mg = 171, fosforo_mg = 352, potassio_mg = 1483, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 3.65), cobre_mcg = 841, manganes_mg = 1.06, selenio_mcg = 3.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.9), riboflavina_mg = coalesce(riboflavina_mg, 0.193), niacina_mg = coalesce(niacina_mg, 1.955), acido_pantotenico_mg = 0.899, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.286), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 66.4, vitamina_k_mcg = 5.6, folato_mcg = 444 where nome = 'Feijão, preto, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 50), ferro_mg = coalesce(ferro_mg, 2.09), magnesio_mg = 50, fosforo_mg = 135, potassio_mg = 387, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 1.14), cobre_mcg = 231, manganes_mg = 0.37, selenio_mcg = 1.3, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.21), riboflavina_mg = coalesce(riboflavina_mg, 0.069), niacina_mg = coalesce(niacina_mg, 0.515), acido_pantotenico_mg = 0.24, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.081), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 207 where nome = 'Feijão, rajado, cozido' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 127), ferro_mg = coalesce(ferro_mg, 5), magnesio_mg = 156, fosforo_mg = 372, potassio_mg = 1332, sodio_mg = coalesce(sodio_mg, 6), zinco_mg = coalesce(zinco_mg, 3.63), cobre_mcg = 794, manganes_mg = 0.92, selenio_mcg = 12.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.747), riboflavina_mg = coalesce(riboflavina_mg, 0.213), niacina_mg = coalesce(niacina_mg, 1.455), acido_pantotenico_mg = 0.748, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.309), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 604 where nome = 'Feijão, rajado, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 52), ferro_mg = coalesce(ferro_mg, 2.3), magnesio_mg = 65, fosforo_mg = 165, potassio_mg = 508, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 0.96), cobre_mcg = 271, manganes_mg = 0.548, selenio_mcg = 1.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.98, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.257), riboflavina_mg = coalesce(riboflavina_mg, 0.063), niacina_mg = coalesce(niacina_mg, 0.57), acido_pantotenico_mg = 0.299, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.175), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 36.9, vitamina_k_mcg = 3.7, folato_mcg = 168 where nome = 'Feijão, rosinha, cozido' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 130), ferro_mg = coalesce(ferro_mg, 6.77), magnesio_mg = 182, fosforo_mg = 415, potassio_mg = 1464, sodio_mg = coalesce(sodio_mg, 8), zinco_mg = coalesce(zinco_mg, 2.55), cobre_mcg = 810, manganes_mg = 1.376, selenio_mcg = 13, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.772), riboflavina_mg = coalesce(riboflavina_mg, 0.192), niacina_mg = coalesce(niacina_mg, 1.892), acido_pantotenico_mg = 0.997, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.527), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 67.2, vitamina_k_mcg = 5.7, folato_mcg = 463 where nome = 'Feijão, rosinha, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 28), ferro_mg = coalesce(ferro_mg, 2.94), magnesio_mg = 45, fosforo_mg = 142, potassio_mg = 403, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 1.07), cobre_mcg = 242, manganes_mg = 0.477, selenio_mcg = 1.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.03, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.2), tiamina_mg = coalesce(tiamina_mg, 0.16), riboflavina_mg = coalesce(riboflavina_mg, 0.058), niacina_mg = coalesce(niacina_mg, 0.578), acido_pantotenico_mg = 0.22, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.12), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 30.5, vitamina_k_mcg = 8.4, folato_mcg = 130 where nome = 'Feijão, roxo, cozido' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 83), ferro_mg = coalesce(ferro_mg, 6.69), magnesio_mg = 138, fosforo_mg = 406, potassio_mg = 1359, sodio_mg = coalesce(sodio_mg, 12), zinco_mg = coalesce(zinco_mg, 2.79), cobre_mcg = 699, manganes_mg = 1.111, selenio_mcg = 3.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4.5), tiamina_mg = coalesce(tiamina_mg, 0.608), riboflavina_mg = coalesce(riboflavina_mg, 0.215), niacina_mg = coalesce(niacina_mg, 2.11), acido_pantotenico_mg = 0.78, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.397), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 65.9, vitamina_k_mcg = 5.6, folato_mcg = 394 where nome = 'Feijão, roxo, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 57), ferro_mg = coalesce(ferro_mg, 4.31), magnesio_mg = 79, fosforo_mg = 252, potassio_mg = 718, sodio_mg = coalesce(sodio_mg, 24), zinco_mg = coalesce(zinco_mg, 2.76), cobre_mcg = 656, manganes_mg = 4.15, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.82, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4), tiamina_mg = coalesce(tiamina_mg, 0.477), riboflavina_mg = coalesce(riboflavina_mg, 0.212), niacina_mg = coalesce(niacina_mg, 1.541), acido_pantotenico_mg = 1.588, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.535), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 99.3, vitamina_k_mcg = 9, folato_mcg = 557 where nome = 'Grão-de-bico, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 130), ferro_mg = coalesce(ferro_mg, 5.23), magnesio_mg = 183, fosforo_mg = 367, potassio_mg = 1392, sodio_mg = coalesce(sodio_mg, 17), zinco_mg = coalesce(zinco_mg, 2.76), cobre_mcg = 1057, manganes_mg = 1.791, selenio_mcg = 8.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.643), riboflavina_mg = coalesce(riboflavina_mg, 0.187), niacina_mg = coalesce(niacina_mg, 2.965), acido_pantotenico_mg = 1.266, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.283), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 456 where nome = 'Guandu, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 19), ferro_mg = coalesce(ferro_mg, 3.33), magnesio_mg = 36, fosforo_mg = 180, potassio_mg = 369, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 1.27), cobre_mcg = 251, manganes_mg = 0.494, selenio_mcg = 2.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.5), tiamina_mg = coalesce(tiamina_mg, 0.169), riboflavina_mg = coalesce(riboflavina_mg, 0.073), niacina_mg = coalesce(niacina_mg, 1.06), acido_pantotenico_mg = 0.638, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.178), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 32.7, vitamina_k_mcg = 1.7, folato_mcg = 181 where nome = 'Lentilha, cozida' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 35), ferro_mg = coalesce(ferro_mg, 6.51), magnesio_mg = 47, fosforo_mg = 281, potassio_mg = 677, sodio_mg = coalesce(sodio_mg, 6), zinco_mg = coalesce(zinco_mg, 3.27), cobre_mcg = 754, manganes_mg = 1.393, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.49, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4.5), tiamina_mg = coalesce(tiamina_mg, 0.873), riboflavina_mg = coalesce(riboflavina_mg, 0.211), niacina_mg = coalesce(niacina_mg, 2.605), acido_pantotenico_mg = 2.14, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.54), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 96.4, vitamina_k_mcg = 5, folato_mcg = 479 where nome = 'Lentilha, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 206), ferro_mg = coalesce(ferro_mg, 6.37), magnesio_mg = 429, fosforo_mg = 494, potassio_mg = 2515, sodio_mg = coalesce(sodio_mg, 13), zinco_mg = coalesce(zinco_mg, 3.92), cobre_mcg = 2920, manganes_mg = 2.275, selenio_mcg = 7.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 6), vitamina_e_mg = 1.95, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.581), riboflavina_mg = coalesce(riboflavina_mg, 1.16), niacina_mg = coalesce(niacina_mg, 4.32), acido_pantotenico_mg = 1.59, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.461), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 190.6, vitamina_k_mcg = 70, folato_mcg = 345 where nome = 'Soja, farinha' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 25), ferro_mg = coalesce(ferro_mg, 0.64), magnesio_mg = 25, fosforo_mg = 52, potassio_mg = 118, sodio_mg = coalesce(sodio_mg, 51), zinco_mg = coalesce(zinco_mg, 0.12), cobre_mcg = 128, manganes_mg = 0.223, selenio_mcg = 4.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.06), riboflavina_mg = coalesce(riboflavina_mg, 0.069), niacina_mg = coalesce(niacina_mg, 0.513), acido_pantotenico_mg = 0.373, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.077), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 23.6, vitamina_k_mcg = 3, folato_mcg = 18 where nome = 'Soja, extrato solúvel, natural, fluido' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 188), ferro_mg = coalesce(ferro_mg, 5.6), magnesio_mg = 228, fosforo_mg = 222, potassio_mg = 199, sodio_mg = coalesce(sodio_mg, 20), zinco_mg = coalesce(zinco_mg, 1.72), cobre_mcg = 380, manganes_mg = 0.889, selenio_mcg = 16.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.6, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0.14), niacina_mg = coalesce(niacina_mg, 0.5), acido_pantotenico_mg = 0.116, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.07), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 62.5, vitamina_k_mcg = 4.6, folato_mcg = 22 where nome = 'Soja, queijo (tofu)' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 176), ferro_mg = coalesce(ferro_mg, 4.36), magnesio_mg = 198, fosforo_mg = 440, potassio_mg = 1013, sodio_mg = coalesce(sodio_mg, 15), zinco_mg = coalesce(zinco_mg, 4.75), cobre_mcg = 1022, manganes_mg = 2.382, selenio_mcg = 8.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4.8), tiamina_mg = coalesce(tiamina_mg, 0.64), riboflavina_mg = coalesce(riboflavina_mg, 0.22), niacina_mg = coalesce(niacina_mg, 2.19), acido_pantotenico_mg = 0.75, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.357), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 355 where nome = 'Tremoço, cru' and fonte = 'TACO' and id_avaliador is null;
