-- Micronutrientes pra "Pescados e frutos do mar" (50 itens — essa
-- categoria não tinha o campo taco_categoria preenchido no SQL
-- original da TACO, mas são todos peixes/frutos do mar) — mesma
-- metodologia das categorias anteriores (0054-0072), fonte USDA
-- FoodData Central. Última leva da tabela TACO — fecha a cobertura de
-- todas as categorias.
--
-- Vários peixes nativos brasileiros de água doce (corimbatá, corvina
-- de água doce, dourada de água doce, tucunaré) e alguns nomes
-- populares ambíguos (porquinho) não têm equivalente na USDA — americana
-- não cataloga peixes amazônicos/de rio brasileiros. Vários preparos
-- fritos/empanados específicos também não tinham entrada própria na
-- USDA (só cru ou só uma versão empanada genérica de rede de fast-food).
--
-- 26 de 50 itens aprovados. "Pintado" (bagre amazônico) foi aceito como
-- aproximação usando catfish americano — mesma ordem taxonômica
-- (Siluriformes), embora família diferente; é a aproximação mais
-- razoável disponível. Salmão consumido no Brasil é majoritariamente de
-- cativeiro, então usei "farmed" da USDA em vez de "wild".

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 72), ferro_mg = coalesce(ferro_mg, 0.56), magnesio_mg = 81, fosforo_mg = 267, potassio_mg = 430, sodio_mg = coalesce(sodio_mg, 419), zinco_mg = coalesce(zinco_mg, 0.57), cobre_mcg = 60, manganes_mg = 0.018, selenio_mcg = 44.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 17), vitamina_e_mg = 0.28, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.054), riboflavina_mg = coalesce(riboflavina_mg, 0.223), niacina_mg = coalesce(niacina_mg, 3.949), acido_pantotenico_mg = 0.432, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.329), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.66), colina_mg = 91.6, vitamina_k_mcg = 0.1, folato_mcg = 3 where nome = 'Abadejo, filé, congelado, assado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 72), ferro_mg = coalesce(ferro_mg, 0.56), magnesio_mg = 81, fosforo_mg = 267, potassio_mg = 430, sodio_mg = coalesce(sodio_mg, 419), zinco_mg = coalesce(zinco_mg, 0.57), cobre_mcg = 60, manganes_mg = 0.018, selenio_mcg = 44.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 17), vitamina_e_mg = 0.28, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.054), riboflavina_mg = coalesce(riboflavina_mg, 0.223), niacina_mg = coalesce(niacina_mg, 3.949), acido_pantotenico_mg = 0.432, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.329), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.66), colina_mg = 91.6, vitamina_k_mcg = 0.1, folato_mcg = 3 where nome = 'Abadejo, filé, congelado,cozido' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 12), ferro_mg = coalesce(ferro_mg, 0.27), magnesio_mg = 34, fosforo_mg = 190, potassio_mg = 331, sodio_mg = coalesce(sodio_mg, 159), zinco_mg = coalesce(zinco_mg, 0.4), cobre_mcg = 41, manganes_mg = 0.011 where nome = 'Abadejo, filé, congelado, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 72), ferro_mg = coalesce(ferro_mg, 0.56), magnesio_mg = 81, fosforo_mg = 267, potassio_mg = 430, sodio_mg = coalesce(sodio_mg, 419), zinco_mg = coalesce(zinco_mg, 0.57), cobre_mcg = 60, manganes_mg = 0.018, selenio_mcg = 44.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 17), vitamina_e_mg = 0.28, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.054), riboflavina_mg = coalesce(riboflavina_mg, 0.223), niacina_mg = coalesce(niacina_mg, 3.949), acido_pantotenico_mg = 0.432, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.329), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.66), colina_mg = 91.6, vitamina_k_mcg = 0.1, folato_mcg = 3 where nome = 'Abadejo, filé, congelado, grelhado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 13), ferro_mg = coalesce(ferro_mg, 1.39), magnesio_mg = 31, fosforo_mg = 311, potassio_mg = 207, sodio_mg = coalesce(sodio_mg, 416), zinco_mg = coalesce(zinco_mg, 0.9), cobre_mcg = 71, manganes_mg = 0.015, selenio_mcg = 76, vitamina_a_mcg = coalesce(vitamina_a_mcg, 23), vitamina_e_mg = 0.87, vitamina_d_mcg = coalesce(vitamina_d_mcg, 6.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.038), riboflavina_mg = coalesce(riboflavina_mg, 0.12), niacina_mg = coalesce(niacina_mg, 12.4), acido_pantotenico_mg = 0.37, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.11), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.2), colina_mg = 29.3, vitamina_k_mcg = 44, folato_mcg = 5 where nome = 'Atum, conserva em óleo' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 8), ferro_mg = coalesce(ferro_mg, 1.02), magnesio_mg = 50, fosforo_mg = 254, potassio_mg = 252, sodio_mg = coalesce(sodio_mg, 39), zinco_mg = coalesce(zinco_mg, 0.6), cobre_mcg = 86, manganes_mg = 0.015, selenio_mcg = 36.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 655), vitamina_e_mg = 1, vitamina_d_mcg = coalesce(vitamina_d_mcg, 5.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.241), riboflavina_mg = coalesce(riboflavina_mg, 0.251), niacina_mg = coalesce(niacina_mg, 8.654), acido_pantotenico_mg = 1.054, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.455), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 9.43), colina_mg = 65, vitamina_k_mcg = 0, folato_mcg = 2 where nome = 'Atum, fresco, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 160), ferro_mg = coalesce(ferro_mg, 2.5), magnesio_mg = 133, fosforo_mg = 950, potassio_mg = 1458, sodio_mg = coalesce(sodio_mg, 7027), zinco_mg = coalesce(zinco_mg, 1.59), cobre_mcg = 176, manganes_mg = 0.05, selenio_mcg = 147.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 42), vitamina_e_mg = 2.84, vitamina_d_mcg = coalesce(vitamina_d_mcg, 4), vitamina_c_mg = coalesce(vitamina_c_mg, 3.5), tiamina_mg = coalesce(tiamina_mg, 0.268), riboflavina_mg = coalesce(riboflavina_mg, 0.24), niacina_mg = coalesce(niacina_mg, 7.5), acido_pantotenico_mg = 1.675, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.864), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 10), colina_mg = 291.3, vitamina_k_mcg = 0.4, folato_mcg = 25 where nome = 'Bacalhau, salgado, refogado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 70), ferro_mg = coalesce(ferro_mg, 0.51), magnesio_mg = 39, fosforo_mg = 237, potassio_mg = 259, sodio_mg = coalesce(sodio_mg, 111), zinco_mg = coalesce(zinco_mg, 1.64), cobre_mcg = 379, manganes_mg = 0.033 where nome = 'Camarão, Rio Grande, grande, cozido' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 64), ferro_mg = coalesce(ferro_mg, 0.52), magnesio_mg = 35, fosforo_mg = 214, potassio_mg = 264, sodio_mg = coalesce(sodio_mg, 119), zinco_mg = coalesce(zinco_mg, 1.34), cobre_mcg = 391, manganes_mg = 0.033 where nome = 'Camarão, Rio Grande, grande, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 91), ferro_mg = coalesce(ferro_mg, 0.5), magnesio_mg = 36, fosforo_mg = 234, potassio_mg = 259, sodio_mg = coalesce(sodio_mg, 395), zinco_mg = coalesce(zinco_mg, 3.81), cobre_mcg = 814, manganes_mg = 0.074, selenio_mcg = 42.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 1.84, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 3.3), tiamina_mg = coalesce(tiamina_mg, 0.023), riboflavina_mg = coalesce(riboflavina_mg, 0.093), niacina_mg = coalesce(niacina_mg, 2.747), acido_pantotenico_mg = 0.997, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.156), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.33), colina_mg = 80.9, vitamina_k_mcg = 0.3, folato_mcg = 51 where nome = 'Caranguejo, cozido' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 15), ferro_mg = coalesce(ferro_mg, 0.37), magnesio_mg = 40, fosforo_mg = 210, potassio_mg = 345, sodio_mg = coalesce(sodio_mg, 56), zinco_mg = coalesce(zinco_mg, 0.42), cobre_mcg = 42, manganes_mg = 0.025, selenio_mcg = 36.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 12), vitamina_e_mg = 1.29, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.075), riboflavina_mg = coalesce(riboflavina_mg, 0.095), niacina_mg = coalesce(niacina_mg, 4.2), acido_pantotenico_mg = 0.75, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.3), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.5), colina_mg = 67, vitamina_k_mcg = 0.1, folato_mcg = 15 where nome = 'Corvina do mar, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 60), ferro_mg = coalesce(ferro_mg, 0.9), magnesio_mg = 30, fosforo_mg = 180, potassio_mg = 275, sodio_mg = coalesce(sodio_mg, 75), zinco_mg = coalesce(zinco_mg, 0.66), cobre_mcg = 232, manganes_mg = 0.7, selenio_mcg = 12.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 51), vitamina_c_mg = coalesce(vitamina_c_mg, 1), tiamina_mg = coalesce(tiamina_mg, 0.07), riboflavina_mg = coalesce(riboflavina_mg, 0.17), niacina_mg = coalesce(niacina_mg, 2.35), acido_pantotenico_mg = 0.75, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.3), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2), folato_mcg = 15 where nome = 'Lambari, congelado, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 60), ferro_mg = coalesce(ferro_mg, 0.9), magnesio_mg = 30, fosforo_mg = 180, potassio_mg = 275, sodio_mg = coalesce(sodio_mg, 75), zinco_mg = coalesce(zinco_mg, 0.66), cobre_mcg = 232, manganes_mg = 0.7, selenio_mcg = 12.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 51), vitamina_c_mg = coalesce(vitamina_c_mg, 1), tiamina_mg = coalesce(tiamina_mg, 0.07), riboflavina_mg = coalesce(riboflavina_mg, 0.17), niacina_mg = coalesce(niacina_mg, 2.35), acido_pantotenico_mg = 0.75, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.3), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2), folato_mcg = 15 where nome = 'Lambari, fresco, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 48), ferro_mg = coalesce(ferro_mg, 0.34), magnesio_mg = 21, fosforo_mg = 222, potassio_mg = 249, sodio_mg = coalesce(sodio_mg, 72), zinco_mg = coalesce(zinco_mg, 0.88), cobre_mcg = 31, manganes_mg = 0.104, selenio_mcg = 32.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 30), vitamina_e_mg = 0.3, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.4), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.056), riboflavina_mg = coalesce(riboflavina_mg, 0.046), niacina_mg = coalesce(niacina_mg, 1.3), acido_pantotenico_mg = 0.216, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.156), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.3), colina_mg = 65, vitamina_k_mcg = 0.1, folato_mcg = 13 where nome = 'Merluza, filé, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 15), ferro_mg = coalesce(ferro_mg, 0.37), magnesio_mg = 40, fosforo_mg = 210, potassio_mg = 345, sodio_mg = coalesce(sodio_mg, 56), zinco_mg = coalesce(zinco_mg, 0.42), cobre_mcg = 42, manganes_mg = 0.025, selenio_mcg = 36.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 12), vitamina_e_mg = 1.29, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.075), riboflavina_mg = coalesce(riboflavina_mg, 0.095), niacina_mg = coalesce(niacina_mg, 4.2), acido_pantotenico_mg = 0.75, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.3), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.5), colina_mg = 67, vitamina_k_mcg = 0.1, folato_mcg = 15 where nome = 'Pescada, branca, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 32), ferro_mg = coalesce(ferro_mg, 0.86), magnesio_mg = 42, fosforo_mg = 217, potassio_mg = 340, sodio_mg = coalesce(sodio_mg, 348), zinco_mg = coalesce(zinco_mg, 0.52), cobre_mcg = 65, manganes_mg = 0.08, selenio_mcg = 38.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 23), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.13), niacina_mg = coalesce(niacina_mg, 4.3), acido_pantotenico_mg = 0.74, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.26), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.1), folato_mcg = 45 where nome = 'Pescada, filé, com farinha de trigo, frito' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 15), ferro_mg = coalesce(ferro_mg, 0.37), magnesio_mg = 40, fosforo_mg = 210, potassio_mg = 345, sodio_mg = coalesce(sodio_mg, 56), zinco_mg = coalesce(zinco_mg, 0.42), cobre_mcg = 42, manganes_mg = 0.025, selenio_mcg = 36.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 12), vitamina_e_mg = 1.29, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.075), riboflavina_mg = coalesce(riboflavina_mg, 0.095), niacina_mg = coalesce(niacina_mg, 4.2), acido_pantotenico_mg = 0.75, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.3), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.5), colina_mg = 67, vitamina_k_mcg = 0.1, folato_mcg = 15 where nome = 'Pescada, filé, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 32), ferro_mg = coalesce(ferro_mg, 0.86), magnesio_mg = 42, fosforo_mg = 217, potassio_mg = 340, sodio_mg = coalesce(sodio_mg, 348), zinco_mg = coalesce(zinco_mg, 0.52), cobre_mcg = 65, manganes_mg = 0.08, selenio_mcg = 38.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 23), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.13), niacina_mg = coalesce(niacina_mg, 4.3), acido_pantotenico_mg = 0.74, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.26), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.1), folato_mcg = 45 where nome = 'Pescada, filé, frito' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 15), ferro_mg = coalesce(ferro_mg, 0.37), magnesio_mg = 40, fosforo_mg = 210, potassio_mg = 345, sodio_mg = coalesce(sodio_mg, 56), zinco_mg = coalesce(zinco_mg, 0.42), cobre_mcg = 42, manganes_mg = 0.025, selenio_mcg = 36.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 12), vitamina_e_mg = 1.29, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.075), riboflavina_mg = coalesce(riboflavina_mg, 0.095), niacina_mg = coalesce(niacina_mg, 4.2), acido_pantotenico_mg = 0.75, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.3), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.5), colina_mg = 67, vitamina_k_mcg = 0.1, folato_mcg = 15 where nome = 'Pescadinha, crua' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 0.35), magnesio_mg = 28, fosforo_mg = 304, potassio_mg = 419, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 0.61), cobre_mcg = 39, manganes_mg = 0.027, selenio_mcg = 14.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 15), vitamina_c_mg = coalesce(vitamina_c_mg, 0.8), tiamina_mg = coalesce(tiamina_mg, 0.227), riboflavina_mg = coalesce(riboflavina_mg, 0.067), niacina_mg = coalesce(niacina_mg, 2.385), acido_pantotenico_mg = 0.91, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.106), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.9), folato_mcg = 10 where nome = 'Pintado, assado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 14), ferro_mg = coalesce(ferro_mg, 0.3), magnesio_mg = 23, fosforo_mg = 209, potassio_mg = 358, sodio_mg = coalesce(sodio_mg, 43), zinco_mg = coalesce(zinco_mg, 0.51), cobre_mcg = 34, manganes_mg = 0.025, selenio_mcg = 12.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 15), vitamina_d_mcg = coalesce(vitamina_d_mcg, 12.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0.7), tiamina_mg = coalesce(tiamina_mg, 0.21), riboflavina_mg = coalesce(riboflavina_mg, 0.072), niacina_mg = coalesce(niacina_mg, 1.907), acido_pantotenico_mg = 0.765, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.116), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.23), folato_mcg = 10 where nome = 'Pintado, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 0.35), magnesio_mg = 28, fosforo_mg = 304, potassio_mg = 419, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 0.61), cobre_mcg = 39, manganes_mg = 0.027, selenio_mcg = 14.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 15), vitamina_c_mg = coalesce(vitamina_c_mg, 0.8), tiamina_mg = coalesce(tiamina_mg, 0.227), riboflavina_mg = coalesce(riboflavina_mg, 0.067), niacina_mg = coalesce(niacina_mg, 2.385), acido_pantotenico_mg = 0.91, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.106), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.9), folato_mcg = 10 where nome = 'Pintado, grelhado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 15), ferro_mg = coalesce(ferro_mg, 0.34), magnesio_mg = 30, fosforo_mg = 252, potassio_mg = 384, sodio_mg = coalesce(sodio_mg, 61), zinco_mg = coalesce(zinco_mg, 0.43), cobre_mcg = 49, manganes_mg = 0.016, selenio_mcg = 41.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 69), vitamina_e_mg = 1.14, vitamina_d_mcg = coalesce(vitamina_d_mcg, 13.1), vitamina_c_mg = coalesce(vitamina_c_mg, 3.7), tiamina_mg = coalesce(tiamina_mg, 0.34), riboflavina_mg = coalesce(riboflavina_mg, 0.135), niacina_mg = coalesce(niacina_mg, 8.045), acido_pantotenico_mg = 1.475, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.647), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.8), colina_mg = 90.5, vitamina_k_mcg = 0.1, folato_mcg = 34 where nome = 'Salmão, filé, com pele, fresco,  grelhado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 9), ferro_mg = coalesce(ferro_mg, 0.34), magnesio_mg = 27, fosforo_mg = 240, potassio_mg = 363, sodio_mg = coalesce(sodio_mg, 59), zinco_mg = coalesce(zinco_mg, 0.36), cobre_mcg = 45, manganes_mg = 0.011, selenio_mcg = 24, vitamina_a_mcg = coalesce(vitamina_a_mcg, 58), vitamina_e_mg = 3.55, vitamina_d_mcg = coalesce(vitamina_d_mcg, 11), vitamina_c_mg = coalesce(vitamina_c_mg, 3.9), tiamina_mg = coalesce(tiamina_mg, 0.207), riboflavina_mg = coalesce(riboflavina_mg, 0.155), niacina_mg = coalesce(niacina_mg, 8.672), acido_pantotenico_mg = 1.547, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.636), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.23), colina_mg = 78.5, vitamina_k_mcg = 0.5, folato_mcg = 26 where nome = 'Salmão, sem pele, fresco, cru' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 15), ferro_mg = coalesce(ferro_mg, 0.34), magnesio_mg = 30, fosforo_mg = 252, potassio_mg = 384, sodio_mg = coalesce(sodio_mg, 61), zinco_mg = coalesce(zinco_mg, 0.43), cobre_mcg = 49, manganes_mg = 0.016, selenio_mcg = 41.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 69), vitamina_e_mg = 1.14, vitamina_d_mcg = coalesce(vitamina_d_mcg, 13.1), vitamina_c_mg = coalesce(vitamina_c_mg, 3.7), tiamina_mg = coalesce(tiamina_mg, 0.34), riboflavina_mg = coalesce(riboflavina_mg, 0.135), niacina_mg = coalesce(niacina_mg, 8.045), acido_pantotenico_mg = 1.475, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.647), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.8), colina_mg = 90.5, vitamina_k_mcg = 0.1, folato_mcg = 34 where nome = 'Salmão, sem pele, fresco, grelhado' and fonte = 'TACO' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 382), ferro_mg = coalesce(ferro_mg, 2.92), magnesio_mg = 39, fosforo_mg = 490, potassio_mg = 397, sodio_mg = coalesce(sodio_mg, 307), zinco_mg = coalesce(zinco_mg, 1.31), cobre_mcg = 186, manganes_mg = 0.108, selenio_mcg = 52.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 32), vitamina_e_mg = 2.04, vitamina_d_mcg = coalesce(vitamina_d_mcg, 4.8), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.08), riboflavina_mg = coalesce(riboflavina_mg, 0.227), niacina_mg = coalesce(niacina_mg, 5.245), acido_pantotenico_mg = 0.642, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.167), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 8.94), colina_mg = 75, vitamina_k_mcg = 2.6, folato_mcg = 10 where nome = 'Sardinha, conserva em óleo' and fonte = 'TACO' and id_avaliador is null;
