-- Migration 0076: micronutrientes IBGE — lote 2 (ovos, laticínios, pescados/conservas simples, pães básicos)
--
-- Segundo lote de curadoria de micronutrientes para a tabela IBGE (POF
-- 2008-2009, fonte = 'IBGE'). Continuação da migration 0075, mesma
-- metodologia de lista positiva (ACEITAR) restrita a itens verificados
-- manualmente um a um — o casamento automático segue não confiável para
-- a maior parte do vocabulário do IBGE (ver header da 0075 para os
-- detalhes do achado).
--
-- Este lote cobre: ovos, laticínios adicionais (leite em pó, creme de
-- leite), pescados/conservas simples (bacalhau, camarão, atum, salmão) e
-- pães básicos. 21 itens aprovados.
--
-- Erros encontrados e corrigidos neste lote:
--   - Leite em pó desnatado: batia com leite LÍQUIDO desnatado (forma
--     errada — pó vs líquido). Corrigido para Milk, dry, nonfat.
--   - Creme de leite / Creme de leite orgânico: batiam com "Light Ice
--     Cream, soft serve" (produto errado). Corrigidos para Cream, fluid,
--     heavy whipping.
--   - Creme de leite light: mesmo problema, corrigido para Cream, fluid,
--     light whipping.
--   - Ovo de codorna, Cru(a): batia com gema de ovo de GALINHA (espécie
--     errada). Corrigido para Egg, quail, whole, fresh, raw. "Ovo de
--     codorna, Cozido(a)" foi excluído deste lote: não existe entrada de
--     ovo de codorna cozido nas bases do USDA, e usar o dado de ovo de
--     galinha cozido seria trocar de espécie — prefiro coluna vazia a
--     dado errado.
--   - Pão de sal: batia com pão branco "sem sal" (contradição direta com
--     o nome do alimento). Corrigido para Bread, white, commercially
--     prepared (com sal, padrão comercial).
--   - Pão integral / Pão integral light: batiam com pão pita integral
--     (forma de pão errada). Corrigidos para Bread, whole-wheat,
--     commercially prepared.
--   - Pão de milho: batia com um pão indígena norte-americano de milho
--     azul ("somiviki", povo Hopi) — produto muito diferente de pão de
--     milho brasileiro. Corrigido para Bread, cornbread, prepared from
--     recipe.
--
-- Também foram substituídos 2 fdc_ids que o algoritmo escolheu
-- corretamente em termos de identidade do alimento, mas cujo registro do
-- USDA (amostra Foundation Foods) não tinha o painel completo de
-- nutrientes carregado (camarão cru, atum em conserva) — trocados por
-- alternativas SR-Legacy do mesmo alimento com dados completos.
--
-- Como sempre: coalesce() preserva valores TACO/IBGE já existentes nas 12
-- colunas legadas; as 15 colunas novas (migration 0054) recebem o valor
-- USDA diretamente.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 50), ferro_mg = coalesce(ferro_mg, 1.19), magnesio_mg = 10, fosforo_mg = 172, potassio_mg = 126, sodio_mg = coalesce(sodio_mg, 124), zinco_mg = coalesce(zinco_mg, 1.05), cobre_mcg = 13, manganes_mg = 0.026, selenio_mcg = 30.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 149), vitamina_e_mg = 1.03, vitamina_d_mcg = coalesce(vitamina_d_mcg, 2.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.066), riboflavina_mg = coalesce(riboflavina_mg, 0.513), niacina_mg = coalesce(niacina_mg, 0.064), acido_pantotenico_mg = 1.398, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.121), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.11), colina_mg = 293.8, vitamina_k_mcg = 0.3, folato_mcg = 44 where nome = 'Ovo de galinha, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 64), ferro_mg = coalesce(ferro_mg, 3.65), magnesio_mg = 13, fosforo_mg = 226, potassio_mg = 132, sodio_mg = coalesce(sodio_mg, 141), zinco_mg = coalesce(zinco_mg, 1.47), cobre_mcg = 62, manganes_mg = 0.038, selenio_mcg = 32, vitamina_a_mcg = coalesce(vitamina_a_mcg, 156), vitamina_e_mg = 1.08, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.4), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.13), riboflavina_mg = coalesce(riboflavina_mg, 0.79), niacina_mg = coalesce(niacina_mg, 0.15), acido_pantotenico_mg = 1.761, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.15), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.58), colina_mg = 263.4, vitamina_k_mcg = 0.3, folato_mcg = 66 where nome = 'Ovo de codorna, Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1257), ferro_mg = coalesce(ferro_mg, 0.32), magnesio_mg = 110, fosforo_mg = 968, potassio_mg = 1794, sodio_mg = coalesce(sodio_mg, 535), zinco_mg = coalesce(zinco_mg, 4.08), cobre_mcg = 41, manganes_mg = 0.02, selenio_mcg = 27.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 6), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 6.8), tiamina_mg = coalesce(tiamina_mg, 0.415), riboflavina_mg = coalesce(riboflavina_mg, 1.55), niacina_mg = coalesce(niacina_mg, 0.951), acido_pantotenico_mg = 3.568, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.361), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 4.03), colina_mg = 169.2, vitamina_k_mcg = 0.1, folato_mcg = 50 where nome = 'Leite em pó desnatado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 66), ferro_mg = coalesce(ferro_mg, 0.1), magnesio_mg = 7, fosforo_mg = 58, potassio_mg = 95, sodio_mg = coalesce(sodio_mg, 27), zinco_mg = coalesce(zinco_mg, 0.24), cobre_mcg = 11, manganes_mg = 0.006, selenio_mcg = 3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 411), vitamina_e_mg = 0.92, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.6), vitamina_c_mg = coalesce(vitamina_c_mg, 0.6), tiamina_mg = coalesce(tiamina_mg, 0.02), riboflavina_mg = coalesce(riboflavina_mg, 0.188), niacina_mg = coalesce(niacina_mg, 0.064), acido_pantotenico_mg = 0.495, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.035), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.16), colina_mg = 16.8, vitamina_k_mcg = 3.2, folato_mcg = 4 where nome = 'Creme de leite' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 66), ferro_mg = coalesce(ferro_mg, 0.1), magnesio_mg = 7, fosforo_mg = 58, potassio_mg = 95, sodio_mg = coalesce(sodio_mg, 27), zinco_mg = coalesce(zinco_mg, 0.24), cobre_mcg = 11, manganes_mg = 0.006, selenio_mcg = 3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 411), vitamina_e_mg = 0.92, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.6), vitamina_c_mg = coalesce(vitamina_c_mg, 0.6), tiamina_mg = coalesce(tiamina_mg, 0.02), riboflavina_mg = coalesce(riboflavina_mg, 0.188), niacina_mg = coalesce(niacina_mg, 0.064), acido_pantotenico_mg = 0.495, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.035), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.16), colina_mg = 16.8, vitamina_k_mcg = 3.2, folato_mcg = 4 where nome = 'Creme de leite orgânico' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 69), ferro_mg = coalesce(ferro_mg, 0.03), magnesio_mg = 7, fosforo_mg = 61, potassio_mg = 97, sodio_mg = coalesce(sodio_mg, 34), zinco_mg = coalesce(zinco_mg, 0.25), cobre_mcg = 7, manganes_mg = 0.001, selenio_mcg = 0.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 279), vitamina_e_mg = 0.88, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.6), vitamina_c_mg = coalesce(vitamina_c_mg, 0.6), tiamina_mg = coalesce(tiamina_mg, 0.024), riboflavina_mg = coalesce(riboflavina_mg, 0.125), niacina_mg = coalesce(niacina_mg, 0.042), acido_pantotenico_mg = 0.259, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.028), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.2), colina_mg = 16.8, vitamina_k_mcg = 2.7, folato_mcg = 4 where nome = 'Creme de leite light' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 160), ferro_mg = coalesce(ferro_mg, 2.5), magnesio_mg = 133, fosforo_mg = 950, potassio_mg = 1458, sodio_mg = coalesce(sodio_mg, 7027), zinco_mg = coalesce(zinco_mg, 1.59), cobre_mcg = 176, manganes_mg = 0.05, selenio_mcg = 147.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 42), vitamina_e_mg = 2.84, vitamina_d_mcg = coalesce(vitamina_d_mcg, 4), vitamina_c_mg = coalesce(vitamina_c_mg, 3.5), tiamina_mg = coalesce(tiamina_mg, 0.268), riboflavina_mg = coalesce(riboflavina_mg, 0.24), niacina_mg = coalesce(niacina_mg, 7.5), acido_pantotenico_mg = 1.675, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.864), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 10), colina_mg = 291.3, vitamina_k_mcg = 0.4, folato_mcg = 25 where nome = 'Bacalhau' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 54), ferro_mg = coalesce(ferro_mg, 0.21), magnesio_mg = 22, fosforo_mg = 244, potassio_mg = 113, sodio_mg = coalesce(sodio_mg, 566), zinco_mg = coalesce(zinco_mg, 0.97), cobre_mcg = 182, manganes_mg = 0.029, selenio_mcg = 29.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 54), vitamina_e_mg = 1.32, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.02), riboflavina_mg = coalesce(riboflavina_mg, 0.015), niacina_mg = coalesce(niacina_mg, 1.778), acido_pantotenico_mg = 0.31, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.161), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.11), colina_mg = 80.9, vitamina_k_mcg = 0.3, folato_mcg = 19 where nome = 'Camarão, Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 1.63), magnesio_mg = 23, fosforo_mg = 139, potassio_mg = 179, sodio_mg = coalesce(sodio_mg, 247), zinco_mg = coalesce(zinco_mg, 0.69), cobre_mcg = 50, manganes_mg = 0.019, selenio_mcg = 70.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 17), vitamina_e_mg = 0.33, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.03), riboflavina_mg = coalesce(riboflavina_mg, 0.084), niacina_mg = coalesce(niacina_mg, 10.136), acido_pantotenico_mg = 0.148, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.319), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.55), colina_mg = 29.3, vitamina_k_mcg = 0.2, folato_mcg = 4 where nome = 'Atum em conserva' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 1.63), magnesio_mg = 23, fosforo_mg = 139, potassio_mg = 179, sodio_mg = coalesce(sodio_mg, 247), zinco_mg = coalesce(zinco_mg, 0.69), cobre_mcg = 50, manganes_mg = 0.019, selenio_mcg = 70.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 17), vitamina_e_mg = 0.33, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.03), riboflavina_mg = coalesce(riboflavina_mg, 0.084), niacina_mg = coalesce(niacina_mg, 10.136), acido_pantotenico_mg = 0.148, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.319), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.55), colina_mg = 29.3, vitamina_k_mcg = 0.2, folato_mcg = 4 where nome = 'Atum em conserva light' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 198), ferro_mg = coalesce(ferro_mg, 0.57), magnesio_mg = 30, fosforo_mg = 321, potassio_mg = 329, sodio_mg = coalesce(sodio_mg, 433), zinco_mg = coalesce(zinco_mg, 0.67), cobre_mcg = 61, manganes_mg = 0.024, selenio_mcg = 30.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 39), vitamina_e_mg = 1.88, vitamina_d_mcg = coalesce(vitamina_d_mcg, 19), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.02), riboflavina_mg = coalesce(riboflavina_mg, 0.2), niacina_mg = coalesce(niacina_mg, 6), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.33), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.4), colina_mg = 74.8, vitamina_k_mcg = 0.1, folato_mcg = 3 where nome = 'Salmão em conserva' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 144), ferro_mg = coalesce(ferro_mg, 3.61), magnesio_mg = 23, fosforo_mg = 98, potassio_mg = 126, sodio_mg = coalesce(sodio_mg, 490), zinco_mg = coalesce(zinco_mg, 0.74), cobre_mcg = 101, manganes_mg = 0.536, selenio_mcg = 22, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.22, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.533), riboflavina_mg = coalesce(riboflavina_mg, 0.243), niacina_mg = coalesce(niacina_mg, 4.78), acido_pantotenico_mg = 0.536, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.087), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 14.6, vitamina_k_mcg = 0.2, folato_mcg = 171 where nome = 'Pão de sal' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 161), ferro_mg = coalesce(ferro_mg, 2.47), magnesio_mg = 75, fosforo_mg = 212, potassio_mg = 254, sodio_mg = coalesce(sodio_mg, 455), zinco_mg = coalesce(zinco_mg, 1.77), cobre_mcg = 227, manganes_mg = 2.174, selenio_mcg = 25.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 2.66, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.394), riboflavina_mg = coalesce(riboflavina_mg, 0.167), niacina_mg = coalesce(niacina_mg, 4.438), acido_pantotenico_mg = 0.646, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.215), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 27.2, vitamina_k_mcg = 7.8, folato_mcg = 42 where nome = 'Pão integral' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 161), ferro_mg = coalesce(ferro_mg, 2.47), magnesio_mg = 75, fosforo_mg = 212, potassio_mg = 254, sodio_mg = coalesce(sodio_mg, 455), zinco_mg = coalesce(zinco_mg, 1.77), cobre_mcg = 227, manganes_mg = 2.174, selenio_mcg = 25.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 2.66, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.394), riboflavina_mg = coalesce(riboflavina_mg, 0.167), niacina_mg = coalesce(niacina_mg, 4.438), acido_pantotenico_mg = 0.646, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.215), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 27.2, vitamina_k_mcg = 7.8, folato_mcg = 42 where nome = 'Pão integral light' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 86), ferro_mg = coalesce(ferro_mg, 2.87), magnesio_mg = 24, fosforo_mg = 94, potassio_mg = 103, sodio_mg = coalesce(sodio_mg, 228), zinco_mg = coalesce(zinco_mg, 0.84), cobre_mcg = 121, manganes_mg = 0.46, selenio_mcg = 26.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 5), vitamina_e_mg = 0.29, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.2), tiamina_mg = coalesce(tiamina_mg, 0.377), riboflavina_mg = coalesce(riboflavina_mg, 0.23), niacina_mg = coalesce(niacina_mg, 3.463), acido_pantotenico_mg = 0.59, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.057), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.11), colina_mg = 29.1, vitamina_k_mcg = 1.6, folato_mcg = 155 where nome = 'Pão doce' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 86), ferro_mg = coalesce(ferro_mg, 2.87), magnesio_mg = 24, fosforo_mg = 94, potassio_mg = 103, sodio_mg = coalesce(sodio_mg, 228), zinco_mg = coalesce(zinco_mg, 0.84), cobre_mcg = 121, manganes_mg = 0.46, selenio_mcg = 26.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 5), vitamina_e_mg = 0.29, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.2), tiamina_mg = coalesce(tiamina_mg, 0.377), riboflavina_mg = coalesce(riboflavina_mg, 0.23), niacina_mg = coalesce(niacina_mg, 3.463), acido_pantotenico_mg = 0.59, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.057), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.11), colina_mg = 29.1, vitamina_k_mcg = 1.6, folato_mcg = 155 where nome = 'Pão doce diet' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 249), ferro_mg = coalesce(ferro_mg, 2.5), magnesio_mg = 25, fosforo_mg = 169, potassio_mg = 147, sodio_mg = coalesce(sodio_mg, 658), zinco_mg = coalesce(zinco_mg, 0.6), cobre_mcg = 51, manganes_mg = 0.118, selenio_mcg = 10.1, vitamina_c_mg = coalesce(vitamina_c_mg, 0.3), tiamina_mg = coalesce(tiamina_mg, 0.291), riboflavina_mg = coalesce(riboflavina_mg, 0.294), niacina_mg = coalesce(niacina_mg, 2.254), acido_pantotenico_mg = 0.339, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.113), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.15), folato_mcg = 118 where nome = 'Pão de milho' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 90), ferro_mg = coalesce(ferro_mg, 2.49), magnesio_mg = 17, fosforo_mg = 120, potassio_mg = 84, sodio_mg = coalesce(sodio_mg, 750), zinco_mg = coalesce(zinco_mg, 0.96), cobre_mcg = 86, manganes_mg = 0.366, selenio_mcg = 19.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 24), vitamina_e_mg = 1.49, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.433), riboflavina_mg = coalesce(riboflavina_mg, 0.303), niacina_mg = coalesce(niacina_mg, 3.279), acido_pantotenico_mg = 0.35, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.048), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.24), colina_mg = 8.5, vitamina_k_mcg = 32.4, folato_mcg = 159 where nome = 'Pão de queijo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 90), ferro_mg = coalesce(ferro_mg, 2.49), magnesio_mg = 17, fosforo_mg = 120, potassio_mg = 84, sodio_mg = coalesce(sodio_mg, 750), zinco_mg = coalesce(zinco_mg, 0.96), cobre_mcg = 86, manganes_mg = 0.366, selenio_mcg = 19.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 24), vitamina_e_mg = 1.49, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.433), riboflavina_mg = coalesce(riboflavina_mg, 0.303), niacina_mg = coalesce(niacina_mg, 3.279), acido_pantotenico_mg = 0.35, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.048), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.24), colina_mg = 8.5, vitamina_k_mcg = 32.4, folato_mcg = 159 where nome = 'Pão de queijo light' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 93), ferro_mg = coalesce(ferro_mg, 3.04), magnesio_mg = 19, fosforo_mg = 106, potassio_mg = 115, sodio_mg = coalesce(sodio_mg, 380), zinco_mg = coalesce(zinco_mg, 0.79), cobre_mcg = 162, manganes_mg = 0.5, selenio_mcg = 30.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 63), vitamina_e_mg = 0.26, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.4), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.438), riboflavina_mg = coalesce(riboflavina_mg, 0.436), niacina_mg = coalesce(niacina_mg, 4.848), acido_pantotenico_mg = 0.282, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.064), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.1), colina_mg = 84.3, vitamina_k_mcg = 0.9, folato_mcg = 130 where nome = 'Pão com ovo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 9), ferro_mg = coalesce(ferro_mg, 2.38), magnesio_mg = 22, fosforo_mg = 198, potassio_mg = 346, sodio_mg = coalesce(sodio_mg, 66), zinco_mg = coalesce(zinco_mg, 5.09), cobre_mcg = 78, manganes_mg = 0.01, selenio_mcg = 17.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 4), vitamina_e_mg = 0.17, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.041), riboflavina_mg = coalesce(riboflavina_mg, 0.151), niacina_mg = coalesce(niacina_mg, 5.494), acido_pantotenico_mg = 0.652, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.392), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.24), colina_mg = 70.9, vitamina_k_mcg = 0.3, folato_mcg = 5 where nome = 'Hambúrguer de carne bovina, Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
