-- Migration 0077: micronutrientes IBGE — lote 3 (carne bovina: cortes e vísceras)
--
-- Terceiro lote de curadoria de micronutrientes para a tabela IBGE. Este é
-- o primeiro lote que ataca diretamente o bloco de carnes, que era a parte
-- mais sistematicamente errada do casamento automático (ver headers das
-- migrations 0075/0076 pro achado completo). Cada um dos 19 itens aqui foi
-- pesquisado individualmente contra as bases SR-Legacy do USDA, no mesmo
-- processo usado na curadoria de Carnes da TACO (migration 0058).
--
-- Erros encontrados e corrigidos (o algoritmo estava usando um pequeno
-- número de entradas do USDA como "catch-all" pra praticamente qualquer
-- corte/víscera bovina cozida):
--   - "Beef, New Zealand, imported, sweetbread, cooked, boiled" (miolo/
--     timo de vitela) era usado como match de Bisteca, Costela, Peito,
--     Víscera, Tripa, Fato e Mocotó bovinos cozidos — todos órgãos/cortes
--     completamente diferentes entre si e do sweetbread. Corrigidos: costela
--     e peito bovino cozidos para brisket/rib cooked, braised.
--   - "Beef, variety meats and by-products, liver, cooked, braised" (fígado)
--     era usado como match de "Carne marica bovina, Refogado" e "Carne
--     bovina, Refogado" — corrigido pra carne bovina genérica (chuck pot
--     roast, cooked, braised); "carne marica" ficou de fora (nome de corte
--     regional sem tradução confirmada).
--   - Bofe bovino (= pulmão bovino) batia com "Beef, Tenderloin Roast"
--     (Assado) e "cured breakfast strips" (bacon, Refogado) — dois produtos
--     sem relação nenhuma com pulmão. Corrigido pra Beef, lungs, cooked,
--     braised nos dois casos.
--   - Tripa bovina batia com T-bone steak grelhado e Tenderloin Roast —
--     cortes nobres sem relação com tripa. Corrigida pra Beef, tripe,
--     cooked, simmered (usada como aproximação também pras variantes
--     grelhada/assada, já que o USDA não tem tripa nessas preparações
--     específicas — a composição mineral/vitamínica muda pouco entre
--     formas de cocção da mesma peça).
--   - "Carne bovina" genérica (cozida/refogada, sem corte especificado)
--     também usava tripa/fígado por engano — corrigida pra um corte comum
--     (chuck pot roast) como aproximação genérica de "carne bovina" sem
--     especificação, consistente com a Cru(a) já usar carne moída genérica.
--
-- Itens que ficaram de fora deste lote (prefiro vazio a dado errado):
--   - Carne marica bovina, Fato bovino: nomes de corte regionais cujo
--     significado exato eu não consegui confirmar com segurança.
--   - Mocotó bovino, Mão bovina (pé/mão de boi): o SR-Legacy do USDA não
--     tem um corte equivalente de pé/mão bovina catalogado.
--   - Víscera bovina (termo genérico demais pra escolher uma víscera
--     específica com segurança).
--
-- Como sempre: coalesce() preserva valores TACO/IBGE já existentes nas 12
-- colunas legadas; as 15 colunas novas (migration 0054) recebem o valor
-- USDA diretamente. Restam ainda: carne suína, aves (frango/peru),
-- embutidos, peixes/frutos do mar variados, refrigerantes, sucos e doces —
-- ficam pra próximos lotes.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 32), ferro_mg = coalesce(ferro_mg, 3.86), magnesio_mg = 30, fosforo_mg = 263, potassio_mg = 447, sodio_mg = coalesce(sodio_mg, 64), zinco_mg = coalesce(zinco_mg, 10.49), cobre_mcg = 172, manganes_mg = 0.02, selenio_mcg = 30, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.14), riboflavina_mg = coalesce(riboflavina_mg, 0.21), niacina_mg = coalesce(niacina_mg, 5.89), acido_pantotenico_mg = 0.41, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.37), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.79), folato_mcg = 10 where nome = 'Músculo bovino, Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 3.36), magnesio_mg = 22, fosforo_mg = 235, potassio_mg = 313, sodio_mg = coalesce(sodio_mg, 58), zinco_mg = coalesce(zinco_mg, 7.8), cobre_mcg = 107, manganes_mg = 0.018, selenio_mcg = 22.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.14, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.065), riboflavina_mg = coalesce(riboflavina_mg, 0.202), niacina_mg = coalesce(niacina_mg, 3.208), acido_pantotenico_mg = 0.337, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.28), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.46), colina_mg = 117.2, vitamina_k_mcg = 1.9, folato_mcg = 7 where nome = 'Costela bovina, Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 3.36), magnesio_mg = 22, fosforo_mg = 235, potassio_mg = 313, sodio_mg = coalesce(sodio_mg, 58), zinco_mg = coalesce(zinco_mg, 7.8), cobre_mcg = 107, manganes_mg = 0.018, selenio_mcg = 22.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.14, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.065), riboflavina_mg = coalesce(riboflavina_mg, 0.202), niacina_mg = coalesce(niacina_mg, 3.208), acido_pantotenico_mg = 0.337, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.28), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.46), colina_mg = 117.2, vitamina_k_mcg = 1.9, folato_mcg = 7 where nome = 'Costela bovina, Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 2.4), magnesio_mg = 19, fosforo_mg = 180, potassio_mg = 237, sodio_mg = coalesce(sodio_mg, 49), zinco_mg = coalesce(zinco_mg, 6.92), cobre_mcg = 90, manganes_mg = 0.01, selenio_mcg = 28.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.5, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.063), riboflavina_mg = coalesce(riboflavina_mg, 0.158), niacina_mg = coalesce(niacina_mg, 4.175), acido_pantotenico_mg = 0.572, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.285), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.92), colina_mg = 110.3, vitamina_k_mcg = 1.8, folato_mcg = 9 where nome = 'Costela bovina, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7), ferro_mg = coalesce(ferro_mg, 2.46), magnesio_mg = 20, fosforo_mg = 207, potassio_mg = 251, sodio_mg = coalesce(sodio_mg, 64), zinco_mg = coalesce(zinco_mg, 5.77), cobre_mcg = 104, manganes_mg = 0.015, selenio_mcg = 22.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.19, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.4), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.06), riboflavina_mg = coalesce(riboflavina_mg, 0.2), niacina_mg = coalesce(niacina_mg, 3.27), acido_pantotenico_mg = 0.31, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.26), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.4), colina_mg = 98.5, vitamina_k_mcg = 1.9, folato_mcg = 7 where nome = 'Peito bovino, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 6.81), magnesio_mg = 26, fosforo_mg = 265, potassio_mg = 184, sodio_mg = coalesce(sodio_mg, 59), zinco_mg = coalesce(zinco_mg, 2.79), cobre_mcg = 648, manganes_mg = 0.041, selenio_mcg = 17, vitamina_a_mcg = coalesce(vitamina_a_mcg, 14), vitamina_e_mg = 2.09, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.237), riboflavina_mg = coalesce(riboflavina_mg, 0.983), niacina_mg = coalesce(niacina_mg, 3.365), acido_pantotenico_mg = 1.231, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.122), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 6.73) where nome = 'Coração bovino, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 4), ferro_mg = coalesce(ferro_mg, 7.17), magnesio_mg = 21, fosforo_mg = 397, potassio_mg = 336, sodio_mg = coalesce(sodio_mg, 55), zinco_mg = coalesce(zinco_mg, 3.4), cobre_mcg = 5730, manganes_mg = 0.328, selenio_mcg = 16.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 21014), vitamina_e_mg = 1.28, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.376), riboflavina_mg = coalesce(riboflavina_mg, 3.04), niacina_mg = coalesce(niacina_mg, 13.8), acido_pantotenico_mg = 9.8, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.452), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 96) where nome = 'Fígado bovino, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 6.54), magnesio_mg = 21, fosforo_mg = 497, potassio_mg = 352, sodio_mg = coalesce(sodio_mg, 79), zinco_mg = coalesce(zinco_mg, 5.3), cobre_mcg = 14283, manganes_mg = 0.356, selenio_mcg = 36.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 9442), vitamina_e_mg = 0.51, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.2), vitamina_c_mg = coalesce(vitamina_c_mg, 1.9), tiamina_mg = coalesce(tiamina_mg, 0.194), riboflavina_mg = coalesce(riboflavina_mg, 3.425), niacina_mg = coalesce(niacina_mg, 17.525), acido_pantotenico_mg = 7.11, vitamina_b6_mg = coalesce(vitamina_b6_mg, 1.017), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 70.58), colina_mg = 426, vitamina_k_mcg = 3.3, folato_mcg = 253 where nome = 'Fígado bovino, Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 6.54), magnesio_mg = 21, fosforo_mg = 497, potassio_mg = 352, sodio_mg = coalesce(sodio_mg, 79), zinco_mg = coalesce(zinco_mg, 5.3), cobre_mcg = 14283, manganes_mg = 0.356, selenio_mcg = 36.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 9442), vitamina_e_mg = 0.51, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.2), vitamina_c_mg = coalesce(vitamina_c_mg, 1.9), tiamina_mg = coalesce(tiamina_mg, 0.194), riboflavina_mg = coalesce(riboflavina_mg, 3.425), niacina_mg = coalesce(niacina_mg, 17.525), acido_pantotenico_mg = 7.11, vitamina_b6_mg = coalesce(vitamina_b6_mg, 1.017), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 70.58), colina_mg = 426, vitamina_k_mcg = 3.3, folato_mcg = 253 where nome = 'Fígado bovino, Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 5), ferro_mg = coalesce(ferro_mg, 2.52), magnesio_mg = 17, fosforo_mg = 157, potassio_mg = 189, sodio_mg = coalesce(sodio_mg, 57), zinco_mg = coalesce(zinco_mg, 4.2), cobre_mcg = 163, manganes_mg = 0.013, selenio_mcg = 3.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 12), vitamina_e_mg = 0.95, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.059), riboflavina_mg = coalesce(riboflavina_mg, 0.227), niacina_mg = coalesce(niacina_mg, 2.58), acido_pantotenico_mg = 0.709, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.072), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.95) where nome = 'Língua bovina, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 5), ferro_mg = coalesce(ferro_mg, 2.61), magnesio_mg = 15, fosforo_mg = 145, potassio_mg = 184, sodio_mg = coalesce(sodio_mg, 65), zinco_mg = coalesce(zinco_mg, 4.09), cobre_mcg = 148, manganes_mg = 0.018, selenio_mcg = 13.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.3, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.4), vitamina_c_mg = coalesce(vitamina_c_mg, 1.3), tiamina_mg = coalesce(tiamina_mg, 0.022), riboflavina_mg = coalesce(riboflavina_mg, 0.294), niacina_mg = coalesce(niacina_mg, 3.49), acido_pantotenico_mg = 0.745, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.155), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.13), colina_mg = 155, vitamina_k_mcg = 1.2, folato_mcg = 7 where nome = 'Língua bovina, Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 81), ferro_mg = coalesce(ferro_mg, 0.66), magnesio_mg = 15, fosforo_mg = 66, potassio_mg = 42, sodio_mg = coalesce(sodio_mg, 68), zinco_mg = coalesce(zinco_mg, 1.71), cobre_mcg = 0, manganes_mg = 0.103, selenio_mcg = 11.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.14, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0.025), niacina_mg = coalesce(niacina_mg, 0.461), acido_pantotenico_mg = 0.097, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.72), vitamina_k_mcg = 0, folato_mcg = 3 where nome = 'Tripa bovina, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 81), ferro_mg = coalesce(ferro_mg, 0.66), magnesio_mg = 15, fosforo_mg = 66, potassio_mg = 42, sodio_mg = coalesce(sodio_mg, 68), zinco_mg = coalesce(zinco_mg, 1.71), cobre_mcg = 0, manganes_mg = 0.103, selenio_mcg = 11.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.14, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0.025), niacina_mg = coalesce(niacina_mg, 0.461), acido_pantotenico_mg = 0.097, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.72), vitamina_k_mcg = 0, folato_mcg = 3 where nome = 'Tripa bovina, Grelhado(a)/brasa/churrasco' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 81), ferro_mg = coalesce(ferro_mg, 0.66), magnesio_mg = 15, fosforo_mg = 66, potassio_mg = 42, sodio_mg = coalesce(sodio_mg, 68), zinco_mg = coalesce(zinco_mg, 1.71), cobre_mcg = 0, manganes_mg = 0.103, selenio_mcg = 11.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.14, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0.025), niacina_mg = coalesce(niacina_mg, 0.461), acido_pantotenico_mg = 0.097, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.72), vitamina_k_mcg = 0, folato_mcg = 3 where nome = 'Tripa bovina, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 5.4), magnesio_mg = 10, fosforo_mg = 178, potassio_mg = 173, sodio_mg = coalesce(sodio_mg, 101), zinco_mg = coalesce(zinco_mg, 1.64), cobre_mcg = 221, manganes_mg = 0.015, selenio_mcg = 50.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 12), vitamina_c_mg = coalesce(vitamina_c_mg, 32.7), tiamina_mg = coalesce(tiamina_mg, 0.035), riboflavina_mg = coalesce(riboflavina_mg, 0.143), niacina_mg = coalesce(niacina_mg, 2.492), acido_pantotenico_mg = 0.623, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.02), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.59), folato_mcg = 8 where nome = 'Bofe bovino, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 5.4), magnesio_mg = 10, fosforo_mg = 178, potassio_mg = 173, sodio_mg = coalesce(sodio_mg, 101), zinco_mg = coalesce(zinco_mg, 1.64), cobre_mcg = 221, manganes_mg = 0.015, selenio_mcg = 50.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 12), vitamina_c_mg = coalesce(vitamina_c_mg, 32.7), tiamina_mg = coalesce(tiamina_mg, 0.035), riboflavina_mg = coalesce(riboflavina_mg, 0.143), niacina_mg = coalesce(niacina_mg, 2.492), acido_pantotenico_mg = 0.623, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.02), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.59), folato_mcg = 8 where nome = 'Bofe bovino, Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 9), ferro_mg = coalesce(ferro_mg, 2.38), magnesio_mg = 22, fosforo_mg = 198, potassio_mg = 346, sodio_mg = coalesce(sodio_mg, 66), zinco_mg = coalesce(zinco_mg, 5.09), cobre_mcg = 78, manganes_mg = 0.01, selenio_mcg = 17.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 4), vitamina_e_mg = 0.17, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.041), riboflavina_mg = coalesce(riboflavina_mg, 0.151), niacina_mg = coalesce(niacina_mg, 5.494), acido_pantotenico_mg = 0.652, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.392), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.24), colina_mg = 70.9, vitamina_k_mcg = 0.3, folato_mcg = 5 where nome = 'Carne bovina, Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 2.53), magnesio_mg = 20, fosforo_mg = 183, potassio_mg = 242, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 6.98), cobre_mcg = 104, manganes_mg = 0.01, selenio_mcg = 28.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.53, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.061), riboflavina_mg = coalesce(riboflavina_mg, 0.178), niacina_mg = coalesce(niacina_mg, 4.273), acido_pantotenico_mg = 0.594, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.295), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.22), colina_mg = 114.7, vitamina_k_mcg = 1.9, folato_mcg = 9 where nome = 'Carne bovina, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 2.53), magnesio_mg = 20, fosforo_mg = 183, potassio_mg = 242, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 6.98), cobre_mcg = 104, manganes_mg = 0.01, selenio_mcg = 28.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.53, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.061), riboflavina_mg = coalesce(riboflavina_mg, 0.178), niacina_mg = coalesce(niacina_mg, 4.273), acido_pantotenico_mg = 0.594, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.295), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.22), colina_mg = 114.7, vitamina_k_mcg = 1.9, folato_mcg = 9 where nome = 'Carne bovina, Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
