-- Migration 0078: micronutrientes IBGE — lote 4 (carne suína: cortes e vísceras)
--
-- Quarto lote de curadoria de micronutrientes para a tabela IBGE.
-- Continuação da migration 0077 (bovinos), agora cobrindo carne suína.
-- Mesmo processo: cada um dos 20 itens foi pesquisado individualmente
-- contra as bases SR-Legacy do USDA.
--
-- Erros encontrados e corrigidos (o algoritmo estava usando "Pork, fresh,
-- ground, cooked" — carne suína moída genérica — como catch-all pra vários
-- cortes/vísceras específicos completamente diferentes entre si):
--   - Figado suíno (cozido/assado): batia com carne moída genérica —
--     corrigido pra Pork, liver, cooked, braised (fígado de verdade).
--   - Mocotó suíno / Pé suíno fresco: batiam com carne moída genérica —
--     corrigidos pra Pork, feet, cooked, simmered (pé de porco de fato).
--   - Orelha suína fresca: batia com carne moída genérica — corrigida pra
--     Pork, ears, frozen, cooked, simmered (orelha de fato).
--   - Alcatra suína, Cozido(a): batia com carne moída genérica; Assado(a)
--     batia com presunto CURADO assado (produto industrializado, não carne
--     fresca) — ambos corrigidos pra Pork, leg (ham), rump half, cooked,
--     roasted (corte de alcatra suína fresca).
--   - Carne suína, Cru(a): batia com "Pork, fresh, variety meats and
--     by-products, feet, raw" (pé de porco cru — corte específico errado
--     pra um item genérico "carne suína"). Corrigida pra Pork, composite
--     of trimmed retail cuts (leg/loin/shoulder/spareribs), raw — a
--     entrada padrão do USDA pra "carne de porco" sem corte especificado.
--   - Carne suína, Cozido(a)/Refogado(a): batiam com fígado suíno cozido —
--     órgão errado pra um item genérico. Corrigidas pro mesmo composite
--     de cortes, cozido.
--
-- Itens que ficaram de fora deste lote (prefiro vazio a dado errado):
--   - Suã suína (corte de espinhaço/coluna usado em feijoada): sem
--     equivalente direto no SR-Legacy.
--   - Míudo suíno (miúdos/vísceras não especificadas): termo genérico
--     demais pra escolher uma víscera específica com segurança.
--
-- Como sempre: coalesce() preserva valores TACO/IBGE já existentes nas 12
-- colunas legadas; as 15 colunas novas (migration 0054) recebem o valor
-- USDA diretamente. Restam ainda: aves (frango/peru), embutidos,
-- peixes/frutos do mar variados, refrigerantes, sucos e doces — ficam
-- pra próximos lotes.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 49), ferro_mg = coalesce(ferro_mg, 0.85), magnesio_mg = 20, fosforo_mg = 224, potassio_mg = 270, sodio_mg = coalesce(sodio_mg, 70), zinco_mg = coalesce(zinco_mg, 3.28), cobre_mcg = 97, manganes_mg = 0.012, selenio_mcg = 44.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.9), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.507), riboflavina_mg = coalesce(riboflavina_mg, 0.332), niacina_mg = coalesce(niacina_mg, 7.604), acido_pantotenico_mg = 0.968, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.515), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.61), colina_mg = 86, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Bisteca suína, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 49), ferro_mg = coalesce(ferro_mg, 0.85), magnesio_mg = 20, fosforo_mg = 224, potassio_mg = 270, sodio_mg = coalesce(sodio_mg, 70), zinco_mg = coalesce(zinco_mg, 3.28), cobre_mcg = 97, manganes_mg = 0.012, selenio_mcg = 44.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.9), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.507), riboflavina_mg = coalesce(riboflavina_mg, 0.332), niacina_mg = coalesce(niacina_mg, 7.604), acido_pantotenico_mg = 0.968, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.515), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.61), colina_mg = 86, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Bisteca suína, Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 21), ferro_mg = coalesce(ferro_mg, 0.9), magnesio_mg = 23, fosforo_mg = 204, potassio_mg = 338, sodio_mg = coalesce(sodio_mg, 67), zinco_mg = coalesce(zinco_mg, 3), cobre_mcg = 83, manganes_mg = 0.012, selenio_mcg = 34.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.25, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.394), riboflavina_mg = coalesce(riboflavina_mg, 0.271), niacina_mg = coalesce(niacina_mg, 3.097), acido_pantotenico_mg = 1.737, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.577), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.01), colina_mg = 87.3, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Costela suína, Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 33), ferro_mg = coalesce(ferro_mg, 1.39), magnesio_mg = 23, fosforo_mg = 208, potassio_mg = 297, sodio_mg = coalesce(sodio_mg, 60), zinco_mg = coalesce(zinco_mg, 4.46), cobre_mcg = 105, manganes_mg = 0.011, selenio_mcg = 48.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.477), riboflavina_mg = coalesce(riboflavina_mg, 0.296), niacina_mg = coalesce(niacina_mg, 5.715), acido_pantotenico_mg = 1.427, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.491), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.94), colina_mg = 113.5, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Costela suína, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 33), ferro_mg = coalesce(ferro_mg, 1.39), magnesio_mg = 23, fosforo_mg = 208, potassio_mg = 297, sodio_mg = coalesce(sodio_mg, 60), zinco_mg = coalesce(zinco_mg, 4.46), cobre_mcg = 105, manganes_mg = 0.011, selenio_mcg = 48.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.477), riboflavina_mg = coalesce(riboflavina_mg, 0.296), niacina_mg = coalesce(niacina_mg, 5.715), acido_pantotenico_mg = 1.427, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.491), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.94), colina_mg = 113.5, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Costela suína, Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 33), ferro_mg = coalesce(ferro_mg, 1.39), magnesio_mg = 23, fosforo_mg = 208, potassio_mg = 297, sodio_mg = coalesce(sodio_mg, 60), zinco_mg = coalesce(zinco_mg, 4.46), cobre_mcg = 105, manganes_mg = 0.011, selenio_mcg = 48.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.477), riboflavina_mg = coalesce(riboflavina_mg, 0.296), niacina_mg = coalesce(niacina_mg, 5.715), acido_pantotenico_mg = 1.427, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.491), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.94), colina_mg = 113.5, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Costela suína, Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 18), ferro_mg = coalesce(ferro_mg, 1.13), magnesio_mg = 20, fosforo_mg = 183, potassio_mg = 387, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 2.48), cobre_mcg = 79, manganes_mg = 0.013, selenio_mcg = 48.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.8), vitamina_c_mg = coalesce(vitamina_c_mg, 0.6), tiamina_mg = coalesce(tiamina_mg, 0.659), riboflavina_mg = coalesce(riboflavina_mg, 0.267), niacina_mg = coalesce(niacina_mg, 4.588), acido_pantotenico_mg = 0.677, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.387), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.55), colina_mg = 98.2, vitamina_k_mcg = 0, folato_mcg = 4 where nome = 'Lombo suíno, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 19), ferro_mg = coalesce(ferro_mg, 4.99), magnesio_mg = 20, fosforo_mg = 174, potassio_mg = 237, sodio_mg = coalesce(sodio_mg, 109), zinco_mg = coalesce(zinco_mg, 4.53), cobre_mcg = 110, manganes_mg = 0.01, selenio_mcg = 15.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.7), tiamina_mg = coalesce(tiamina_mg, 0.317), riboflavina_mg = coalesce(riboflavina_mg, 0.51), niacina_mg = coalesce(niacina_mg, 5.34), acido_pantotenico_mg = 0.507, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.23), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.39), folato_mcg = 4 where nome = 'Língua suína, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 19), ferro_mg = coalesce(ferro_mg, 4.99), magnesio_mg = 20, fosforo_mg = 174, potassio_mg = 237, sodio_mg = coalesce(sodio_mg, 109), zinco_mg = coalesce(zinco_mg, 4.53), cobre_mcg = 110, manganes_mg = 0.01, selenio_mcg = 15.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.7), tiamina_mg = coalesce(tiamina_mg, 0.317), riboflavina_mg = coalesce(riboflavina_mg, 0.51), niacina_mg = coalesce(niacina_mg, 5.34), acido_pantotenico_mg = 0.507, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.23), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.39), folato_mcg = 4 where nome = 'Língua suína, Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 10), ferro_mg = coalesce(ferro_mg, 17.92), magnesio_mg = 14, fosforo_mg = 241, potassio_mg = 150, sodio_mg = coalesce(sodio_mg, 49), zinco_mg = coalesce(zinco_mg, 6.72), cobre_mcg = 634, manganes_mg = 0.3, selenio_mcg = 67.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 5405), vitamina_c_mg = coalesce(vitamina_c_mg, 23.6), tiamina_mg = coalesce(tiamina_mg, 0.258), riboflavina_mg = coalesce(riboflavina_mg, 2.196), niacina_mg = coalesce(niacina_mg, 8.435), acido_pantotenico_mg = 4.774, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.57), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 18.67), folato_mcg = 163 where nome = 'Figado suíno, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 10), ferro_mg = coalesce(ferro_mg, 17.92), magnesio_mg = 14, fosforo_mg = 241, potassio_mg = 150, sodio_mg = coalesce(sodio_mg, 49), zinco_mg = coalesce(zinco_mg, 6.72), cobre_mcg = 634, manganes_mg = 0.3, selenio_mcg = 67.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 5405), vitamina_c_mg = coalesce(vitamina_c_mg, 23.6), tiamina_mg = coalesce(tiamina_mg, 0.258), riboflavina_mg = coalesce(riboflavina_mg, 2.196), niacina_mg = coalesce(niacina_mg, 8.435), acido_pantotenico_mg = 4.774, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.57), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 18.67), folato_mcg = 163 where nome = 'Figado suíno, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 0), ferro_mg = coalesce(ferro_mg, 0.98), magnesio_mg = 5, fosforo_mg = 82, potassio_mg = 33, sodio_mg = coalesce(sodio_mg, 73), zinco_mg = coalesce(zinco_mg, 1.05), cobre_mcg = 62, manganes_mg = 0.018, selenio_mcg = 23, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.09, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.016), riboflavina_mg = coalesce(riboflavina_mg, 0.057), niacina_mg = coalesce(niacina_mg, 0.585), acido_pantotenico_mg = 0.24, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.038), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.41), colina_mg = 75.4, vitamina_k_mcg = 0, folato_mcg = 2 where nome = 'Mocotó suíno, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 0), ferro_mg = coalesce(ferro_mg, 0.98), magnesio_mg = 5, fosforo_mg = 82, potassio_mg = 33, sodio_mg = coalesce(sodio_mg, 73), zinco_mg = coalesce(zinco_mg, 1.05), cobre_mcg = 62, manganes_mg = 0.018, selenio_mcg = 23, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.09, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.016), riboflavina_mg = coalesce(riboflavina_mg, 0.057), niacina_mg = coalesce(niacina_mg, 0.585), acido_pantotenico_mg = 0.24, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.038), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.41), colina_mg = 75.4, vitamina_k_mcg = 0, folato_mcg = 2 where nome = 'Pé suíno fresco, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 18), ferro_mg = coalesce(ferro_mg, 1.5), magnesio_mg = 7, fosforo_mg = 24, potassio_mg = 40, sodio_mg = coalesce(sodio_mg, 167), zinco_mg = coalesce(zinco_mg, 0.2), cobre_mcg = 6, manganes_mg = 0.01, selenio_mcg = 4.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.02), riboflavina_mg = coalesce(riboflavina_mg, 0.07), niacina_mg = coalesce(niacina_mg, 0.56), acido_pantotenico_mg = 0.037, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.01), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.04), folato_mcg = 0 where nome = 'Orelha suína fresca, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 16), ferro_mg = coalesce(ferro_mg, 0.9), magnesio_mg = 25, fosforo_mg = 255, potassio_mg = 416, sodio_mg = coalesce(sodio_mg, 77), zinco_mg = coalesce(zinco_mg, 2.31), cobre_mcg = 112, manganes_mg = 0.016, selenio_mcg = 25, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.27, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.4), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.489), riboflavina_mg = coalesce(riboflavina_mg, 0.379), niacina_mg = coalesce(niacina_mg, 7.444), acido_pantotenico_mg = 0.859, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.501), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.67), colina_mg = 92.8, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Alcatra suína, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 16), ferro_mg = coalesce(ferro_mg, 0.9), magnesio_mg = 25, fosforo_mg = 255, potassio_mg = 416, sodio_mg = coalesce(sodio_mg, 77), zinco_mg = coalesce(zinco_mg, 2.31), cobre_mcg = 112, manganes_mg = 0.016, selenio_mcg = 25, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.27, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.4), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.489), riboflavina_mg = coalesce(riboflavina_mg, 0.379), niacina_mg = coalesce(niacina_mg, 7.444), acido_pantotenico_mg = 0.859, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.501), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.67), colina_mg = 92.8, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Alcatra suína, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 19), ferro_mg = coalesce(ferro_mg, 0.86), magnesio_mg = 21, fosforo_mg = 200, potassio_mg = 335, sodio_mg = coalesce(sodio_mg, 55), zinco_mg = coalesce(zinco_mg, 2.01), cobre_mcg = 64, manganes_mg = 0.011, selenio_mcg = 28.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_c_mg = coalesce(vitamina_c_mg, 0.5), tiamina_mg = coalesce(tiamina_mg, 0.841), riboflavina_mg = coalesce(riboflavina_mg, 0.254), niacina_mg = coalesce(niacina_mg, 4.504), acido_pantotenico_mg = 0.73, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.445), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.66), folato_mcg = 5 where nome = 'Carne suína, Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 20), ferro_mg = coalesce(ferro_mg, 1.11), magnesio_mg = 24, fosforo_mg = 221, potassio_mg = 341, sodio_mg = coalesce(sodio_mg, 57), zinco_mg = coalesce(zinco_mg, 3.06), cobre_mcg = 90, manganes_mg = 0.01, selenio_mcg = 42, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.13, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.9), vitamina_c_mg = coalesce(vitamina_c_mg, 0.1), tiamina_mg = coalesce(tiamina_mg, 0.611), riboflavina_mg = coalesce(riboflavina_mg, 0.29), niacina_mg = coalesce(niacina_mg, 6.047), acido_pantotenico_mg = 0.844, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.542), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.7), colina_mg = 80.1, vitamina_k_mcg = 0, folato_mcg = 2 where nome = 'Carne suína, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 20), ferro_mg = coalesce(ferro_mg, 1.11), magnesio_mg = 24, fosforo_mg = 221, potassio_mg = 341, sodio_mg = coalesce(sodio_mg, 57), zinco_mg = coalesce(zinco_mg, 3.06), cobre_mcg = 90, manganes_mg = 0.01, selenio_mcg = 42, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.13, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.9), vitamina_c_mg = coalesce(vitamina_c_mg, 0.1), tiamina_mg = coalesce(tiamina_mg, 0.611), riboflavina_mg = coalesce(riboflavina_mg, 0.29), niacina_mg = coalesce(niacina_mg, 6.047), acido_pantotenico_mg = 0.844, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.542), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.7), colina_mg = 80.1, vitamina_k_mcg = 0, folato_mcg = 2 where nome = 'Carne suína, Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 1.29), magnesio_mg = 24, fosforo_mg = 226, potassio_mg = 362, sodio_mg = coalesce(sodio_mg, 73), zinco_mg = coalesce(zinco_mg, 3.21), cobre_mcg = 44, manganes_mg = 0.011, selenio_mcg = 35.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0.7), tiamina_mg = coalesce(tiamina_mg, 0.706), riboflavina_mg = coalesce(riboflavina_mg, 0.22), niacina_mg = coalesce(niacina_mg, 4.206), acido_pantotenico_mg = 0.52, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.391), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.54), colina_mg = 88.3, vitamina_k_mcg = 0, folato_mcg = 6 where nome = 'Quarto suíno, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
