-- Migration 0080: micronutrientes IBGE — lote 6 (embutidos e conservas simples)
--
-- Sexto lote de curadoria de micronutrientes para a tabela IBGE. Cobre
-- salsicha, linguiça e conservas/pastas de carne e peixe. 13 itens
-- aprovados.
--
-- Erros corrigidos:
--   - Linguiça (suína, bovina, mista, etc.), Cru(a): batia com "Sausage,
--     turkey, fresh, raw" (linguiça de peru — espécie errada pra um item
--     que abrange suína/bovina/mista). Corrigida pra Sausage, pork,
--     chorizo, raw — a aproximação mais próxima de linguiça crua
--     disponível no SR-Legacy.
--   - Linguiça de frango, Cru(a): batia com "Chicken, ground, raw" (frango
--     moído cru — não é um produto de linguiça, é carne crua pura).
--     Corrigida pra Sausage, turkey, breakfast links, raw (peru é a ave
--     mais próxima disponível já formulada como linguiça/embutido cru).
--
-- Itens que ficaram de fora (prefiro vazio a dado errado): "Carne bovina
-- em conserva" (batia com um prato pronto de ensopado enlatado com
-- legumes, não carne pura), "Nabo em conserva" (batia com folhas de nabo,
-- não a raiz) e "Creme de legumes (sopa desidratada)"/"light" (batiam com
-- um substituto de creme líquido industrial, produto sem relação).
--
-- Como sempre: coalesce() preserva valores TACO/IBGE já existentes nas 12
-- colunas legadas; as 15 colunas novas (migration 0054) recebem o valor
-- USDA diretamente. Restam ainda: refrigerantes, sucos e doces — ficam
-- pra próximos lotes (e provavelmente exigirão pesquisa externa, já que
-- boa parte bate sistematicamente com produtos genéricos tipo "cream
-- soda"/"sweet chocolate candy" sem relação real com o item do IBGE).

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 29), ferro_mg = coalesce(ferro_mg, 0.86), magnesio_mg = 16, fosforo_mg = 185, potassio_mg = 82, sodio_mg = coalesce(sodio_mg, 897), zinco_mg = coalesce(zinco_mg, 0.58), cobre_mcg = 97, manganes_mg = 0.172, selenio_mcg = 9.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 32), vitamina_e_mg = 2.52, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.06), riboflavina_mg = coalesce(riboflavina_mg, 0.02), niacina_mg = coalesce(niacina_mg, 1.24), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.06), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.53), colina_mg = 50.6, vitamina_k_mcg = 4.7, folato_mcg = 62 where nome = 'Camarão, Empanado(a)/à milanesa' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 19), ferro_mg = coalesce(ferro_mg, 1.17), magnesio_mg = 19, fosforo_mg = 177, potassio_mg = 262, sodio_mg = coalesce(sodio_mg, 593), zinco_mg = coalesce(zinco_mg, 3.06), cobre_mcg = 86, manganes_mg = 0.021, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 13), vitamina_e_mg = 0.13, vitamina_c_mg = coalesce(vitamina_c_mg, 2.3), tiamina_mg = coalesce(tiamina_mg, 0.077), riboflavina_mg = coalesce(riboflavina_mg, 0.234), niacina_mg = coalesce(niacina_mg, 4.6), acido_pantotenico_mg = 1.02, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.431), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.3), vitamina_k_mcg = 0, folato_mcg = 5 where nome = 'Salsicha no varejo, Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 107), ferro_mg = coalesce(ferro_mg, 1.12), magnesio_mg = 11, fosforo_mg = 180, potassio_mg = 323, sodio_mg = coalesce(sodio_mg, 914), zinco_mg = coalesce(zinco_mg, 1.25), cobre_mcg = 40, manganes_mg = 0.02, selenio_mcg = 13.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 31), vitamina_e_mg = 0.45, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.6), vitamina_c_mg = coalesce(vitamina_c_mg, 19.4), tiamina_mg = coalesce(tiamina_mg, 0.044), riboflavina_mg = coalesce(riboflavina_mg, 0.145), niacina_mg = coalesce(niacina_mg, 2.672), acido_pantotenico_mg = 0.551, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.067), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.69), colina_mg = 54.3, vitamina_k_mcg = 1.7, folato_mcg = 9 where nome = 'Salsicha no varejo, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 10), ferro_mg = coalesce(ferro_mg, 0.88), magnesio_mg = 7, fosforo_mg = 49, potassio_mg = 101, sodio_mg = coalesce(sodio_mg, 879), zinco_mg = coalesce(zinco_mg, 1.6), cobre_mcg = 30, selenio_mcg = 16.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.22, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.6), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.087), riboflavina_mg = coalesce(riboflavina_mg, 0.107), niacina_mg = coalesce(niacina_mg, 1.613), acido_pantotenico_mg = 0.35, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.12), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.02), colina_mg = 43.7, vitamina_k_mcg = 1.6, folato_mcg = 4 where nome = 'Salsicha em conserva' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 19), ferro_mg = coalesce(ferro_mg, 1.41), magnesio_mg = 20, fosforo_mg = 149, potassio_mg = 308, sodio_mg = coalesce(sodio_mg, 788), zinco_mg = coalesce(zinco_mg, 1.68), cobre_mcg = 84, manganes_mg = 0.093, selenio_mcg = 18.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.22, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.207), riboflavina_mg = coalesce(riboflavina_mg, 0.31), niacina_mg = coalesce(niacina_mg, 5.47), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.313), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2), colina_mg = 96.7, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Linguiça (suína, bovina, mista, etc.), Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 1.57), magnesio_mg = 14, fosforo_mg = 141, potassio_mg = 258, sodio_mg = coalesce(sodio_mg, 813), zinco_mg = coalesce(zinco_mg, 4.38), cobre_mcg = 69, manganes_mg = 0, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 13), vitamina_e_mg = 0.24, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.048), riboflavina_mg = coalesce(riboflavina_mg, 0.15), niacina_mg = coalesce(niacina_mg, 3.6), acido_pantotenico_mg = 0.515, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.313), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.01), colina_mg = 51.4, vitamina_k_mcg = 1.1, folato_mcg = 3 where nome = 'Linguiça (suína, bovina, mista, etc.), Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 1.57), magnesio_mg = 14, fosforo_mg = 141, potassio_mg = 258, sodio_mg = coalesce(sodio_mg, 813), zinco_mg = coalesce(zinco_mg, 4.38), cobre_mcg = 69, manganes_mg = 0, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 13), vitamina_e_mg = 0.24, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.048), riboflavina_mg = coalesce(riboflavina_mg, 0.15), niacina_mg = coalesce(niacina_mg, 3.6), acido_pantotenico_mg = 0.515, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.313), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.01), colina_mg = 51.4, vitamina_k_mcg = 1.1, folato_mcg = 3 where nome = 'Linguiça (suína, bovina, mista, etc.), Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 1.57), magnesio_mg = 14, fosforo_mg = 141, potassio_mg = 258, sodio_mg = coalesce(sodio_mg, 813), zinco_mg = coalesce(zinco_mg, 4.38), cobre_mcg = 69, manganes_mg = 0, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 13), vitamina_e_mg = 0.24, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.048), riboflavina_mg = coalesce(riboflavina_mg, 0.15), niacina_mg = coalesce(niacina_mg, 3.6), acido_pantotenico_mg = 0.515, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.313), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.01), colina_mg = 51.4, vitamina_k_mcg = 1.1, folato_mcg = 3 where nome = 'Linguiça (suína, bovina, mista, etc.), Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 55), ferro_mg = coalesce(ferro_mg, 1.34), magnesio_mg = 20, fosforo_mg = 174, potassio_mg = 258, sodio_mg = coalesce(sodio_mg, 714), zinco_mg = coalesce(zinco_mg, 2.51), cobre_mcg = 72, manganes_mg = 0.078, selenio_mcg = 12.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.19, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.4), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.039), riboflavina_mg = coalesce(riboflavina_mg, 0.299), niacina_mg = coalesce(niacina_mg, 4.433), acido_pantotenico_mg = 0.808, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.259), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.28), colina_mg = 33.9, vitamina_k_mcg = 0.4, folato_mcg = 6 where nome = 'Linguiça de frango, Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 0.72), magnesio_mg = 10, fosforo_mg = 82, potassio_mg = 215, sodio_mg = coalesce(sodio_mg, 1289), zinco_mg = coalesce(zinco_mg, 1.48), cobre_mcg = 37, manganes_mg = 0.024, selenio_mcg = 28, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.26, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 1), tiamina_mg = coalesce(tiamina_mg, 0.367), riboflavina_mg = coalesce(riboflavina_mg, 0.194), niacina_mg = coalesce(niacina_mg, 3.126), acido_pantotenico_mg = 0.473, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.21), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.9), colina_mg = 61.8, vitamina_k_mcg = 0, folato_mcg = 6 where nome = 'Pasta de carne em conserva' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7), ferro_mg = coalesce(ferro_mg, 0.95), magnesio_mg = 13, fosforo_mg = 139, potassio_mg = 284, sodio_mg = coalesce(sodio_mg, 1280), zinco_mg = coalesce(zinco_mg, 1.83), cobre_mcg = 50, manganes_mg = 0.025, selenio_mcg = 18.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.25, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.6), vitamina_c_mg = coalesce(vitamina_c_mg, 2), tiamina_mg = coalesce(tiamina_mg, 0.535), riboflavina_mg = coalesce(riboflavina_mg, 0.165), niacina_mg = coalesce(niacina_mg, 3.2), acido_pantotenico_mg = 0.28, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.32), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.7), colina_mg = 64.4, vitamina_k_mcg = 0, folato_mcg = 1 where nome = 'Pasta de presunto em conserva' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 14), ferro_mg = coalesce(ferro_mg, 1.3), magnesio_mg = 19, fosforo_mg = 153, potassio_mg = 153, sodio_mg = coalesce(sodio_mg, 482), zinco_mg = coalesce(zinco_mg, 2.5), cobre_mcg = 50, selenio_mcg = 18.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 53), vitamina_e_mg = 0.32, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0.1), niacina_mg = coalesce(niacina_mg, 2.4), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.19), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1), colina_mg = 73.8, vitamina_k_mcg = 2.3, folato_mcg = 2 where nome = 'Pasta de galinha em conserva' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 283), ferro_mg = coalesce(ferro_mg, 0.77), magnesio_mg = 32, fosforo_mg = 379, potassio_mg = 333, sodio_mg = coalesce(sodio_mg, 381), zinco_mg = coalesce(zinco_mg, 0.96), cobre_mcg = 82, manganes_mg = 0.031, selenio_mcg = 39.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 20), vitamina_e_mg = 1.28, vitamina_d_mcg = coalesce(vitamina_d_mcg, 14.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.027), riboflavina_mg = coalesce(riboflavina_mg, 0.202), niacina_mg = coalesce(niacina_mg, 7.409), acido_pantotenico_mg = 0.563, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.105), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 4.95), colina_mg = 87.8, vitamina_k_mcg = 0.1, folato_mcg = 4 where nome = 'Pasta de peixe em conserva' and fonte = 'IBGE' and id_avaliador is null;
