-- Migration 0081: micronutrientes Fabricante — lote 1 (Temperos e Especiarias puras)
--
-- Primeira migration de micronutrientes para a tabela de alimentos com
-- fonte='Fabricante' (produtos de varejo/marca, extraídos da ficha
-- nutricional de cada produto em casaspedro.com.br — ver
-- scripts/tabela_alimentos_*_casaspedro.sql). Essa fonte é estruturalmente
-- diferente de TACO/IBGE: não existe uma base fechada de ~600-2000 itens
-- pra casar item a item — são ~370 produtos de marca específicos
-- (suplementos, temperos, farinhas, doces, castanhas, bebidas vegetais),
-- a maioria sem equivalente direto no USDA porque são formulações
-- proprietárias (misturas de tempero de marca, whey protein com sabor
-- específico, etc.) cuja composição de vitaminas/minerais depende
-- inteiramente da receita do fabricante.
--
-- Por isso, ao contrário de TACO/IBGE, não houve casamento automático —
-- cada um dos 19 itens deste lote foi escolhido manualmente, restrito à
-- categoria "Temperos e Especiarias" (62 itens no total) e, dentro dela,
-- só às especiarias/ervas PURAS de um único ingrediente (páprica, canela,
-- cominho, curry, shitake seco, anis estrelado, cravo, gengibre, alho em
-- pó, cebola em pó/flocos, sal).
--
-- Ficaram de fora deste lote (prefiro vazio a dado errado): as ~40
-- misturas proprietárias de marca (Tempero Pega Esposa, Tempero
-- Paranaense, Tempero Mineiro, Chimichurri, Tempera Tudo, Lemon Pepper,
-- etc. — cada uma é uma receita de sal + especiarias específica da marca,
-- sem equivalente USDA), Colorau/Colorau Extra Forte (urucum — sem
-- entrada equivalente no USDA), Alho Picado (os valores da própria ficha
-- indicam um produto bem diluído — provavelmente em conserva/óleo — não
-- alho puro, usar o dado do pó daria valor errado), Alho Torrado, Cebola
-- Crispy (cebola frita empanada, perfil de gordura muito diferente) e
-- Fumaça Em Pó (aromatizante de fumaça líquida, sem equivalente no USDA).
--
-- Como nas migrations de TACO/IBGE: coalesce() preserva os valores já
-- existentes nas 12 colunas legadas (aqui, só sodio_mg costuma vir
-- preenchido da própria ficha do fabricante); as 15 colunas novas
-- (migration 0054) recebem o valor USDA diretamente. Restam ainda:
-- Suplementos, Grãos e Sementes/Farinhas, Doces, Castanhas/Chocolates e
-- Bebidas Vegetais — a maioria também dominada por produtos formulados de
-- marca; grãos/farinhas e castanhas têm chance real de aproveitamento em
-- lotes futuros por serem majoritariamente ingredientes simples.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 229), ferro_mg = coalesce(ferro_mg, 21.14), magnesio_mg = 178, fosforo_mg = 314, potassio_mg = 2280, sodio_mg = coalesce(sodio_mg, 68), zinco_mg = coalesce(zinco_mg, 4.33), cobre_mcg = 713, manganes_mg = 1.59, selenio_mcg = 6.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2463), vitamina_e_mg = 29.1, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.9), tiamina_mg = coalesce(tiamina_mg, 0.33), riboflavina_mg = coalesce(riboflavina_mg, 1.23), niacina_mg = coalesce(niacina_mg, 10.06), acido_pantotenico_mg = 2.51, vitamina_b6_mg = coalesce(vitamina_b6_mg, 2.141), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 51.5, vitamina_k_mcg = 80.3, folato_mcg = 49 where nome = 'Páprica Defumada Condimentada - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 229), ferro_mg = coalesce(ferro_mg, 21.14), magnesio_mg = 178, fosforo_mg = 314, potassio_mg = 2280, sodio_mg = coalesce(sodio_mg, 68), zinco_mg = coalesce(zinco_mg, 4.33), cobre_mcg = 713, manganes_mg = 1.59, selenio_mcg = 6.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2463), vitamina_e_mg = 29.1, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.9), tiamina_mg = coalesce(tiamina_mg, 0.33), riboflavina_mg = coalesce(riboflavina_mg, 1.23), niacina_mg = coalesce(niacina_mg, 10.06), acido_pantotenico_mg = 2.51, vitamina_b6_mg = coalesce(vitamina_b6_mg, 2.141), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 51.5, vitamina_k_mcg = 80.3, folato_mcg = 49 where nome = 'Páprica Picante Condimentada - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 229), ferro_mg = coalesce(ferro_mg, 21.14), magnesio_mg = 178, fosforo_mg = 314, potassio_mg = 2280, sodio_mg = coalesce(sodio_mg, 68), zinco_mg = coalesce(zinco_mg, 4.33), cobre_mcg = 713, manganes_mg = 1.59, selenio_mcg = 6.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2463), vitamina_e_mg = 29.1, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.9), tiamina_mg = coalesce(tiamina_mg, 0.33), riboflavina_mg = coalesce(riboflavina_mg, 1.23), niacina_mg = coalesce(niacina_mg, 10.06), acido_pantotenico_mg = 2.51, vitamina_b6_mg = coalesce(vitamina_b6_mg, 2.141), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 51.5, vitamina_k_mcg = 80.3, folato_mcg = 49 where nome = 'Páprica Defumada Extra - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 229), ferro_mg = coalesce(ferro_mg, 21.14), magnesio_mg = 178, fosforo_mg = 314, potassio_mg = 2280, sodio_mg = coalesce(sodio_mg, 68), zinco_mg = coalesce(zinco_mg, 4.33), cobre_mcg = 713, manganes_mg = 1.59, selenio_mcg = 6.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2463), vitamina_e_mg = 29.1, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.9), tiamina_mg = coalesce(tiamina_mg, 0.33), riboflavina_mg = coalesce(riboflavina_mg, 1.23), niacina_mg = coalesce(niacina_mg, 10.06), acido_pantotenico_mg = 2.51, vitamina_b6_mg = coalesce(vitamina_b6_mg, 2.141), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 51.5, vitamina_k_mcg = 80.3, folato_mcg = 49 where nome = 'Páprica Doce Condimentada - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 229), ferro_mg = coalesce(ferro_mg, 21.14), magnesio_mg = 178, fosforo_mg = 314, potassio_mg = 2280, sodio_mg = coalesce(sodio_mg, 68), zinco_mg = coalesce(zinco_mg, 4.33), cobre_mcg = 713, manganes_mg = 1.59, selenio_mcg = 6.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2463), vitamina_e_mg = 29.1, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.9), tiamina_mg = coalesce(tiamina_mg, 0.33), riboflavina_mg = coalesce(riboflavina_mg, 1.23), niacina_mg = coalesce(niacina_mg, 10.06), acido_pantotenico_mg = 2.51, vitamina_b6_mg = coalesce(vitamina_b6_mg, 2.141), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 51.5, vitamina_k_mcg = 80.3, folato_mcg = 49 where nome = 'Páprica Extra - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 229), ferro_mg = coalesce(ferro_mg, 21.14), magnesio_mg = 178, fosforo_mg = 314, potassio_mg = 2280, sodio_mg = coalesce(sodio_mg, 68), zinco_mg = coalesce(zinco_mg, 4.33), cobre_mcg = 713, manganes_mg = 1.59, selenio_mcg = 6.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2463), vitamina_e_mg = 29.1, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.9), tiamina_mg = coalesce(tiamina_mg, 0.33), riboflavina_mg = coalesce(riboflavina_mg, 1.23), niacina_mg = coalesce(niacina_mg, 10.06), acido_pantotenico_mg = 2.51, vitamina_b6_mg = coalesce(vitamina_b6_mg, 2.141), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 51.5, vitamina_k_mcg = 80.3, folato_mcg = 49 where nome = 'Páprica Picante Extra - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1002), ferro_mg = coalesce(ferro_mg, 8.32), magnesio_mg = 60, fosforo_mg = 64, potassio_mg = 431, sodio_mg = coalesce(sodio_mg, 10), zinco_mg = coalesce(zinco_mg, 1.83), cobre_mcg = 339, manganes_mg = 17.466, selenio_mcg = 3.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 15), vitamina_e_mg = 2.32, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 3.8), tiamina_mg = coalesce(tiamina_mg, 0.022), riboflavina_mg = coalesce(riboflavina_mg, 0.041), niacina_mg = coalesce(niacina_mg, 1.332), acido_pantotenico_mg = 0.358, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.158), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 11, vitamina_k_mcg = 31.2, folato_mcg = 6 where nome = 'Canela Em Pau Pequena - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1002), ferro_mg = coalesce(ferro_mg, 8.32), magnesio_mg = 60, fosforo_mg = 64, potassio_mg = 431, sodio_mg = coalesce(sodio_mg, 10), zinco_mg = coalesce(zinco_mg, 1.83), cobre_mcg = 339, manganes_mg = 17.466, selenio_mcg = 3.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 15), vitamina_e_mg = 2.32, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 3.8), tiamina_mg = coalesce(tiamina_mg, 0.022), riboflavina_mg = coalesce(riboflavina_mg, 0.041), niacina_mg = coalesce(niacina_mg, 1.332), acido_pantotenico_mg = 0.358, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.158), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 11, vitamina_k_mcg = 31.2, folato_mcg = 6 where nome = 'Canela Em Pó Importada - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 931), ferro_mg = coalesce(ferro_mg, 66.36), magnesio_mg = 366, fosforo_mg = 499, potassio_mg = 1788, sodio_mg = coalesce(sodio_mg, 168), zinco_mg = coalesce(zinco_mg, 4.8), cobre_mcg = 867, manganes_mg = 3.333, selenio_mcg = 5.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 64), vitamina_e_mg = 3.33, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 7.7), tiamina_mg = coalesce(tiamina_mg, 0.628), riboflavina_mg = coalesce(riboflavina_mg, 0.327), niacina_mg = coalesce(niacina_mg, 4.579), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.435), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 24.7, vitamina_k_mcg = 5.4, folato_mcg = 10 where nome = 'Cominho Em Pó Importado - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 525), ferro_mg = coalesce(ferro_mg, 19.1), magnesio_mg = 255, fosforo_mg = 367, potassio_mg = 1170, sodio_mg = coalesce(sodio_mg, 52), zinco_mg = coalesce(zinco_mg, 4.7), cobre_mcg = 1200, manganes_mg = 8.3, selenio_mcg = 40.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 25.24, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.7), tiamina_mg = coalesce(tiamina_mg, 0.176), riboflavina_mg = coalesce(riboflavina_mg, 0.2), niacina_mg = coalesce(niacina_mg, 3.26), acido_pantotenico_mg = 1.07, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.105), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 64.2, vitamina_k_mcg = 99.8, folato_mcg = 56 where nome = 'Curry - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 1.72), magnesio_mg = 132, fosforo_mg = 294, potassio_mg = 1534, sodio_mg = coalesce(sodio_mg, 13), zinco_mg = coalesce(zinco_mg, 7.66), cobre_mcg = 5165, manganes_mg = 1.176, selenio_mcg = 46.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 3.9), vitamina_c_mg = coalesce(vitamina_c_mg, 3.5), tiamina_mg = coalesce(tiamina_mg, 0.3), riboflavina_mg = coalesce(riboflavina_mg, 1.27), niacina_mg = coalesce(niacina_mg, 14.1), acido_pantotenico_mg = 21.879, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.965), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 201.7, vitamina_k_mcg = 0, folato_mcg = 163 where nome = 'Shitake Fatiado - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 646), ferro_mg = coalesce(ferro_mg, 36.96), magnesio_mg = 170, fosforo_mg = 440, potassio_mg = 1441, sodio_mg = coalesce(sodio_mg, 16), zinco_mg = coalesce(zinco_mg, 5.3), cobre_mcg = 910, manganes_mg = 2.3, selenio_mcg = 5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 16), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 21), tiamina_mg = coalesce(tiamina_mg, 0.34), riboflavina_mg = coalesce(riboflavina_mg, 0.29), niacina_mg = coalesce(niacina_mg, 3.06), acido_pantotenico_mg = 0.797, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.65), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 10 where nome = 'Anis Estrelado - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 632), ferro_mg = coalesce(ferro_mg, 11.83), magnesio_mg = 259, fosforo_mg = 104, potassio_mg = 1020, sodio_mg = coalesce(sodio_mg, 277), zinco_mg = coalesce(zinco_mg, 2.32), cobre_mcg = 368, manganes_mg = 60.127, selenio_mcg = 7.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 8), vitamina_e_mg = 8.82, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.2), tiamina_mg = coalesce(tiamina_mg, 0.158), riboflavina_mg = coalesce(riboflavina_mg, 0.22), niacina_mg = coalesce(niacina_mg, 1.56), acido_pantotenico_mg = 0.509, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.391), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 37.4, vitamina_k_mcg = 141.8, folato_mcg = 25 where nome = 'Cravo Em Pó - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 114), ferro_mg = coalesce(ferro_mg, 19.8), magnesio_mg = 214, fosforo_mg = 168, potassio_mg = 1320, sodio_mg = coalesce(sodio_mg, 27), zinco_mg = coalesce(zinco_mg, 3.64), cobre_mcg = 480, manganes_mg = 33.3, selenio_mcg = 55.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.7), tiamina_mg = coalesce(tiamina_mg, 0.046), riboflavina_mg = coalesce(riboflavina_mg, 0.17), niacina_mg = coalesce(niacina_mg, 9.62), acido_pantotenico_mg = 0.477, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.626), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 41.2, vitamina_k_mcg = 0.8, folato_mcg = 13 where nome = 'Gengibre Em Pó - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 79), ferro_mg = coalesce(ferro_mg, 5.65), magnesio_mg = 77, fosforo_mg = 414, potassio_mg = 1193, sodio_mg = coalesce(sodio_mg, 60), zinco_mg = coalesce(zinco_mg, 2.99), cobre_mcg = 533, manganes_mg = 0.979, selenio_mcg = 23.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.67, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.2), tiamina_mg = coalesce(tiamina_mg, 0.435), riboflavina_mg = coalesce(riboflavina_mg, 0.141), niacina_mg = coalesce(niacina_mg, 0.796), acido_pantotenico_mg = 0.743, vitamina_b6_mg = coalesce(vitamina_b6_mg, 1.654), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 67.5, vitamina_k_mcg = 0.4, folato_mcg = 47 where nome = 'Alho Em Pó - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 384), ferro_mg = coalesce(ferro_mg, 3.9), magnesio_mg = 113, fosforo_mg = 322, potassio_mg = 985, sodio_mg = coalesce(sodio_mg, 73), zinco_mg = coalesce(zinco_mg, 4.05), cobre_mcg = 590, manganes_mg = 1.3, selenio_mcg = 14.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.27, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 23.4), tiamina_mg = coalesce(tiamina_mg, 0.457), riboflavina_mg = coalesce(riboflavina_mg, 0.08), niacina_mg = coalesce(niacina_mg, 0.321), acido_pantotenico_mg = 0.732, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.718), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 39, vitamina_k_mcg = 4.1, folato_mcg = 64 where nome = 'Cebola Em Pó - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 257), ferro_mg = coalesce(ferro_mg, 1.55), magnesio_mg = 92, fosforo_mg = 303, potassio_mg = 1622, sodio_mg = coalesce(sodio_mg, 21), zinco_mg = coalesce(zinco_mg, 1.89), cobre_mcg = 416, manganes_mg = 1.389, selenio_mcg = 5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 0.18, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 75), tiamina_mg = coalesce(tiamina_mg, 0.5), riboflavina_mg = coalesce(riboflavina_mg, 0.1), niacina_mg = coalesce(niacina_mg, 0.99), acido_pantotenico_mg = 1.38, vitamina_b6_mg = coalesce(vitamina_b6_mg, 1.6), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 53.9, vitamina_k_mcg = 3.8, folato_mcg = 166 where nome = 'Cebola Em Flocos - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 384), ferro_mg = coalesce(ferro_mg, 3.9), magnesio_mg = 113, fosforo_mg = 322, potassio_mg = 985, sodio_mg = coalesce(sodio_mg, 73), zinco_mg = coalesce(zinco_mg, 4.05), cobre_mcg = 590, manganes_mg = 1.3, selenio_mcg = 14.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.27, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 23.4), tiamina_mg = coalesce(tiamina_mg, 0.457), riboflavina_mg = coalesce(riboflavina_mg, 0.08), niacina_mg = coalesce(niacina_mg, 0.321), acido_pantotenico_mg = 0.732, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.718), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 39, vitamina_k_mcg = 4.1, folato_mcg = 64 where nome = 'Cebola Roxa Granulada - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 24), ferro_mg = coalesce(ferro_mg, 0.33), magnesio_mg = 1, fosforo_mg = 0, potassio_mg = 8, sodio_mg = coalesce(sodio_mg, 38758), zinco_mg = coalesce(zinco_mg, 0.1), cobre_mcg = 30, manganes_mg = 0.1, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Sal Dourado - 50g' and categoria = 'Temperos e Especiarias' and fonte = 'Fabricante' and id_avaliador is null;
