-- Migration 0082: micronutrientes Fabricante — lote 2 (Grãos e Sementes / Farinhas)
--
-- Segunda migration de micronutrientes pra fonte='Fabricante'. Cobre as
-- categorias "Grãos e Sementes" e "Farinhas" (produtos a granel de
-- empório: arroz, feijão, quinoa, sementes, farinhas — ver
-- scripts/tabela_alimentos_graos_farinhas_casaspedro.sql), que são
-- majoritariamente ingredientes simples de um só componente — bem mais
-- tratável que Temperos (dominado por misturas de marca). 53 itens
-- aprovados (41 de Grãos e Sementes, 12 de Farinhas), de 72 no total.
--
-- Aproximações assumidas (mesma variedade/espécie, sem entrada USDA
-- específica pra sub-variedade — perfil mineral/vitamínico deve ser
-- equivalente ou muito próximo):
--   - Arroz integral agulinha/cateto, branco/vermelho: todos usam a
--     mesma entrada de arroz integral de grão longo genérico.
--   - Feijão carioca: usa pinto bean (mesmo tipo de feijão, sem entrada
--     "carioca" específica no USDA).
--   - Lentilha vermelha, quinoa (flocos/grão/vermelha/preta/mista), chia
--     branca, gergelim preto/torrado, grão de bico miúdo: usam a entrada
--     genérica da espécie (variedade de cor/processamento não muda o
--     perfil mineral/vitamínico de forma relevante).
--   - Arroz arbóreo (grão médio) e basmati (grão longo aromático): usam
--     as entradas de arroz branco de grão médio/longo mais próximas.
--   - Canjica branca: usa "Hominy, canned, white" — não há entrada de
--     milho de canjica seco no USDA; é o milho branco processado mais
--     próximo disponível.
--   - Farinha de mesa: usa farinha de mandioca (é farinha de mandioca
--     torrada grossa, mesmo ingrediente-base).
--
-- Itens que ficaram de fora deste lote (prefiro vazio a dado errado):
--   - Feijão Corda, Feijão Fradinho: são variações de feijão-de-corda
--     (cowpea) — o USDA só tem cowpea em vagem imatura/congelada, não a
--     semente seca madura que é o produto real vendido a granel.
--   - Ervilha Canadense: não há entrada de ervilha seca inteira crua no
--     USDA (só ervilha verde fresca/enlatada/congelada).
--   - Arroz Preto, Milho de Pipoca (grão não estourado), Alpiste
--     (canário): sem entrada equivalente no USDA.
--   - Arroz 7 Cereais: mistura de grãos, sem equivalente único.
--   - Farinha de Acaçá, Farinha de Acarajé, Farinha de Banana Verde,
--     Farinha de Coco, Farinha de Amora, Farinha de Maracujá: sem
--     entrada equivalente no USDA.
--   - Farinha de Rosca, Farinha Panko: sem entrada de farinha de rosca
--     seca isolada no USDA (só como componente descrito dentro de outro
--     alimento, com umidade muito diferente).
--   - Farinha Multiuso Sem Glúten Schar, Farinha Sem Glúten Aminna:
--     misturas proprietárias de marca.
--   - Farinha de Paçoquita: é paçoca (doce de amendoim) moída, não um
--     ingrediente simples.
--
-- Como sempre: coalesce() preserva os valores já existentes nas 12
-- colunas legadas (aqui, sodio_mg vem da própria ficha do fabricante); as
-- 15 colunas novas (migration 0054) recebem o valor USDA diretamente.
-- Restam ainda: Suplementos, Doces, Castanhas/Chocolates e Bebidas
-- Vegetais.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 10), ferro_mg = coalesce(ferro_mg, 0.62), magnesio_mg = 16, fosforo_mg = 35, potassio_mg = 9, sodio_mg = coalesce(sodio_mg, 267), zinco_mg = coalesce(zinco_mg, 1.05), cobre_mcg = 30, manganes_mg = 0.07, selenio_mcg = 3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.05, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.3), tiamina_mg = coalesce(tiamina_mg, 0.003), riboflavina_mg = coalesce(riboflavina_mg, 0.006), niacina_mg = coalesce(niacina_mg, 0.033), acido_pantotenico_mg = 0.154, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.005), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 3.1, vitamina_k_mcg = 0.2, folato_mcg = 1 where nome = 'Canjica Branca - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 9), ferro_mg = coalesce(ferro_mg, 1.29), magnesio_mg = 116, fosforo_mg = 311, potassio_mg = 250, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 2.13), cobre_mcg = 302, manganes_mg = 2.853, selenio_mcg = 17.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.6, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.541), riboflavina_mg = coalesce(riboflavina_mg, 0.095), niacina_mg = coalesce(niacina_mg, 6.494), acido_pantotenico_mg = 1.065, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.477), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 21.5, vitamina_k_mcg = 0.6, folato_mcg = 23 where nome = 'Arroz Integral Agulinha Branco - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 9), ferro_mg = coalesce(ferro_mg, 1.29), magnesio_mg = 116, fosforo_mg = 311, potassio_mg = 250, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 2.13), cobre_mcg = 302, manganes_mg = 2.853, selenio_mcg = 17.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.6, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.541), riboflavina_mg = coalesce(riboflavina_mg, 0.095), niacina_mg = coalesce(niacina_mg, 6.494), acido_pantotenico_mg = 1.065, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.477), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 21.5, vitamina_k_mcg = 0.6, folato_mcg = 23 where nome = 'Arroz Integral Agulinha Vermelho - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 9), ferro_mg = coalesce(ferro_mg, 1.29), magnesio_mg = 116, fosforo_mg = 311, potassio_mg = 250, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 2.13), cobre_mcg = 302, manganes_mg = 2.853, selenio_mcg = 17.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.6, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.541), riboflavina_mg = coalesce(riboflavina_mg, 0.095), niacina_mg = coalesce(niacina_mg, 6.494), acido_pantotenico_mg = 1.065, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.477), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 21.5, vitamina_k_mcg = 0.6, folato_mcg = 23 where nome = 'Arroz Integral Cateto Branco - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 9), ferro_mg = coalesce(ferro_mg, 1.29), magnesio_mg = 116, fosforo_mg = 311, potassio_mg = 250, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 2.13), cobre_mcg = 302, manganes_mg = 2.853, selenio_mcg = 17.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.6, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.541), riboflavina_mg = coalesce(riboflavina_mg, 0.095), niacina_mg = coalesce(niacina_mg, 6.494), acido_pantotenico_mg = 1.065, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.477), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 21.5, vitamina_k_mcg = 0.6, folato_mcg = 23 where nome = 'Arroz Integral Cateto Vermelho - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 9), ferro_mg = coalesce(ferro_mg, 1.29), magnesio_mg = 116, fosforo_mg = 311, potassio_mg = 250, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 2.13), cobre_mcg = 302, manganes_mg = 2.853, selenio_mcg = 17.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.6, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.541), riboflavina_mg = coalesce(riboflavina_mg, 0.095), niacina_mg = coalesce(niacina_mg, 6.494), acido_pantotenico_mg = 1.065, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.477), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 21.5, vitamina_k_mcg = 0.6, folato_mcg = 23 where nome = 'Arroz Integral Vermelho - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 29), ferro_mg = coalesce(ferro_mg, 2.5), magnesio_mg = 79, fosforo_mg = 221, potassio_mg = 280, sodio_mg = coalesce(sodio_mg, 9), zinco_mg = coalesce(zinco_mg, 2.13), cobre_mcg = 420, manganes_mg = 1.322, selenio_mcg = 37.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.191), riboflavina_mg = coalesce(riboflavina_mg, 0.114), niacina_mg = coalesce(niacina_mg, 4.604), acido_pantotenico_mg = 0.282, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.26), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 37.8, vitamina_k_mcg = 2.2, folato_mcg = 23 where nome = 'Cevadinha - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 975), ferro_mg = coalesce(ferro_mg, 14.55), magnesio_mg = 351, fosforo_mg = 629, potassio_mg = 468, sodio_mg = coalesce(sodio_mg, 11), zinco_mg = coalesce(zinco_mg, 7.75), cobre_mcg = 4082, manganes_mg = 2.46, selenio_mcg = 34.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.25, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.791), riboflavina_mg = coalesce(riboflavina_mg, 0.247), niacina_mg = coalesce(niacina_mg, 4.515), acido_pantotenico_mg = 0.05, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.79), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 25.6, vitamina_k_mcg = 0, folato_mcg = 97 where nome = 'Gergelim Integral - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 975), ferro_mg = coalesce(ferro_mg, 14.55), magnesio_mg = 351, fosforo_mg = 629, potassio_mg = 468, sodio_mg = coalesce(sodio_mg, 11), zinco_mg = coalesce(zinco_mg, 7.75), cobre_mcg = 4082, manganes_mg = 2.46, selenio_mcg = 34.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.25, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.791), riboflavina_mg = coalesce(riboflavina_mg, 0.247), niacina_mg = coalesce(niacina_mg, 4.515), acido_pantotenico_mg = 0.05, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.79), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 25.6, vitamina_k_mcg = 0, folato_mcg = 97 where nome = 'Gergelim Preto - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 975), ferro_mg = coalesce(ferro_mg, 14.55), magnesio_mg = 351, fosforo_mg = 629, potassio_mg = 468, sodio_mg = coalesce(sodio_mg, 11), zinco_mg = coalesce(zinco_mg, 7.75), cobre_mcg = 4082, manganes_mg = 2.46, selenio_mcg = 34.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.25, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.791), riboflavina_mg = coalesce(riboflavina_mg, 0.247), niacina_mg = coalesce(niacina_mg, 4.515), acido_pantotenico_mg = 0.05, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.79), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 25.6, vitamina_k_mcg = 0, folato_mcg = 97 where nome = 'Gergelim Torrado - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 20), ferro_mg = coalesce(ferro_mg, 1.58), magnesio_mg = 1, fosforo_mg = 7, potassio_mg = 11, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.12), cobre_mcg = 20, manganes_mg = 0.11, selenio_mcg = 0.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.004), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0.135, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.008), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 1.2, vitamina_k_mcg = 0, folato_mcg = 4 where nome = 'Sagu - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 35), ferro_mg = coalesce(ferro_mg, 6.51), magnesio_mg = 47, fosforo_mg = 281, potassio_mg = 677, sodio_mg = coalesce(sodio_mg, 6), zinco_mg = coalesce(zinco_mg, 3.27), cobre_mcg = 754, manganes_mg = 1.393, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.49, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4.5), tiamina_mg = coalesce(tiamina_mg, 0.873), riboflavina_mg = coalesce(riboflavina_mg, 0.211), niacina_mg = coalesce(niacina_mg, 2.605), acido_pantotenico_mg = 2.14, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.54), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 96.4, vitamina_k_mcg = 5, folato_mcg = 479 where nome = 'Lentilha - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 35), ferro_mg = coalesce(ferro_mg, 6.51), magnesio_mg = 47, fosforo_mg = 281, potassio_mg = 677, sodio_mg = coalesce(sodio_mg, 6), zinco_mg = coalesce(zinco_mg, 3.27), cobre_mcg = 754, manganes_mg = 1.393, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.49, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4.5), tiamina_mg = coalesce(tiamina_mg, 0.873), riboflavina_mg = coalesce(riboflavina_mg, 0.211), niacina_mg = coalesce(niacina_mg, 2.605), acido_pantotenico_mg = 2.14, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.54), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 96.4, vitamina_k_mcg = 5, folato_mcg = 479 where nome = 'Lentilha Vermelha Canadense - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 57), ferro_mg = coalesce(ferro_mg, 4.31), magnesio_mg = 79, fosforo_mg = 252, potassio_mg = 718, sodio_mg = coalesce(sodio_mg, 24), zinco_mg = coalesce(zinco_mg, 2.76), cobre_mcg = 656, manganes_mg = 4.15, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.82, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4), tiamina_mg = coalesce(tiamina_mg, 0.477), riboflavina_mg = coalesce(riboflavina_mg, 0.212), niacina_mg = coalesce(niacina_mg, 1.541), acido_pantotenico_mg = 1.588, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.535), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 99.3, vitamina_k_mcg = 9, folato_mcg = 557 where nome = 'Grão de Bico Graúdo - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 57), ferro_mg = coalesce(ferro_mg, 4.31), magnesio_mg = 79, fosforo_mg = 252, potassio_mg = 718, sodio_mg = coalesce(sodio_mg, 24), zinco_mg = coalesce(zinco_mg, 2.76), cobre_mcg = 656, manganes_mg = 4.15, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.82, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4), tiamina_mg = coalesce(tiamina_mg, 0.477), riboflavina_mg = coalesce(riboflavina_mg, 0.212), niacina_mg = coalesce(niacina_mg, 1.541), acido_pantotenico_mg = 1.588, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.535), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 99.3, vitamina_k_mcg = 9, folato_mcg = 557 where nome = 'Grão de Bico Miúdo - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 113), ferro_mg = coalesce(ferro_mg, 5.07), magnesio_mg = 176, fosforo_mg = 411, potassio_mg = 1393, sodio_mg = coalesce(sodio_mg, 12), zinco_mg = coalesce(zinco_mg, 2.28), cobre_mcg = 893, manganes_mg = 1.148, selenio_mcg = 27.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 6.3), tiamina_mg = coalesce(tiamina_mg, 0.713), riboflavina_mg = coalesce(riboflavina_mg, 0.212), niacina_mg = coalesce(niacina_mg, 1.174), acido_pantotenico_mg = 0.785, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.474), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 66.2, vitamina_k_mcg = 5.6, folato_mcg = 525 where nome = 'Feijão Carioca - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 66), ferro_mg = coalesce(ferro_mg, 4.98), magnesio_mg = 127, fosforo_mg = 381, potassio_mg = 1254, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 5.04), cobre_mcg = 1094, manganes_mg = 1.73, selenio_mcg = 3.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.455), riboflavina_mg = coalesce(riboflavina_mg, 0.22), niacina_mg = coalesce(niacina_mg, 2.63), acido_pantotenico_mg = 1.471, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.351), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 622 where nome = 'Feijão Azuky - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 240), ferro_mg = coalesce(ferro_mg, 10.44), magnesio_mg = 190, fosforo_mg = 301, potassio_mg = 1795, sodio_mg = coalesce(sodio_mg, 16), zinco_mg = coalesce(zinco_mg, 3.67), cobre_mcg = 984, manganes_mg = 1.796, selenio_mcg = 12.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.437), riboflavina_mg = coalesce(riboflavina_mg, 0.146), niacina_mg = coalesce(niacina_mg, 0.479), acido_pantotenico_mg = 0.732, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.318), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 66.2, vitamina_k_mcg = 5.6, folato_mcg = 388 where nome = 'Feijão Branco - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 83), ferro_mg = coalesce(ferro_mg, 6.69), magnesio_mg = 138, fosforo_mg = 406, potassio_mg = 1359, sodio_mg = coalesce(sodio_mg, 12), zinco_mg = coalesce(zinco_mg, 2.79), cobre_mcg = 699, manganes_mg = 1.111, selenio_mcg = 3.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4.5), tiamina_mg = coalesce(tiamina_mg, 0.608), riboflavina_mg = coalesce(riboflavina_mg, 0.215), niacina_mg = coalesce(niacina_mg, 2.11), acido_pantotenico_mg = 0.78, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.397), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 65.9, vitamina_k_mcg = 5.6, folato_mcg = 394 where nome = 'Feijão Vermelho - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 123), ferro_mg = coalesce(ferro_mg, 5.02), magnesio_mg = 171, fosforo_mg = 352, potassio_mg = 1483, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 3.65), cobre_mcg = 841, manganes_mg = 1.06, selenio_mcg = 3.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.9), riboflavina_mg = coalesce(riboflavina_mg, 0.193), niacina_mg = coalesce(niacina_mg, 1.955), acido_pantotenico_mg = 0.899, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.286), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 66.4, vitamina_k_mcg = 5.6, folato_mcg = 444 where nome = 'Feijão Preto Especial - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 39), ferro_mg = coalesce(ferro_mg, 6.26), magnesio_mg = 239, fosforo_mg = 842, potassio_mg = 892, sodio_mg = coalesce(sodio_mg, 12), zinco_mg = coalesce(zinco_mg, 12.29), cobre_mcg = 796, manganes_mg = 13.301, selenio_mcg = 79.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 1.882), riboflavina_mg = coalesce(riboflavina_mg, 0.499), niacina_mg = coalesce(niacina_mg, 6.813), acido_pantotenico_mg = 2.257, vitamina_b6_mg = coalesce(vitamina_b6_mg, 1.3), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 281 where nome = 'Gérmen de Trigo - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 73), ferro_mg = coalesce(ferro_mg, 10.57), magnesio_mg = 611, fosforo_mg = 1013, potassio_mg = 1182, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 7.27), cobre_mcg = 998, manganes_mg = 11.5, selenio_mcg = 77.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 1.49, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.523), riboflavina_mg = coalesce(riboflavina_mg, 0.577), niacina_mg = coalesce(niacina_mg, 13.578), acido_pantotenico_mg = 2.181, vitamina_b6_mg = coalesce(vitamina_b6_mg, 1.303), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 74.4, vitamina_k_mcg = 1.9, folato_mcg = 79 where nome = 'Farelo de Trigo - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 47), ferro_mg = coalesce(ferro_mg, 4.57), magnesio_mg = 197, fosforo_mg = 457, potassio_mg = 563, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 3.1), cobre_mcg = 590, manganes_mg = 2.033, selenio_mcg = 8.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 2.44, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), tiamina_mg = coalesce(tiamina_mg, 0.36), riboflavina_mg = coalesce(riboflavina_mg, 0.318), niacina_mg = coalesce(niacina_mg, 1.52), acido_pantotenico_mg = 0.772, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.487), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 70.2, vitamina_k_mcg = 0, folato_mcg = 184 where nome = 'Quinoa Em Flocos - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 47), ferro_mg = coalesce(ferro_mg, 4.57), magnesio_mg = 197, fosforo_mg = 457, potassio_mg = 563, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 3.1), cobre_mcg = 590, manganes_mg = 2.033, selenio_mcg = 8.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 2.44, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), tiamina_mg = coalesce(tiamina_mg, 0.36), riboflavina_mg = coalesce(riboflavina_mg, 0.318), niacina_mg = coalesce(niacina_mg, 1.52), acido_pantotenico_mg = 0.772, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.487), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 70.2, vitamina_k_mcg = 0, folato_mcg = 184 where nome = 'Quinoa Em Grão - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 47), ferro_mg = coalesce(ferro_mg, 4.57), magnesio_mg = 197, fosforo_mg = 457, potassio_mg = 563, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 3.1), cobre_mcg = 590, manganes_mg = 2.033, selenio_mcg = 8.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 2.44, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), tiamina_mg = coalesce(tiamina_mg, 0.36), riboflavina_mg = coalesce(riboflavina_mg, 0.318), niacina_mg = coalesce(niacina_mg, 1.52), acido_pantotenico_mg = 0.772, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.487), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 70.2, vitamina_k_mcg = 0, folato_mcg = 184 where nome = 'Quinoa Em Grão Vermelha - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 47), ferro_mg = coalesce(ferro_mg, 4.57), magnesio_mg = 197, fosforo_mg = 457, potassio_mg = 563, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 3.1), cobre_mcg = 590, manganes_mg = 2.033, selenio_mcg = 8.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 2.44, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), tiamina_mg = coalesce(tiamina_mg, 0.36), riboflavina_mg = coalesce(riboflavina_mg, 0.318), niacina_mg = coalesce(niacina_mg, 1.52), acido_pantotenico_mg = 0.772, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.487), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 70.2, vitamina_k_mcg = 0, folato_mcg = 184 where nome = 'Quinoa Em Grão Preta - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 47), ferro_mg = coalesce(ferro_mg, 4.57), magnesio_mg = 197, fosforo_mg = 457, potassio_mg = 563, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 3.1), cobre_mcg = 590, manganes_mg = 2.033, selenio_mcg = 8.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 2.44, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), tiamina_mg = coalesce(tiamina_mg, 0.36), riboflavina_mg = coalesce(riboflavina_mg, 0.318), niacina_mg = coalesce(niacina_mg, 1.52), acido_pantotenico_mg = 0.772, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.487), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 70.2, vitamina_k_mcg = 0, folato_mcg = 184 where nome = 'Quinoa Em Grão Mista - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 47), ferro_mg = coalesce(ferro_mg, 4.57), magnesio_mg = 197, fosforo_mg = 457, potassio_mg = 563, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 3.1), cobre_mcg = 590, manganes_mg = 2.033, selenio_mcg = 8.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 2.44, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), tiamina_mg = coalesce(tiamina_mg, 0.36), riboflavina_mg = coalesce(riboflavina_mg, 0.318), niacina_mg = coalesce(niacina_mg, 1.52), acido_pantotenico_mg = 0.772, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.487), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 70.2, vitamina_k_mcg = 0, folato_mcg = 184 where nome = 'Quinoa Flocos Integral Vitalin - 120g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 47), ferro_mg = coalesce(ferro_mg, 4.57), magnesio_mg = 197, fosforo_mg = 457, potassio_mg = 563, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 3.1), cobre_mcg = 590, manganes_mg = 2.033, selenio_mcg = 8.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 2.44, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), tiamina_mg = coalesce(tiamina_mg, 0.36), riboflavina_mg = coalesce(riboflavina_mg, 0.318), niacina_mg = coalesce(niacina_mg, 1.52), acido_pantotenico_mg = 0.772, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.487), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 70.2, vitamina_k_mcg = 0, folato_mcg = 184 where nome = 'Quinoa Grãos Orgânica Vitalin - 200g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 2.47), magnesio_mg = 221, fosforo_mg = 319, potassio_mg = 320, sodio_mg = coalesce(sodio_mg, 11), zinco_mg = coalesce(zinco_mg, 2.42), cobre_mcg = 624, manganes_mg = 1.618, selenio_mcg = 8.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.224), riboflavina_mg = coalesce(riboflavina_mg, 0.271), niacina_mg = coalesce(niacina_mg, 5.135), acido_pantotenico_mg = 1.233, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.353), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 54.2, folato_mcg = 42 where nome = 'Cache (Trigo Sarraceno) - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 78), ferro_mg = coalesce(ferro_mg, 5.25), magnesio_mg = 325, fosforo_mg = 660, potassio_mg = 645, sodio_mg = coalesce(sodio_mg, 9), zinco_mg = coalesce(zinco_mg, 5), cobre_mcg = 1800, manganes_mg = 1.95, selenio_mcg = 53, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 35.17, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.4), tiamina_mg = coalesce(tiamina_mg, 1.48), riboflavina_mg = coalesce(riboflavina_mg, 0.355), niacina_mg = coalesce(niacina_mg, 8.335), acido_pantotenico_mg = 1.13, vitamina_b6_mg = coalesce(vitamina_b6_mg, 1.345), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 55.1, vitamina_k_mcg = 0, folato_mcg = 227 where nome = 'Girassol Sem Casca - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 255), ferro_mg = coalesce(ferro_mg, 5.73), magnesio_mg = 392, fosforo_mg = 642, potassio_mg = 813, sodio_mg = coalesce(sodio_mg, 30), zinco_mg = coalesce(zinco_mg, 4.34), cobre_mcg = 1220, manganes_mg = 2.482, selenio_mcg = 25.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.31, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.6), tiamina_mg = coalesce(tiamina_mg, 1.644), riboflavina_mg = coalesce(riboflavina_mg, 0.161), niacina_mg = coalesce(niacina_mg, 3.08), acido_pantotenico_mg = 0.985, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.473), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 78.7, vitamina_k_mcg = 4.3, folato_mcg = 87 where nome = 'Linhaça Dourada Luxo - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 255), ferro_mg = coalesce(ferro_mg, 5.73), magnesio_mg = 392, fosforo_mg = 642, potassio_mg = 813, sodio_mg = coalesce(sodio_mg, 30), zinco_mg = coalesce(zinco_mg, 4.34), cobre_mcg = 1220, manganes_mg = 2.482, selenio_mcg = 25.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.31, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.6), tiamina_mg = coalesce(tiamina_mg, 1.644), riboflavina_mg = coalesce(riboflavina_mg, 0.161), niacina_mg = coalesce(niacina_mg, 3.08), acido_pantotenico_mg = 0.985, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.473), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 78.7, vitamina_k_mcg = 4.3, folato_mcg = 87 where nome = 'Linhaça - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 46), ferro_mg = coalesce(ferro_mg, 8.82), magnesio_mg = 592, fosforo_mg = 1233, potassio_mg = 809, sodio_mg = coalesce(sodio_mg, 7), zinco_mg = coalesce(zinco_mg, 7.81), cobre_mcg = 1343, manganes_mg = 4.543, selenio_mcg = 9.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 2.18, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.9), tiamina_mg = coalesce(tiamina_mg, 0.273), riboflavina_mg = coalesce(riboflavina_mg, 0.153), niacina_mg = coalesce(niacina_mg, 4.987), acido_pantotenico_mg = 0.75, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.143), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 63, vitamina_k_mcg = 7.3, folato_mcg = 58 where nome = 'Semente de Abóbora Sem Casca Crua - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 631), ferro_mg = coalesce(ferro_mg, 7.72), magnesio_mg = 335, fosforo_mg = 860, potassio_mg = 407, sodio_mg = coalesce(sodio_mg, 16), zinco_mg = coalesce(zinco_mg, 4.58), cobre_mcg = 924, manganes_mg = 2.723, selenio_mcg = 55.2, vitamina_e_mg = 0.5, vitamina_c_mg = coalesce(vitamina_c_mg, 1.6), tiamina_mg = coalesce(tiamina_mg, 0.62), riboflavina_mg = coalesce(riboflavina_mg, 0.17), niacina_mg = coalesce(niacina_mg, 8.83), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0) where nome = 'Semente de Chia - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 631), ferro_mg = coalesce(ferro_mg, 7.72), magnesio_mg = 335, fosforo_mg = 860, potassio_mg = 407, sodio_mg = coalesce(sodio_mg, 16), zinco_mg = coalesce(zinco_mg, 4.58), cobre_mcg = 924, manganes_mg = 2.723, selenio_mcg = 55.2, vitamina_e_mg = 0.5, vitamina_c_mg = coalesce(vitamina_c_mg, 1.6), tiamina_mg = coalesce(tiamina_mg, 0.62), riboflavina_mg = coalesce(riboflavina_mg, 0.17), niacina_mg = coalesce(niacina_mg, 8.83), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0) where nome = 'Semente de Chia Branca - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 9), ferro_mg = coalesce(ferro_mg, 0.8), magnesio_mg = 35, fosforo_mg = 108, potassio_mg = 86, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 1.16), cobre_mcg = 110, manganes_mg = 1.1, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.07), riboflavina_mg = coalesce(riboflavina_mg, 0.048), niacina_mg = coalesce(niacina_mg, 1.6), acido_pantotenico_mg = 1.342, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.145), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 9 where nome = 'Arroz Arbóreo Maninho - 1kg' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 9), ferro_mg = coalesce(ferro_mg, 0.8), magnesio_mg = 35, fosforo_mg = 108, potassio_mg = 86, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 1.16), cobre_mcg = 110, manganes_mg = 1.1, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.07), riboflavina_mg = coalesce(riboflavina_mg, 0.048), niacina_mg = coalesce(niacina_mg, 1.6), acido_pantotenico_mg = 1.342, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.145), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 9 where nome = 'Arroz Arbóreo Paganini - 500g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 28), ferro_mg = coalesce(ferro_mg, 0.8), magnesio_mg = 25, fosforo_mg = 115, potassio_mg = 115, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 1.09), cobre_mcg = 220, manganes_mg = 1.088, selenio_mcg = 15.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.07), riboflavina_mg = coalesce(riboflavina_mg, 0.049), niacina_mg = coalesce(niacina_mg, 1.6), acido_pantotenico_mg = 1.014, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.164), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 5.8, vitamina_k_mcg = 0.1, folato_mcg = 8 where nome = 'Arroz Branco Tipo 1 Agulinha - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 28), ferro_mg = coalesce(ferro_mg, 0.8), magnesio_mg = 25, fosforo_mg = 115, potassio_mg = 115, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 1.09), cobre_mcg = 220, manganes_mg = 1.088, selenio_mcg = 15.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.07), riboflavina_mg = coalesce(riboflavina_mg, 0.049), niacina_mg = coalesce(niacina_mg, 1.6), acido_pantotenico_mg = 1.014, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.164), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 5.8, vitamina_k_mcg = 0.1, folato_mcg = 8 where nome = 'Arroz Basmati Flora - 500g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 54), ferro_mg = coalesce(ferro_mg, 4.72), magnesio_mg = 177, fosforo_mg = 523, potassio_mg = 429, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 3.97), cobre_mcg = 626, manganes_mg = 4.916, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.763), riboflavina_mg = coalesce(riboflavina_mg, 0.139), niacina_mg = coalesce(niacina_mg, 0.961), acido_pantotenico_mg = 1.349, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.119), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 56 where nome = 'Aveia Sem Casca Ou Em Grão - 100g' and categoria = 'Grãos e Sementes' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 10), ferro_mg = coalesce(ferro_mg, 0.35), magnesio_mg = 35, fosforo_mg = 98, potassio_mg = 76, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 0.8), cobre_mcg = 130, manganes_mg = 1.2, selenio_mcg = 15.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.138), riboflavina_mg = coalesce(riboflavina_mg, 0.021), niacina_mg = coalesce(niacina_mg, 2.59), acido_pantotenico_mg = 0.819, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.436), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 5.8, vitamina_k_mcg = 0, folato_mcg = 4 where nome = 'Farinha de Arroz - 100g' and categoria = 'Farinhas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 1.98), magnesio_mg = 112, fosforo_mg = 337, potassio_mg = 289, sodio_mg = coalesce(sodio_mg, 8), zinco_mg = coalesce(zinco_mg, 2.45), cobre_mcg = 230, manganes_mg = 4.013, vitamina_e_mg = 0.6, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.443), riboflavina_mg = coalesce(riboflavina_mg, 0.08), niacina_mg = coalesce(niacina_mg, 6.34), acido_pantotenico_mg = 1.591, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.736), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 16 where nome = 'Farinha de Arroz Integral - 100g' and categoria = 'Farinhas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 52), ferro_mg = coalesce(ferro_mg, 4.25), magnesio_mg = 138, fosforo_mg = 410, potassio_mg = 362, sodio_mg = coalesce(sodio_mg, 6), zinco_mg = coalesce(zinco_mg, 3.64), cobre_mcg = 391, manganes_mg = 3.63, selenio_mcg = 28.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.42, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.46), riboflavina_mg = coalesce(riboflavina_mg, 0.155), niacina_mg = coalesce(niacina_mg, 1.125), acido_pantotenico_mg = 1.12, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.1), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 40.4, vitamina_k_mcg = 2, folato_mcg = 32 where nome = 'Farinha de Aveia - 100g' and categoria = 'Farinhas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 52), ferro_mg = coalesce(ferro_mg, 4.25), magnesio_mg = 138, fosforo_mg = 410, potassio_mg = 362, sodio_mg = coalesce(sodio_mg, 6), zinco_mg = coalesce(zinco_mg, 3.64), cobre_mcg = 391, manganes_mg = 3.63, selenio_mcg = 28.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.42, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.46), riboflavina_mg = coalesce(riboflavina_mg, 0.155), niacina_mg = coalesce(niacina_mg, 1.125), acido_pantotenico_mg = 1.12, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.1), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 40.4, vitamina_k_mcg = 2, folato_mcg = 32 where nome = 'Farinha de Aveia Sem Glúten Casas Pedro - 200g' and categoria = 'Farinhas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 631), ferro_mg = coalesce(ferro_mg, 7.72), magnesio_mg = 335, fosforo_mg = 860, potassio_mg = 407, sodio_mg = coalesce(sodio_mg, 16), zinco_mg = coalesce(zinco_mg, 4.58), cobre_mcg = 924, manganes_mg = 2.723, selenio_mcg = 55.2, vitamina_e_mg = 0.5, vitamina_c_mg = coalesce(vitamina_c_mg, 1.6), tiamina_mg = coalesce(tiamina_mg, 0.62), riboflavina_mg = coalesce(riboflavina_mg, 0.17), niacina_mg = coalesce(niacina_mg, 8.83), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0) where nome = 'Farinha de Chia - 100g' and categoria = 'Farinhas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 255), ferro_mg = coalesce(ferro_mg, 5.73), magnesio_mg = 392, fosforo_mg = 642, potassio_mg = 813, sodio_mg = coalesce(sodio_mg, 30), zinco_mg = coalesce(zinco_mg, 4.34), cobre_mcg = 1220, manganes_mg = 2.482, selenio_mcg = 25.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.31, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.6), tiamina_mg = coalesce(tiamina_mg, 1.644), riboflavina_mg = coalesce(riboflavina_mg, 0.161), niacina_mg = coalesce(niacina_mg, 3.08), acido_pantotenico_mg = 0.985, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.473), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 78.7, vitamina_k_mcg = 4.3, folato_mcg = 87 where nome = 'Farinha de Linhaça Dourada - 100g' and categoria = 'Farinhas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 13), ferro_mg = coalesce(ferro_mg, 3.16), magnesio_mg = 25, fosforo_mg = 89, potassio_mg = 112, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 0.68), cobre_mcg = 60, manganes_mg = 0.65, selenio_mcg = 36.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.06, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.387), riboflavina_mg = coalesce(riboflavina_mg, 0.291), niacina_mg = coalesce(niacina_mg, 3.892), acido_pantotenico_mg = 0.443, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.115), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 10.8, vitamina_k_mcg = 0.3, folato_mcg = 17 where nome = 'Farinha de Matzá Pão Ázimo - 500g' and categoria = 'Farinhas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 46), ferro_mg = coalesce(ferro_mg, 8.82), magnesio_mg = 592, fosforo_mg = 1233, potassio_mg = 809, sodio_mg = coalesce(sodio_mg, 7), zinco_mg = coalesce(zinco_mg, 7.81), cobre_mcg = 1343, manganes_mg = 4.543, selenio_mcg = 9.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 2.18, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.9), tiamina_mg = coalesce(tiamina_mg, 0.273), riboflavina_mg = coalesce(riboflavina_mg, 0.153), niacina_mg = coalesce(niacina_mg, 4.987), acido_pantotenico_mg = 0.75, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.143), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 63, vitamina_k_mcg = 7.3, folato_mcg = 58 where nome = 'Farinha de Semente de Abóbora - 100g' and categoria = 'Farinhas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 20), ferro_mg = coalesce(ferro_mg, 1.58), magnesio_mg = 1, fosforo_mg = 7, potassio_mg = 11, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.12), cobre_mcg = 20, manganes_mg = 0.11, selenio_mcg = 0.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.004), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0.135, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.008), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 1.2, vitamina_k_mcg = 0, folato_mcg = 4 where nome = 'Farinha de Tapioca do Pará - 100g' and categoria = 'Farinhas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 34), ferro_mg = coalesce(ferro_mg, 3.6), magnesio_mg = 137, fosforo_mg = 357, potassio_mg = 363, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 2.6), cobre_mcg = 410, manganes_mg = 4.067, selenio_mcg = 61.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.71, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.502), riboflavina_mg = coalesce(riboflavina_mg, 0.165), niacina_mg = coalesce(niacina_mg, 4.957), acido_pantotenico_mg = 0.603, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.407), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 31.2, vitamina_k_mcg = 1.9, folato_mcg = 44 where nome = 'Farinha de Trigo Integral - 100g' and categoria = 'Farinhas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 74.55), ferro_mg = coalesce(ferro_mg, 3.988), magnesio_mg = 33.56, fosforo_mg = 39.24, potassio_mg = 197.6, sodio_mg = coalesce(sodio_mg, 13.08), zinco_mg = coalesce(zinco_mg, 0.41), cobre_mcg = 76.63, manganes_mg = 0.395, molibdenio_mcg = 2.534, selenio_mcg = 0, tiamina_mg = coalesce(tiamina_mg, 0.051), riboflavina_mg = coalesce(riboflavina_mg, 0.068), niacina_mg = coalesce(niacina_mg, 0.6), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.05), biotina_mcg = 0.519 where nome = 'Farinha de Mesa - 100g' and categoria = 'Farinhas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 3.45), magnesio_mg = 127, fosforo_mg = 241, potassio_mg = 287, sodio_mg = coalesce(sodio_mg, 35), zinco_mg = coalesce(zinco_mg, 1.82), cobre_mcg = 193, manganes_mg = 0.498, selenio_mcg = 15.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 11), vitamina_e_mg = 0.42, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.385), riboflavina_mg = coalesce(riboflavina_mg, 0.201), niacina_mg = coalesce(niacina_mg, 3.632), acido_pantotenico_mg = 0.425, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.304), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 21.6, vitamina_k_mcg = 0.3, folato_mcg = 25 where nome = 'Farinha de Milho Amarelo - 100g' and categoria = 'Farinhas' and fonte = 'Fabricante' and id_avaliador is null;
