-- Migration 0083: micronutrientes Fabricante — lote 3 (Castanhas/Oleaginosas e Chocolates)
--
-- Terceira migration de micronutrientes pra fonte='Fabricante'. Cobre as
-- categorias "Castanhas e Oleaginosas" (84 itens, ver
-- scripts/tabela_alimentos_castanhas_chocolates_casaspedro.sql) e
-- "Chocolates" (parte do mesmo arquivo). 28 itens de castanhas + 18 de
-- chocolates aprovados = 46 no total.
--
-- Castanhas e Oleaginosas: majoritariamente ingredientes simples (moídas/
-- picadas/inteiras, cruas ou torradas), mapeadas direto pra
-- amendoim/nozes/castanha de caju/amêndoa/castanha do
-- pará/avelã/macadâmia/damasco seco cru no USDA. Ficaram de fora
-- (prefiro vazio a dado errado): os "Mix" (Vegetais Chips, Love, Berry,
-- Saúde, Nuts, Crocante Mostarda e Mel, Gergelim, Frutas Tropicais —
-- misturas de composição variável), as castanhas de caju CARAMELIZADAS
-- (7 variantes com sabor — produto de confeitaria, não a castanha crua/
-- torrada), as pastas de amendoim com sabor de marca (Dr Peanut, Mandubim,
-- Casas Pedro Tradicional/Crocante) e os amendoins temperados/salgados de
-- receita própria (Doce Com Canela, Japonês, Picante, Churrasco, Com
-- Salsa e Cebola, Assado Com Lascas de Alho, Confeito Amendoim, Figo
-- Caramelizado).
--
-- Chocolates: aqui deu pra usar as entradas do USDA por FAIXA DE % DE
-- CACAU (dark 45-59%/70-85%, chocolate ao leite, chocolate branco) como
-- aproximação razoável — mesmo sem ser a marca exata, é o mesmo tipo de
-- produto de confeitaria/cobertura. "Chocolate Marfim" da Nestlé é a
-- linha de chocolate branco da marca, por isso foi pro grupo branco.
-- Ficaram de fora: as versões DIET (formulação de açúcar diferente, sem
-- equivalente no USDA), "Chocolate Top Blend Harald" (mistura sem % de
-- cacau declarado), "Micanga de Chocolate" (a composição da própria ficha
-- — 0g de gordura — sugere que não é chocolate de verdade, e sim
-- confeito/granulado colorido), "Cobertura Chocolate Marvi" (ficha com 0g
-- de proteína/gordura/açúcar pra um produto de cobertura de chocolate —
-- dado da própria ficha parece inconsistente) e "Granola Chocolate e
-- Amendoim" (produto composto).
--
-- Como sempre: coalesce() preserva os valores já existentes nas 12
-- colunas legadas; as 15 colunas novas (migration 0054) recebem o valor
-- USDA diretamente. Restam ainda: Suplementos, Doces e Bebidas Vegetais.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 92), ferro_mg = coalesce(ferro_mg, 4.58), magnesio_mg = 168, fosforo_mg = 376, potassio_mg = 705, sodio_mg = coalesce(sodio_mg, 18), zinco_mg = coalesce(zinco_mg, 3.27), cobre_mcg = 1144, manganes_mg = 1.934, selenio_mcg = 7.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 8.33, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.64), riboflavina_mg = coalesce(riboflavina_mg, 0.135), niacina_mg = coalesce(niacina_mg, 12.066), acido_pantotenico_mg = 1.767, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.348), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 52.5, vitamina_k_mcg = 0, folato_mcg = 240 where nome = 'Amendoim Moído - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 92), ferro_mg = coalesce(ferro_mg, 4.58), magnesio_mg = 168, fosforo_mg = 376, potassio_mg = 705, sodio_mg = coalesce(sodio_mg, 18), zinco_mg = coalesce(zinco_mg, 3.27), cobre_mcg = 1144, manganes_mg = 1.934, selenio_mcg = 7.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 8.33, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.64), riboflavina_mg = coalesce(riboflavina_mg, 0.135), niacina_mg = coalesce(niacina_mg, 12.066), acido_pantotenico_mg = 1.767, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.348), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 52.5, vitamina_k_mcg = 0, folato_mcg = 240 where nome = 'Amendoim Picado - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 92), ferro_mg = coalesce(ferro_mg, 4.58), magnesio_mg = 168, fosforo_mg = 376, potassio_mg = 705, sodio_mg = coalesce(sodio_mg, 18), zinco_mg = coalesce(zinco_mg, 3.27), cobre_mcg = 1144, manganes_mg = 1.934, selenio_mcg = 7.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 8.33, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.64), riboflavina_mg = coalesce(riboflavina_mg, 0.135), niacina_mg = coalesce(niacina_mg, 12.066), acido_pantotenico_mg = 1.767, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.348), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 52.5, vitamina_k_mcg = 0, folato_mcg = 240 where nome = 'Amendoim Graúdo - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 92), ferro_mg = coalesce(ferro_mg, 4.58), magnesio_mg = 168, fosforo_mg = 376, potassio_mg = 705, sodio_mg = coalesce(sodio_mg, 18), zinco_mg = coalesce(zinco_mg, 3.27), cobre_mcg = 1144, manganes_mg = 1.934, selenio_mcg = 7.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 8.33, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.64), riboflavina_mg = coalesce(riboflavina_mg, 0.135), niacina_mg = coalesce(niacina_mg, 12.066), acido_pantotenico_mg = 1.767, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.348), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 52.5, vitamina_k_mcg = 0, folato_mcg = 240 where nome = 'Amendoim da Casa - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 58), ferro_mg = coalesce(ferro_mg, 1.58), magnesio_mg = 178, fosforo_mg = 363, potassio_mg = 634, sodio_mg = coalesce(sodio_mg, 6), zinco_mg = coalesce(zinco_mg, 2.77), cobre_mcg = 428, manganes_mg = 1.786, selenio_mcg = 9.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 4.93, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.152), riboflavina_mg = coalesce(riboflavina_mg, 0.197), niacina_mg = coalesce(niacina_mg, 14.355), acido_pantotenico_mg = 1.011, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.466), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 64.6, vitamina_k_mcg = 0, folato_mcg = 97 where nome = 'Amendoim Sem Pele Torrado Sem Sal - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 58), ferro_mg = coalesce(ferro_mg, 1.58), magnesio_mg = 178, fosforo_mg = 363, potassio_mg = 634, sodio_mg = coalesce(sodio_mg, 410), zinco_mg = coalesce(zinco_mg, 2.77), cobre_mcg = 428, manganes_mg = 1.786, selenio_mcg = 9.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 4.93, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.152), riboflavina_mg = coalesce(riboflavina_mg, 0.197), niacina_mg = coalesce(niacina_mg, 14.355), acido_pantotenico_mg = 1.011, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.466), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 64.6, vitamina_k_mcg = 0, folato_mcg = 97 where nome = 'Amendoim Sem Pele Torrado Salgado - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 49), ferro_mg = coalesce(ferro_mg, 1.74), magnesio_mg = 168, fosforo_mg = 335, potassio_mg = 558, sodio_mg = coalesce(sodio_mg, 17), zinco_mg = coalesce(zinco_mg, 2.51), cobre_mcg = 422, manganes_mg = 1.665, selenio_mcg = 4.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 9.1, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.15), riboflavina_mg = coalesce(riboflavina_mg, 0.192), niacina_mg = coalesce(niacina_mg, 13.112), acido_pantotenico_mg = 1.137, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.441), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 63, vitamina_k_mcg = 0.3, folato_mcg = 87 where nome = 'Pasta de Amendoim (Peanut Butter) - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 98), ferro_mg = coalesce(ferro_mg, 2.91), magnesio_mg = 158, fosforo_mg = 346, potassio_mg = 441, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 3.09), cobre_mcg = 1586, manganes_mg = 3.414, selenio_mcg = 4.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 0.7, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.3), tiamina_mg = coalesce(tiamina_mg, 0.341), riboflavina_mg = coalesce(riboflavina_mg, 0.15), niacina_mg = coalesce(niacina_mg, 1.125), acido_pantotenico_mg = 0.57, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.537), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 39.2, vitamina_k_mcg = 2.7, folato_mcg = 98 where nome = 'Nozes Moída - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 98), ferro_mg = coalesce(ferro_mg, 2.91), magnesio_mg = 158, fosforo_mg = 346, potassio_mg = 441, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 3.09), cobre_mcg = 1586, manganes_mg = 3.414, selenio_mcg = 4.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 0.7, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.3), tiamina_mg = coalesce(tiamina_mg, 0.341), riboflavina_mg = coalesce(riboflavina_mg, 0.15), niacina_mg = coalesce(niacina_mg, 1.125), acido_pantotenico_mg = 0.57, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.537), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 39.2, vitamina_k_mcg = 2.7, folato_mcg = 98 where nome = 'Nozes Sem Casca Picada - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 98), ferro_mg = coalesce(ferro_mg, 2.91), magnesio_mg = 158, fosforo_mg = 346, potassio_mg = 441, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 3.09), cobre_mcg = 1586, manganes_mg = 3.414, selenio_mcg = 4.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 0.7, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.3), tiamina_mg = coalesce(tiamina_mg, 0.341), riboflavina_mg = coalesce(riboflavina_mg, 0.15), niacina_mg = coalesce(niacina_mg, 1.125), acido_pantotenico_mg = 0.57, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.537), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 39.2, vitamina_k_mcg = 2.7, folato_mcg = 98 where nome = 'Nozes Sem Casca Partida Clara - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 98), ferro_mg = coalesce(ferro_mg, 2.91), magnesio_mg = 158, fosforo_mg = 346, potassio_mg = 441, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 3.09), cobre_mcg = 1586, manganes_mg = 3.414, selenio_mcg = 4.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 0.7, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.3), tiamina_mg = coalesce(tiamina_mg, 0.341), riboflavina_mg = coalesce(riboflavina_mg, 0.15), niacina_mg = coalesce(niacina_mg, 1.125), acido_pantotenico_mg = 0.57, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.537), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 39.2, vitamina_k_mcg = 2.7, folato_mcg = 98 where nome = 'Nozes Sem Casca Inteira Clara - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 70), ferro_mg = coalesce(ferro_mg, 2.53), magnesio_mg = 121, fosforo_mg = 277, potassio_mg = 410, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 4.53), cobre_mcg = 1200, manganes_mg = 4.5, selenio_mcg = 3.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 1.4, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.1), tiamina_mg = coalesce(tiamina_mg, 0.66), riboflavina_mg = coalesce(riboflavina_mg, 0.13), niacina_mg = coalesce(niacina_mg, 1.167), acido_pantotenico_mg = 0.863, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.21), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 40.5, vitamina_k_mcg = 3.5, folato_mcg = 22 where nome = 'Nozes Pecan Inteira - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 70), ferro_mg = coalesce(ferro_mg, 2.65), magnesio_mg = 118, fosforo_mg = 198, potassio_mg = 363, sodio_mg = coalesce(sodio_mg, 353), zinco_mg = coalesce(zinco_mg, 1.29), cobre_mcg = 570, manganes_mg = 3.036, selenio_mcg = 11.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.57, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.7), tiamina_mg = coalesce(tiamina_mg, 0.71), riboflavina_mg = coalesce(riboflavina_mg, 0.087), niacina_mg = coalesce(niacina_mg, 2.274), acido_pantotenico_mg = 0.603, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.359), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 44.6, vitamina_k_mcg = 0, folato_mcg = 10 where nome = 'Nozes Macadâmia Torrada Com Sal - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 70), ferro_mg = coalesce(ferro_mg, 2.65), magnesio_mg = 118, fosforo_mg = 198, potassio_mg = 363, sodio_mg = coalesce(sodio_mg, 4), zinco_mg = coalesce(zinco_mg, 1.29), cobre_mcg = 570, manganes_mg = 3.036, selenio_mcg = 11.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.57, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.7), tiamina_mg = coalesce(tiamina_mg, 0.71), riboflavina_mg = coalesce(riboflavina_mg, 0.087), niacina_mg = coalesce(niacina_mg, 2.274), acido_pantotenico_mg = 0.603, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.359), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 44.6, vitamina_k_mcg = 0, folato_mcg = 10 where nome = 'Nozes Macadâmia Torrada Sem Sal - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 37), ferro_mg = coalesce(ferro_mg, 6.68), magnesio_mg = 292, fosforo_mg = 593, potassio_mg = 660, sodio_mg = coalesce(sodio_mg, 12), zinco_mg = coalesce(zinco_mg, 5.78), cobre_mcg = 2195, manganes_mg = 1.655, selenio_mcg = 19.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.9, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.5), tiamina_mg = coalesce(tiamina_mg, 0.423), riboflavina_mg = coalesce(riboflavina_mg, 0.058), niacina_mg = coalesce(niacina_mg, 1.062), acido_pantotenico_mg = 0.864, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.417), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), vitamina_k_mcg = 34.1, folato_mcg = 25 where nome = 'Castanha de Caju F2 Moída - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 37), ferro_mg = coalesce(ferro_mg, 6.68), magnesio_mg = 292, fosforo_mg = 593, potassio_mg = 660, sodio_mg = coalesce(sodio_mg, 12), zinco_mg = coalesce(zinco_mg, 5.78), cobre_mcg = 2195, manganes_mg = 1.655, selenio_mcg = 19.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.9, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.5), tiamina_mg = coalesce(tiamina_mg, 0.423), riboflavina_mg = coalesce(riboflavina_mg, 0.058), niacina_mg = coalesce(niacina_mg, 1.062), acido_pantotenico_mg = 0.864, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.417), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), vitamina_k_mcg = 34.1, folato_mcg = 25 where nome = 'Castanha de Caju X2 Picada Crua Miúda - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 37), ferro_mg = coalesce(ferro_mg, 6.68), magnesio_mg = 292, fosforo_mg = 593, potassio_mg = 660, sodio_mg = coalesce(sodio_mg, 12), zinco_mg = coalesce(zinco_mg, 5.78), cobre_mcg = 2195, manganes_mg = 1.655, selenio_mcg = 19.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.9, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.5), tiamina_mg = coalesce(tiamina_mg, 0.423), riboflavina_mg = coalesce(riboflavina_mg, 0.058), niacina_mg = coalesce(niacina_mg, 1.062), acido_pantotenico_mg = 0.864, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.417), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), vitamina_k_mcg = 34.1, folato_mcg = 25 where nome = 'Castanha de Caju Picada Crua Graúda - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 45), ferro_mg = coalesce(ferro_mg, 6), magnesio_mg = 260, fosforo_mg = 490, potassio_mg = 565, sodio_mg = coalesce(sodio_mg, 640), zinco_mg = coalesce(zinco_mg, 5.6), cobre_mcg = 2220, manganes_mg = 0.826, selenio_mcg = 11.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.92, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.2), riboflavina_mg = coalesce(riboflavina_mg, 0.2), niacina_mg = coalesce(niacina_mg, 1.4), acido_pantotenico_mg = 1.217, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.256), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 61, vitamina_k_mcg = 34.7, folato_mcg = 69 where nome = 'Castanha de Caju Com Sal (W4) - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 45), ferro_mg = coalesce(ferro_mg, 6), magnesio_mg = 260, fosforo_mg = 490, potassio_mg = 565, sodio_mg = coalesce(sodio_mg, 16), zinco_mg = coalesce(zinco_mg, 5.6), cobre_mcg = 2220, manganes_mg = 0.826, selenio_mcg = 11.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.92, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.2), riboflavina_mg = coalesce(riboflavina_mg, 0.2), niacina_mg = coalesce(niacina_mg, 1.4), acido_pantotenico_mg = 1.217, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.256), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 61, vitamina_k_mcg = 34.7, folato_mcg = 69 where nome = 'Castanha de Caju X2T Picada Torrada Miúda - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 45), ferro_mg = coalesce(ferro_mg, 6), magnesio_mg = 260, fosforo_mg = 490, potassio_mg = 565, sodio_mg = coalesce(sodio_mg, 16), zinco_mg = coalesce(zinco_mg, 5.6), cobre_mcg = 2220, manganes_mg = 0.826, selenio_mcg = 11.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.92, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.2), riboflavina_mg = coalesce(riboflavina_mg, 0.2), niacina_mg = coalesce(niacina_mg, 1.4), acido_pantotenico_mg = 1.217, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.256), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 61, vitamina_k_mcg = 34.7, folato_mcg = 69 where nome = 'Castanha de Caju G2T Picada Torrada Graúda - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 269), ferro_mg = coalesce(ferro_mg, 3.71), magnesio_mg = 270, fosforo_mg = 481, potassio_mg = 733, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 3.12), cobre_mcg = 1031, manganes_mg = 2.179, selenio_mcg = 4.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 25.63, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.205), riboflavina_mg = coalesce(riboflavina_mg, 1.138), niacina_mg = coalesce(niacina_mg, 3.618), acido_pantotenico_mg = 0.471, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.137), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 52.1, vitamina_k_mcg = 0, folato_mcg = 44 where nome = 'Amêndoa Moída - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 269), ferro_mg = coalesce(ferro_mg, 3.71), magnesio_mg = 270, fosforo_mg = 481, potassio_mg = 733, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 3.12), cobre_mcg = 1031, manganes_mg = 2.179, selenio_mcg = 4.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 25.63, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.205), riboflavina_mg = coalesce(riboflavina_mg, 1.138), niacina_mg = coalesce(niacina_mg, 3.618), acido_pantotenico_mg = 0.471, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.137), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 52.1, vitamina_k_mcg = 0, folato_mcg = 44 where nome = 'Amêndoa Sem Pele Moída Luxo - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 160), ferro_mg = coalesce(ferro_mg, 2.43), magnesio_mg = 376, fosforo_mg = 725, potassio_mg = 659, sodio_mg = coalesce(sodio_mg, 3), zinco_mg = coalesce(zinco_mg, 4.06), cobre_mcg = 1743, manganes_mg = 1.223, selenio_mcg = 1917, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 5.65, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.7), tiamina_mg = coalesce(tiamina_mg, 0.617), riboflavina_mg = coalesce(riboflavina_mg, 0.035), niacina_mg = coalesce(niacina_mg, 0.295), acido_pantotenico_mg = 0.184, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.101), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 28.8, vitamina_k_mcg = 0, folato_mcg = 22 where nome = 'Castanha do Pará Moída - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 114), ferro_mg = coalesce(ferro_mg, 4.7), magnesio_mg = 163, fosforo_mg = 290, potassio_mg = 680, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 2.45), cobre_mcg = 1725, manganes_mg = 6.175, selenio_mcg = 2.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 15.03, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 6.3), tiamina_mg = coalesce(tiamina_mg, 0.643), riboflavina_mg = coalesce(riboflavina_mg, 0.113), niacina_mg = coalesce(niacina_mg, 1.8), acido_pantotenico_mg = 0.918, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.563), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 45.6, vitamina_k_mcg = 14.2, folato_mcg = 113 where nome = 'Avelã Moída - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 57), ferro_mg = coalesce(ferro_mg, 4.31), magnesio_mg = 79, fosforo_mg = 252, potassio_mg = 718, sodio_mg = coalesce(sodio_mg, 24), zinco_mg = coalesce(zinco_mg, 2.76), cobre_mcg = 656, manganes_mg = 4.15, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.82, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4), tiamina_mg = coalesce(tiamina_mg, 0.477), riboflavina_mg = coalesce(riboflavina_mg, 0.212), niacina_mg = coalesce(niacina_mg, 1.541), acido_pantotenico_mg = 1.588, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.535), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 99.3, vitamina_k_mcg = 9, folato_mcg = 557 where nome = 'Grão de Bico Moído - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 2.47), magnesio_mg = 221, fosforo_mg = 319, potassio_mg = 320, sodio_mg = coalesce(sodio_mg, 11), zinco_mg = coalesce(zinco_mg, 2.42), cobre_mcg = 624, manganes_mg = 1.618, selenio_mcg = 8.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.224), riboflavina_mg = coalesce(riboflavina_mg, 0.271), niacina_mg = coalesce(niacina_mg, 5.135), acido_pantotenico_mg = 1.233, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.353), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 54.2, folato_mcg = 42 where nome = 'Cache Moído (Trigo Sarraceno) - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 255), ferro_mg = coalesce(ferro_mg, 5.73), magnesio_mg = 392, fosforo_mg = 642, potassio_mg = 813, sodio_mg = coalesce(sodio_mg, 30), zinco_mg = coalesce(zinco_mg, 4.34), cobre_mcg = 1220, manganes_mg = 2.482, selenio_mcg = 25.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.31, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.6), tiamina_mg = coalesce(tiamina_mg, 1.644), riboflavina_mg = coalesce(riboflavina_mg, 0.161), niacina_mg = coalesce(niacina_mg, 3.08), acido_pantotenico_mg = 0.985, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.473), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 78.7, vitamina_k_mcg = 4.3, folato_mcg = 87 where nome = 'Linhaça Moída - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 55), ferro_mg = coalesce(ferro_mg, 2.66), magnesio_mg = 32, fosforo_mg = 71, potassio_mg = 1162, sodio_mg = coalesce(sodio_mg, 10), zinco_mg = coalesce(zinco_mg, 0.39), cobre_mcg = 343, manganes_mg = 0.235, selenio_mcg = 2.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 180), vitamina_e_mg = 4.33, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1), tiamina_mg = coalesce(tiamina_mg, 0.015), riboflavina_mg = coalesce(riboflavina_mg, 0.074), niacina_mg = coalesce(niacina_mg, 2.589), acido_pantotenico_mg = 0.516, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.143), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 13.9, vitamina_k_mcg = 3.1, folato_mcg = 10 where nome = 'Damasco Doce Picado - 100g' and categoria = 'Castanhas e Oleaginosas' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 56), ferro_mg = coalesce(ferro_mg, 8.02), magnesio_mg = 146, fosforo_mg = 206, potassio_mg = 559, sodio_mg = coalesce(sodio_mg, 24), zinco_mg = coalesce(zinco_mg, 2.01), cobre_mcg = 1028, manganes_mg = 1.419, selenio_mcg = 3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.54, tiamina_mg = coalesce(tiamina_mg, 0.025), riboflavina_mg = coalesce(riboflavina_mg, 0.05), niacina_mg = coalesce(niacina_mg, 0.725), acido_pantotenico_mg = 0.297, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.042), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.23), vitamina_k_mcg = 8.1 where nome = 'Chocolate Meio Amargo Nestlé - 1kg' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 56), ferro_mg = coalesce(ferro_mg, 8.02), magnesio_mg = 146, fosforo_mg = 206, potassio_mg = 559, sodio_mg = coalesce(sodio_mg, 24), zinco_mg = coalesce(zinco_mg, 2.01), cobre_mcg = 1028, manganes_mg = 1.419, selenio_mcg = 3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.54, tiamina_mg = coalesce(tiamina_mg, 0.025), riboflavina_mg = coalesce(riboflavina_mg, 0.05), niacina_mg = coalesce(niacina_mg, 0.725), acido_pantotenico_mg = 0.297, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.042), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.23), vitamina_k_mcg = 8.1 where nome = 'Chocolate Meio Amargo Sicao - 1,01kg' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 56), ferro_mg = coalesce(ferro_mg, 8.02), magnesio_mg = 146, fosforo_mg = 206, potassio_mg = 559, sodio_mg = coalesce(sodio_mg, 24), zinco_mg = coalesce(zinco_mg, 2.01), cobre_mcg = 1028, manganes_mg = 1.419, selenio_mcg = 3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.54, tiamina_mg = coalesce(tiamina_mg, 0.025), riboflavina_mg = coalesce(riboflavina_mg, 0.05), niacina_mg = coalesce(niacina_mg, 0.725), acido_pantotenico_mg = 0.297, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.042), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.23), vitamina_k_mcg = 8.1 where nome = 'Chocolate Meio Amargo Fracionado Sicao - 1,01kg' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 56), ferro_mg = coalesce(ferro_mg, 8.02), magnesio_mg = 146, fosforo_mg = 206, potassio_mg = 559, sodio_mg = coalesce(sodio_mg, 24), zinco_mg = coalesce(zinco_mg, 2.01), cobre_mcg = 1028, manganes_mg = 1.419, selenio_mcg = 3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.54, tiamina_mg = coalesce(tiamina_mg, 0.025), riboflavina_mg = coalesce(riboflavina_mg, 0.05), niacina_mg = coalesce(niacina_mg, 0.725), acido_pantotenico_mg = 0.297, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.042), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.23), vitamina_k_mcg = 8.1 where nome = 'Chocolate Meio Amargo Melken - 1,010kg' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 56), ferro_mg = coalesce(ferro_mg, 8.02), magnesio_mg = 146, fosforo_mg = 206, potassio_mg = 559, sodio_mg = coalesce(sodio_mg, 24), zinco_mg = coalesce(zinco_mg, 2.01), cobre_mcg = 1028, manganes_mg = 1.419, selenio_mcg = 3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.54, tiamina_mg = coalesce(tiamina_mg, 0.025), riboflavina_mg = coalesce(riboflavina_mg, 0.05), niacina_mg = coalesce(niacina_mg, 0.725), acido_pantotenico_mg = 0.297, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.042), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.23), vitamina_k_mcg = 8.1 where nome = 'Gotas de Chocolate Meio Amargo Sicao - 100g' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 73), ferro_mg = coalesce(ferro_mg, 11.9), magnesio_mg = 228, fosforo_mg = 308, potassio_mg = 715, sodio_mg = coalesce(sodio_mg, 20), zinco_mg = coalesce(zinco_mg, 3.31), cobre_mcg = 1766, manganes_mg = 1.948, selenio_mcg = 6.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.59, tiamina_mg = coalesce(tiamina_mg, 0.034), riboflavina_mg = coalesce(riboflavina_mg, 0.078), niacina_mg = coalesce(niacina_mg, 1.054), acido_pantotenico_mg = 0.418, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.038), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.28), vitamina_k_mcg = 7.3 where nome = 'Chocolate Black 72% Zermatt' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 73), ferro_mg = coalesce(ferro_mg, 11.9), magnesio_mg = 228, fosforo_mg = 308, potassio_mg = 715, sodio_mg = coalesce(sodio_mg, 20), zinco_mg = coalesce(zinco_mg, 3.31), cobre_mcg = 1766, manganes_mg = 1.948, selenio_mcg = 6.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.59, tiamina_mg = coalesce(tiamina_mg, 0.034), riboflavina_mg = coalesce(riboflavina_mg, 0.078), niacina_mg = coalesce(niacina_mg, 1.054), acido_pantotenico_mg = 0.418, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.038), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.28), vitamina_k_mcg = 7.3 where nome = 'Gotas de Chocolate Belga Amargo 70,5% Cacau Callebaut - 100g' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 189), ferro_mg = coalesce(ferro_mg, 2.35), magnesio_mg = 63, fosforo_mg = 208, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 79), zinco_mg = coalesce(zinco_mg, 2.3), cobre_mcg = 491, manganes_mg = 0.471, selenio_mcg = 4.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 59), vitamina_e_mg = 0.51, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.112), riboflavina_mg = coalesce(riboflavina_mg, 0.298), niacina_mg = coalesce(niacina_mg, 0.386), acido_pantotenico_mg = 0.472, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.75), colina_mg = 46.1, vitamina_k_mcg = 5.7, folato_mcg = 11 where nome = 'Chocolate Ao Leite Nestlé - 1kg' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 189), ferro_mg = coalesce(ferro_mg, 2.35), magnesio_mg = 63, fosforo_mg = 208, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 79), zinco_mg = coalesce(zinco_mg, 2.3), cobre_mcg = 491, manganes_mg = 0.471, selenio_mcg = 4.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 59), vitamina_e_mg = 0.51, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.112), riboflavina_mg = coalesce(riboflavina_mg, 0.298), niacina_mg = coalesce(niacina_mg, 0.386), acido_pantotenico_mg = 0.472, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.75), colina_mg = 46.1, vitamina_k_mcg = 5.7, folato_mcg = 11 where nome = 'Chocolate Ao Leite Sicao - 1,01kg' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 189), ferro_mg = coalesce(ferro_mg, 2.35), magnesio_mg = 63, fosforo_mg = 208, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 79), zinco_mg = coalesce(zinco_mg, 2.3), cobre_mcg = 491, manganes_mg = 0.471, selenio_mcg = 4.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 59), vitamina_e_mg = 0.51, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.112), riboflavina_mg = coalesce(riboflavina_mg, 0.298), niacina_mg = coalesce(niacina_mg, 0.386), acido_pantotenico_mg = 0.472, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.75), colina_mg = 46.1, vitamina_k_mcg = 5.7, folato_mcg = 11 where nome = 'Chocolate Top Ao Leite Harald - 1,010kg' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 189), ferro_mg = coalesce(ferro_mg, 2.35), magnesio_mg = 63, fosforo_mg = 208, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 79), zinco_mg = coalesce(zinco_mg, 2.3), cobre_mcg = 491, manganes_mg = 0.471, selenio_mcg = 4.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 59), vitamina_e_mg = 0.51, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.112), riboflavina_mg = coalesce(riboflavina_mg, 0.298), niacina_mg = coalesce(niacina_mg, 0.386), acido_pantotenico_mg = 0.472, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.75), colina_mg = 46.1, vitamina_k_mcg = 5.7, folato_mcg = 11 where nome = 'Chocolate Ao Leite Pedaço - 100g' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 189), ferro_mg = coalesce(ferro_mg, 2.35), magnesio_mg = 63, fosforo_mg = 208, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 79), zinco_mg = coalesce(zinco_mg, 2.3), cobre_mcg = 491, manganes_mg = 0.471, selenio_mcg = 4.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 59), vitamina_e_mg = 0.51, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.112), riboflavina_mg = coalesce(riboflavina_mg, 0.298), niacina_mg = coalesce(niacina_mg, 0.386), acido_pantotenico_mg = 0.472, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.75), colina_mg = 46.1, vitamina_k_mcg = 5.7, folato_mcg = 11 where nome = 'Gotas de Chocolate Belga Ao Leite 33,6% Cacau Callebaut - 100g' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 189), ferro_mg = coalesce(ferro_mg, 2.35), magnesio_mg = 63, fosforo_mg = 208, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 79), zinco_mg = coalesce(zinco_mg, 2.3), cobre_mcg = 491, manganes_mg = 0.471, selenio_mcg = 4.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 59), vitamina_e_mg = 0.51, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.112), riboflavina_mg = coalesce(riboflavina_mg, 0.298), niacina_mg = coalesce(niacina_mg, 0.386), acido_pantotenico_mg = 0.472, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.75), colina_mg = 46.1, vitamina_k_mcg = 5.7, folato_mcg = 11 where nome = 'Gotinha de Chocolate Mavalerio - 100g' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 189), ferro_mg = coalesce(ferro_mg, 2.35), magnesio_mg = 63, fosforo_mg = 208, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 79), zinco_mg = coalesce(zinco_mg, 2.3), cobre_mcg = 491, manganes_mg = 0.471, selenio_mcg = 4.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 59), vitamina_e_mg = 0.51, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.112), riboflavina_mg = coalesce(riboflavina_mg, 0.298), niacina_mg = coalesce(niacina_mg, 0.386), acido_pantotenico_mg = 0.472, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.75), colina_mg = 46.1, vitamina_k_mcg = 5.7, folato_mcg = 11 where nome = 'Flocos de Chocolate Mil Cores - 100g' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 199), ferro_mg = coalesce(ferro_mg, 0.24), magnesio_mg = 12, fosforo_mg = 176, potassio_mg = 286, sodio_mg = coalesce(sodio_mg, 90), zinco_mg = coalesce(zinco_mg, 0.74), cobre_mcg = 60, manganes_mg = 0.008, selenio_mcg = 4.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 9), vitamina_e_mg = 0.96, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.5), tiamina_mg = coalesce(tiamina_mg, 0.063), riboflavina_mg = coalesce(riboflavina_mg, 0.282), niacina_mg = coalesce(niacina_mg, 0.745), acido_pantotenico_mg = 0.608, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.056), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.56), colina_mg = 29.5, vitamina_k_mcg = 9.1, folato_mcg = 7 where nome = 'Chocolate Marfim Nestlé - 1kg' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 199), ferro_mg = coalesce(ferro_mg, 0.24), magnesio_mg = 12, fosforo_mg = 176, potassio_mg = 286, sodio_mg = coalesce(sodio_mg, 90), zinco_mg = coalesce(zinco_mg, 0.74), cobre_mcg = 60, manganes_mg = 0.008, selenio_mcg = 4.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 9), vitamina_e_mg = 0.96, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.5), tiamina_mg = coalesce(tiamina_mg, 0.063), riboflavina_mg = coalesce(riboflavina_mg, 0.282), niacina_mg = coalesce(niacina_mg, 0.745), acido_pantotenico_mg = 0.608, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.056), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.56), colina_mg = 29.5, vitamina_k_mcg = 9.1, folato_mcg = 7 where nome = 'Chocolate Top Branco Harald - 1,010kg' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 199), ferro_mg = coalesce(ferro_mg, 0.24), magnesio_mg = 12, fosforo_mg = 176, potassio_mg = 286, sodio_mg = coalesce(sodio_mg, 90), zinco_mg = coalesce(zinco_mg, 0.74), cobre_mcg = 60, manganes_mg = 0.008, selenio_mcg = 4.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 9), vitamina_e_mg = 0.96, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.5), tiamina_mg = coalesce(tiamina_mg, 0.063), riboflavina_mg = coalesce(riboflavina_mg, 0.282), niacina_mg = coalesce(niacina_mg, 0.745), acido_pantotenico_mg = 0.608, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.056), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.56), colina_mg = 29.5, vitamina_k_mcg = 9.1, folato_mcg = 7 where nome = 'Chocolate Branco Pedaços - 100g' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 60), ferro_mg = coalesce(ferro_mg, 2.28), magnesio_mg = 70, fosforo_mg = 175, potassio_mg = 618, sodio_mg = coalesce(sodio_mg, 190), zinco_mg = coalesce(zinco_mg, 0.8), cobre_mcg = 200, selenio_mcg = 6.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 33), vitamina_e_mg = 0.17, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.5), tiamina_mg = coalesce(tiamina_mg, 0.173), riboflavina_mg = coalesce(riboflavina_mg, 0.2), niacina_mg = coalesce(niacina_mg, 2.003), acido_pantotenico_mg = 0.316, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.156), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.42), colina_mg = 27.2, vitamina_k_mcg = 2.5, folato_mcg = 50 where nome = 'Chocolate Em Pó 32% Cacau Nestlé - 100g' and categoria = 'Chocolates' and fonte = 'Fabricante' and id_avaliador is null;
