-- Migration 0084: micronutrientes Fabricante — lote 4 (Bebidas Vegetais, Doces e itens avulsos)
--
-- Fecha a curadoria de micronutrientes da tabela Fabricante (não no
-- sentido de 100% completa — essa fonte tem uma fração grande de
-- produtos formulados de marca sem equivalente seguro no USDA, igual
-- explicado nos headers das migrations 0081-0083 — mas sim no sentido de
-- ter passado por todas as categorias e extraído tudo que dava pra
-- aproveitar com segurança). 15 itens aprovados neste lote:
--
-- Bebidas Vegetais (2/12): só a água de coco integral (produto natural,
-- sem leite/creme adicionado) — os leites de castanha/amêndoa/aveia
-- ficaram de fora porque costumam ser fortificados com cálcio/vitamina D/
-- B12 e a fortificação varia de marca pra marca, sem como inferir do
-- "leite de amêndoa" genérico do USDA.
--
-- Doces (4/62): coco ralado/em flocos sem açúcar (3 cortes do mesmo
-- ingrediente) e uma barra de chocolate 72% cacau sem sabor adicionado —
-- o resto da categoria é confeitaria de marca (Bis, Trento, alfajores,
-- bombons, biscoitos amanteigados, balas), mesmo padrão de baixo
-- aproveitamento já visto em "Alimentos preparados" da TACO.
--
-- Itens avulsos de migrations anteriores (0036/0037/0038) que também são
-- fonte='Fabricante' mas nunca tinham passado pelo pipeline de
-- micronutrientes:
--   - Filé Mignon Suíno (Cru/Cozido/Assado): o item que o usuário
--     perguntou no início desta sessão de curadoria ("colocou o filé
--     mignon suíno?") — agora com micronutrientes do corte de lombo
--     suíno mais próximo (tenderloin) do USDA.
--   - Queijo Cottage (Tirolez): match direto e correto.
--   - Albumina em Pó (Saltos, Fama, Naturovos, Growth Natural/Banana):
--     diferente de Whey Protein (formulação complexa de marca), albumina
--     é clara de ovo desidratada pura — um ingrediente de um único
--     componente, casável com segurança contra "Egg, white, dried" do
--     USDA. O restante de Suplementos (Whey de toda marca, creatina,
--     pré-treino, maltodextrina) ficou de fora: são formulações
--     proprietárias (ou, no caso da creatina pura, uma substância
--     sintetizada sem perfil de vitaminas/minerais — nada a preencher).
--
-- Como sempre: coalesce() preserva os valores já existentes nas 12
-- colunas legadas; as 15 colunas novas (migration 0054) recebem o valor
-- USDA diretamente.
--
-- RESUMO GERAL da fonte Fabricante (migrations 0081-0084): de ~380 itens
-- totais, 82 receberam micronutrientes (19 temperos + 53 grãos/farinhas +
-- 46 castanhas/chocolates + 15 deste lote). O restante — a maior parte —
-- são formulações de marca (temperos compostos, whey/suplementos,
-- doces/biscoitos, leites vegetais, chocolates sem % declarada) sem
-- equivalente seguro no USDA; qualquer correção futura exigiria dado real
-- do rótulo de cada produto, não uma aproximação genérica.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7), ferro_mg = coalesce(ferro_mg, 0.03), magnesio_mg = 6, fosforo_mg = 5, potassio_mg = 165, sodio_mg = coalesce(sodio_mg, 26), zinco_mg = coalesce(zinco_mg, 0.02), cobre_mcg = 8, manganes_mg = 0.221, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 9.9), tiamina_mg = coalesce(tiamina_mg, 0.03), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Água de Coco Integral Casas Pedro - 1l' and categoria = 'Bebidas Vegetais' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7), ferro_mg = coalesce(ferro_mg, 0.03), magnesio_mg = 6, fosforo_mg = 5, potassio_mg = 165, sodio_mg = coalesce(sodio_mg, 26), zinco_mg = coalesce(zinco_mg, 0.02), cobre_mcg = 8, manganes_mg = 0.221, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 9.9), tiamina_mg = coalesce(tiamina_mg, 0.03), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Água de Coco Integral Casas Pedro - 300ml' and categoria = 'Bebidas Vegetais' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 26), ferro_mg = coalesce(ferro_mg, 3.32), magnesio_mg = 90, fosforo_mg = 206, potassio_mg = 543, sodio_mg = coalesce(sodio_mg, 37), zinco_mg = coalesce(zinco_mg, 2.01), cobre_mcg = 796, manganes_mg = 2.745, selenio_mcg = 18.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.44, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.5), tiamina_mg = coalesce(tiamina_mg, 0.06), riboflavina_mg = coalesce(riboflavina_mg, 0.1), niacina_mg = coalesce(niacina_mg, 0.603), acido_pantotenico_mg = 0.8, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.3), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 22.1, vitamina_k_mcg = 0.3, folato_mcg = 9 where nome = 'Coco Ralado Fino Sem Açúcar - 100g' and categoria = 'Doces' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 26), ferro_mg = coalesce(ferro_mg, 3.32), magnesio_mg = 90, fosforo_mg = 206, potassio_mg = 543, sodio_mg = coalesce(sodio_mg, 37), zinco_mg = coalesce(zinco_mg, 2.01), cobre_mcg = 796, manganes_mg = 2.745, selenio_mcg = 18.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.44, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.5), tiamina_mg = coalesce(tiamina_mg, 0.06), riboflavina_mg = coalesce(riboflavina_mg, 0.1), niacina_mg = coalesce(niacina_mg, 0.603), acido_pantotenico_mg = 0.8, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.3), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 22.1, vitamina_k_mcg = 0.3, folato_mcg = 9 where nome = 'Coco Ralado Grosso Sem Açúcar - 100g' and categoria = 'Doces' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 26), ferro_mg = coalesce(ferro_mg, 3.32), magnesio_mg = 90, fosforo_mg = 206, potassio_mg = 543, sodio_mg = coalesce(sodio_mg, 37), zinco_mg = coalesce(zinco_mg, 2.01), cobre_mcg = 796, manganes_mg = 2.745, selenio_mcg = 18.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.44, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.5), tiamina_mg = coalesce(tiamina_mg, 0.06), riboflavina_mg = coalesce(riboflavina_mg, 0.1), niacina_mg = coalesce(niacina_mg, 0.603), acido_pantotenico_mg = 0.8, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.3), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 22.1, vitamina_k_mcg = 0.3, folato_mcg = 9 where nome = 'Coco Em Flocos Sem Açúcar - 100g' and categoria = 'Doces' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 73), ferro_mg = coalesce(ferro_mg, 11.9), magnesio_mg = 228, fosforo_mg = 308, potassio_mg = 715, sodio_mg = coalesce(sodio_mg, 20), zinco_mg = coalesce(zinco_mg, 3.31), cobre_mcg = 1766, manganes_mg = 1.948, selenio_mcg = 6.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.59, tiamina_mg = coalesce(tiamina_mg, 0.034), riboflavina_mg = coalesce(riboflavina_mg, 0.078), niacina_mg = coalesce(niacina_mg, 1.054), acido_pantotenico_mg = 0.418, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.038), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.28), vitamina_k_mcg = 7.3 where nome = 'Barra de Chocolate 72% Casas Pedro - 40g' and categoria = 'Doces' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 5), ferro_mg = coalesce(ferro_mg, 0.98), magnesio_mg = 27, fosforo_mg = 247, potassio_mg = 399, sodio_mg = coalesce(sodio_mg, 53), zinco_mg = coalesce(zinco_mg, 1.89), cobre_mcg = 90, manganes_mg = 0.015, selenio_mcg = 30.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.22, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.998), riboflavina_mg = coalesce(riboflavina_mg, 0.342), niacina_mg = coalesce(niacina_mg, 6.684), acido_pantotenico_mg = 0.846, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.777), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.51), colina_mg = 80.8, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Filé Mignon Suíno, Cru(a)' and categoria = 'Carnes e derivados' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 5), ferro_mg = coalesce(ferro_mg, 1.43), magnesio_mg = 36, fosforo_mg = 295, potassio_mg = 451, sodio_mg = coalesce(sodio_mg, 65), zinco_mg = coalesce(zinco_mg, 2.95), cobre_mcg = 68, manganes_mg = 0.012, selenio_mcg = 51.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_c_mg = coalesce(vitamina_c_mg, 1), tiamina_mg = coalesce(tiamina_mg, 0.988), riboflavina_mg = coalesce(riboflavina_mg, 0.387), niacina_mg = coalesce(niacina_mg, 5.135), acido_pantotenico_mg = 0.917, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.528), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1), folato_mcg = 6 where nome = 'Filé Mignon Suíno, Cozido(a)' and categoria = 'Carnes e derivados' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 1.15), magnesio_mg = 29, fosforo_mg = 267, potassio_mg = 421, sodio_mg = coalesce(sodio_mg, 57), zinco_mg = coalesce(zinco_mg, 2.42), cobre_mcg = 111, manganes_mg = 0.013, selenio_mcg = 38.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.08, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.95), riboflavina_mg = coalesce(riboflavina_mg, 0.387), niacina_mg = coalesce(niacina_mg, 7.432), acido_pantotenico_mg = 1.012, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.739), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.57), colina_mg = 88.9, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Filé Mignon Suíno, Assado(a)' and categoria = 'Carnes e derivados' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 111), ferro_mg = coalesce(ferro_mg, 0.13), magnesio_mg = 9, fosforo_mg = 150, potassio_mg = 125, sodio_mg = coalesce(sodio_mg, 308), zinco_mg = coalesce(zinco_mg, 0.51), cobre_mcg = 33, manganes_mg = 0.015, selenio_mcg = 11.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 68), vitamina_e_mg = 0.08, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.02), riboflavina_mg = coalesce(riboflavina_mg, 0.251), niacina_mg = coalesce(niacina_mg, 0.103), acido_pantotenico_mg = 0.524, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.057), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.47), colina_mg = 16.3, vitamina_k_mcg = 0, folato_mcg = 8 where nome = 'Queijo Cottage, Tirolez' and categoria = 'Leite e derivados' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 62), ferro_mg = coalesce(ferro_mg, 0.15), magnesio_mg = 88, fosforo_mg = 111, potassio_mg = 1125, sodio_mg = coalesce(sodio_mg, 1280), zinco_mg = coalesce(zinco_mg, 0.1), cobre_mcg = 114, manganes_mg = 0.007, selenio_mcg = 125.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.005), riboflavina_mg = coalesce(riboflavina_mg, 2.53), niacina_mg = coalesce(niacina_mg, 0.865), acido_pantotenico_mg = 0.775, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.18), colina_mg = 8.4, vitamina_k_mcg = 0, folato_mcg = 18 where nome = 'Albumina em Pó, Saltos' and categoria = 'Suplementos' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 62), ferro_mg = coalesce(ferro_mg, 0.15), magnesio_mg = 88, fosforo_mg = 111, potassio_mg = 1125, sodio_mg = coalesce(sodio_mg, 1280), zinco_mg = coalesce(zinco_mg, 0.1), cobre_mcg = 114, manganes_mg = 0.007, selenio_mcg = 125.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.005), riboflavina_mg = coalesce(riboflavina_mg, 2.53), niacina_mg = coalesce(niacina_mg, 0.865), acido_pantotenico_mg = 0.775, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.18), colina_mg = 8.4, vitamina_k_mcg = 0, folato_mcg = 18 where nome = 'Albumina em Pó, Fama' and categoria = 'Suplementos' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 62), ferro_mg = coalesce(ferro_mg, 0.15), magnesio_mg = 88, fosforo_mg = 111, potassio_mg = 1125, sodio_mg = coalesce(sodio_mg, 1280), zinco_mg = coalesce(zinco_mg, 0.1), cobre_mcg = 114, manganes_mg = 0.007, selenio_mcg = 125.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.005), riboflavina_mg = coalesce(riboflavina_mg, 2.53), niacina_mg = coalesce(niacina_mg, 0.865), acido_pantotenico_mg = 0.775, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.18), colina_mg = 8.4, vitamina_k_mcg = 0, folato_mcg = 18 where nome = 'Albumina em Pó, Naturovos' and categoria = 'Suplementos' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 62), ferro_mg = coalesce(ferro_mg, 0.15), magnesio_mg = 88, fosforo_mg = 111, potassio_mg = 1125, sodio_mg = coalesce(sodio_mg, 1280), zinco_mg = coalesce(zinco_mg, 0.1), cobre_mcg = 114, manganes_mg = 0.007, selenio_mcg = 125.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.005), riboflavina_mg = coalesce(riboflavina_mg, 2.53), niacina_mg = coalesce(niacina_mg, 0.865), acido_pantotenico_mg = 0.775, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.18), colina_mg = 8.4, vitamina_k_mcg = 0, folato_mcg = 18 where nome = 'Albumina Growth, sabor Natural' and categoria = 'Suplementos' and fonte = 'Fabricante' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 62), ferro_mg = coalesce(ferro_mg, 0.15), magnesio_mg = 88, fosforo_mg = 111, potassio_mg = 1125, sodio_mg = coalesce(sodio_mg, 1280), zinco_mg = coalesce(zinco_mg, 0.1), cobre_mcg = 114, manganes_mg = 0.007, selenio_mcg = 125.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.005), riboflavina_mg = coalesce(riboflavina_mg, 2.53), niacina_mg = coalesce(niacina_mg, 0.865), acido_pantotenico_mg = 0.775, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.18), colina_mg = 8.4, vitamina_k_mcg = 0, folato_mcg = 18 where nome = 'Albumina Growth, sabor Banana' and categoria = 'Suplementos' and fonte = 'Fabricante' and id_avaliador is null;
