-- Migration 0085: micronutrientes IBGE — refrigerantes e sucos (pesquisa externa, TBCA)
--
-- Lote de recuperação por pesquisa externa, mesmo processo já usado nas
-- migrations 0057/0060/0061 da TACO (frutas/verduras/carnes rejeitadas
-- no casamento automático, recuperadas item a item na internet). Aqui os
-- refrigerantes e sucos do IBGE — que batiam sistematicamente com
-- entradas erradas do USDA ("Carbonated beverage, cream soda" pra
-- qualquer refrigerante, "Orange Pineapple Juice Blend"/produtos de
-- marca americana tipo NAKED JUICE/ODWALLA pra qualquer suco de fruta,
-- porque o USDA simplesmente não tem refrigerante de guaraná nem a
-- maioria dos sucos brasileiros — foram buscados diretamente na TBCA
-- (Tabela Brasileira de Composição de Alimentos, USP/FoRC/BRASILFOODS,
-- www.tbca.net.br), que é a fonte certa pra produto genuinamente
-- brasileiro sem equivalente americano. 26 itens.
--
-- Valores "tr" (traço, quantidade não quantificável) da TBCA foram
-- tratados como ausentes, não como zero — mantendo o mesmo princípio de
-- "prefiro coluna vazia a dado errado" mesmo dentro de uma fonte
-- confiável.
--
-- Refrigerantes: cola/guaraná/limão (Sprite)/água tônica, cada um nas
-- versões tradicional e diet/light (a TBCA não distingue diet de light,
-- ambos usam a mesma entrada "c/ adoçante"). "Paraguai" (marca de
-- refrigerante popular vendida em vários sabores) foi aproximado pro
-- sabor guaraná, o mais comum da linha. "Refrigerante não especificado"
-- ficou de fora por falta de um sabor padrão pra assumir.
--
-- Sucos: abacaxi, laranja (puro e combinado com banana/beterraba/
-- cenoura), manga e maracujá usaram a versão "s/açúcar" da TBCA — o teor
-- de carboidrato/açúcar já cadastrado nesses itens do IBGE bate com suco
-- natural sem adição. Morango usou a versão "c/açúcar": o valor de
-- açúcar já cadastrado no IBGE (14,45g/100ml) é bem mais alto do que
-- morango puro sustentaria, indicando que o produto real tem açúcar
-- adicionado. Versões "orgânico" reaproveitam o mesmo dado da versão
-- convencional (composição de vitaminas/minerais não muda de forma
-- relevante por ser orgânico).
--
-- Como sempre: coalesce() preserva os valores já existentes nas 12
-- colunas legadas; as 15 colunas novas (migration 0054) recebem o valor
-- da TBCA diretamente.
--
-- O que ainda resta pesquisar do IBGE (fora do escopo deste lote): doces
-- industrializados (balas, biscoitos, bombons — sistematicamente errados
-- também, batendo com "Candies, sweet chocolate" genérico do USDA) e os
-- ~1600 itens fora do pool "rigoroso" já revisado (itens com score baixo
-- ou sem match no casamento automático).

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1.37), sodio_mg = coalesce(sodio_mg, 6.15), fosforo_mg = 16.7, potassio_mg = 0.91, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_e_mg = 0, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 0 where nome = 'Refrigerante de cola tradicional' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0030H
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1.41), sodio_mg = coalesce(sodio_mg, 8.34), potassio_mg = 1.38, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_e_mg = 0, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 0 where nome = 'Refrigerante de guaraná tradicional' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0031H
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1.75), sodio_mg = coalesce(sodio_mg, 9.26), magnesio_mg = 0.53, potassio_mg = 4.27, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_e_mg = 0, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 0 where nome = 'Sprit refrigerante tradicional' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0033H (tipo limão)
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1.37), sodio_mg = coalesce(sodio_mg, 10.1), fosforo_mg = 16.7, potassio_mg = 0.91, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_e_mg = 0, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 0 where nome = 'Refrigerante de cola light' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0049N
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1.37), sodio_mg = coalesce(sodio_mg, 10.1), fosforo_mg = 16.7, potassio_mg = 0.91, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_e_mg = 0, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 0 where nome = 'Refrigerante de cola diet' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0049N
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1.41), sodio_mg = coalesce(sodio_mg, 13.9), magnesio_mg = 0.53, potassio_mg = 4.27, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_e_mg = 0, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 0 where nome = 'Refrigerante de guaraná light' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0050N
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1.41), sodio_mg = coalesce(sodio_mg, 13.9), magnesio_mg = 0.53, potassio_mg = 4.27, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_e_mg = 0, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 0 where nome = 'Refrigerante de guaraná diet' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0050N
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1.75), sodio_mg = coalesce(sodio_mg, 12.8), fosforo_mg = 0.15, potassio_mg = 1.51, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_e_mg = 0, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 0 where nome = 'Refrigerante de limão diet' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0052N
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1.08), sodio_mg = coalesce(sodio_mg, 30.7), potassio_mg = 1.51, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_e_mg = 0, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 0 where nome = 'Refrigerante de quinino dietético' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0048N (tipo água tônica)
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1.41), sodio_mg = coalesce(sodio_mg, 8.34), potassio_mg = 1.38, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_e_mg = 0, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 0 where nome = 'Paraguai refrigerante tradicional' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0031H (aproximação — marca de refrigerante popular, sabor guaraná é o mais comum da linha)
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1.41), sodio_mg = coalesce(sodio_mg, 13.9), magnesio_mg = 0.53, potassio_mg = 4.27, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_e_mg = 0, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 0 where nome = 'Paraguai refrigerante light' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0050N (mesma aproximação)
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6.3), ferro_mg = coalesce(ferro_mg, 0.16), magnesio_mg = 5.7, fosforo_mg = 3.61, potassio_mg = 47.2, sodio_mg = coalesce(sodio_mg, 0.97), zinco_mg = coalesce(zinco_mg, 0.05), cobre_mcg = 40, manganes_mg = 0.51, selenio_mcg = 0.14, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0.34), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 11.4), tiamina_mg = coalesce(tiamina_mg, 0.06), riboflavina_mg = coalesce(riboflavina_mg, 0.01), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 3.87 where nome = 'Suco de abacaxi' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0109C (natural, s/açúcar)
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6.3), ferro_mg = coalesce(ferro_mg, 0.16), magnesio_mg = 5.7, fosforo_mg = 3.61, potassio_mg = 47.2, sodio_mg = coalesce(sodio_mg, 0.97), zinco_mg = coalesce(zinco_mg, 0.05), cobre_mcg = 40, manganes_mg = 0.51, selenio_mcg = 0.14, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0.34), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 11.4), tiamina_mg = coalesce(tiamina_mg, 0.06), riboflavina_mg = coalesce(riboflavina_mg, 0.01), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 3.87 where nome = 'Suco de abacaxi orgânico' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0109C
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7.53), ferro_mg = coalesce(ferro_mg, 0.02), magnesio_mg = 8.97, fosforo_mg = 17.4, potassio_mg = 148, cobre_mcg = 20, manganes_mg = 0.02, selenio_mcg = 0.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0.86), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 69.7), tiamina_mg = coalesce(tiamina_mg, 0.04), riboflavina_mg = coalesce(riboflavina_mg, 0.01), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.02), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 24.6 where nome = 'Suco de laranja' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0038C (média diferentes variedades, s/açúcar)
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7.53), ferro_mg = coalesce(ferro_mg, 0.02), magnesio_mg = 8.97, fosforo_mg = 17.4, potassio_mg = 148, cobre_mcg = 20, manganes_mg = 0.02, selenio_mcg = 0.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0.86), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 69.7), tiamina_mg = coalesce(tiamina_mg, 0.04), riboflavina_mg = coalesce(riboflavina_mg, 0.01), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.02), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 24.6 where nome = 'Suco de laranja orgânico' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0038C
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17.3), ferro_mg = coalesce(ferro_mg, 0.13), magnesio_mg = 12.5, fosforo_mg = 15.9, potassio_mg = 160, sodio_mg = coalesce(sodio_mg, 0.29), zinco_mg = coalesce(zinco_mg, 0.1), cobre_mcg = 40, manganes_mg = 0.13, selenio_mcg = 0.19, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3.5), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 28.3), tiamina_mg = coalesce(tiamina_mg, 0.04), riboflavina_mg = coalesce(riboflavina_mg, 0.02), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.04), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 20.2 where nome = 'Suco de laranja com banana' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0153C (s/açúcar)
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 25.8), ferro_mg = coalesce(ferro_mg, 0.17), magnesio_mg = 13.7, fosforo_mg = 20, potassio_mg = 216, sodio_mg = coalesce(sodio_mg, 2.95), zinco_mg = coalesce(zinco_mg, 0.22), cobre_mcg = 50, manganes_mg = 0.36, selenio_mcg = 0.27, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1.32), vitamina_e_mg = 0.27, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 35.7), tiamina_mg = coalesce(tiamina_mg, 0.06), riboflavina_mg = coalesce(riboflavina_mg, 0.03), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.03), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 53 where nome = 'Suco de laranja e beterraba' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0155C (s/açúcar)
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11.6), ferro_mg = coalesce(ferro_mg, 0.14), magnesio_mg = 8.72, fosforo_mg = 17.9, potassio_mg = 187, sodio_mg = coalesce(sodio_mg, 3.34), zinco_mg = coalesce(zinco_mg, 0.09), cobre_mcg = 30, manganes_mg = 0.04, selenio_mcg = 0.39, vitamina_a_mcg = coalesce(vitamina_a_mcg, 112), vitamina_e_mg = 0.18, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 52.9), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.02), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 20.4 where nome = 'Suco de laranja e cenoura' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0137C (s/açúcar)
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11.6), ferro_mg = coalesce(ferro_mg, 0.14), magnesio_mg = 8.72, fosforo_mg = 17.9, potassio_mg = 187, sodio_mg = coalesce(sodio_mg, 3.34), zinco_mg = coalesce(zinco_mg, 0.09), cobre_mcg = 30, manganes_mg = 0.04, selenio_mcg = 0.39, vitamina_a_mcg = coalesce(vitamina_a_mcg, 112), vitamina_e_mg = 0.18, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 52.9), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.02), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 20.4 where nome = 'Suco de laranja cenoura e beterraba' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0137C (aproximação — mesmo valor já usado pra laranja+cenoura; o dado-base do IBGE pra esse trio é idêntico ao de laranja+cenoura/laranja+beterraba)
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11.6), ferro_mg = coalesce(ferro_mg, 0.14), magnesio_mg = 8.72, fosforo_mg = 17.9, potassio_mg = 187, sodio_mg = coalesce(sodio_mg, 3.34), zinco_mg = coalesce(zinco_mg, 0.09), cobre_mcg = 30, manganes_mg = 0.04, selenio_mcg = 0.39, vitamina_a_mcg = coalesce(vitamina_a_mcg, 112), vitamina_e_mg = 0.18, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 52.9), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.02), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 20.4 where nome = 'Suco de laranja cenoura e beterraba orgânico' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0137C
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 2.88), ferro_mg = coalesce(ferro_mg, 0.04), magnesio_mg = 2.76, fosforo_mg = 3.9, potassio_mg = 53.9, sodio_mg = coalesce(sodio_mg, 0.29), zinco_mg = coalesce(zinco_mg, 0.03), cobre_mcg = 30, manganes_mg = 0.05, selenio_mcg = 0.19, vitamina_a_mcg = coalesce(vitamina_a_mcg, 47.2), vitamina_e_mg = 0.23, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 9.57), tiamina_mg = coalesce(tiamina_mg, 0.01), riboflavina_mg = coalesce(riboflavina_mg, 0.01), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.01), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 14.1 where nome = 'Suco de manga' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0141C (s/açúcar)
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 2.88), ferro_mg = coalesce(ferro_mg, 0.04), magnesio_mg = 2.76, fosforo_mg = 3.9, potassio_mg = 53.9, sodio_mg = coalesce(sodio_mg, 0.29), zinco_mg = coalesce(zinco_mg, 0.03), cobre_mcg = 30, manganes_mg = 0.05, selenio_mcg = 0.19, vitamina_a_mcg = coalesce(vitamina_a_mcg, 47.2), vitamina_e_mg = 0.23, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 9.57), tiamina_mg = coalesce(tiamina_mg, 0.01), riboflavina_mg = coalesce(riboflavina_mg, 0.01), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.01), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 14.1 where nome = 'Suco de manga orgânico' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0141C
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 0.51), ferro_mg = coalesce(ferro_mg, 0.05), magnesio_mg = 2.11, fosforo_mg = 4.8, potassio_mg = 32.1, sodio_mg = coalesce(sodio_mg, 0.15), zinco_mg = coalesce(zinco_mg, 0.04), cobre_mcg = 20, manganes_mg = 0.01, selenio_mcg = 0.08, vitamina_a_mcg = coalesce(vitamina_a_mcg, 5.14), vitamina_e_mg = 0.01, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.88), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 0.87 where nome = 'Suco de maracujá' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0143C (natural, s/açúcar)
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 0.51), ferro_mg = coalesce(ferro_mg, 0.05), magnesio_mg = 2.11, fosforo_mg = 4.8, potassio_mg = 32.1, sodio_mg = coalesce(sodio_mg, 0.15), zinco_mg = coalesce(zinco_mg, 0.04), cobre_mcg = 20, manganes_mg = 0.01, selenio_mcg = 0.08, vitamina_a_mcg = coalesce(vitamina_a_mcg, 5.14), vitamina_e_mg = 0.01, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.88), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 0.87 where nome = 'Suco de maracujá orgânico' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0143C
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7.85), ferro_mg = coalesce(ferro_mg, 0.14), magnesio_mg = 5.52, fosforo_mg = 14.4, potassio_mg = 51.1, sodio_mg = coalesce(sodio_mg, 6.1), zinco_mg = coalesce(zinco_mg, 0.05), cobre_mcg = 20, manganes_mg = 0.1, selenio_mcg = 0.21, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2.23), vitamina_e_mg = 0.19, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 34.9), riboflavina_mg = coalesce(riboflavina_mg, 0.01), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.01), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 10.9 where nome = 'Suco de morango' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0148C (natural, c/açúcar — teor de açúcar já cadastrado no IBGE pra esse item bate com versão adoçada, não com morango puro)
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7.85), ferro_mg = coalesce(ferro_mg, 0.14), magnesio_mg = 5.52, fosforo_mg = 14.4, potassio_mg = 51.1, sodio_mg = coalesce(sodio_mg, 6.1), zinco_mg = coalesce(zinco_mg, 0.05), cobre_mcg = 20, manganes_mg = 0.1, selenio_mcg = 0.21, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2.23), vitamina_e_mg = 0.19, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 34.9), riboflavina_mg = coalesce(riboflavina_mg, 0.01), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.01), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 10.9 where nome = 'Suco de morango orgânico' and fonte = 'IBGE' and id_avaliador is null; -- TBCA BRC0148C
