-- Migration 0087: micronutrientes IBGE — lote 7 (hortaliças, grãos e leguminosas soltas — 2ª rodada)
--
-- Primeiro lote fora do pool "rigoroso" (razao>=1.0 && score>=2.5) usado
-- nos lotes 1-6 (migrations 0075-0080). O IBGE tem 991 itens marcados
-- "alta_confianca" pelo algoritmo, mas só 352 caíam no corte rigoroso;
-- dos 724 restantes revisados agora, a qualidade do match automático é
-- ainda pior que a do "rigoroso" — o algoritmo geralmente só bateu 2
-- palavras genéricas (score=2) e errou o alimento por completo: "Corn
-- oil" pra grão de milho cru, "Rice crackers" pra arroz cru, "Cabbage,
-- kimchi" pra repolho sem preparo, "TACO BELL, Nachos" pra pimentão,
-- "Rice noodles" (macarrão de arroz) pra macarrão de trigo comum.
--
-- 51 itens aprovados neste lote, todos com fdc_id escolhido manualmente
-- (nenhum usa a sugestão original do algoritmo). Boa parte é a versão
-- "sem preparo especificado", "orgânico" ou com um molho/tempero simples
-- (ao vinagrete, ao alho e óleo, molho vermelho/branco) do MESMO alimento
-- já resolvido nos lotes 1-6 — nesses casos reaproveitei o fdc_id já
-- verificado, sem pesquisa nova (cenoura, repolho, brócolis, espinafre,
-- couve, jiló, abobrinha, abóbora, berinjela, cebola).
--
-- Itens novos pesquisados agora: alface, tomate, alho, pimentão (todos
-- crus, primeira vez que aparecem na base), grão de bico, lentilha, soja
-- em grão, amendoim em grão/moído, aveia em flocos, gérmen de trigo,
-- arroz (branco e integral, incluindo versões "sem preparo"/orgânico) e
-- macarrão de trigo comum (cru/cozido/refogado/ensopado) — corrigindo o
-- erro de espécie de grão do algoritmo (macarrão de arroz em vez de
-- trigo). "Purê de batata" também entrou (mashed potato). "Broto de
-- feijão" foi corrigido de vagem (Green beans) pra broto de feijão-mungo
-- de verdade (mung bean sprouts), que é o alimento real por trás do
-- nome.
--
-- Itens que ficaram de fora deste sub-lote de hortaliças/grãos (sem
-- equivalente seguro): Macarrão instantâneo (produto industrializado com
-- tempero, perfil de sódio muito diferente de massa comum), Macarrão com
-- carne/com peixe (pratos compostos), Ervilha em grão (sem entrada de
-- ervilha seca inteira crua no USDA), e vários itens regionais (Xerém de
-- milho, Puba de milho/fubá, Farinha de copioba/d'água/beiju/láctea,
-- Catalonha, Pupunha, Mangalô, Língua de vaca) cujo significado exato eu
-- não consegui confirmar com segurança suficiente pra escolher um
-- fdc_id — ficam pra uma eventual pesquisa externa dedicada.
--
-- Como sempre: coalesce() preserva os valores já existentes nas 12
-- colunas legadas; as 15 colunas novas (migration 0054) recebem o valor
-- USDA diretamente. Ainda restam ~670 itens do pool alta_confianca
-- abaixo do corte rigoroso (carnes/laticínios/processados/frutas
-- principalmente), mais 175 baixa_confianca e 805 sem_match — próximos
-- lotes continuam por aí.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 33), ferro_mg = coalesce(ferro_mg, 0.3), magnesio_mg = 12, fosforo_mg = 35, potassio_mg = 320, sodio_mg = coalesce(sodio_mg, 69), zinco_mg = coalesce(zinco_mg, 0.24), cobre_mcg = 45, manganes_mg = 0.143, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 835), vitamina_e_mg = 0.66, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 5.9), tiamina_mg = coalesce(tiamina_mg, 0.066), riboflavina_mg = coalesce(riboflavina_mg, 0.058), niacina_mg = coalesce(niacina_mg, 0.983), acido_pantotenico_mg = 0.273, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.138), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 8.8, vitamina_k_mcg = 13.2, folato_mcg = 19 where nome = 'Cenoura' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 30), ferro_mg = coalesce(ferro_mg, 0.34), magnesio_mg = 10, fosforo_mg = 30, potassio_mg = 235, sodio_mg = coalesce(sodio_mg, 302), zinco_mg = coalesce(zinco_mg, 0.2), cobre_mcg = 17, manganes_mg = 0.155, selenio_mcg = 0.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 852), vitamina_e_mg = 1.03, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 3.6), tiamina_mg = coalesce(tiamina_mg, 0.066), riboflavina_mg = coalesce(riboflavina_mg, 0.044), niacina_mg = coalesce(niacina_mg, 0.645), acido_pantotenico_mg = 0.232, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.153), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 8.8, vitamina_k_mcg = 13.7, folato_mcg = 2 where nome = 'Cenoura, Molho vermelho' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 30), ferro_mg = coalesce(ferro_mg, 0.34), magnesio_mg = 10, fosforo_mg = 30, potassio_mg = 235, sodio_mg = coalesce(sodio_mg, 302), zinco_mg = coalesce(zinco_mg, 0.2), cobre_mcg = 17, manganes_mg = 0.155, selenio_mcg = 0.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 852), vitamina_e_mg = 1.03, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 3.6), tiamina_mg = coalesce(tiamina_mg, 0.066), riboflavina_mg = coalesce(riboflavina_mg, 0.044), niacina_mg = coalesce(niacina_mg, 0.645), acido_pantotenico_mg = 0.232, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.153), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 8.8, vitamina_k_mcg = 13.7, folato_mcg = 2 where nome = 'Cenoura, Ao alho e óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 30), ferro_mg = coalesce(ferro_mg, 0.34), magnesio_mg = 10, fosforo_mg = 30, potassio_mg = 235, sodio_mg = coalesce(sodio_mg, 302), zinco_mg = coalesce(zinco_mg, 0.2), cobre_mcg = 17, manganes_mg = 0.155, selenio_mcg = 0.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 852), vitamina_e_mg = 1.03, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 3.6), tiamina_mg = coalesce(tiamina_mg, 0.066), riboflavina_mg = coalesce(riboflavina_mg, 0.044), niacina_mg = coalesce(niacina_mg, 0.645), acido_pantotenico_mg = 0.232, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.153), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 8.8, vitamina_k_mcg = 13.7, folato_mcg = 2 where nome = 'Cenoura, Ao vinagrete' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 40), ferro_mg = coalesce(ferro_mg, 0.47), magnesio_mg = 12, fosforo_mg = 26, potassio_mg = 170, sodio_mg = coalesce(sodio_mg, 18), zinco_mg = coalesce(zinco_mg, 0.18), cobre_mcg = 19, manganes_mg = 0.16, selenio_mcg = 0.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 5), vitamina_e_mg = 0.15, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 36.6), tiamina_mg = coalesce(tiamina_mg, 0.061), riboflavina_mg = coalesce(riboflavina_mg, 0.04), niacina_mg = coalesce(niacina_mg, 0.234), acido_pantotenico_mg = 0.212, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.124), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 10.7, vitamina_k_mcg = 76, folato_mcg = 43 where nome = 'Repolho' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 48), ferro_mg = coalesce(ferro_mg, 0.17), magnesio_mg = 15, fosforo_mg = 33, potassio_mg = 196, sodio_mg = coalesce(sodio_mg, 8), zinco_mg = coalesce(zinco_mg, 0.2), cobre_mcg = 17, manganes_mg = 0.205, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 4), vitamina_e_mg = 0.14, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 37.5), tiamina_mg = coalesce(tiamina_mg, 0.061), riboflavina_mg = coalesce(riboflavina_mg, 0.038), niacina_mg = coalesce(niacina_mg, 0.248), acido_pantotenico_mg = 0.174, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.112), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 20.3, vitamina_k_mcg = 108.7, folato_mcg = 30 where nome = 'Repolho, Molho branco' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 48), ferro_mg = coalesce(ferro_mg, 0.17), magnesio_mg = 15, fosforo_mg = 33, potassio_mg = 196, sodio_mg = coalesce(sodio_mg, 8), zinco_mg = coalesce(zinco_mg, 0.2), cobre_mcg = 17, manganes_mg = 0.205, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 4), vitamina_e_mg = 0.14, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 37.5), tiamina_mg = coalesce(tiamina_mg, 0.061), riboflavina_mg = coalesce(riboflavina_mg, 0.038), niacina_mg = coalesce(niacina_mg, 0.248), acido_pantotenico_mg = 0.174, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.112), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 20.3, vitamina_k_mcg = 108.7, folato_mcg = 30 where nome = 'Repolho, Ao alho e óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 47), ferro_mg = coalesce(ferro_mg, 0.73), magnesio_mg = 21, fosforo_mg = 66, potassio_mg = 316, sodio_mg = coalesce(sodio_mg, 33), zinco_mg = coalesce(zinco_mg, 0.41), cobre_mcg = 49, manganes_mg = 0.21, selenio_mcg = 2.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 31), vitamina_e_mg = 0.78, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 89.2), tiamina_mg = coalesce(tiamina_mg, 0.071), riboflavina_mg = coalesce(riboflavina_mg, 0.117), niacina_mg = coalesce(niacina_mg, 0.639), acido_pantotenico_mg = 0.573, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.175), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 18.7, vitamina_k_mcg = 101.6, folato_mcg = 63 where nome = 'Brócolis' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 40), ferro_mg = coalesce(ferro_mg, 0.67), magnesio_mg = 21, fosforo_mg = 67, potassio_mg = 293, sodio_mg = coalesce(sodio_mg, 262), zinco_mg = coalesce(zinco_mg, 0.45), cobre_mcg = 61, manganes_mg = 0.194, selenio_mcg = 1.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 77), vitamina_e_mg = 1.45, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 64.9), tiamina_mg = coalesce(tiamina_mg, 0.063), riboflavina_mg = coalesce(riboflavina_mg, 0.123), niacina_mg = coalesce(niacina_mg, 0.553), acido_pantotenico_mg = 0.616, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.2), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 40.1, vitamina_k_mcg = 141.1, folato_mcg = 108 where nome = 'Brócolis, Ao alho e óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 40), ferro_mg = coalesce(ferro_mg, 0.67), magnesio_mg = 21, fosforo_mg = 67, potassio_mg = 293, sodio_mg = coalesce(sodio_mg, 262), zinco_mg = coalesce(zinco_mg, 0.45), cobre_mcg = 61, manganes_mg = 0.194, selenio_mcg = 1.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 77), vitamina_e_mg = 1.45, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 64.9), tiamina_mg = coalesce(tiamina_mg, 0.063), riboflavina_mg = coalesce(riboflavina_mg, 0.123), niacina_mg = coalesce(niacina_mg, 0.553), acido_pantotenico_mg = 0.616, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.2), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 40.1, vitamina_k_mcg = 141.1, folato_mcg = 108 where nome = 'Brócolis, Ao vinagrete' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 99), ferro_mg = coalesce(ferro_mg, 2.71), magnesio_mg = 79, fosforo_mg = 49, potassio_mg = 558, sodio_mg = coalesce(sodio_mg, 79), zinco_mg = coalesce(zinco_mg, 0.53), cobre_mcg = 130, manganes_mg = 0.897, selenio_mcg = 1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 469), vitamina_e_mg = 2.03, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 28.1), tiamina_mg = coalesce(tiamina_mg, 0.078), riboflavina_mg = coalesce(riboflavina_mg, 0.189), niacina_mg = coalesce(niacina_mg, 0.724), acido_pantotenico_mg = 0.065, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.195), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 19.3, vitamina_k_mcg = 482.9, folato_mcg = 194 where nome = 'Espinafre' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 136), ferro_mg = coalesce(ferro_mg, 3.57), magnesio_mg = 87, fosforo_mg = 56, potassio_mg = 466, sodio_mg = coalesce(sodio_mg, 306), zinco_mg = coalesce(zinco_mg, 0.76), cobre_mcg = 174, manganes_mg = 0.935, selenio_mcg = 1.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 524), vitamina_e_mg = 2.08, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 9.8), tiamina_mg = coalesce(tiamina_mg, 0.095), riboflavina_mg = coalesce(riboflavina_mg, 0.236), niacina_mg = coalesce(niacina_mg, 0.49), acido_pantotenico_mg = 0.145, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.242), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 19.7, vitamina_k_mcg = 493.6, folato_mcg = 146 where nome = 'Espinafre, Ao vinagrete' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 254), ferro_mg = coalesce(ferro_mg, 1.6), magnesio_mg = 33, fosforo_mg = 55, potassio_mg = 348, sodio_mg = coalesce(sodio_mg, 53), zinco_mg = coalesce(zinco_mg, 0.39), cobre_mcg = 53, manganes_mg = 0.92, selenio_mcg = 0.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 241), vitamina_e_mg = 0.66, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 93.4), tiamina_mg = coalesce(tiamina_mg, 0.113), riboflavina_mg = coalesce(riboflavina_mg, 0.347), niacina_mg = coalesce(niacina_mg, 1.18), acido_pantotenico_mg = 0.37, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.147), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0.5, vitamina_k_mcg = 389.6, folato_mcg = 62 where nome = 'Couve' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 9), ferro_mg = coalesce(ferro_mg, 0.23), magnesio_mg = 14, fosforo_mg = 24, potassio_mg = 229, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 0.16), cobre_mcg = 81, manganes_mg = 0.232, selenio_mcg = 0.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 0.3, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 2.2), tiamina_mg = coalesce(tiamina_mg, 0.039), riboflavina_mg = coalesce(riboflavina_mg, 0.037), niacina_mg = coalesce(niacina_mg, 0.649), acido_pantotenico_mg = 0.281, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.084), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.9, vitamina_k_mcg = 3.5, folato_mcg = 22 where nome = 'Jiló' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 0.25), magnesio_mg = 11, fosforo_mg = 15, potassio_mg = 123, sodio_mg = coalesce(sodio_mg, 239), zinco_mg = coalesce(zinco_mg, 0.12), cobre_mcg = 59, manganes_mg = 0.113, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.41, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.3), tiamina_mg = coalesce(tiamina_mg, 0.076), riboflavina_mg = coalesce(riboflavina_mg, 0.02), niacina_mg = coalesce(niacina_mg, 0.6), acido_pantotenico_mg = 0.075, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.086), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 9.4, vitamina_k_mcg = 2.9, folato_mcg = 14 where nome = 'Jiló, Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 0.25), magnesio_mg = 11, fosforo_mg = 15, potassio_mg = 123, sodio_mg = coalesce(sodio_mg, 239), zinco_mg = coalesce(zinco_mg, 0.12), cobre_mcg = 59, manganes_mg = 0.113, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.41, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.3), tiamina_mg = coalesce(tiamina_mg, 0.076), riboflavina_mg = coalesce(riboflavina_mg, 0.02), niacina_mg = coalesce(niacina_mg, 0.6), acido_pantotenico_mg = 0.075, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.086), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 9.4, vitamina_k_mcg = 2.9, folato_mcg = 14 where nome = 'Jiló, Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 18), ferro_mg = coalesce(ferro_mg, 0.37), magnesio_mg = 19, fosforo_mg = 37, potassio_mg = 264, sodio_mg = coalesce(sodio_mg, 3), zinco_mg = coalesce(zinco_mg, 0.33), cobre_mcg = 52, manganes_mg = 0.173, selenio_mcg = 0.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 56), vitamina_e_mg = 0.12, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 12.9), tiamina_mg = coalesce(tiamina_mg, 0.035), riboflavina_mg = coalesce(riboflavina_mg, 0.024), niacina_mg = coalesce(niacina_mg, 0.51), acido_pantotenico_mg = 0.288, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.08), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 9.4, vitamina_k_mcg = 4.2, folato_mcg = 28 where nome = 'Abobrinha, Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 18), ferro_mg = coalesce(ferro_mg, 0.37), magnesio_mg = 19, fosforo_mg = 37, potassio_mg = 264, sodio_mg = coalesce(sodio_mg, 3), zinco_mg = coalesce(zinco_mg, 0.33), cobre_mcg = 52, manganes_mg = 0.173, selenio_mcg = 0.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 56), vitamina_e_mg = 0.12, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 12.9), tiamina_mg = coalesce(tiamina_mg, 0.035), riboflavina_mg = coalesce(riboflavina_mg, 0.024), niacina_mg = coalesce(niacina_mg, 0.51), acido_pantotenico_mg = 0.288, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.08), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 9.4, vitamina_k_mcg = 4.2, folato_mcg = 28 where nome = 'Abobrinha, Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 15), ferro_mg = coalesce(ferro_mg, 0.57), magnesio_mg = 9, fosforo_mg = 30, potassio_mg = 230, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.23), cobre_mcg = 91, manganes_mg = 0.089, selenio_mcg = 0.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 288), vitamina_e_mg = 0.8, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4.7), tiamina_mg = coalesce(tiamina_mg, 0.031), riboflavina_mg = coalesce(riboflavina_mg, 0.078), niacina_mg = coalesce(niacina_mg, 0.413), acido_pantotenico_mg = 0.201, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.044), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.2, vitamina_k_mcg = 0.8, folato_mcg = 9 where nome = 'Abóbora, Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 15), ferro_mg = coalesce(ferro_mg, 0.57), magnesio_mg = 9, fosforo_mg = 30, potassio_mg = 230, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.23), cobre_mcg = 91, manganes_mg = 0.089, selenio_mcg = 0.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 288), vitamina_e_mg = 0.8, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4.7), tiamina_mg = coalesce(tiamina_mg, 0.031), riboflavina_mg = coalesce(riboflavina_mg, 0.078), niacina_mg = coalesce(niacina_mg, 0.413), acido_pantotenico_mg = 0.201, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.044), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.2, vitamina_k_mcg = 0.8, folato_mcg = 9 where nome = 'Abóbora, Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 9), ferro_mg = coalesce(ferro_mg, 0.23), magnesio_mg = 14, fosforo_mg = 24, potassio_mg = 229, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 0.16), cobre_mcg = 81, manganes_mg = 0.232, selenio_mcg = 0.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 0.3, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 2.2), tiamina_mg = coalesce(tiamina_mg, 0.039), riboflavina_mg = coalesce(riboflavina_mg, 0.037), niacina_mg = coalesce(niacina_mg, 0.649), acido_pantotenico_mg = 0.281, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.084), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.9, vitamina_k_mcg = 3.5, folato_mcg = 22 where nome = 'Berinjela' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 33), ferro_mg = coalesce(ferro_mg, 0.97), magnesio_mg = 14, fosforo_mg = 30, potassio_mg = 247, sodio_mg = coalesce(sodio_mg, 8), zinco_mg = coalesce(zinco_mg, 0.23), cobre_mcg = 48, manganes_mg = 0.155, selenio_mcg = 0.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 436), vitamina_e_mg = 0.13, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4), tiamina_mg = coalesce(tiamina_mg, 0.072), riboflavina_mg = coalesce(riboflavina_mg, 0.067), niacina_mg = coalesce(niacina_mg, 0.313), acido_pantotenico_mg = 0.142, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.074), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 9.9, vitamina_k_mcg = 102.5, folato_mcg = 136 where nome = 'Alface' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 33), ferro_mg = coalesce(ferro_mg, 0.97), magnesio_mg = 14, fosforo_mg = 30, potassio_mg = 247, sodio_mg = coalesce(sodio_mg, 8), zinco_mg = coalesce(zinco_mg, 0.23), cobre_mcg = 48, manganes_mg = 0.155, selenio_mcg = 0.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 436), vitamina_e_mg = 0.13, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4), tiamina_mg = coalesce(tiamina_mg, 0.072), riboflavina_mg = coalesce(riboflavina_mg, 0.067), niacina_mg = coalesce(niacina_mg, 0.313), acido_pantotenico_mg = 0.142, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.074), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 9.9, vitamina_k_mcg = 102.5, folato_mcg = 136 where nome = 'Alface orgânica' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 10), ferro_mg = coalesce(ferro_mg, 0.27), magnesio_mg = 11, fosforo_mg = 24, potassio_mg = 237, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 0.17), cobre_mcg = 59, manganes_mg = 0.114, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 42), vitamina_e_mg = 0.54, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 13.7), tiamina_mg = coalesce(tiamina_mg, 0.037), riboflavina_mg = coalesce(riboflavina_mg, 0.019), niacina_mg = coalesce(niacina_mg, 0.594), acido_pantotenico_mg = 0.089, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.08), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.7, vitamina_k_mcg = 7.9, folato_mcg = 15 where nome = 'Tomate' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 10), ferro_mg = coalesce(ferro_mg, 0.27), magnesio_mg = 11, fosforo_mg = 24, potassio_mg = 237, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 0.17), cobre_mcg = 59, manganes_mg = 0.114, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 42), vitamina_e_mg = 0.54, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 13.7), tiamina_mg = coalesce(tiamina_mg, 0.037), riboflavina_mg = coalesce(riboflavina_mg, 0.019), niacina_mg = coalesce(niacina_mg, 0.594), acido_pantotenico_mg = 0.089, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.08), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.7, vitamina_k_mcg = 7.9, folato_mcg = 15 where nome = 'Tomate orgânico' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 23), ferro_mg = coalesce(ferro_mg, 0.21), magnesio_mg = 10, fosforo_mg = 29, potassio_mg = 146, sodio_mg = coalesce(sodio_mg, 4), zinco_mg = coalesce(zinco_mg, 0.17), cobre_mcg = 39, manganes_mg = 0.129, selenio_mcg = 0.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 7.4), tiamina_mg = coalesce(tiamina_mg, 0.046), riboflavina_mg = coalesce(riboflavina_mg, 0.027), niacina_mg = coalesce(niacina_mg, 0.116), acido_pantotenico_mg = 0.123, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.12), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.1, vitamina_k_mcg = 0.4, folato_mcg = 19 where nome = 'Cebola' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 0.24), magnesio_mg = 11, fosforo_mg = 35, potassio_mg = 166, sodio_mg = coalesce(sodio_mg, 239), zinco_mg = coalesce(zinco_mg, 0.21), cobre_mcg = 67, manganes_mg = 0.153, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 5.2), tiamina_mg = coalesce(tiamina_mg, 0.042), riboflavina_mg = coalesce(riboflavina_mg, 0.023), niacina_mg = coalesce(niacina_mg, 0.165), acido_pantotenico_mg = 0.113, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.129), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.8, vitamina_k_mcg = 0.5, folato_mcg = 15 where nome = 'Cebola, Ao vinagrete' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 0.24), magnesio_mg = 11, fosforo_mg = 35, potassio_mg = 166, sodio_mg = coalesce(sodio_mg, 239), zinco_mg = coalesce(zinco_mg, 0.21), cobre_mcg = 67, manganes_mg = 0.153, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 5.2), tiamina_mg = coalesce(tiamina_mg, 0.042), riboflavina_mg = coalesce(riboflavina_mg, 0.023), niacina_mg = coalesce(niacina_mg, 0.165), acido_pantotenico_mg = 0.113, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.129), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.8, vitamina_k_mcg = 0.5, folato_mcg = 15 where nome = 'Cebola, Molho vermelho' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 181), ferro_mg = coalesce(ferro_mg, 1.7), magnesio_mg = 25, fosforo_mg = 153, potassio_mg = 401, sodio_mg = coalesce(sodio_mg, 17), zinco_mg = coalesce(zinco_mg, 1.16), cobre_mcg = 299, manganes_mg = 1.672, selenio_mcg = 14.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.08, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 31.2), tiamina_mg = coalesce(tiamina_mg, 0.2), riboflavina_mg = coalesce(riboflavina_mg, 0.11), niacina_mg = coalesce(niacina_mg, 0.7), acido_pantotenico_mg = 0.596, vitamina_b6_mg = coalesce(vitamina_b6_mg, 1.235), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 23.2, vitamina_k_mcg = 1.7, folato_mcg = 3 where nome = 'Alho' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7), ferro_mg = coalesce(ferro_mg, 0.43), magnesio_mg = 12, fosforo_mg = 26, potassio_mg = 211, sodio_mg = coalesce(sodio_mg, 4), zinco_mg = coalesce(zinco_mg, 0.25), cobre_mcg = 17, manganes_mg = 0.112, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 157), vitamina_e_mg = 1.58, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 127.7), tiamina_mg = coalesce(tiamina_mg, 0.054), riboflavina_mg = coalesce(riboflavina_mg, 0.085), niacina_mg = coalesce(niacina_mg, 0.979), acido_pantotenico_mg = 0.317, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.291), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 5.6, vitamina_k_mcg = 4.9, folato_mcg = 46 where nome = 'Pimentão' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7), ferro_mg = coalesce(ferro_mg, 0.43), magnesio_mg = 12, fosforo_mg = 26, potassio_mg = 211, sodio_mg = coalesce(sodio_mg, 4), zinco_mg = coalesce(zinco_mg, 0.25), cobre_mcg = 17, manganes_mg = 0.112, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 157), vitamina_e_mg = 1.58, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 127.7), tiamina_mg = coalesce(tiamina_mg, 0.054), riboflavina_mg = coalesce(riboflavina_mg, 0.085), niacina_mg = coalesce(niacina_mg, 0.979), acido_pantotenico_mg = 0.317, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.291), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 5.6, vitamina_k_mcg = 4.9, folato_mcg = 46 where nome = 'Pimentão orgânico' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 13), ferro_mg = coalesce(ferro_mg, 0.91), magnesio_mg = 21, fosforo_mg = 54, potassio_mg = 149, sodio_mg = coalesce(sodio_mg, 6), zinco_mg = coalesce(zinco_mg, 0.41), cobre_mcg = 164, manganes_mg = 0.188, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 0.1, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 13.2), tiamina_mg = coalesce(tiamina_mg, 0.084), riboflavina_mg = coalesce(riboflavina_mg, 0.124), niacina_mg = coalesce(niacina_mg, 0.749), acido_pantotenico_mg = 0.38, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.088), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 14.4, vitamina_k_mcg = 33, folato_mcg = 61 where nome = 'Broto de feijão, Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 12), ferro_mg = coalesce(ferro_mg, 0.65), magnesio_mg = 14, fosforo_mg = 28, potassio_mg = 101, sodio_mg = coalesce(sodio_mg, 10), zinco_mg = coalesce(zinco_mg, 0.47), cobre_mcg = 122, manganes_mg = 0.14, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 0.07, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 11.4), tiamina_mg = coalesce(tiamina_mg, 0.05), riboflavina_mg = coalesce(riboflavina_mg, 0.102), niacina_mg = coalesce(niacina_mg, 0.817), acido_pantotenico_mg = 0.243, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.054), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 9.9, vitamina_k_mcg = 22.7, folato_mcg = 29 where nome = 'Broto de feijão, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 24), ferro_mg = coalesce(ferro_mg, 0.27), magnesio_mg = 18, fosforo_mg = 46, potassio_mg = 296, sodio_mg = coalesce(sodio_mg, 302), zinco_mg = coalesce(zinco_mg, 0.28), cobre_mcg = 145, manganes_mg = 0.119, selenio_mcg = 0.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 7), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.2), vitamina_c_mg = coalesce(vitamina_c_mg, 6.2), tiamina_mg = coalesce(tiamina_mg, 0.089), riboflavina_mg = coalesce(riboflavina_mg, 0.041), niacina_mg = coalesce(niacina_mg, 1.118), acido_pantotenico_mg = 0.485, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.232), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.07), colina_mg = 13.3, vitamina_k_mcg = 1.8, folato_mcg = 8 where nome = 'Purê de batata' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 2), ferro_mg = coalesce(ferro_mg, 0.52), magnesio_mg = 37, fosforo_mg = 89, potassio_mg = 270, sodio_mg = coalesce(sodio_mg, 15), zinco_mg = coalesce(zinco_mg, 0.45), cobre_mcg = 54, manganes_mg = 0.161, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.07, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 6.8), tiamina_mg = coalesce(tiamina_mg, 0.2), riboflavina_mg = coalesce(riboflavina_mg, 0.06), niacina_mg = coalesce(niacina_mg, 1.7), acido_pantotenico_mg = 0.76, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.055), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), vitamina_k_mcg = 0.3, folato_mcg = 46 where nome = 'Milho (em grão)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 28), ferro_mg = coalesce(ferro_mg, 0.8), magnesio_mg = 25, fosforo_mg = 115, potassio_mg = 115, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 1.09), cobre_mcg = 220, manganes_mg = 1.088, selenio_mcg = 15.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.07), riboflavina_mg = coalesce(riboflavina_mg, 0.049), niacina_mg = coalesce(niacina_mg, 1.6), acido_pantotenico_mg = 1.014, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.164), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 5.8, vitamina_k_mcg = 0.1, folato_mcg = 8 where nome = 'Arroz (polido, parboilizado, agulha, agulhinha, etc.)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 28), ferro_mg = coalesce(ferro_mg, 0.8), magnesio_mg = 25, fosforo_mg = 115, potassio_mg = 115, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 1.09), cobre_mcg = 220, manganes_mg = 1.088, selenio_mcg = 15.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.07), riboflavina_mg = coalesce(riboflavina_mg, 0.049), niacina_mg = coalesce(niacina_mg, 1.6), acido_pantotenico_mg = 1.014, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.164), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 5.8, vitamina_k_mcg = 0.1, folato_mcg = 8 where nome = 'Arroz  orgânico' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 9), ferro_mg = coalesce(ferro_mg, 1.29), magnesio_mg = 116, fosforo_mg = 311, potassio_mg = 250, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 2.13), cobre_mcg = 302, manganes_mg = 2.853, selenio_mcg = 17.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.6, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.541), riboflavina_mg = coalesce(riboflavina_mg, 0.095), niacina_mg = coalesce(niacina_mg, 6.494), acido_pantotenico_mg = 1.065, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.477), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 21.5, vitamina_k_mcg = 0.6, folato_mcg = 23 where nome = 'Arroz integral' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 9), ferro_mg = coalesce(ferro_mg, 1.29), magnesio_mg = 116, fosforo_mg = 311, potassio_mg = 250, sodio_mg = coalesce(sodio_mg, 5), zinco_mg = coalesce(zinco_mg, 2.13), cobre_mcg = 302, manganes_mg = 2.853, selenio_mcg = 17.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.6, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.541), riboflavina_mg = coalesce(riboflavina_mg, 0.095), niacina_mg = coalesce(niacina_mg, 6.494), acido_pantotenico_mg = 1.065, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.477), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 21.5, vitamina_k_mcg = 0.6, folato_mcg = 23 where nome = 'Arroz integral orgânico' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 57), ferro_mg = coalesce(ferro_mg, 4.31), magnesio_mg = 79, fosforo_mg = 252, potassio_mg = 718, sodio_mg = coalesce(sodio_mg, 24), zinco_mg = coalesce(zinco_mg, 2.76), cobre_mcg = 656, manganes_mg = 4.15, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.82, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4), tiamina_mg = coalesce(tiamina_mg, 0.477), riboflavina_mg = coalesce(riboflavina_mg, 0.212), niacina_mg = coalesce(niacina_mg, 1.541), acido_pantotenico_mg = 1.588, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.535), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 99.3, vitamina_k_mcg = 9, folato_mcg = 557 where nome = 'Grão de bico' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 35), ferro_mg = coalesce(ferro_mg, 6.51), magnesio_mg = 47, fosforo_mg = 281, potassio_mg = 677, sodio_mg = coalesce(sodio_mg, 6), zinco_mg = coalesce(zinco_mg, 3.27), cobre_mcg = 754, manganes_mg = 1.393, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.49, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4.5), tiamina_mg = coalesce(tiamina_mg, 0.873), riboflavina_mg = coalesce(riboflavina_mg, 0.211), niacina_mg = coalesce(niacina_mg, 2.605), acido_pantotenico_mg = 2.14, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.54), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 96.4, vitamina_k_mcg = 5, folato_mcg = 479 where nome = 'Lentilha' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 277), ferro_mg = coalesce(ferro_mg, 15.7), magnesio_mg = 280, fosforo_mg = 704, potassio_mg = 1797, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 4.89), cobre_mcg = 1658, manganes_mg = 2.517, selenio_mcg = 17.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 0.85, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 6), tiamina_mg = coalesce(tiamina_mg, 0.874), riboflavina_mg = coalesce(riboflavina_mg, 0.87), niacina_mg = coalesce(niacina_mg, 1.623), acido_pantotenico_mg = 0.793, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.377), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 115.9, vitamina_k_mcg = 47, folato_mcg = 375 where nome = 'Soja em grão' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 92), ferro_mg = coalesce(ferro_mg, 4.58), magnesio_mg = 168, fosforo_mg = 376, potassio_mg = 705, sodio_mg = coalesce(sodio_mg, 18), zinco_mg = coalesce(zinco_mg, 3.27), cobre_mcg = 1144, manganes_mg = 1.934, selenio_mcg = 7.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 8.33, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.64), riboflavina_mg = coalesce(riboflavina_mg, 0.135), niacina_mg = coalesce(niacina_mg, 12.066), acido_pantotenico_mg = 1.767, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.348), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 52.5, vitamina_k_mcg = 0, folato_mcg = 240 where nome = 'Amendoim (em grão) in natura' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 92), ferro_mg = coalesce(ferro_mg, 4.58), magnesio_mg = 168, fosforo_mg = 376, potassio_mg = 705, sodio_mg = coalesce(sodio_mg, 18), zinco_mg = coalesce(zinco_mg, 3.27), cobre_mcg = 1144, manganes_mg = 1.934, selenio_mcg = 7.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 8.33, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.64), riboflavina_mg = coalesce(riboflavina_mg, 0.135), niacina_mg = coalesce(niacina_mg, 12.066), acido_pantotenico_mg = 1.767, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.348), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 52.5, vitamina_k_mcg = 0, folato_mcg = 240 where nome = 'Amendoim moído' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 54), ferro_mg = coalesce(ferro_mg, 4.72), magnesio_mg = 177, fosforo_mg = 523, potassio_mg = 429, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 3.97), cobre_mcg = 626, manganes_mg = 4.916, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.763), riboflavina_mg = coalesce(riboflavina_mg, 0.139), niacina_mg = coalesce(niacina_mg, 0.961), acido_pantotenico_mg = 1.349, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.119), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 56 where nome = 'Aveia em flocos' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 39), ferro_mg = coalesce(ferro_mg, 6.26), magnesio_mg = 239, fosforo_mg = 842, potassio_mg = 892, sodio_mg = coalesce(sodio_mg, 12), zinco_mg = coalesce(zinco_mg, 12.29), cobre_mcg = 796, manganes_mg = 13.301, selenio_mcg = 79.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 1.882), riboflavina_mg = coalesce(riboflavina_mg, 0.499), niacina_mg = coalesce(niacina_mg, 6.813), acido_pantotenico_mg = 2.257, vitamina_b6_mg = coalesce(vitamina_b6_mg, 1.3), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 281 where nome = 'Germe de trigo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 21), ferro_mg = coalesce(ferro_mg, 1.3), magnesio_mg = 53, fosforo_mg = 189, potassio_mg = 223, sodio_mg = coalesce(sodio_mg, 6), zinco_mg = coalesce(zinco_mg, 1.41), cobre_mcg = 289, manganes_mg = 0.917, selenio_mcg = 63.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.06), niacina_mg = coalesce(niacina_mg, 1.7), acido_pantotenico_mg = 0.431, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.142), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), vitamina_k_mcg = 0.1, folato_mcg = 18 where nome = 'Macarrão, Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7), ferro_mg = coalesce(ferro_mg, 0.5), magnesio_mg = 18, fosforo_mg = 58, potassio_mg = 44, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.51), cobre_mcg = 100, manganes_mg = 0.322, selenio_mcg = 26.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.06, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.02), riboflavina_mg = coalesce(riboflavina_mg, 0.02), niacina_mg = coalesce(niacina_mg, 0.4), acido_pantotenico_mg = 0.112, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.049), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.4, vitamina_k_mcg = 0, folato_mcg = 7 where nome = 'Macarrão, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7), ferro_mg = coalesce(ferro_mg, 0.5), magnesio_mg = 18, fosforo_mg = 58, potassio_mg = 44, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.51), cobre_mcg = 100, manganes_mg = 0.322, selenio_mcg = 26.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.06, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.02), riboflavina_mg = coalesce(riboflavina_mg, 0.02), niacina_mg = coalesce(niacina_mg, 0.4), acido_pantotenico_mg = 0.112, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.049), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.4, vitamina_k_mcg = 0, folato_mcg = 7 where nome = 'Macarrão, Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7), ferro_mg = coalesce(ferro_mg, 0.5), magnesio_mg = 18, fosforo_mg = 58, potassio_mg = 44, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.51), cobre_mcg = 100, manganes_mg = 0.322, selenio_mcg = 26.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.06, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.02), riboflavina_mg = coalesce(riboflavina_mg, 0.02), niacina_mg = coalesce(niacina_mg, 0.4), acido_pantotenico_mg = 0.112, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.049), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.4, vitamina_k_mcg = 0, folato_mcg = 7 where nome = 'Macarrão, Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 21), ferro_mg = coalesce(ferro_mg, 1.3), magnesio_mg = 53, fosforo_mg = 189, potassio_mg = 223, sodio_mg = coalesce(sodio_mg, 6), zinco_mg = coalesce(zinco_mg, 1.41), cobre_mcg = 289, manganes_mg = 0.917, selenio_mcg = 63.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.06), niacina_mg = coalesce(niacina_mg, 1.7), acido_pantotenico_mg = 0.431, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.142), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), vitamina_k_mcg = 0.1, folato_mcg = 18 where nome = 'Macarrão' and fonte = 'IBGE' and id_avaliador is null;
