-- Migration 0088: micronutrientes IBGE — lote 8 (frutas soltas, açúcar e mel)
--
-- Continuação do lote 7 no pool abaixo do corte "rigoroso". 20 itens
-- aprovados: frutas sem preparo especificado (banana, laranja, limão,
-- figo, maçã, maracujá, melão, pêssego, ameixa, morango, acerola —
-- primeira vez que aparecem na base, já que os lotes de Frutas da TACO
-- não têm equivalente na IBGE), açúcar, açúcar mascavo e mel.
--
-- "Limão (comum, galego, etc.)" foi mapeado pra lima ácida (Limes, raw)
-- em vez de limão amarelo (lemon) — a lima ácida brasileira (Tahiti,
-- galego) é o produto real por trás do nome, mais próxima em composição
-- de limes do que de lemons.
--
-- Itens que ficaram de fora (sem entrada equivalente segura no USDA):
-- Caju (fruto do cajueiro, não a castanha — não existe entrada
-- separada), Pitanga, Umbu (frutas nativas brasileiras sem equivalente
-- americano), Cuscuz e Cuscuz de tapioca (o "couscous" do USDA é feito
-- de sêmola de trigo; o cuscuz brasileiro é feito de milho ou tapioca —
-- produtos de espécie de grão diferente, usar o couscous de trigo daria
-- dado errado).
--
-- Como sempre: coalesce() preserva os valores já existentes nas 12
-- colunas legadas; as 15 colunas novas (migration 0054) recebem o valor
-- USDA diretamente.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 5), ferro_mg = coalesce(ferro_mg, 0.26), magnesio_mg = 27, fosforo_mg = 22, potassio_mg = 358, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.15), cobre_mcg = 78, manganes_mg = 0.27, selenio_mcg = 1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.1, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 8.7), tiamina_mg = coalesce(tiamina_mg, 0.031), riboflavina_mg = coalesce(riboflavina_mg, 0.073), niacina_mg = coalesce(niacina_mg, 0.665), acido_pantotenico_mg = 0.334, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.367), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 9.8, vitamina_k_mcg = 0.5, folato_mcg = 20 where nome = 'Banana (ouro, prata, d´água, da terra, etc.)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 5), ferro_mg = coalesce(ferro_mg, 0.26), magnesio_mg = 27, fosforo_mg = 22, potassio_mg = 358, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.15), cobre_mcg = 78, manganes_mg = 0.27, selenio_mcg = 1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.1, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 8.7), tiamina_mg = coalesce(tiamina_mg, 0.031), riboflavina_mg = coalesce(riboflavina_mg, 0.073), niacina_mg = coalesce(niacina_mg, 0.665), acido_pantotenico_mg = 0.334, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.367), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 9.8, vitamina_k_mcg = 0.5, folato_mcg = 20 where nome = 'Banana (ouro, prata, d´água, da terra, etc.), Mingau' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 5), ferro_mg = coalesce(ferro_mg, 0.26), magnesio_mg = 27, fosforo_mg = 22, potassio_mg = 358, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.15), cobre_mcg = 78, manganes_mg = 0.27, selenio_mcg = 1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.1, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 8.7), tiamina_mg = coalesce(tiamina_mg, 0.031), riboflavina_mg = coalesce(riboflavina_mg, 0.073), niacina_mg = coalesce(niacina_mg, 0.665), acido_pantotenico_mg = 0.334, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.367), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 9.8, vitamina_k_mcg = 0.5, folato_mcg = 20 where nome = 'Banana (ouro, prata, d´água, da terra, etc.), Sopa' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 40), ferro_mg = coalesce(ferro_mg, 0.1), magnesio_mg = 10, fosforo_mg = 14, potassio_mg = 181, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 0.07), cobre_mcg = 45, manganes_mg = 0.025, selenio_mcg = 0.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 11), vitamina_e_mg = 0.18, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 53.2), tiamina_mg = coalesce(tiamina_mg, 0.087), riboflavina_mg = coalesce(riboflavina_mg, 0.04), niacina_mg = coalesce(niacina_mg, 0.282), acido_pantotenico_mg = 0.25, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.06), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 8.4, vitamina_k_mcg = 0, folato_mcg = 30 where nome = 'Laranja (pera, seleta, lima, da terra, etc.)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 33), ferro_mg = coalesce(ferro_mg, 0.6), magnesio_mg = 6, fosforo_mg = 18, potassio_mg = 102, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 0.11), cobre_mcg = 65, manganes_mg = 0.008, selenio_mcg = 0.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.22, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 29.1), tiamina_mg = coalesce(tiamina_mg, 0.03), riboflavina_mg = coalesce(riboflavina_mg, 0.02), niacina_mg = coalesce(niacina_mg, 0.2), acido_pantotenico_mg = 0.217, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.043), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 5.1, vitamina_k_mcg = 0.6, folato_mcg = 8 where nome = 'Limão (comum, galego, etc.)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 35), ferro_mg = coalesce(ferro_mg, 0.37), magnesio_mg = 17, fosforo_mg = 14, potassio_mg = 232, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.15), cobre_mcg = 70, manganes_mg = 0.128, selenio_mcg = 0.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 7), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 2), tiamina_mg = coalesce(tiamina_mg, 0.06), riboflavina_mg = coalesce(riboflavina_mg, 0.05), niacina_mg = coalesce(niacina_mg, 0.4), acido_pantotenico_mg = 0.3, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.113), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 4.7, vitamina_k_mcg = 4.7, folato_mcg = 6 where nome = 'Figo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 0.12), magnesio_mg = 5, fosforo_mg = 11, potassio_mg = 107, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.04), cobre_mcg = 27, manganes_mg = 0.035, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.18, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4.6), tiamina_mg = coalesce(tiamina_mg, 0.017), riboflavina_mg = coalesce(riboflavina_mg, 0.026), niacina_mg = coalesce(niacina_mg, 0.091), acido_pantotenico_mg = 0.061, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.041), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 3.4, vitamina_k_mcg = 2.2, folato_mcg = 3 where nome = 'Maçã' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 0.12), magnesio_mg = 5, fosforo_mg = 11, potassio_mg = 107, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.04), cobre_mcg = 27, manganes_mg = 0.035, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.18, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 4.6), tiamina_mg = coalesce(tiamina_mg, 0.017), riboflavina_mg = coalesce(riboflavina_mg, 0.026), niacina_mg = coalesce(niacina_mg, 0.091), acido_pantotenico_mg = 0.061, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.041), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 3.4, vitamina_k_mcg = 2.2, folato_mcg = 3 where nome = 'Maçã orgânica' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 12), ferro_mg = coalesce(ferro_mg, 1.6), magnesio_mg = 29, fosforo_mg = 68, potassio_mg = 348, sodio_mg = coalesce(sodio_mg, 28), zinco_mg = coalesce(zinco_mg, 0.1), cobre_mcg = 86, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 64), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 30), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0.13), niacina_mg = coalesce(niacina_mg, 1.5), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.1), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 7.6, vitamina_k_mcg = 0.7, folato_mcg = 14 where nome = 'Maracujá' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 9), ferro_mg = coalesce(ferro_mg, 0.21), magnesio_mg = 12, fosforo_mg = 15, potassio_mg = 267, sodio_mg = coalesce(sodio_mg, 16), zinco_mg = coalesce(zinco_mg, 0.18), cobre_mcg = 41, manganes_mg = 0.041, selenio_mcg = 0.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 169), vitamina_e_mg = 0.05, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 36.7), tiamina_mg = coalesce(tiamina_mg, 0.041), riboflavina_mg = coalesce(riboflavina_mg, 0.019), niacina_mg = coalesce(niacina_mg, 0.734), acido_pantotenico_mg = 0.105, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.072), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 7.6, vitamina_k_mcg = 2.5, folato_mcg = 21 where nome = 'Melão' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 0.25), magnesio_mg = 9, fosforo_mg = 20, potassio_mg = 190, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 0.17), cobre_mcg = 68, manganes_mg = 0.061, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 16), vitamina_e_mg = 0.73, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 6.6), tiamina_mg = coalesce(tiamina_mg, 0.024), riboflavina_mg = coalesce(riboflavina_mg, 0.031), niacina_mg = coalesce(niacina_mg, 0.806), acido_pantotenico_mg = 0.153, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.025), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.1, vitamina_k_mcg = 2.6, folato_mcg = 4 where nome = 'Pêssego' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 0.17), magnesio_mg = 7, fosforo_mg = 16, potassio_mg = 157, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 0.1), cobre_mcg = 57, manganes_mg = 0.052, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 17), vitamina_e_mg = 0.26, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 9.5), tiamina_mg = coalesce(tiamina_mg, 0.028), riboflavina_mg = coalesce(riboflavina_mg, 0.026), niacina_mg = coalesce(niacina_mg, 0.417), acido_pantotenico_mg = 0.135, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.029), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 1.9, vitamina_k_mcg = 6.4, folato_mcg = 5 where nome = 'Ameixa' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 16), ferro_mg = coalesce(ferro_mg, 0.41), magnesio_mg = 13, fosforo_mg = 24, potassio_mg = 153, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.14), cobre_mcg = 48, manganes_mg = 0.386, selenio_mcg = 0.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1), vitamina_e_mg = 0.29, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 58.8), tiamina_mg = coalesce(tiamina_mg, 0.024), riboflavina_mg = coalesce(riboflavina_mg, 0.022), niacina_mg = coalesce(niacina_mg, 0.386), acido_pantotenico_mg = 0.125, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.047), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 5.7, vitamina_k_mcg = 2.2, folato_mcg = 24 where nome = 'Morango' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 12), ferro_mg = coalesce(ferro_mg, 0.2), magnesio_mg = 18, fosforo_mg = 11, potassio_mg = 146, sodio_mg = coalesce(sodio_mg, 7), zinco_mg = coalesce(zinco_mg, 0.1), cobre_mcg = 86, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 38), vitamina_c_mg = coalesce(vitamina_c_mg, 1677.6), tiamina_mg = coalesce(tiamina_mg, 0.02), riboflavina_mg = coalesce(riboflavina_mg, 0.06), niacina_mg = coalesce(niacina_mg, 0.4), acido_pantotenico_mg = 0.309, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.009), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 14 where nome = 'Acerola' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 12), ferro_mg = coalesce(ferro_mg, 0.2), magnesio_mg = 18, fosforo_mg = 11, potassio_mg = 146, sodio_mg = coalesce(sodio_mg, 7), zinco_mg = coalesce(zinco_mg, 0.1), cobre_mcg = 86, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 38), vitamina_c_mg = coalesce(vitamina_c_mg, 1677.6), tiamina_mg = coalesce(tiamina_mg, 0.02), riboflavina_mg = coalesce(riboflavina_mg, 0.06), niacina_mg = coalesce(niacina_mg, 0.4), acido_pantotenico_mg = 0.309, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.009), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), folato_mcg = 14 where nome = 'Acerola orgânica' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1), ferro_mg = coalesce(ferro_mg, 0.05), magnesio_mg = 0, fosforo_mg = 0, potassio_mg = 2, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.01), cobre_mcg = 7, manganes_mg = 0.004, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0.019), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Açúcar' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1), ferro_mg = coalesce(ferro_mg, 0.05), magnesio_mg = 0, fosforo_mg = 0, potassio_mg = 2, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.01), cobre_mcg = 7, manganes_mg = 0.004, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0.019), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Açúcar light' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 83), ferro_mg = coalesce(ferro_mg, 0.71), magnesio_mg = 9, fosforo_mg = 4, potassio_mg = 133, sodio_mg = coalesce(sodio_mg, 28), zinco_mg = coalesce(zinco_mg, 0.03), cobre_mcg = 47, manganes_mg = 0.064, selenio_mcg = 1.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0.11), acido_pantotenico_mg = 0.132, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.041), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 2.3, vitamina_k_mcg = 0, folato_mcg = 1 where nome = 'Açúcar mascavo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 0.42), magnesio_mg = 2, fosforo_mg = 4, potassio_mg = 52, sodio_mg = coalesce(sodio_mg, 4), zinco_mg = coalesce(zinco_mg, 0.22), cobre_mcg = 36, manganes_mg = 0.08, selenio_mcg = 0.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.5), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0.038), niacina_mg = coalesce(niacina_mg, 0.121), acido_pantotenico_mg = 0.068, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.024), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 2.2, vitamina_k_mcg = 0, folato_mcg = 2 where nome = 'Mel' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 78), ferro_mg = coalesce(ferro_mg, 0.97), magnesio_mg = 110, fosforo_mg = 308, potassio_mg = 407, sodio_mg = coalesce(sodio_mg, 156), zinco_mg = coalesce(zinco_mg, 3.94), cobre_mcg = 774, manganes_mg = 1.243, selenio_mcg = 4.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 4.1, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.1), riboflavina_mg = coalesce(riboflavina_mg, 0.14), niacina_mg = coalesce(niacina_mg, 7.922), acido_pantotenico_mg = 0.83, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.153), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 29.4, vitamina_k_mcg = 0, folato_mcg = 75 where nome = 'Doce de amendoim' and fonte = 'IBGE' and id_avaliador is null;
