-- Migration 0089: micronutrientes IBGE — lote 9 (molhos/condimentos e mais cortes bovinos)
--
-- Continuação do pool abaixo do corte "rigoroso". 19 itens aprovados:
-- molho de soja (shoyu), leite de coco, molho/massa/caldo de tomate,
-- gergelim, e mais cortes de carne bovina que não tinham entrado nos
-- lotes 3/9 anteriores (acém, paleta, bisteca, os preparos que faltavam
-- de músculo bovino).
--
-- Erros corrigidos: Massa de tomate batia com "Pasta, dry" (massa de
-- MACARRÃO, não extrato de tomate) — corrigida pra tomato paste de
-- verdade. Acém/Paleta/Bisteca bovina batiam com bisão (Game meat,
-- bison), avestruz-relacionados ou vísceras — corrigidos pro mesmo corte
-- de chuck genérico já usado como aproximação de "carne bovina" na
-- migration 0077.
--
-- Como sempre: coalesce() preserva os valores já existentes nas 12
-- colunas legadas; as 15 colunas novas (migration 0054) recebem o valor
-- USDA diretamente.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 33), ferro_mg = coalesce(ferro_mg, 1.45), magnesio_mg = 74, fosforo_mg = 166, potassio_mg = 435, sodio_mg = coalesce(sodio_mg, 5493), zinco_mg = coalesce(zinco_mg, 0.87), cobre_mcg = 43, manganes_mg = 1.018, selenio_mcg = 0.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.033), riboflavina_mg = coalesce(riboflavina_mg, 0.165), niacina_mg = coalesce(niacina_mg, 2.196), acido_pantotenico_mg = 0.297, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.148), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 18.3, vitamina_k_mcg = 0, folato_mcg = 14 where nome = 'Molho de soja' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 33), ferro_mg = coalesce(ferro_mg, 1.45), magnesio_mg = 74, fosforo_mg = 166, potassio_mg = 435, sodio_mg = coalesce(sodio_mg, 5493), zinco_mg = coalesce(zinco_mg, 0.87), cobre_mcg = 43, manganes_mg = 1.018, selenio_mcg = 0.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.033), riboflavina_mg = coalesce(riboflavina_mg, 0.165), niacina_mg = coalesce(niacina_mg, 2.196), acido_pantotenico_mg = 0.297, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.148), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 18.3, vitamina_k_mcg = 0, folato_mcg = 14 where nome = 'Molho de soja light' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 16), ferro_mg = coalesce(ferro_mg, 1.64), magnesio_mg = 37, fosforo_mg = 100, potassio_mg = 263, sodio_mg = coalesce(sodio_mg, 15), zinco_mg = coalesce(zinco_mg, 0.67), cobre_mcg = 266, manganes_mg = 0.916, selenio_mcg = 6.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.15, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 2.8), tiamina_mg = coalesce(tiamina_mg, 0.026), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0.76), acido_pantotenico_mg = 0.183, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.033), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 8.5, vitamina_k_mcg = 0.1, folato_mcg = 16 where nome = 'Leite de coco' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 16), ferro_mg = coalesce(ferro_mg, 1.64), magnesio_mg = 37, fosforo_mg = 100, potassio_mg = 263, sodio_mg = coalesce(sodio_mg, 15), zinco_mg = coalesce(zinco_mg, 0.67), cobre_mcg = 266, manganes_mg = 0.916, selenio_mcg = 6.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.15, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 2.8), tiamina_mg = coalesce(tiamina_mg, 0.026), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0.76), acido_pantotenico_mg = 0.183, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.033), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 8.5, vitamina_k_mcg = 0.1, folato_mcg = 16 where nome = 'Leite de coco light' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 14), ferro_mg = coalesce(ferro_mg, 0.96), magnesio_mg = 15, fosforo_mg = 27, potassio_mg = 297, sodio_mg = coalesce(sodio_mg, 474), zinco_mg = coalesce(zinco_mg, 0.22), cobre_mcg = 115, manganes_mg = 0.113, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 22), vitamina_e_mg = 1.44, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 7), tiamina_mg = coalesce(tiamina_mg, 0.024), riboflavina_mg = coalesce(riboflavina_mg, 0.065), niacina_mg = coalesce(niacina_mg, 0.991), acido_pantotenico_mg = 0.309, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.098), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 9.9, vitamina_k_mcg = 2.8, folato_mcg = 9 where nome = 'Molho de tomate' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 36), ferro_mg = coalesce(ferro_mg, 2.98), magnesio_mg = 42, fosforo_mg = 83, potassio_mg = 1014, sodio_mg = coalesce(sodio_mg, 59), zinco_mg = coalesce(zinco_mg, 0.63), cobre_mcg = 365, manganes_mg = 0.302, selenio_mcg = 5.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 76), vitamina_e_mg = 4.3, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 21.9), tiamina_mg = coalesce(tiamina_mg, 0.06), riboflavina_mg = coalesce(riboflavina_mg, 0.153), niacina_mg = coalesce(niacina_mg, 3.076), acido_pantotenico_mg = 0.142, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.216), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 38.5, vitamina_k_mcg = 11.4, folato_mcg = 12 where nome = 'Massa de tomate' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 14), ferro_mg = coalesce(ferro_mg, 0.96), magnesio_mg = 15, fosforo_mg = 27, potassio_mg = 297, sodio_mg = coalesce(sodio_mg, 474), zinco_mg = coalesce(zinco_mg, 0.22), cobre_mcg = 115, manganes_mg = 0.113, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 22), vitamina_e_mg = 1.44, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 7), tiamina_mg = coalesce(tiamina_mg, 0.024), riboflavina_mg = coalesce(riboflavina_mg, 0.065), niacina_mg = coalesce(niacina_mg, 0.991), acido_pantotenico_mg = 0.309, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.098), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 9.9, vitamina_k_mcg = 2.8, folato_mcg = 9 where nome = 'Caldo de tomate' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 975), ferro_mg = coalesce(ferro_mg, 14.55), magnesio_mg = 351, fosforo_mg = 629, potassio_mg = 468, sodio_mg = coalesce(sodio_mg, 11), zinco_mg = coalesce(zinco_mg, 7.75), cobre_mcg = 4082, manganes_mg = 2.46, selenio_mcg = 34.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.25, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.791), riboflavina_mg = coalesce(riboflavina_mg, 0.247), niacina_mg = coalesce(niacina_mg, 4.515), acido_pantotenico_mg = 0.05, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.79), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 25.6, vitamina_k_mcg = 0, folato_mcg = 97 where nome = 'Gergelim' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 2.53), magnesio_mg = 20, fosforo_mg = 183, potassio_mg = 242, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 6.98), cobre_mcg = 104, manganes_mg = 0.01, selenio_mcg = 28.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.53, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.061), riboflavina_mg = coalesce(riboflavina_mg, 0.178), niacina_mg = coalesce(niacina_mg, 4.273), acido_pantotenico_mg = 0.594, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.295), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.22), colina_mg = 114.7, vitamina_k_mcg = 1.9, folato_mcg = 9 where nome = 'Acém, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 2.53), magnesio_mg = 20, fosforo_mg = 183, potassio_mg = 242, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 6.98), cobre_mcg = 104, manganes_mg = 0.01, selenio_mcg = 28.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.53, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.061), riboflavina_mg = coalesce(riboflavina_mg, 0.178), niacina_mg = coalesce(niacina_mg, 4.273), acido_pantotenico_mg = 0.594, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.295), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.22), colina_mg = 114.7, vitamina_k_mcg = 1.9, folato_mcg = 9 where nome = 'Acém, Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 2.53), magnesio_mg = 20, fosforo_mg = 183, potassio_mg = 242, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 6.98), cobre_mcg = 104, manganes_mg = 0.01, selenio_mcg = 28.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.53, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.061), riboflavina_mg = coalesce(riboflavina_mg, 0.178), niacina_mg = coalesce(niacina_mg, 4.273), acido_pantotenico_mg = 0.594, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.295), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.22), colina_mg = 114.7, vitamina_k_mcg = 1.9, folato_mcg = 9 where nome = 'Acém, Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 2.53), magnesio_mg = 20, fosforo_mg = 183, potassio_mg = 242, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 6.98), cobre_mcg = 104, manganes_mg = 0.01, selenio_mcg = 28.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.53, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.061), riboflavina_mg = coalesce(riboflavina_mg, 0.178), niacina_mg = coalesce(niacina_mg, 4.273), acido_pantotenico_mg = 0.594, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.295), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.22), colina_mg = 114.7, vitamina_k_mcg = 1.9, folato_mcg = 9 where nome = 'Paleta, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 2.53), magnesio_mg = 20, fosforo_mg = 183, potassio_mg = 242, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 6.98), cobre_mcg = 104, manganes_mg = 0.01, selenio_mcg = 28.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.53, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.061), riboflavina_mg = coalesce(riboflavina_mg, 0.178), niacina_mg = coalesce(niacina_mg, 4.273), acido_pantotenico_mg = 0.594, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.295), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.22), colina_mg = 114.7, vitamina_k_mcg = 1.9, folato_mcg = 9 where nome = 'Paleta, Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 1.67), magnesio_mg = 19, fosforo_mg = 174, potassio_mg = 290, sodio_mg = coalesce(sodio_mg, 62), zinco_mg = coalesce(zinco_mg, 4.54), cobre_mcg = 81, manganes_mg = 0.011, selenio_mcg = 20.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.4, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.07), riboflavina_mg = coalesce(riboflavina_mg, 0.139), niacina_mg = coalesce(niacina_mg, 4.331), acido_pantotenico_mg = 0.553, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.456), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.65), colina_mg = 80.3, vitamina_k_mcg = 1.6, folato_mcg = 10 where nome = 'Bisteca bovina, Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 2.53), magnesio_mg = 20, fosforo_mg = 183, potassio_mg = 242, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 6.98), cobre_mcg = 104, manganes_mg = 0.01, selenio_mcg = 28.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.53, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.061), riboflavina_mg = coalesce(riboflavina_mg, 0.178), niacina_mg = coalesce(niacina_mg, 4.273), acido_pantotenico_mg = 0.594, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.295), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.22), colina_mg = 114.7, vitamina_k_mcg = 1.9, folato_mcg = 9 where nome = 'Bisteca bovina, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 2.53), magnesio_mg = 20, fosforo_mg = 183, potassio_mg = 242, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 6.98), cobre_mcg = 104, manganes_mg = 0.01, selenio_mcg = 28.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.53, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.061), riboflavina_mg = coalesce(riboflavina_mg, 0.178), niacina_mg = coalesce(niacina_mg, 4.273), acido_pantotenico_mg = 0.594, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.295), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.22), colina_mg = 114.7, vitamina_k_mcg = 1.9, folato_mcg = 9 where nome = 'Bisteca bovina, Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 2.53), magnesio_mg = 20, fosforo_mg = 183, potassio_mg = 242, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 6.98), cobre_mcg = 104, manganes_mg = 0.01, selenio_mcg = 28.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.53, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.061), riboflavina_mg = coalesce(riboflavina_mg, 0.178), niacina_mg = coalesce(niacina_mg, 4.273), acido_pantotenico_mg = 0.594, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.295), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.22), colina_mg = 114.7, vitamina_k_mcg = 1.9, folato_mcg = 9 where nome = 'Bisteca bovina, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 32), ferro_mg = coalesce(ferro_mg, 3.86), magnesio_mg = 30, fosforo_mg = 263, potassio_mg = 447, sodio_mg = coalesce(sodio_mg, 64), zinco_mg = coalesce(zinco_mg, 10.49), cobre_mcg = 172, manganes_mg = 0.02, selenio_mcg = 30, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.14), riboflavina_mg = coalesce(riboflavina_mg, 0.21), niacina_mg = coalesce(niacina_mg, 5.89), acido_pantotenico_mg = 0.41, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.37), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.79), folato_mcg = 10 where nome = 'Músculo bovino, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 32), ferro_mg = coalesce(ferro_mg, 3.86), magnesio_mg = 30, fosforo_mg = 263, potassio_mg = 447, sodio_mg = coalesce(sodio_mg, 64), zinco_mg = coalesce(zinco_mg, 10.49), cobre_mcg = 172, manganes_mg = 0.02, selenio_mcg = 30, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.14), riboflavina_mg = coalesce(riboflavina_mg, 0.21), niacina_mg = coalesce(niacina_mg, 5.89), acido_pantotenico_mg = 0.41, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.37), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.79), folato_mcg = 10 where nome = 'Músculo bovino, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
