-- Migration 0090: micronutrientes IBGE — lote 10 (carne moída e preparos bovinos/suínos restantes)
--
-- Continuação do pool abaixo do corte "rigoroso". 22 itens aprovados:
-- carne moída em todos os preparos comuns (cru/cozido/refogado/assado/
-- molho vermelho — item de consumo bem frequente, corrigindo alce/urso/
-- peru como espécie errada pra "carne moída" genérica), os preparos que
-- faltavam de fígado/língua/costela bovina (grelhado, assado, molho
-- vermelho — reaproveitando os fdc_ids já verificados nos lotes 3/9),
-- e mais suínos: bisteca/costela/lombo assados (reaproveitando o mesmo
-- corte já usado pro cozido, já que o algoritmo trocava por presunto
-- CURADO assado — produto industrializado, não carne fresca), pernil
-- suíno (cozido/assado/refogado — já era um match razoável, presunto é
-- literalmente pernil), toucinho (corrigido de "Salt, table" — sal de
-- cozinha — pra gordura de porco de verdade) e mais um preparo de carne
-- suína genérica.
--
-- Como sempre: coalesce() preserva os valores já existentes nas 12
-- colunas legadas; as 15 colunas novas (migration 0054) recebem o valor
-- USDA diretamente.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 15), ferro_mg = coalesce(ferro_mg, 2.09), magnesio_mg = 18, fosforo_mg = 171, potassio_mg = 295, sodio_mg = coalesce(sodio_mg, 66), zinco_mg = coalesce(zinco_mg, 4.48), cobre_mcg = 67, manganes_mg = 0.01, selenio_mcg = 15.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 4), vitamina_e_mg = 0.17, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.042), riboflavina_mg = coalesce(riboflavina_mg, 0.151), niacina_mg = coalesce(niacina_mg, 4.649), acido_pantotenico_mg = 0.549, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.346), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.17), colina_mg = 61.2, vitamina_k_mcg = 1.3, folato_mcg = 6 where nome = 'Carne moída, Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 2.93), magnesio_mg = 25, fosforo_mg = 238, potassio_mg = 407, sodio_mg = coalesce(sodio_mg, 89), zinco_mg = coalesce(zinco_mg, 6.62), cobre_mcg = 93, manganes_mg = 0.012, selenio_mcg = 21.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.12, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.044), riboflavina_mg = coalesce(riboflavina_mg, 0.191), niacina_mg = coalesce(niacina_mg, 6.318), acido_pantotenico_mg = 0.807, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.428), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.8), colina_mg = 91.4, vitamina_k_mcg = 1.7, folato_mcg = 10 where nome = 'Carne moída, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 2.93), magnesio_mg = 25, fosforo_mg = 238, potassio_mg = 407, sodio_mg = coalesce(sodio_mg, 89), zinco_mg = coalesce(zinco_mg, 6.62), cobre_mcg = 93, manganes_mg = 0.012, selenio_mcg = 21.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.12, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.044), riboflavina_mg = coalesce(riboflavina_mg, 0.191), niacina_mg = coalesce(niacina_mg, 6.318), acido_pantotenico_mg = 0.807, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.428), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.8), colina_mg = 91.4, vitamina_k_mcg = 1.7, folato_mcg = 10 where nome = 'Carne moída, Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 18), ferro_mg = coalesce(ferro_mg, 2.74), magnesio_mg = 20, fosforo_mg = 186, potassio_mg = 286, sodio_mg = coalesce(sodio_mg, 64), zinco_mg = coalesce(zinco_mg, 6.45), cobre_mcg = 79, manganes_mg = 0.01, selenio_mcg = 21, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.12, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.04), riboflavina_mg = coalesce(riboflavina_mg, 0.171), niacina_mg = coalesce(niacina_mg, 4.927), acido_pantotenico_mg = 0.598, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.338), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.49), colina_mg = 85.5, vitamina_k_mcg = 1.6, folato_mcg = 6 where nome = 'Carne moída, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 2.93), magnesio_mg = 25, fosforo_mg = 238, potassio_mg = 407, sodio_mg = coalesce(sodio_mg, 89), zinco_mg = coalesce(zinco_mg, 6.62), cobre_mcg = 93, manganes_mg = 0.012, selenio_mcg = 21.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.12, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.044), riboflavina_mg = coalesce(riboflavina_mg, 0.191), niacina_mg = coalesce(niacina_mg, 6.318), acido_pantotenico_mg = 0.807, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.428), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.8), colina_mg = 91.4, vitamina_k_mcg = 1.7, folato_mcg = 10 where nome = 'Carne moída, Molho vermelho' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 6.54), magnesio_mg = 21, fosforo_mg = 497, potassio_mg = 352, sodio_mg = coalesce(sodio_mg, 79), zinco_mg = coalesce(zinco_mg, 5.3), cobre_mcg = 14283, manganes_mg = 0.356, selenio_mcg = 36.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 9442), vitamina_e_mg = 0.51, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.2), vitamina_c_mg = coalesce(vitamina_c_mg, 1.9), tiamina_mg = coalesce(tiamina_mg, 0.194), riboflavina_mg = coalesce(riboflavina_mg, 3.425), niacina_mg = coalesce(niacina_mg, 17.525), acido_pantotenico_mg = 7.11, vitamina_b6_mg = coalesce(vitamina_b6_mg, 1.017), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 70.58), colina_mg = 426, vitamina_k_mcg = 3.3, folato_mcg = 253 where nome = 'Fígado bovino, Grelhado(a)/brasa/churrasco' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 6.54), magnesio_mg = 21, fosforo_mg = 497, potassio_mg = 352, sodio_mg = coalesce(sodio_mg, 79), zinco_mg = coalesce(zinco_mg, 5.3), cobre_mcg = 14283, manganes_mg = 0.356, selenio_mcg = 36.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 9442), vitamina_e_mg = 0.51, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.2), vitamina_c_mg = coalesce(vitamina_c_mg, 1.9), tiamina_mg = coalesce(tiamina_mg, 0.194), riboflavina_mg = coalesce(riboflavina_mg, 3.425), niacina_mg = coalesce(niacina_mg, 17.525), acido_pantotenico_mg = 7.11, vitamina_b6_mg = coalesce(vitamina_b6_mg, 1.017), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 70.58), colina_mg = 426, vitamina_k_mcg = 3.3, folato_mcg = 253 where nome = 'Fígado bovino, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 6.54), magnesio_mg = 21, fosforo_mg = 497, potassio_mg = 352, sodio_mg = coalesce(sodio_mg, 79), zinco_mg = coalesce(zinco_mg, 5.3), cobre_mcg = 14283, manganes_mg = 0.356, selenio_mcg = 36.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 9442), vitamina_e_mg = 0.51, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.2), vitamina_c_mg = coalesce(vitamina_c_mg, 1.9), tiamina_mg = coalesce(tiamina_mg, 0.194), riboflavina_mg = coalesce(riboflavina_mg, 3.425), niacina_mg = coalesce(niacina_mg, 17.525), acido_pantotenico_mg = 7.11, vitamina_b6_mg = coalesce(vitamina_b6_mg, 1.017), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 70.58), colina_mg = 426, vitamina_k_mcg = 3.3, folato_mcg = 253 where nome = 'Fígado bovino, Molho vermelho' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 5), ferro_mg = coalesce(ferro_mg, 2.52), magnesio_mg = 17, fosforo_mg = 157, potassio_mg = 189, sodio_mg = coalesce(sodio_mg, 57), zinco_mg = coalesce(zinco_mg, 4.2), cobre_mcg = 163, manganes_mg = 0.013, selenio_mcg = 3.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 12), vitamina_e_mg = 0.95, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.059), riboflavina_mg = coalesce(riboflavina_mg, 0.227), niacina_mg = coalesce(niacina_mg, 2.58), acido_pantotenico_mg = 0.709, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.072), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.95) where nome = 'Língua bovina, Grelhado(a)/brasa/churrasco' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 5), ferro_mg = coalesce(ferro_mg, 2.52), magnesio_mg = 17, fosforo_mg = 157, potassio_mg = 189, sodio_mg = coalesce(sodio_mg, 57), zinco_mg = coalesce(zinco_mg, 4.2), cobre_mcg = 163, manganes_mg = 0.013, selenio_mcg = 3.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 12), vitamina_e_mg = 0.95, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.059), riboflavina_mg = coalesce(riboflavina_mg, 0.227), niacina_mg = coalesce(niacina_mg, 2.58), acido_pantotenico_mg = 0.709, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.072), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.95) where nome = 'Língua bovina, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 5), ferro_mg = coalesce(ferro_mg, 2.52), magnesio_mg = 17, fosforo_mg = 157, potassio_mg = 189, sodio_mg = coalesce(sodio_mg, 57), zinco_mg = coalesce(zinco_mg, 4.2), cobre_mcg = 163, manganes_mg = 0.013, selenio_mcg = 3.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 12), vitamina_e_mg = 0.95, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.059), riboflavina_mg = coalesce(riboflavina_mg, 0.227), niacina_mg = coalesce(niacina_mg, 2.58), acido_pantotenico_mg = 0.709, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.072), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.95) where nome = 'Língua bovina, Molho vermelho' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 3.36), magnesio_mg = 22, fosforo_mg = 235, potassio_mg = 313, sodio_mg = coalesce(sodio_mg, 58), zinco_mg = coalesce(zinco_mg, 7.8), cobre_mcg = 107, manganes_mg = 0.018, selenio_mcg = 22.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.14, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.065), riboflavina_mg = coalesce(riboflavina_mg, 0.202), niacina_mg = coalesce(niacina_mg, 3.208), acido_pantotenico_mg = 0.337, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.28), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.46), colina_mg = 117.2, vitamina_k_mcg = 1.9, folato_mcg = 7 where nome = 'Costela bovina, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 49), ferro_mg = coalesce(ferro_mg, 0.85), magnesio_mg = 20, fosforo_mg = 224, potassio_mg = 270, sodio_mg = coalesce(sodio_mg, 70), zinco_mg = coalesce(zinco_mg, 3.28), cobre_mcg = 97, manganes_mg = 0.012, selenio_mcg = 44.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.9), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.507), riboflavina_mg = coalesce(riboflavina_mg, 0.332), niacina_mg = coalesce(niacina_mg, 7.604), acido_pantotenico_mg = 0.968, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.515), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.61), colina_mg = 86, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Bisteca suína, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 49), ferro_mg = coalesce(ferro_mg, 0.85), magnesio_mg = 20, fosforo_mg = 224, potassio_mg = 270, sodio_mg = coalesce(sodio_mg, 70), zinco_mg = coalesce(zinco_mg, 3.28), cobre_mcg = 97, manganes_mg = 0.012, selenio_mcg = 44.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.9), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.507), riboflavina_mg = coalesce(riboflavina_mg, 0.332), niacina_mg = coalesce(niacina_mg, 7.604), acido_pantotenico_mg = 0.968, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.515), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.61), colina_mg = 86, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Bisteca suína' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 8), ferro_mg = coalesce(ferro_mg, 1.37), magnesio_mg = 21, fosforo_mg = 265, potassio_mg = 386, sodio_mg = coalesce(sodio_mg, 969), zinco_mg = coalesce(zinco_mg, 2.55), cobre_mcg = 132, selenio_mcg = 19.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.28, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.8), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.73), riboflavina_mg = coalesce(riboflavina_mg, 0.31), niacina_mg = coalesce(niacina_mg, 5.74), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.33), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.69), colina_mg = 87.2, vitamina_k_mcg = 0, folato_mcg = 3 where nome = 'Pernil suíno, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7), ferro_mg = coalesce(ferro_mg, 0.94), magnesio_mg = 22, fosforo_mg = 227, potassio_mg = 316, sodio_mg = coalesce(sodio_mg, 1327), zinco_mg = coalesce(zinco_mg, 2.57), cobre_mcg = 87, manganes_mg = 0.016, selenio_mcg = 25.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.26, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.9), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.68), riboflavina_mg = coalesce(riboflavina_mg, 0.254), niacina_mg = coalesce(niacina_mg, 5.02), acido_pantotenico_mg = 0.498, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.47), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.7), colina_mg = 101.9, vitamina_k_mcg = 0, folato_mcg = 4 where nome = 'Pernil suíno, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 8), ferro_mg = coalesce(ferro_mg, 1.37), magnesio_mg = 21, fosforo_mg = 265, potassio_mg = 386, sodio_mg = coalesce(sodio_mg, 969), zinco_mg = coalesce(zinco_mg, 2.55), cobre_mcg = 132, selenio_mcg = 19.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.28, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.8), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.73), riboflavina_mg = coalesce(riboflavina_mg, 0.31), niacina_mg = coalesce(niacina_mg, 5.74), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.33), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.69), colina_mg = 87.2, vitamina_k_mcg = 0, folato_mcg = 3 where nome = 'Pernil suíno, Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 33), ferro_mg = coalesce(ferro_mg, 1.39), magnesio_mg = 23, fosforo_mg = 208, potassio_mg = 297, sodio_mg = coalesce(sodio_mg, 60), zinco_mg = coalesce(zinco_mg, 4.46), cobre_mcg = 105, manganes_mg = 0.011, selenio_mcg = 48.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.477), riboflavina_mg = coalesce(riboflavina_mg, 0.296), niacina_mg = coalesce(niacina_mg, 5.715), acido_pantotenico_mg = 1.427, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.491), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.94), colina_mg = 113.5, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Costela suína, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 33), ferro_mg = coalesce(ferro_mg, 1.39), magnesio_mg = 23, fosforo_mg = 208, potassio_mg = 297, sodio_mg = coalesce(sodio_mg, 60), zinco_mg = coalesce(zinco_mg, 4.46), cobre_mcg = 105, manganes_mg = 0.011, selenio_mcg = 48.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.477), riboflavina_mg = coalesce(riboflavina_mg, 0.296), niacina_mg = coalesce(niacina_mg, 5.715), acido_pantotenico_mg = 1.427, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.491), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.94), colina_mg = 113.5, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Costela suína' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 18), ferro_mg = coalesce(ferro_mg, 1.13), magnesio_mg = 20, fosforo_mg = 183, potassio_mg = 387, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 2.48), cobre_mcg = 79, manganes_mg = 0.013, selenio_mcg = 48.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.21, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.8), vitamina_c_mg = coalesce(vitamina_c_mg, 0.6), tiamina_mg = coalesce(tiamina_mg, 0.659), riboflavina_mg = coalesce(riboflavina_mg, 0.267), niacina_mg = coalesce(niacina_mg, 4.588), acido_pantotenico_mg = 0.677, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.387), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.55), colina_mg = 98.2, vitamina_k_mcg = 0, folato_mcg = 4 where nome = 'Lombo suíno, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 14), ferro_mg = coalesce(ferro_mg, 0.26), magnesio_mg = 6, fosforo_mg = 84, potassio_mg = 333, sodio_mg = coalesce(sodio_mg, 47), zinco_mg = coalesce(zinco_mg, 0.6), cobre_mcg = 67, manganes_mg = 0, selenio_mcg = 9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 26), vitamina_e_mg = 0.42, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.16), riboflavina_mg = coalesce(riboflavina_mg, 0.09), niacina_mg = coalesce(niacina_mg, 2.63), acido_pantotenico_mg = 0.43, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.143), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.67), colina_mg = 31, vitamina_k_mcg = 0, folato_mcg = 0 where nome = 'Toucinho' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 20), ferro_mg = coalesce(ferro_mg, 1.11), magnesio_mg = 24, fosforo_mg = 221, potassio_mg = 341, sodio_mg = coalesce(sodio_mg, 57), zinco_mg = coalesce(zinco_mg, 3.06), cobre_mcg = 90, manganes_mg = 0.01, selenio_mcg = 42, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.13, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.9), vitamina_c_mg = coalesce(vitamina_c_mg, 0.1), tiamina_mg = coalesce(tiamina_mg, 0.611), riboflavina_mg = coalesce(riboflavina_mg, 0.29), niacina_mg = coalesce(niacina_mg, 6.047), acido_pantotenico_mg = 0.844, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.542), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.7), colina_mg = 80.1, vitamina_k_mcg = 0, folato_mcg = 2 where nome = 'Carne suína, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
