-- Migration 0091: micronutrientes IBGE — lote 11 (carne caprina/ovina e preparos restantes de carne moída)
--
-- Continuação do pool abaixo do corte "rigoroso". 26 itens aprovados:
-- carne caprina (cabrito, bode, caprino/caprina — todos sinônimos
-- regionais de carne de cabra no Brasil) e carne ovina (carneiro,
-- ovelha), usando "Game meat, goat" e "Lamb, ground" do USDA — o
-- algoritmo batia sistematicamente com urso, peru ou frango, todos sem
-- relação com cabra/carneiro. Também os preparos restantes de carne
-- moída (molho branco, ao alho e óleo, ensopado, sopa, bare) e dois
-- itens suínos avulsos (língua suína assada, pernil cozido).
--
-- Itens que ficaram de fora (sem equivalente no USDA — caças silvestres
-- brasileiras específicas, não criadas comercialmente nos EUA): Carne da
-- paca, Carne de jacaré, Carne de capivara, Carne de cotia, Carne de
-- jabuti, Carne de outros animais (espécie genérica não identificável).
--
-- Como sempre: coalesce() preserva os valores já existentes nas 12
-- colunas legadas; as 15 colunas novas (migration 0054) recebem o valor
-- USDA diretamente.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 2.93), magnesio_mg = 25, fosforo_mg = 238, potassio_mg = 407, sodio_mg = coalesce(sodio_mg, 89), zinco_mg = coalesce(zinco_mg, 6.62), cobre_mcg = 93, manganes_mg = 0.012, selenio_mcg = 21.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.12, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.044), riboflavina_mg = coalesce(riboflavina_mg, 0.191), niacina_mg = coalesce(niacina_mg, 6.318), acido_pantotenico_mg = 0.807, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.428), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.8), colina_mg = 91.4, vitamina_k_mcg = 1.7, folato_mcg = 10 where nome = 'Carne moída, Molho branco' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 2.93), magnesio_mg = 25, fosforo_mg = 238, potassio_mg = 407, sodio_mg = coalesce(sodio_mg, 89), zinco_mg = coalesce(zinco_mg, 6.62), cobre_mcg = 93, manganes_mg = 0.012, selenio_mcg = 21.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.12, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.044), riboflavina_mg = coalesce(riboflavina_mg, 0.191), niacina_mg = coalesce(niacina_mg, 6.318), acido_pantotenico_mg = 0.807, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.428), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.8), colina_mg = 91.4, vitamina_k_mcg = 1.7, folato_mcg = 10 where nome = 'Carne moída, Ao alho e óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 2.93), magnesio_mg = 25, fosforo_mg = 238, potassio_mg = 407, sodio_mg = coalesce(sodio_mg, 89), zinco_mg = coalesce(zinco_mg, 6.62), cobre_mcg = 93, manganes_mg = 0.012, selenio_mcg = 21.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.12, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.044), riboflavina_mg = coalesce(riboflavina_mg, 0.191), niacina_mg = coalesce(niacina_mg, 6.318), acido_pantotenico_mg = 0.807, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.428), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.8), colina_mg = 91.4, vitamina_k_mcg = 1.7, folato_mcg = 10 where nome = 'Carne moída, Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 2.93), magnesio_mg = 25, fosforo_mg = 238, potassio_mg = 407, sodio_mg = coalesce(sodio_mg, 89), zinco_mg = coalesce(zinco_mg, 6.62), cobre_mcg = 93, manganes_mg = 0.012, selenio_mcg = 21.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 3), vitamina_e_mg = 0.12, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.044), riboflavina_mg = coalesce(riboflavina_mg, 0.191), niacina_mg = coalesce(niacina_mg, 6.318), acido_pantotenico_mg = 0.807, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.428), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.8), colina_mg = 91.4, vitamina_k_mcg = 1.7, folato_mcg = 10 where nome = 'Carne moída, Sopa' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 15), ferro_mg = coalesce(ferro_mg, 2.09), magnesio_mg = 18, fosforo_mg = 171, potassio_mg = 295, sodio_mg = coalesce(sodio_mg, 66), zinco_mg = coalesce(zinco_mg, 4.48), cobre_mcg = 67, manganes_mg = 0.01, selenio_mcg = 15.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 4), vitamina_e_mg = 0.17, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.042), riboflavina_mg = coalesce(riboflavina_mg, 0.151), niacina_mg = coalesce(niacina_mg, 4.649), acido_pantotenico_mg = 0.549, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.346), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.17), colina_mg = 61.2, vitamina_k_mcg = 1.3, folato_mcg = 6 where nome = 'Carne moída' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 3.73), magnesio_mg = 0, fosforo_mg = 201, potassio_mg = 405, sodio_mg = coalesce(sodio_mg, 86), zinco_mg = coalesce(zinco_mg, 5.27), cobre_mcg = 303, manganes_mg = 0.042, selenio_mcg = 11.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.34, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.61), niacina_mg = coalesce(niacina_mg, 3.95), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.19), colina_mg = 106.4, vitamina_k_mcg = 1.2, folato_mcg = 5 where nome = 'Carne de cabrito, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 3.73), magnesio_mg = 0, fosforo_mg = 201, potassio_mg = 405, sodio_mg = coalesce(sodio_mg, 86), zinco_mg = coalesce(zinco_mg, 5.27), cobre_mcg = 303, manganes_mg = 0.042, selenio_mcg = 11.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.34, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.61), niacina_mg = coalesce(niacina_mg, 3.95), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.19), colina_mg = 106.4, vitamina_k_mcg = 1.2, folato_mcg = 5 where nome = 'Carne de cabrito, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 3.73), magnesio_mg = 0, fosforo_mg = 201, potassio_mg = 405, sodio_mg = coalesce(sodio_mg, 86), zinco_mg = coalesce(zinco_mg, 5.27), cobre_mcg = 303, manganes_mg = 0.042, selenio_mcg = 11.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.34, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.61), niacina_mg = coalesce(niacina_mg, 3.95), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.19), colina_mg = 106.4, vitamina_k_mcg = 1.2, folato_mcg = 5 where nome = 'Carne de bode, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 3.73), magnesio_mg = 0, fosforo_mg = 201, potassio_mg = 405, sodio_mg = coalesce(sodio_mg, 86), zinco_mg = coalesce(zinco_mg, 5.27), cobre_mcg = 303, manganes_mg = 0.042, selenio_mcg = 11.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.34, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.61), niacina_mg = coalesce(niacina_mg, 3.95), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.19), colina_mg = 106.4, vitamina_k_mcg = 1.2, folato_mcg = 5 where nome = 'Carne de bode, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 3.73), magnesio_mg = 0, fosforo_mg = 201, potassio_mg = 405, sodio_mg = coalesce(sodio_mg, 86), zinco_mg = coalesce(zinco_mg, 5.27), cobre_mcg = 303, manganes_mg = 0.042, selenio_mcg = 11.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.34, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.61), niacina_mg = coalesce(niacina_mg, 3.95), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.19), colina_mg = 106.4, vitamina_k_mcg = 1.2, folato_mcg = 5 where nome = 'Carne de bode, Frito(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 3.73), magnesio_mg = 0, fosforo_mg = 201, potassio_mg = 405, sodio_mg = coalesce(sodio_mg, 86), zinco_mg = coalesce(zinco_mg, 5.27), cobre_mcg = 303, manganes_mg = 0.042, selenio_mcg = 11.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.34, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.61), niacina_mg = coalesce(niacina_mg, 3.95), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.19), colina_mg = 106.4, vitamina_k_mcg = 1.2, folato_mcg = 5 where nome = 'Carne caprina, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 3.73), magnesio_mg = 0, fosforo_mg = 201, potassio_mg = 405, sodio_mg = coalesce(sodio_mg, 86), zinco_mg = coalesce(zinco_mg, 5.27), cobre_mcg = 303, manganes_mg = 0.042, selenio_mcg = 11.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.34, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.61), niacina_mg = coalesce(niacina_mg, 3.95), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.19), colina_mg = 106.4, vitamina_k_mcg = 1.2, folato_mcg = 5 where nome = 'Carne caprina, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 3.73), magnesio_mg = 0, fosforo_mg = 201, potassio_mg = 405, sodio_mg = coalesce(sodio_mg, 86), zinco_mg = coalesce(zinco_mg, 5.27), cobre_mcg = 303, manganes_mg = 0.042, selenio_mcg = 11.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.34, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.61), niacina_mg = coalesce(niacina_mg, 3.95), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.19), colina_mg = 106.4, vitamina_k_mcg = 1.2, folato_mcg = 5 where nome = 'Carne caprina, Frito(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 3.73), magnesio_mg = 0, fosforo_mg = 201, potassio_mg = 405, sodio_mg = coalesce(sodio_mg, 86), zinco_mg = coalesce(zinco_mg, 5.27), cobre_mcg = 303, manganes_mg = 0.042, selenio_mcg = 11.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.34, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.61), niacina_mg = coalesce(niacina_mg, 3.95), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.19), colina_mg = 106.4, vitamina_k_mcg = 1.2, folato_mcg = 5 where nome = 'Carne caprina, Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 13), ferro_mg = coalesce(ferro_mg, 2.83), fosforo_mg = 180, potassio_mg = 385, sodio_mg = coalesce(sodio_mg, 82), zinco_mg = coalesce(zinco_mg, 4), cobre_mcg = 256, manganes_mg = 0.038, selenio_mcg = 8.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.11), riboflavina_mg = coalesce(riboflavina_mg, 0.49), niacina_mg = coalesce(niacina_mg, 3.75), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.13), folato_mcg = 5 where nome = 'Carne de caprino, Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 3.73), magnesio_mg = 0, fosforo_mg = 201, potassio_mg = 405, sodio_mg = coalesce(sodio_mg, 86), zinco_mg = coalesce(zinco_mg, 5.27), cobre_mcg = 303, manganes_mg = 0.042, selenio_mcg = 11.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.34, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.61), niacina_mg = coalesce(niacina_mg, 3.95), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.19), colina_mg = 106.4, vitamina_k_mcg = 1.2, folato_mcg = 5 where nome = 'Carne de caprino, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 3.73), magnesio_mg = 0, fosforo_mg = 201, potassio_mg = 405, sodio_mg = coalesce(sodio_mg, 86), zinco_mg = coalesce(zinco_mg, 5.27), cobre_mcg = 303, manganes_mg = 0.042, selenio_mcg = 11.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.34, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.61), niacina_mg = coalesce(niacina_mg, 3.95), vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.19), colina_mg = 106.4, vitamina_k_mcg = 1.2, folato_mcg = 5 where nome = 'Carne de caprino, Frito(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 1.79), magnesio_mg = 24, fosforo_mg = 201, potassio_mg = 339, sodio_mg = coalesce(sodio_mg, 81), zinco_mg = coalesce(zinco_mg, 4.67), cobre_mcg = 128, manganes_mg = 0.024, selenio_mcg = 27.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.14, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.1), riboflavina_mg = coalesce(riboflavina_mg, 0.25), niacina_mg = coalesce(niacina_mg, 6.7), acido_pantotenico_mg = 0.66, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.14), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.61), colina_mg = 93.4, vitamina_k_mcg = 5.3, folato_mcg = 19 where nome = 'Carne de carneiro, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 1.79), magnesio_mg = 24, fosforo_mg = 201, potassio_mg = 339, sodio_mg = coalesce(sodio_mg, 81), zinco_mg = coalesce(zinco_mg, 4.67), cobre_mcg = 128, manganes_mg = 0.024, selenio_mcg = 27.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.14, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.1), riboflavina_mg = coalesce(riboflavina_mg, 0.25), niacina_mg = coalesce(niacina_mg, 6.7), acido_pantotenico_mg = 0.66, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.14), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.61), colina_mg = 93.4, vitamina_k_mcg = 5.3, folato_mcg = 19 where nome = 'Carne de carneiro, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 1.79), magnesio_mg = 24, fosforo_mg = 201, potassio_mg = 339, sodio_mg = coalesce(sodio_mg, 81), zinco_mg = coalesce(zinco_mg, 4.67), cobre_mcg = 128, manganes_mg = 0.024, selenio_mcg = 27.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.14, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.1), riboflavina_mg = coalesce(riboflavina_mg, 0.25), niacina_mg = coalesce(niacina_mg, 6.7), acido_pantotenico_mg = 0.66, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.14), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.61), colina_mg = 93.4, vitamina_k_mcg = 5.3, folato_mcg = 19 where nome = 'Carne de carneiro, Frito(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 1.79), magnesio_mg = 24, fosforo_mg = 201, potassio_mg = 339, sodio_mg = coalesce(sodio_mg, 81), zinco_mg = coalesce(zinco_mg, 4.67), cobre_mcg = 128, manganes_mg = 0.024, selenio_mcg = 27.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.14, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.1), riboflavina_mg = coalesce(riboflavina_mg, 0.25), niacina_mg = coalesce(niacina_mg, 6.7), acido_pantotenico_mg = 0.66, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.14), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.61), colina_mg = 93.4, vitamina_k_mcg = 5.3, folato_mcg = 19 where nome = 'Carne de carneiro, Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 1.79), magnesio_mg = 24, fosforo_mg = 201, potassio_mg = 339, sodio_mg = coalesce(sodio_mg, 81), zinco_mg = coalesce(zinco_mg, 4.67), cobre_mcg = 128, manganes_mg = 0.024, selenio_mcg = 27.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.14, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.1), riboflavina_mg = coalesce(riboflavina_mg, 0.25), niacina_mg = coalesce(niacina_mg, 6.7), acido_pantotenico_mg = 0.66, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.14), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.61), colina_mg = 93.4, vitamina_k_mcg = 5.3, folato_mcg = 19 where nome = 'Carne de ovelha, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 1.79), magnesio_mg = 24, fosforo_mg = 201, potassio_mg = 339, sodio_mg = coalesce(sodio_mg, 81), zinco_mg = coalesce(zinco_mg, 4.67), cobre_mcg = 128, manganes_mg = 0.024, selenio_mcg = 27.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.14, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.1), riboflavina_mg = coalesce(riboflavina_mg, 0.25), niacina_mg = coalesce(niacina_mg, 6.7), acido_pantotenico_mg = 0.66, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.14), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.61), colina_mg = 93.4, vitamina_k_mcg = 5.3, folato_mcg = 19 where nome = 'Carne de ovelha, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 1.79), magnesio_mg = 24, fosforo_mg = 201, potassio_mg = 339, sodio_mg = coalesce(sodio_mg, 81), zinco_mg = coalesce(zinco_mg, 4.67), cobre_mcg = 128, manganes_mg = 0.024, selenio_mcg = 27.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.14, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.1), riboflavina_mg = coalesce(riboflavina_mg, 0.25), niacina_mg = coalesce(niacina_mg, 6.7), acido_pantotenico_mg = 0.66, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.14), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.61), colina_mg = 93.4, vitamina_k_mcg = 5.3, folato_mcg = 19 where nome = 'Carne de ovelha, Frito(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 19), ferro_mg = coalesce(ferro_mg, 4.99), magnesio_mg = 20, fosforo_mg = 174, potassio_mg = 237, sodio_mg = coalesce(sodio_mg, 109), zinco_mg = coalesce(zinco_mg, 4.53), cobre_mcg = 110, manganes_mg = 0.01, selenio_mcg = 15.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.7), tiamina_mg = coalesce(tiamina_mg, 0.317), riboflavina_mg = coalesce(riboflavina_mg, 0.51), niacina_mg = coalesce(niacina_mg, 5.34), acido_pantotenico_mg = 0.507, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.23), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.39), folato_mcg = 4 where nome = 'Língua suína, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 0.39), magnesio_mg = 8, fosforo_mg = 384, potassio_mg = 165, sodio_mg = coalesce(sodio_mg, 900), zinco_mg = coalesce(zinco_mg, 0.91), cobre_mcg = 41, manganes_mg = 0.028, selenio_mcg = 10.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.6), tiamina_mg = coalesce(tiamina_mg, 0.402), riboflavina_mg = coalesce(riboflavina_mg, 0.101), niacina_mg = coalesce(niacina_mg, 2.276), acido_pantotenico_mg = 0.238, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.231), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.38), folato_mcg = 2 where nome = 'Pernil, Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
