-- Migration 0092: micronutrientes IBGE — lote 12 (queijos e leites)
--
-- A partir deste lote, priorizando alimentos de consumo diário (a pedido
-- do usuário) em vez de seguir cegamente a ordem do pool "alta_confianca
-- restante" — itens raros/regionais (caças silvestres, doces
-- industrializados sem produto único, etc.) ficam pra depois. 31 itens
-- aprovados: queijos e leites, duas categorias de consumo muito frequente
-- que ainda não tinham micronutrientes no IBGE.
--
-- Queijos: o algoritmo batia quase todo queijo nomeado com uma única
-- entrada genérica "Cheese" do USDA (sem tipo definido) — corrigido pro
-- tipo específico onde existe equivalente real: muçarela, provolone,
-- ricota e gorgonzola (batem exato); prato/colonial/de colônia
-- aproximados por gouda (mesma família de queijo semiduro amarelo);
-- queijo do reino por edam (é literalmente o edam importado
-- historicamente); ralado por parmesão ralado; coalho por monterey jack
-- (queijo semifirme grelhável); canastra e "não especificado" por queso
-- fresco (mesmo perfil do queijo minas já usado); polenguinho por queijo
-- processado americano (mesma categoria de produto industrializado).
--
-- Leites: o algoritmo batia quase tudo com "Milk, 2%" mesmo quando o
-- nome indicava outra coisa — corrigidos: leite de vaca fresco (era 2%,
-- devia ser integral 3,25%), leite de cabra (era leite de vaca — espécie
-- errada), leite em pó integral (batia com substituto de café em pó —
-- produto completamente errado), leite condensado (batia com leite
-- líquido 2% — produto completamente diferente). "Leite em pó" reaproveita
-- o mesmo fdc já usado na migration 0076 pra "Leite em pó desnatado".
-- Também trocado 1 fdc_id (leite de vaca integral) cujo registro original
-- (amostra Foundation Foods) não tinha o painel completo de nutrientes.
--
-- Como sempre: coalesce() preserva os valores já existentes nas 12
-- colunas legadas; as 15 colunas novas (migration 0054) recebem o valor
-- USDA diretamente.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 505), ferro_mg = coalesce(ferro_mg, 0.44), magnesio_mg = 20, fosforo_mg = 354, potassio_mg = 76, sodio_mg = coalesce(sodio_mg, 486), zinco_mg = coalesce(zinco_mg, 2.92), cobre_mcg = 11, manganes_mg = 0.03, selenio_mcg = 17, vitamina_a_mcg = coalesce(vitamina_a_mcg, 179), vitamina_e_mg = 0.19, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.4), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.03), riboflavina_mg = coalesce(riboflavina_mg, 0.283), niacina_mg = coalesce(niacina_mg, 0.104), acido_pantotenico_mg = 0.141, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.037), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.28), colina_mg = 15.4, vitamina_k_mcg = 2.3, folato_mcg = 7 where nome = 'Queijo muçarela' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 505), ferro_mg = coalesce(ferro_mg, 0.44), magnesio_mg = 20, fosforo_mg = 354, potassio_mg = 76, sodio_mg = coalesce(sodio_mg, 486), zinco_mg = coalesce(zinco_mg, 2.92), cobre_mcg = 11, manganes_mg = 0.03, selenio_mcg = 17, vitamina_a_mcg = coalesce(vitamina_a_mcg, 179), vitamina_e_mg = 0.19, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.4), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.03), riboflavina_mg = coalesce(riboflavina_mg, 0.283), niacina_mg = coalesce(niacina_mg, 0.104), acido_pantotenico_mg = 0.141, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.037), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.28), colina_mg = 15.4, vitamina_k_mcg = 2.3, folato_mcg = 7 where nome = 'Queijo muçarela light' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 505), ferro_mg = coalesce(ferro_mg, 0.44), magnesio_mg = 20, fosforo_mg = 354, potassio_mg = 76, sodio_mg = coalesce(sodio_mg, 486), zinco_mg = coalesce(zinco_mg, 2.92), cobre_mcg = 11, manganes_mg = 0.03, selenio_mcg = 17, vitamina_a_mcg = coalesce(vitamina_a_mcg, 179), vitamina_e_mg = 0.19, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.4), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.03), riboflavina_mg = coalesce(riboflavina_mg, 0.283), niacina_mg = coalesce(niacina_mg, 0.104), acido_pantotenico_mg = 0.141, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.037), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.28), colina_mg = 15.4, vitamina_k_mcg = 2.3, folato_mcg = 7 where nome = 'Queijo de búfala' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 756), ferro_mg = coalesce(ferro_mg, 0.52), magnesio_mg = 28, fosforo_mg = 496, potassio_mg = 138, sodio_mg = coalesce(sodio_mg, 727), zinco_mg = coalesce(zinco_mg, 3.23), cobre_mcg = 26, manganes_mg = 0.01, selenio_mcg = 14.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 236), vitamina_e_mg = 0.23, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.019), riboflavina_mg = coalesce(riboflavina_mg, 0.321), niacina_mg = coalesce(niacina_mg, 0.156), acido_pantotenico_mg = 0.476, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.073), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.46), colina_mg = 15.4, vitamina_k_mcg = 2.2, folato_mcg = 10 where nome = 'Queijo provolone' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 206), ferro_mg = coalesce(ferro_mg, 0.13), magnesio_mg = 20, fosforo_mg = 154, potassio_mg = 219, sodio_mg = coalesce(sodio_mg, 110), zinco_mg = coalesce(zinco_mg, 0.53), cobre_mcg = 18, manganes_mg = 0.011, selenio_mcg = 5.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 120), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.013), riboflavina_mg = coalesce(riboflavina_mg, 0.298), niacina_mg = coalesce(niacina_mg, 0.137), acido_pantotenico_mg = 0.461, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.097), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.85), colina_mg = 17.5, vitamina_k_mcg = 1.1, folato_mcg = 4 where nome = 'Queijo ricota' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 206), ferro_mg = coalesce(ferro_mg, 0.13), magnesio_mg = 20, fosforo_mg = 154, potassio_mg = 219, sodio_mg = coalesce(sodio_mg, 110), zinco_mg = coalesce(zinco_mg, 0.53), cobre_mcg = 18, manganes_mg = 0.011, selenio_mcg = 5.9, vitamina_a_mcg = coalesce(vitamina_a_mcg, 120), vitamina_e_mg = 0.11, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.013), riboflavina_mg = coalesce(riboflavina_mg, 0.298), niacina_mg = coalesce(niacina_mg, 0.137), acido_pantotenico_mg = 0.461, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.097), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.85), colina_mg = 17.5, vitamina_k_mcg = 1.1, folato_mcg = 4 where nome = 'Queijo ricota light' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 528), ferro_mg = coalesce(ferro_mg, 0.31), magnesio_mg = 23, fosforo_mg = 387, potassio_mg = 256, sodio_mg = coalesce(sodio_mg, 1146), zinco_mg = coalesce(zinco_mg, 2.66), cobre_mcg = 40, manganes_mg = 0.009, selenio_mcg = 14.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 198), vitamina_e_mg = 0.25, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.029), riboflavina_mg = coalesce(riboflavina_mg, 0.382), niacina_mg = coalesce(niacina_mg, 1.016), acido_pantotenico_mg = 1.729, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.166), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.22), colina_mg = 15.4, vitamina_k_mcg = 2.4, folato_mcg = 36 where nome = 'Queijo gorgonzola' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 700), ferro_mg = coalesce(ferro_mg, 0.24), magnesio_mg = 29, fosforo_mg = 546, potassio_mg = 121, sodio_mg = coalesce(sodio_mg, 819), zinco_mg = coalesce(zinco_mg, 3.9), cobre_mcg = 36, manganes_mg = 0.011, selenio_mcg = 14.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 165), vitamina_e_mg = 0.24, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.03), riboflavina_mg = coalesce(riboflavina_mg, 0.334), niacina_mg = coalesce(niacina_mg, 0.063), acido_pantotenico_mg = 0.34, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.08), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.54), colina_mg = 15.4, vitamina_k_mcg = 2.3, folato_mcg = 21 where nome = 'Queijo prato' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 700), ferro_mg = coalesce(ferro_mg, 0.24), magnesio_mg = 29, fosforo_mg = 546, potassio_mg = 121, sodio_mg = coalesce(sodio_mg, 819), zinco_mg = coalesce(zinco_mg, 3.9), cobre_mcg = 36, manganes_mg = 0.011, selenio_mcg = 14.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 165), vitamina_e_mg = 0.24, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.03), riboflavina_mg = coalesce(riboflavina_mg, 0.334), niacina_mg = coalesce(niacina_mg, 0.063), acido_pantotenico_mg = 0.34, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.08), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.54), colina_mg = 15.4, vitamina_k_mcg = 2.3, folato_mcg = 21 where nome = 'Queijo prato light' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 700), ferro_mg = coalesce(ferro_mg, 0.24), magnesio_mg = 29, fosforo_mg = 546, potassio_mg = 121, sodio_mg = coalesce(sodio_mg, 819), zinco_mg = coalesce(zinco_mg, 3.9), cobre_mcg = 36, manganes_mg = 0.011, selenio_mcg = 14.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 165), vitamina_e_mg = 0.24, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.03), riboflavina_mg = coalesce(riboflavina_mg, 0.334), niacina_mg = coalesce(niacina_mg, 0.063), acido_pantotenico_mg = 0.34, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.08), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.54), colina_mg = 15.4, vitamina_k_mcg = 2.3, folato_mcg = 21 where nome = 'Queijo colonial' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 700), ferro_mg = coalesce(ferro_mg, 0.24), magnesio_mg = 29, fosforo_mg = 546, potassio_mg = 121, sodio_mg = coalesce(sodio_mg, 819), zinco_mg = coalesce(zinco_mg, 3.9), cobre_mcg = 36, manganes_mg = 0.011, selenio_mcg = 14.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 165), vitamina_e_mg = 0.24, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.03), riboflavina_mg = coalesce(riboflavina_mg, 0.334), niacina_mg = coalesce(niacina_mg, 0.063), acido_pantotenico_mg = 0.34, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.08), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.54), colina_mg = 15.4, vitamina_k_mcg = 2.3, folato_mcg = 21 where nome = 'Queijo de colônia' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 731), ferro_mg = coalesce(ferro_mg, 0.44), magnesio_mg = 30, fosforo_mg = 536, potassio_mg = 188, sodio_mg = coalesce(sodio_mg, 973), zinco_mg = coalesce(zinco_mg, 3.75), cobre_mcg = 36, manganes_mg = 0.011, selenio_mcg = 14.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 243), vitamina_e_mg = 0.24, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.037), riboflavina_mg = coalesce(riboflavina_mg, 0.389), niacina_mg = coalesce(niacina_mg, 0.082), acido_pantotenico_mg = 0.281, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.076), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.54), colina_mg = 15.4, vitamina_k_mcg = 2.3, folato_mcg = 16 where nome = 'Queijo de reino' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 853), ferro_mg = coalesce(ferro_mg, 0.49), magnesio_mg = 34, fosforo_mg = 627, potassio_mg = 180, sodio_mg = coalesce(sodio_mg, 1804), zinco_mg = coalesce(zinco_mg, 4.2), cobre_mcg = 40, manganes_mg = 0.071, selenio_mcg = 34.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 262), vitamina_e_mg = 0.53, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.026), riboflavina_mg = coalesce(riboflavina_mg, 0.358), niacina_mg = coalesce(niacina_mg, 0.08), acido_pantotenico_mg = 0.45, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.081), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.4), colina_mg = 14.1, vitamina_k_mcg = 1.7, folato_mcg = 6 where nome = 'Queijo ralado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 853), ferro_mg = coalesce(ferro_mg, 0.49), magnesio_mg = 34, fosforo_mg = 627, potassio_mg = 180, sodio_mg = coalesce(sodio_mg, 1804), zinco_mg = coalesce(zinco_mg, 4.2), cobre_mcg = 40, manganes_mg = 0.071, selenio_mcg = 34.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 262), vitamina_e_mg = 0.53, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.026), riboflavina_mg = coalesce(riboflavina_mg, 0.358), niacina_mg = coalesce(niacina_mg, 0.08), acido_pantotenico_mg = 0.45, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.081), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.4), colina_mg = 14.1, vitamina_k_mcg = 1.7, folato_mcg = 6 where nome = 'Queijo ralado light' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 746), ferro_mg = coalesce(ferro_mg, 0.72), magnesio_mg = 27, fosforo_mg = 444, potassio_mg = 81, sodio_mg = coalesce(sodio_mg, 600), zinco_mg = coalesce(zinco_mg, 3), cobre_mcg = 32, manganes_mg = 0.011, selenio_mcg = 14.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 198), vitamina_e_mg = 0.26, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.6), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.015), riboflavina_mg = coalesce(riboflavina_mg, 0.39), niacina_mg = coalesce(niacina_mg, 0.093), acido_pantotenico_mg = 0.21, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.079), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.83), colina_mg = 15.4, vitamina_k_mcg = 2.5, folato_mcg = 18 where nome = 'Queijo de coalho' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 746), ferro_mg = coalesce(ferro_mg, 0.72), magnesio_mg = 27, fosforo_mg = 444, potassio_mg = 81, sodio_mg = coalesce(sodio_mg, 600), zinco_mg = coalesce(zinco_mg, 3), cobre_mcg = 32, manganes_mg = 0.011, selenio_mcg = 14.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 198), vitamina_e_mg = 0.26, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.6), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.015), riboflavina_mg = coalesce(riboflavina_mg, 0.39), niacina_mg = coalesce(niacina_mg, 0.093), acido_pantotenico_mg = 0.21, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.079), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.83), colina_mg = 15.4, vitamina_k_mcg = 2.5, folato_mcg = 18 where nome = 'Queijo de coalho light' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 746), ferro_mg = coalesce(ferro_mg, 0.72), magnesio_mg = 27, fosforo_mg = 444, potassio_mg = 81, sodio_mg = coalesce(sodio_mg, 600), zinco_mg = coalesce(zinco_mg, 3), cobre_mcg = 32, manganes_mg = 0.011, selenio_mcg = 14.5, vitamina_a_mcg = coalesce(vitamina_a_mcg, 198), vitamina_e_mg = 0.26, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.6), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.015), riboflavina_mg = coalesce(riboflavina_mg, 0.39), niacina_mg = coalesce(niacina_mg, 0.093), acido_pantotenico_mg = 0.21, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.079), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.83), colina_mg = 15.4, vitamina_k_mcg = 2.5, folato_mcg = 18 where nome = 'Queijo de coalho frescal orgânico' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 566), ferro_mg = coalesce(ferro_mg, 0.2), magnesio_mg = 24, fosforo_mg = 385, potassio_mg = 129, sodio_mg = coalesce(sodio_mg, 751), zinco_mg = coalesce(zinco_mg, 2.58), cobre_mcg = 33, manganes_mg = 0.014, selenio_mcg = 19.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 224), vitamina_e_mg = 0.37, vitamina_d_mcg = coalesce(vitamina_d_mcg, 2.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.042), riboflavina_mg = coalesce(riboflavina_mg, 0.173), niacina_mg = coalesce(niacina_mg, 0.027), acido_pantotenico_mg = 0.358, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.076), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.68), colina_mg = 12.5, vitamina_k_mcg = 1, folato_mcg = 7 where nome = 'Queijo canastra' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 566), ferro_mg = coalesce(ferro_mg, 0.2), magnesio_mg = 24, fosforo_mg = 385, potassio_mg = 129, sodio_mg = coalesce(sodio_mg, 751), zinco_mg = coalesce(zinco_mg, 2.58), cobre_mcg = 33, manganes_mg = 0.014, selenio_mcg = 19.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 224), vitamina_e_mg = 0.37, vitamina_d_mcg = coalesce(vitamina_d_mcg, 2.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.042), riboflavina_mg = coalesce(riboflavina_mg, 0.173), niacina_mg = coalesce(niacina_mg, 0.027), acido_pantotenico_mg = 0.358, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.076), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.68), colina_mg = 12.5, vitamina_k_mcg = 1, folato_mcg = 7 where nome = 'Queijo não especificado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 566), ferro_mg = coalesce(ferro_mg, 0.2), magnesio_mg = 24, fosforo_mg = 385, potassio_mg = 129, sodio_mg = coalesce(sodio_mg, 751), zinco_mg = coalesce(zinco_mg, 2.58), cobre_mcg = 33, manganes_mg = 0.014, selenio_mcg = 19.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 224), vitamina_e_mg = 0.37, vitamina_d_mcg = coalesce(vitamina_d_mcg, 2.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.042), riboflavina_mg = coalesce(riboflavina_mg, 0.173), niacina_mg = coalesce(niacina_mg, 0.027), acido_pantotenico_mg = 0.358, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.076), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.68), colina_mg = 12.5, vitamina_k_mcg = 1, folato_mcg = 7 where nome = 'Queijo não especificado light' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1045), ferro_mg = coalesce(ferro_mg, 0.63), magnesio_mg = 26, fosforo_mg = 641, potassio_mg = 132, sodio_mg = coalesce(sodio_mg, 1671), zinco_mg = coalesce(zinco_mg, 2.49), cobre_mcg = 46, manganes_mg = 0.041, selenio_mcg = 20.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 317), vitamina_e_mg = 0.8, vitamina_d_mcg = coalesce(vitamina_d_mcg, 7.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.015), riboflavina_mg = coalesce(riboflavina_mg, 0.234), niacina_mg = coalesce(niacina_mg, 0.076), acido_pantotenico_mg = 0.403, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.054), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.5), colina_mg = 19.2, vitamina_k_mcg = 3.7, folato_mcg = 8 where nome = 'Queijo polenguinho' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 113), ferro_mg = coalesce(ferro_mg, 0.03), magnesio_mg = 10, fosforo_mg = 84, potassio_mg = 132, sodio_mg = coalesce(sodio_mg, 43), zinco_mg = coalesce(zinco_mg, 0.37), cobre_mcg = 25, manganes_mg = 0.004, selenio_mcg = 3.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 46), vitamina_e_mg = 0.07, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.046), riboflavina_mg = coalesce(riboflavina_mg, 0.169), niacina_mg = coalesce(niacina_mg, 0.089), acido_pantotenico_mg = 0.373, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.45), colina_mg = 14.3, vitamina_k_mcg = 0.3, folato_mcg = 5 where nome = 'Leite de vaca integral' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 113), ferro_mg = coalesce(ferro_mg, 0.03), magnesio_mg = 10, fosforo_mg = 84, potassio_mg = 132, sodio_mg = coalesce(sodio_mg, 43), zinco_mg = coalesce(zinco_mg, 0.37), cobre_mcg = 25, manganes_mg = 0.004, selenio_mcg = 3.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 46), vitamina_e_mg = 0.07, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.046), riboflavina_mg = coalesce(riboflavina_mg, 0.169), niacina_mg = coalesce(niacina_mg, 0.089), acido_pantotenico_mg = 0.373, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.45), colina_mg = 14.3, vitamina_k_mcg = 0.3, folato_mcg = 5 where nome = 'Leite de vaca integral orgânico' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 113), ferro_mg = coalesce(ferro_mg, 0.03), magnesio_mg = 10, fosforo_mg = 84, potassio_mg = 132, sodio_mg = coalesce(sodio_mg, 43), zinco_mg = coalesce(zinco_mg, 0.37), cobre_mcg = 25, manganes_mg = 0.004, selenio_mcg = 3.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 46), vitamina_e_mg = 0.07, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.046), riboflavina_mg = coalesce(riboflavina_mg, 0.169), niacina_mg = coalesce(niacina_mg, 0.089), acido_pantotenico_mg = 0.373, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.45), colina_mg = 14.3, vitamina_k_mcg = 0.3, folato_mcg = 5 where nome = 'Leite de vaca fresco' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 113), ferro_mg = coalesce(ferro_mg, 0.03), magnesio_mg = 10, fosforo_mg = 84, potassio_mg = 132, sodio_mg = coalesce(sodio_mg, 43), zinco_mg = coalesce(zinco_mg, 0.37), cobre_mcg = 25, manganes_mg = 0.004, selenio_mcg = 3.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 46), vitamina_e_mg = 0.07, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.046), riboflavina_mg = coalesce(riboflavina_mg, 0.169), niacina_mg = coalesce(niacina_mg, 0.089), acido_pantotenico_mg = 0.373, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.45), colina_mg = 14.3, vitamina_k_mcg = 0.3, folato_mcg = 5 where nome = 'Leite de vaca fresco orgânico' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 134), ferro_mg = coalesce(ferro_mg, 0.05), magnesio_mg = 14, fosforo_mg = 111, potassio_mg = 204, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 0.3), cobre_mcg = 46, manganes_mg = 0.018, selenio_mcg = 1.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 57), vitamina_e_mg = 0.07, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.3), vitamina_c_mg = coalesce(vitamina_c_mg, 1.3), tiamina_mg = coalesce(tiamina_mg, 0.048), riboflavina_mg = coalesce(riboflavina_mg, 0.138), niacina_mg = coalesce(niacina_mg, 0.277), acido_pantotenico_mg = 0.31, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.046), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.07), colina_mg = 16, vitamina_k_mcg = 0.3, folato_mcg = 1 where nome = 'Leite de cabra' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 912), ferro_mg = coalesce(ferro_mg, 0.47), magnesio_mg = 85, fosforo_mg = 776, potassio_mg = 1330, sodio_mg = coalesce(sodio_mg, 371), zinco_mg = coalesce(zinco_mg, 3.34), cobre_mcg = 80, manganes_mg = 0.04, selenio_mcg = 16.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 258), vitamina_e_mg = 0.58, vitamina_d_mcg = coalesce(vitamina_d_mcg, 10.5), vitamina_c_mg = coalesce(vitamina_c_mg, 8.6), tiamina_mg = coalesce(tiamina_mg, 0.283), riboflavina_mg = coalesce(riboflavina_mg, 1.205), niacina_mg = coalesce(niacina_mg, 0.646), acido_pantotenico_mg = 2.271, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.302), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.25), colina_mg = 119.3, vitamina_k_mcg = 2.2, folato_mcg = 37 where nome = 'Leite em pó integral' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 1257), ferro_mg = coalesce(ferro_mg, 0.32), magnesio_mg = 110, fosforo_mg = 968, potassio_mg = 1794, sodio_mg = coalesce(sodio_mg, 535), zinco_mg = coalesce(zinco_mg, 4.08), cobre_mcg = 41, manganes_mg = 0.02, selenio_mcg = 27.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 6), vitamina_e_mg = 0, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 6.8), tiamina_mg = coalesce(tiamina_mg, 0.415), riboflavina_mg = coalesce(riboflavina_mg, 1.55), niacina_mg = coalesce(niacina_mg, 0.951), acido_pantotenico_mg = 3.568, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.361), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 4.03), colina_mg = 169.2, vitamina_k_mcg = 0.1, folato_mcg = 50 where nome = 'Leite em pó' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 912), ferro_mg = coalesce(ferro_mg, 0.47), magnesio_mg = 85, fosforo_mg = 776, potassio_mg = 1330, sodio_mg = coalesce(sodio_mg, 371), zinco_mg = coalesce(zinco_mg, 3.34), cobre_mcg = 80, manganes_mg = 0.04, selenio_mcg = 16.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 258), vitamina_e_mg = 0.58, vitamina_d_mcg = coalesce(vitamina_d_mcg, 10.5), vitamina_c_mg = coalesce(vitamina_c_mg, 8.6), tiamina_mg = coalesce(tiamina_mg, 0.283), riboflavina_mg = coalesce(riboflavina_mg, 1.205), niacina_mg = coalesce(niacina_mg, 0.646), acido_pantotenico_mg = 2.271, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.302), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 3.25), colina_mg = 119.3, vitamina_k_mcg = 2.2, folato_mcg = 37 where nome = 'Leite em pó com sabor' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 284), ferro_mg = coalesce(ferro_mg, 0.19), magnesio_mg = 26, fosforo_mg = 253, potassio_mg = 371, sodio_mg = coalesce(sodio_mg, 127), zinco_mg = coalesce(zinco_mg, 0.94), cobre_mcg = 15, manganes_mg = 0.006, selenio_mcg = 14.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 74), vitamina_e_mg = 0.16, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.2), vitamina_c_mg = coalesce(vitamina_c_mg, 2.6), tiamina_mg = coalesce(tiamina_mg, 0.09), riboflavina_mg = coalesce(riboflavina_mg, 0.416), niacina_mg = coalesce(niacina_mg, 0.21), acido_pantotenico_mg = 0.75, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.051), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.44), colina_mg = 89.1, vitamina_k_mcg = 0.6, folato_mcg = 11 where nome = 'Leite condensado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 113), ferro_mg = coalesce(ferro_mg, 0.03), magnesio_mg = 10, fosforo_mg = 84, potassio_mg = 132, sodio_mg = coalesce(sodio_mg, 43), zinco_mg = coalesce(zinco_mg, 0.37), cobre_mcg = 25, manganes_mg = 0.004, selenio_mcg = 3.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 46), vitamina_e_mg = 0.07, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.046), riboflavina_mg = coalesce(riboflavina_mg, 0.169), niacina_mg = coalesce(niacina_mg, 0.089), acido_pantotenico_mg = 0.373, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.036), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.45), colina_mg = 14.3, vitamina_k_mcg = 0.3, folato_mcg = 5 where nome = 'Leite não especificado pasteurizado' and fonte = 'IBGE' and id_avaliador is null;
