-- Migration 0093: micronutrientes IBGE — lote 13 (ovos e peixe genérico)
--
-- Continuação do foco em alimentos de consumo diário. 29 itens
-- aprovados: ovo de galinha em vários preparos (cru, frito, com manteiga/
-- óleo, assado, molho vermelho, ao alho e óleo, ao vinagrete, ensopado,
-- mingau) e ovo de codorna cru; e peixe sem espécie declarada ("de mar",
-- "de água doce", "não especificado") em vários preparos.
--
-- Ovos: o algoritmo batia sistematicamente com produtos de FRANGO
-- (frango moído cru, peito processado, rolinho de ovo com frango) em vez
-- do ovo em si — corrigidos pra Egg, whole (cru/frito); os preparos sem
-- dado próprio reaproveitam o mesmo fdc já usado (corretamente) em "Ovo
-- de galinha, Refogado(a)" (omelete).
--
-- Peixe genérico: o algoritmo já acertava razoavelmente "Cozido(a)"
-- (bacalhau do Pacífico cozido, um whitefish genérico razoável) — esse
-- mesmo fdc foi estendido pros demais preparos cozidos (refogado,
-- ensopado, molho vermelho/branco) como aproximação de método de
-- cocção. "Cru(a)" corrigido de carpa (peixe de água doce específico,
-- errado pra "peixe de mar") pra bacalhau cru, um whitefish genérico mais
-- seguro pra qualquer peixe sem espécie declarada.
--
-- Itens que ficaram de fora deste lote (prefiro vazio a dado errado):
-- variantes "salgado"/"seco" de peixe (produto desidratado com sódio
-- muito mais alto — usar o peixe fresco/cozido comum subestimaria o
-- sódio real), Fios de ovos/Ovo de páscoa/Kinder ovo/Doce à base de ovos
-- (produtos de confeitaria, não ovo de verdade), Ovo de codorna cozido
-- (sem dado de ovo de codorna cozido no USDA — já decidido no lote 2).
--
-- Como sempre: coalesce() preserva os valores já existentes nas 12
-- colunas legadas; as 15 colunas novas (migration 0054) recebem o valor
-- USDA diretamente.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 56), ferro_mg = coalesce(ferro_mg, 1.75), magnesio_mg = 12, fosforo_mg = 198, potassio_mg = 138, sodio_mg = coalesce(sodio_mg, 142), zinco_mg = coalesce(zinco_mg, 1.29), cobre_mcg = 72, manganes_mg = 0.028, selenio_mcg = 30.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 160), vitamina_e_mg = 1.05, vitamina_d_mcg = coalesce(vitamina_d_mcg, 2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.04), riboflavina_mg = coalesce(riboflavina_mg, 0.457), niacina_mg = coalesce(niacina_mg, 0.075), acido_pantotenico_mg = 1.533, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.17), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.89), colina_mg = 293.8, vitamina_k_mcg = 0.3, folato_mcg = 47 where nome = 'Ovo de galinha, Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 56), ferro_mg = coalesce(ferro_mg, 1.75), magnesio_mg = 12, fosforo_mg = 198, potassio_mg = 138, sodio_mg = coalesce(sodio_mg, 142), zinco_mg = coalesce(zinco_mg, 1.29), cobre_mcg = 72, manganes_mg = 0.028, selenio_mcg = 30.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 160), vitamina_e_mg = 1.05, vitamina_d_mcg = coalesce(vitamina_d_mcg, 2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.04), riboflavina_mg = coalesce(riboflavina_mg, 0.457), niacina_mg = coalesce(niacina_mg, 0.075), acido_pantotenico_mg = 1.533, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.17), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.89), colina_mg = 293.8, vitamina_k_mcg = 0.3, folato_mcg = 47 where nome = 'Ovo de galinha' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 62), ferro_mg = coalesce(ferro_mg, 1.89), magnesio_mg = 13, fosforo_mg = 215, potassio_mg = 152, sodio_mg = coalesce(sodio_mg, 207), zinco_mg = coalesce(zinco_mg, 1.39), cobre_mcg = 78, manganes_mg = 0.03, selenio_mcg = 33.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 219), vitamina_e_mg = 1.31, vitamina_d_mcg = coalesce(vitamina_d_mcg, 2.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.044), riboflavina_mg = coalesce(riboflavina_mg, 0.495), niacina_mg = coalesce(niacina_mg, 0.082), acido_pantotenico_mg = 1.66, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.184), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.97), colina_mg = 317.1, vitamina_k_mcg = 5.6, folato_mcg = 51 where nome = 'Ovo de galinha, Frito(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 62), ferro_mg = coalesce(ferro_mg, 1.89), magnesio_mg = 13, fosforo_mg = 215, potassio_mg = 152, sodio_mg = coalesce(sodio_mg, 207), zinco_mg = coalesce(zinco_mg, 1.39), cobre_mcg = 78, manganes_mg = 0.03, selenio_mcg = 33.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 219), vitamina_e_mg = 1.31, vitamina_d_mcg = coalesce(vitamina_d_mcg, 2.2), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.044), riboflavina_mg = coalesce(riboflavina_mg, 0.495), niacina_mg = coalesce(niacina_mg, 0.082), acido_pantotenico_mg = 1.66, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.184), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.97), colina_mg = 317.1, vitamina_k_mcg = 5.6, folato_mcg = 51 where nome = 'Ovo de galinha, Com manteiga/óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 48), ferro_mg = coalesce(ferro_mg, 1.48), magnesio_mg = 11, fosforo_mg = 167, potassio_mg = 117, sodio_mg = coalesce(sodio_mg, 155), zinco_mg = coalesce(zinco_mg, 1.09), cobre_mcg = 63, manganes_mg = 0.024, selenio_mcg = 25.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 172), vitamina_e_mg = 1.29, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.034), riboflavina_mg = coalesce(riboflavina_mg, 0.386), niacina_mg = coalesce(niacina_mg, 0.064), acido_pantotenico_mg = 1.289, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.143), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.76), colina_mg = 247.6, vitamina_k_mcg = 4.5, folato_mcg = 39 where nome = 'Ovo de galinha, Assado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 48), ferro_mg = coalesce(ferro_mg, 1.48), magnesio_mg = 11, fosforo_mg = 167, potassio_mg = 117, sodio_mg = coalesce(sodio_mg, 155), zinco_mg = coalesce(zinco_mg, 1.09), cobre_mcg = 63, manganes_mg = 0.024, selenio_mcg = 25.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 172), vitamina_e_mg = 1.29, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.034), riboflavina_mg = coalesce(riboflavina_mg, 0.386), niacina_mg = coalesce(niacina_mg, 0.064), acido_pantotenico_mg = 1.289, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.143), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.76), colina_mg = 247.6, vitamina_k_mcg = 4.5, folato_mcg = 39 where nome = 'Ovo de galinha, Molho vermelho' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 48), ferro_mg = coalesce(ferro_mg, 1.48), magnesio_mg = 11, fosforo_mg = 167, potassio_mg = 117, sodio_mg = coalesce(sodio_mg, 155), zinco_mg = coalesce(zinco_mg, 1.09), cobre_mcg = 63, manganes_mg = 0.024, selenio_mcg = 25.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 172), vitamina_e_mg = 1.29, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.034), riboflavina_mg = coalesce(riboflavina_mg, 0.386), niacina_mg = coalesce(niacina_mg, 0.064), acido_pantotenico_mg = 1.289, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.143), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.76), colina_mg = 247.6, vitamina_k_mcg = 4.5, folato_mcg = 39 where nome = 'Ovo de galinha, Ao alho e óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 48), ferro_mg = coalesce(ferro_mg, 1.48), magnesio_mg = 11, fosforo_mg = 167, potassio_mg = 117, sodio_mg = coalesce(sodio_mg, 155), zinco_mg = coalesce(zinco_mg, 1.09), cobre_mcg = 63, manganes_mg = 0.024, selenio_mcg = 25.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 172), vitamina_e_mg = 1.29, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.034), riboflavina_mg = coalesce(riboflavina_mg, 0.386), niacina_mg = coalesce(niacina_mg, 0.064), acido_pantotenico_mg = 1.289, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.143), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.76), colina_mg = 247.6, vitamina_k_mcg = 4.5, folato_mcg = 39 where nome = 'Ovo de galinha, Ao vinagrete' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 48), ferro_mg = coalesce(ferro_mg, 1.48), magnesio_mg = 11, fosforo_mg = 167, potassio_mg = 117, sodio_mg = coalesce(sodio_mg, 155), zinco_mg = coalesce(zinco_mg, 1.09), cobre_mcg = 63, manganes_mg = 0.024, selenio_mcg = 25.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 172), vitamina_e_mg = 1.29, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.034), riboflavina_mg = coalesce(riboflavina_mg, 0.386), niacina_mg = coalesce(niacina_mg, 0.064), acido_pantotenico_mg = 1.289, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.143), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.76), colina_mg = 247.6, vitamina_k_mcg = 4.5, folato_mcg = 39 where nome = 'Ovo de galinha, Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 48), ferro_mg = coalesce(ferro_mg, 1.48), magnesio_mg = 11, fosforo_mg = 167, potassio_mg = 117, sodio_mg = coalesce(sodio_mg, 155), zinco_mg = coalesce(zinco_mg, 1.09), cobre_mcg = 63, manganes_mg = 0.024, selenio_mcg = 25.8, vitamina_a_mcg = coalesce(vitamina_a_mcg, 172), vitamina_e_mg = 1.29, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.7), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.034), riboflavina_mg = coalesce(riboflavina_mg, 0.386), niacina_mg = coalesce(niacina_mg, 0.064), acido_pantotenico_mg = 1.289, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.143), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.76), colina_mg = 247.6, vitamina_k_mcg = 4.5, folato_mcg = 39 where nome = 'Ovo de galinha, Mingau' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 64), ferro_mg = coalesce(ferro_mg, 3.65), magnesio_mg = 13, fosforo_mg = 226, potassio_mg = 132, sodio_mg = coalesce(sodio_mg, 141), zinco_mg = coalesce(zinco_mg, 1.47), cobre_mcg = 62, manganes_mg = 0.038, selenio_mcg = 32, vitamina_a_mcg = coalesce(vitamina_a_mcg, 156), vitamina_e_mg = 1.08, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.4), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.13), riboflavina_mg = coalesce(riboflavina_mg, 0.79), niacina_mg = coalesce(niacina_mg, 0.15), acido_pantotenico_mg = 1.761, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.15), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 1.58), colina_mg = 263.4, vitamina_k_mcg = 0.3, folato_mcg = 66 where nome = 'Ovo de codorna' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 16), ferro_mg = coalesce(ferro_mg, 0.38), magnesio_mg = 32, fosforo_mg = 203, potassio_mg = 413, sodio_mg = coalesce(sodio_mg, 54), zinco_mg = coalesce(zinco_mg, 0.45), cobre_mcg = 28, manganes_mg = 0.015, selenio_mcg = 33.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 12), vitamina_e_mg = 0.64, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.9), vitamina_c_mg = coalesce(vitamina_c_mg, 1), tiamina_mg = coalesce(tiamina_mg, 0.076), riboflavina_mg = coalesce(riboflavina_mg, 0.065), niacina_mg = coalesce(niacina_mg, 2.063), acido_pantotenico_mg = 0.153, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.245), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.91), colina_mg = 65.2, vitamina_k_mcg = 0.1, folato_mcg = 7 where nome = 'Peixe de mar (inteiro, em posta, em filé, etc.), Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 0.16), magnesio_mg = 35, fosforo_mg = 205, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 134), zinco_mg = coalesce(zinco_mg, 0.43), cobre_mcg = 19, manganes_mg = 0.012 where nome = 'Peixe de mar (inteiro, em posta, em filé, etc.), Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 0.16), magnesio_mg = 35, fosforo_mg = 205, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 134), zinco_mg = coalesce(zinco_mg, 0.43), cobre_mcg = 19, manganes_mg = 0.012 where nome = 'Peixe de mar (inteiro, em posta, em filé, etc.), Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 0.16), magnesio_mg = 35, fosforo_mg = 205, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 134), zinco_mg = coalesce(zinco_mg, 0.43), cobre_mcg = 19, manganes_mg = 0.012 where nome = 'Peixe de mar (inteiro, em posta, em filé, etc.), Molho vermelho' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 0.16), magnesio_mg = 35, fosforo_mg = 205, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 134), zinco_mg = coalesce(zinco_mg, 0.43), cobre_mcg = 19, manganes_mg = 0.012 where nome = 'Peixe de mar (inteiro, em posta, em filé, etc.), Molho branco' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 16), ferro_mg = coalesce(ferro_mg, 0.38), magnesio_mg = 32, fosforo_mg = 203, potassio_mg = 413, sodio_mg = coalesce(sodio_mg, 54), zinco_mg = coalesce(zinco_mg, 0.45), cobre_mcg = 28, manganes_mg = 0.015, selenio_mcg = 33.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 12), vitamina_e_mg = 0.64, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.9), vitamina_c_mg = coalesce(vitamina_c_mg, 1), tiamina_mg = coalesce(tiamina_mg, 0.076), riboflavina_mg = coalesce(riboflavina_mg, 0.065), niacina_mg = coalesce(niacina_mg, 2.063), acido_pantotenico_mg = 0.153, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.245), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.91), colina_mg = 65.2, vitamina_k_mcg = 0.1, folato_mcg = 7 where nome = 'Peixe de água doce (inteiro, em posta, em filé, etc.), Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 0.16), magnesio_mg = 35, fosforo_mg = 205, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 134), zinco_mg = coalesce(zinco_mg, 0.43), cobre_mcg = 19, manganes_mg = 0.012 where nome = 'Peixe de água doce (inteiro, em posta, em filé, etc.), Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 0.16), magnesio_mg = 35, fosforo_mg = 205, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 134), zinco_mg = coalesce(zinco_mg, 0.43), cobre_mcg = 19, manganes_mg = 0.012 where nome = 'Peixe de água doce (inteiro, em posta, em filé, etc.), Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 0.16), magnesio_mg = 35, fosforo_mg = 205, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 134), zinco_mg = coalesce(zinco_mg, 0.43), cobre_mcg = 19, manganes_mg = 0.012 where nome = 'Peixe de água doce (inteiro, em posta, em filé, etc.), Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 0.16), magnesio_mg = 35, fosforo_mg = 205, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 134), zinco_mg = coalesce(zinco_mg, 0.43), cobre_mcg = 19, manganes_mg = 0.012 where nome = 'Peixe de água doce (inteiro, em posta, em filé, etc.), Molho vermelho' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 0.16), magnesio_mg = 35, fosforo_mg = 205, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 134), zinco_mg = coalesce(zinco_mg, 0.43), cobre_mcg = 19, manganes_mg = 0.012 where nome = 'Peixe de água doce (inteiro, em posta, em filé, etc.), Molho branco' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 16), ferro_mg = coalesce(ferro_mg, 0.38), magnesio_mg = 32, fosforo_mg = 203, potassio_mg = 413, sodio_mg = coalesce(sodio_mg, 54), zinco_mg = coalesce(zinco_mg, 0.45), cobre_mcg = 28, manganes_mg = 0.015, selenio_mcg = 33.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 12), vitamina_e_mg = 0.64, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.9), vitamina_c_mg = coalesce(vitamina_c_mg, 1), tiamina_mg = coalesce(tiamina_mg, 0.076), riboflavina_mg = coalesce(riboflavina_mg, 0.065), niacina_mg = coalesce(niacina_mg, 2.063), acido_pantotenico_mg = 0.153, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.245), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.91), colina_mg = 65.2, vitamina_k_mcg = 0.1, folato_mcg = 7 where nome = 'Peixe de água doce (inteiro, em posta, em filé, etc.)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 16), ferro_mg = coalesce(ferro_mg, 0.38), magnesio_mg = 32, fosforo_mg = 203, potassio_mg = 413, sodio_mg = coalesce(sodio_mg, 54), zinco_mg = coalesce(zinco_mg, 0.45), cobre_mcg = 28, manganes_mg = 0.015, selenio_mcg = 33.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 12), vitamina_e_mg = 0.64, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.9), vitamina_c_mg = coalesce(vitamina_c_mg, 1), tiamina_mg = coalesce(tiamina_mg, 0.076), riboflavina_mg = coalesce(riboflavina_mg, 0.065), niacina_mg = coalesce(niacina_mg, 2.063), acido_pantotenico_mg = 0.153, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.245), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.91), colina_mg = 65.2, vitamina_k_mcg = 0.1, folato_mcg = 7 where nome = 'Peixe não especificado (inteiro, em posta, em filé, etc.), Cru(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 0.16), magnesio_mg = 35, fosforo_mg = 205, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 134), zinco_mg = coalesce(zinco_mg, 0.43), cobre_mcg = 19, manganes_mg = 0.012 where nome = 'Peixe não especificado (inteiro, em posta, em filé, etc.), Cozido(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 0.16), magnesio_mg = 35, fosforo_mg = 205, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 134), zinco_mg = coalesce(zinco_mg, 0.43), cobre_mcg = 19, manganes_mg = 0.012 where nome = 'Peixe não especificado (inteiro, em posta, em filé, etc.), Refogado(a)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 0.16), magnesio_mg = 35, fosforo_mg = 205, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 134), zinco_mg = coalesce(zinco_mg, 0.43), cobre_mcg = 19, manganes_mg = 0.012 where nome = 'Peixe não especificado (inteiro, em posta, em filé, etc.), Ensopado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 0.16), magnesio_mg = 35, fosforo_mg = 205, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 134), zinco_mg = coalesce(zinco_mg, 0.43), cobre_mcg = 19, manganes_mg = 0.012 where nome = 'Peixe não especificado (inteiro, em posta, em filé, etc.), Molho vermelho' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 0.16), magnesio_mg = 35, fosforo_mg = 205, potassio_mg = 372, sodio_mg = coalesce(sodio_mg, 134), zinco_mg = coalesce(zinco_mg, 0.43), cobre_mcg = 19, manganes_mg = 0.012 where nome = 'Peixe não especificado (inteiro, em posta, em filé, etc.), Molho branco' and fonte = 'IBGE' and id_avaliador is null;
