-- Migration 0094: micronutrientes IBGE — lote 14 (preparos "com manteiga/óleo" e óleos/manteiga)
--
-- Continuação do foco em alimentos de consumo diário. 24 itens
-- aprovados: as variantes de preparo "Com manteiga/óleo" e "Ao alho e
-- óleo" de hortaliças, massa e carnes já resolvidas em lotes anteriores
-- (cenoura, couve, jiló, vagem, cebola, macarrão, fígado/carne bovina,
-- carne suína, frango, filé de frango, camarão, salsicha, linguiça) —
-- reaproveitando o mesmo fdc_id já verificado da versão cozida/refogada
-- mais próxima, já que o método de cocção (refogar com um pouco de
-- gordura) é essencialmente o mesmo. Também óleo não especificado (óleo
-- de soja, o mais consumido no Brasil), óleo de dendê e a confirmação de
-- manteiga/margarina que já estavam corretas.
--
-- Trocado 1 fdc_id (Óleo não especificado) cujo registro original
-- (mesma amostra Foundation Foods de "Óleo de soja") não tinha o painel
-- completo de nutrientes.
--
-- Como sempre: coalesce() preserva os valores já existentes nas 12
-- colunas legadas; as 15 colunas novas (migration 0054) recebem o valor
-- USDA diretamente.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 30), ferro_mg = coalesce(ferro_mg, 0.34), magnesio_mg = 10, fosforo_mg = 30, potassio_mg = 235, sodio_mg = coalesce(sodio_mg, 302), zinco_mg = coalesce(zinco_mg, 0.2), cobre_mcg = 17, manganes_mg = 0.155, selenio_mcg = 0.7, vitamina_a_mcg = coalesce(vitamina_a_mcg, 852), vitamina_e_mg = 1.03, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 3.6), tiamina_mg = coalesce(tiamina_mg, 0.066), riboflavina_mg = coalesce(riboflavina_mg, 0.044), niacina_mg = coalesce(niacina_mg, 0.645), acido_pantotenico_mg = 0.232, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.153), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 8.8, vitamina_k_mcg = 13.7, folato_mcg = 2 where nome = 'Cenoura, Com manteiga/óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 150), ferro_mg = coalesce(ferro_mg, 0.84), magnesio_mg = 25, fosforo_mg = 42, potassio_mg = 144, sodio_mg = coalesce(sodio_mg, 252), zinco_mg = coalesce(zinco_mg, 0.27), cobre_mcg = 67, manganes_mg = 0.542, selenio_mcg = 1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 146), vitamina_e_mg = 1.61, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 17.8), tiamina_mg = coalesce(tiamina_mg, 0.063), riboflavina_mg = coalesce(riboflavina_mg, 0.14), niacina_mg = coalesce(niacina_mg, 0.457), acido_pantotenico_mg = 0.17, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.063), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0.4, vitamina_k_mcg = 418.5, folato_mcg = 65 where nome = 'Couve, Ao alho e óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 150), ferro_mg = coalesce(ferro_mg, 0.84), magnesio_mg = 25, fosforo_mg = 42, potassio_mg = 144, sodio_mg = coalesce(sodio_mg, 252), zinco_mg = coalesce(zinco_mg, 0.27), cobre_mcg = 67, manganes_mg = 0.542, selenio_mcg = 1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 146), vitamina_e_mg = 1.61, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 17.8), tiamina_mg = coalesce(tiamina_mg, 0.063), riboflavina_mg = coalesce(riboflavina_mg, 0.14), niacina_mg = coalesce(niacina_mg, 0.457), acido_pantotenico_mg = 0.17, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.063), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0.4, vitamina_k_mcg = 418.5, folato_mcg = 65 where nome = 'Couve, Com manteiga/óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 0.25), magnesio_mg = 11, fosforo_mg = 15, potassio_mg = 123, sodio_mg = coalesce(sodio_mg, 239), zinco_mg = coalesce(zinco_mg, 0.12), cobre_mcg = 59, manganes_mg = 0.113, selenio_mcg = 0.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.41, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1.3), tiamina_mg = coalesce(tiamina_mg, 0.076), riboflavina_mg = coalesce(riboflavina_mg, 0.02), niacina_mg = coalesce(niacina_mg, 0.6), acido_pantotenico_mg = 0.075, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.086), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 9.4, vitamina_k_mcg = 2.9, folato_mcg = 14 where nome = 'Jiló, Com manteiga/óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 44), ferro_mg = coalesce(ferro_mg, 0.65), magnesio_mg = 18, fosforo_mg = 29, potassio_mg = 146, sodio_mg = coalesce(sodio_mg, 239), zinco_mg = coalesce(zinco_mg, 0.25), cobre_mcg = 57, manganes_mg = 0.285, selenio_mcg = 0.2, vitamina_a_mcg = coalesce(vitamina_a_mcg, 35), vitamina_e_mg = 0.46, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 9.7), tiamina_mg = coalesce(tiamina_mg, 0.074), riboflavina_mg = coalesce(riboflavina_mg, 0.097), niacina_mg = coalesce(niacina_mg, 0.614), acido_pantotenico_mg = 0.074, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.056), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 16.9, vitamina_k_mcg = 47.9, folato_mcg = 33 where nome = 'Vagem, Com manteiga/óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 22), ferro_mg = coalesce(ferro_mg, 0.24), magnesio_mg = 11, fosforo_mg = 35, potassio_mg = 166, sodio_mg = coalesce(sodio_mg, 239), zinco_mg = coalesce(zinco_mg, 0.21), cobre_mcg = 67, manganes_mg = 0.153, selenio_mcg = 0.6, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.02, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 5.2), tiamina_mg = coalesce(tiamina_mg, 0.042), riboflavina_mg = coalesce(riboflavina_mg, 0.023), niacina_mg = coalesce(niacina_mg, 0.165), acido_pantotenico_mg = 0.113, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.129), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.8, vitamina_k_mcg = 0.5, folato_mcg = 15 where nome = 'Cebola, Com manteiga/óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7), ferro_mg = coalesce(ferro_mg, 0.5), magnesio_mg = 18, fosforo_mg = 58, potassio_mg = 44, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.51), cobre_mcg = 100, manganes_mg = 0.322, selenio_mcg = 26.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.06, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.02), riboflavina_mg = coalesce(riboflavina_mg, 0.02), niacina_mg = coalesce(niacina_mg, 0.4), acido_pantotenico_mg = 0.112, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.049), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.4, vitamina_k_mcg = 0, folato_mcg = 7 where nome = 'Macarrão, Ao alho e óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 7), ferro_mg = coalesce(ferro_mg, 0.5), magnesio_mg = 18, fosforo_mg = 58, potassio_mg = 44, sodio_mg = coalesce(sodio_mg, 1), zinco_mg = coalesce(zinco_mg, 0.51), cobre_mcg = 100, manganes_mg = 0.322, selenio_mcg = 26.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.06, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.02), riboflavina_mg = coalesce(riboflavina_mg, 0.02), niacina_mg = coalesce(niacina_mg, 0.4), acido_pantotenico_mg = 0.112, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.049), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 6.4, vitamina_k_mcg = 0, folato_mcg = 7 where nome = 'Macarrão, Com manteiga/óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 6.54), magnesio_mg = 21, fosforo_mg = 497, potassio_mg = 352, sodio_mg = coalesce(sodio_mg, 79), zinco_mg = coalesce(zinco_mg, 5.3), cobre_mcg = 14283, manganes_mg = 0.356, selenio_mcg = 36.1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 9442), vitamina_e_mg = 0.51, vitamina_d_mcg = coalesce(vitamina_d_mcg, 1.2), vitamina_c_mg = coalesce(vitamina_c_mg, 1.9), tiamina_mg = coalesce(tiamina_mg, 0.194), riboflavina_mg = coalesce(riboflavina_mg, 3.425), niacina_mg = coalesce(niacina_mg, 17.525), acido_pantotenico_mg = 7.11, vitamina_b6_mg = coalesce(vitamina_b6_mg, 1.017), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 70.58), colina_mg = 426, vitamina_k_mcg = 3.3, folato_mcg = 253 where nome = 'Fígado bovino, Ao alho e óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 20), ferro_mg = coalesce(ferro_mg, 1.11), magnesio_mg = 24, fosforo_mg = 221, potassio_mg = 341, sodio_mg = coalesce(sodio_mg, 57), zinco_mg = coalesce(zinco_mg, 3.06), cobre_mcg = 90, manganes_mg = 0.01, selenio_mcg = 42, vitamina_a_mcg = coalesce(vitamina_a_mcg, 2), vitamina_e_mg = 0.13, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.9), vitamina_c_mg = coalesce(vitamina_c_mg, 0.1), tiamina_mg = coalesce(tiamina_mg, 0.611), riboflavina_mg = coalesce(riboflavina_mg, 0.29), niacina_mg = coalesce(niacina_mg, 6.047), acido_pantotenico_mg = 0.844, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.542), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.7), colina_mg = 80.1, vitamina_k_mcg = 0, folato_mcg = 2 where nome = 'Carne suína, Ao alho e óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 2.53), magnesio_mg = 20, fosforo_mg = 183, potassio_mg = 242, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 6.98), cobre_mcg = 104, manganes_mg = 0.01, selenio_mcg = 28.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.53, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.061), riboflavina_mg = coalesce(riboflavina_mg, 0.178), niacina_mg = coalesce(niacina_mg, 4.273), acido_pantotenico_mg = 0.594, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.295), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.22), colina_mg = 114.7, vitamina_k_mcg = 1.9, folato_mcg = 9 where nome = 'Carne bovina, Ao alho e óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 17), ferro_mg = coalesce(ferro_mg, 2.53), magnesio_mg = 20, fosforo_mg = 183, potassio_mg = 242, sodio_mg = coalesce(sodio_mg, 50), zinco_mg = coalesce(zinco_mg, 6.98), cobre_mcg = 104, manganes_mg = 0.01, selenio_mcg = 28.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.53, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.3), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.061), riboflavina_mg = coalesce(riboflavina_mg, 0.178), niacina_mg = coalesce(niacina_mg, 4.273), acido_pantotenico_mg = 0.594, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.295), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.22), colina_mg = 114.7, vitamina_k_mcg = 1.9, folato_mcg = 9 where nome = 'Carne bovina, Com manteiga/óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 13), ferro_mg = coalesce(ferro_mg, 1.64), magnesio_mg = 19, fosforo_mg = 151, potassio_mg = 171, sodio_mg = coalesce(sodio_mg, 67), zinco_mg = coalesce(zinco_mg, 1.96), cobre_mcg = 79, manganes_mg = 0.034, selenio_mcg = 21.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 182), vitamina_e_mg = 0.28, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1), tiamina_mg = coalesce(tiamina_mg, 0.054), riboflavina_mg = coalesce(riboflavina_mg, 0.221), niacina_mg = coalesce(niacina_mg, 5.677), acido_pantotenico_mg = 0.878, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.234), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.95), colina_mg = 67.2, vitamina_k_mcg = 1.9, folato_mcg = 25 where nome = 'Frango em pedaços, Ao alho e óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 13), ferro_mg = coalesce(ferro_mg, 1.64), magnesio_mg = 19, fosforo_mg = 151, potassio_mg = 171, sodio_mg = coalesce(sodio_mg, 67), zinco_mg = coalesce(zinco_mg, 1.96), cobre_mcg = 79, manganes_mg = 0.034, selenio_mcg = 21.4, vitamina_a_mcg = coalesce(vitamina_a_mcg, 182), vitamina_e_mg = 0.28, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 1), tiamina_mg = coalesce(tiamina_mg, 0.054), riboflavina_mg = coalesce(riboflavina_mg, 0.221), niacina_mg = coalesce(niacina_mg, 5.677), acido_pantotenico_mg = 0.878, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.234), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.95), colina_mg = 67.2, vitamina_k_mcg = 1.9, folato_mcg = 25 where nome = 'Frango em pedaços, Com manteiga/óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 13), ferro_mg = coalesce(ferro_mg, 0.88), magnesio_mg = 24, fosforo_mg = 165, potassio_mg = 187, sodio_mg = coalesce(sodio_mg, 63), zinco_mg = coalesce(zinco_mg, 0.97), cobre_mcg = 43, manganes_mg = 0.018, selenio_mcg = 22.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 6), vitamina_e_mg = 0.27, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.1), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.042), riboflavina_mg = coalesce(riboflavina_mg, 0.119), niacina_mg = coalesce(niacina_mg, 8.469), acido_pantotenico_mg = 0.573, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.33), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.23), colina_mg = 78.5, vitamina_k_mcg = 0.2, folato_mcg = 3 where nome = 'Filé de frango, Ao alho e óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 70), ferro_mg = coalesce(ferro_mg, 0.51), magnesio_mg = 39, fosforo_mg = 237, potassio_mg = 259, sodio_mg = coalesce(sodio_mg, 111), zinco_mg = coalesce(zinco_mg, 1.64), cobre_mcg = 379, manganes_mg = 0.033 where nome = 'Camarão, Ao alho e óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 107), ferro_mg = coalesce(ferro_mg, 1.12), magnesio_mg = 11, fosforo_mg = 180, potassio_mg = 323, sodio_mg = coalesce(sodio_mg, 914), zinco_mg = coalesce(zinco_mg, 1.25), cobre_mcg = 40, manganes_mg = 0.02, selenio_mcg = 13.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 31), vitamina_e_mg = 0.45, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.6), vitamina_c_mg = coalesce(vitamina_c_mg, 19.4), tiamina_mg = coalesce(tiamina_mg, 0.044), riboflavina_mg = coalesce(riboflavina_mg, 0.145), niacina_mg = coalesce(niacina_mg, 2.672), acido_pantotenico_mg = 0.551, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.067), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.69), colina_mg = 54.3, vitamina_k_mcg = 1.7, folato_mcg = 9 where nome = 'Salsicha no varejo, Ao alho e óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 107), ferro_mg = coalesce(ferro_mg, 1.12), magnesio_mg = 11, fosforo_mg = 180, potassio_mg = 323, sodio_mg = coalesce(sodio_mg, 914), zinco_mg = coalesce(zinco_mg, 1.25), cobre_mcg = 40, manganes_mg = 0.02, selenio_mcg = 13.3, vitamina_a_mcg = coalesce(vitamina_a_mcg, 31), vitamina_e_mg = 0.45, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.6), vitamina_c_mg = coalesce(vitamina_c_mg, 19.4), tiamina_mg = coalesce(tiamina_mg, 0.044), riboflavina_mg = coalesce(riboflavina_mg, 0.145), niacina_mg = coalesce(niacina_mg, 2.672), acido_pantotenico_mg = 0.551, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.067), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.69), colina_mg = 54.3, vitamina_k_mcg = 1.7, folato_mcg = 9 where nome = 'Salsicha no varejo, Com manteiga/óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 11), ferro_mg = coalesce(ferro_mg, 1.57), magnesio_mg = 14, fosforo_mg = 141, potassio_mg = 258, sodio_mg = coalesce(sodio_mg, 813), zinco_mg = coalesce(zinco_mg, 4.38), cobre_mcg = 69, manganes_mg = 0, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 13), vitamina_e_mg = 0.24, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.048), riboflavina_mg = coalesce(riboflavina_mg, 0.15), niacina_mg = coalesce(niacina_mg, 3.6), acido_pantotenico_mg = 0.515, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.313), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 2.01), colina_mg = 51.4, vitamina_k_mcg = 1.1, folato_mcg = 3 where nome = 'Linguiça (suína, bovina, mista, etc.), Com manteiga/óleo' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 0), ferro_mg = coalesce(ferro_mg, 0.05), magnesio_mg = 0, fosforo_mg = 0, potassio_mg = 0, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 0.01), cobre_mcg = 0, manganes_mg = 0, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 8.18, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0.2, vitamina_k_mcg = 183.9, folato_mcg = 0 where nome = 'Óleo não especificado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 0), ferro_mg = coalesce(ferro_mg, 0.01), magnesio_mg = 0, fosforo_mg = 0, potassio_mg = 0, sodio_mg = coalesce(sodio_mg, 0), zinco_mg = coalesce(zinco_mg, 0), cobre_mcg = 0, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 15.94, vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 0.3, vitamina_k_mcg = 8, folato_mcg = 0 where nome = 'Óleo de dendê' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 24), ferro_mg = coalesce(ferro_mg, 0.02), magnesio_mg = 2, fosforo_mg = 24, potassio_mg = 24, sodio_mg = coalesce(sodio_mg, 643), zinco_mg = coalesce(zinco_mg, 0.09), cobre_mcg = 0, manganes_mg = 0, selenio_mcg = 1, vitamina_a_mcg = coalesce(vitamina_a_mcg, 684), vitamina_e_mg = 2.32, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.005), riboflavina_mg = coalesce(riboflavina_mg, 0.034), niacina_mg = coalesce(niacina_mg, 0.042), acido_pantotenico_mg = 0.11, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.003), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.17), colina_mg = 18.8, vitamina_k_mcg = 7, folato_mcg = 3 where nome = 'Manteiga de garrafa' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 3), ferro_mg = coalesce(ferro_mg, 0), magnesio_mg = 1, fosforo_mg = 5, potassio_mg = 17, sodio_mg = coalesce(sodio_mg, 657), zinco_mg = coalesce(zinco_mg, 0), cobre_mcg = 0, manganes_mg = 0, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 819), vitamina_e_mg = 15.43, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.1), tiamina_mg = coalesce(tiamina_mg, 0), riboflavina_mg = coalesce(riboflavina_mg, 0), niacina_mg = coalesce(niacina_mg, 0), acido_pantotenico_mg = 0.085, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.08), colina_mg = 12.4, vitamina_k_mcg = 91.7, folato_mcg = 1 where nome = 'Margarina com ou sem sal' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 6), ferro_mg = coalesce(ferro_mg, 0.04), magnesio_mg = 1, fosforo_mg = 7, potassio_mg = 51, sodio_mg = coalesce(sodio_mg, 584), zinco_mg = coalesce(zinco_mg, 0.02), cobre_mcg = 9, manganes_mg = 0.005, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 1348), vitamina_e_mg = 13.45, vitamina_d_mcg = coalesce(vitamina_d_mcg, 17.5), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.003), riboflavina_mg = coalesce(riboflavina_mg, 0.003), niacina_mg = coalesce(niacina_mg, 0.004), acido_pantotenico_mg = 0.03, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.384), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.06), colina_mg = 12.4, vitamina_k_mcg = 74.6, folato_mcg = 1 where nome = 'Margarina light' and fonte = 'IBGE' and id_avaliador is null;
