-- Migration 0095: micronutrientes IBGE — lote 15 (pão e café)
--
-- Continuação do foco em alimentos de consumo diário: pão de forma e
-- café, dois itens centrais do café da manhã brasileiro. 9 itens
-- aprovados.
--
-- Pão: corrigido de "Bread, egg" (pão tipo brioche/challah, produto
-- errado) pra pão de forma branco comercial comum, o mais próximo do que
-- "pão de forma industrializado" realmente significa.
--
-- Café: corrigido de "SILK Coffee, soymilk" (bebida de soja sabor café,
-- produto completamente diferente — nem é café de verdade) pra café
-- coado/espresso de verdade.
--
-- Como sempre: coalesce() preserva os valores já existentes nas 12
-- colunas legadas; as 15 colunas novas (migration 0054) recebem o valor
-- USDA diretamente.

update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 144), ferro_mg = coalesce(ferro_mg, 3.61), magnesio_mg = 23, fosforo_mg = 98, potassio_mg = 126, sodio_mg = coalesce(sodio_mg, 490), zinco_mg = coalesce(zinco_mg, 0.74), cobre_mcg = 101, manganes_mg = 0.536, selenio_mcg = 22, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.22, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.533), riboflavina_mg = coalesce(riboflavina_mg, 0.243), niacina_mg = coalesce(niacina_mg, 4.78), acido_pantotenico_mg = 0.536, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.087), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 14.6, vitamina_k_mcg = 0.2, folato_mcg = 171 where nome = 'Pão de forma industrializado de qualquer marca' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 144), ferro_mg = coalesce(ferro_mg, 3.61), magnesio_mg = 23, fosforo_mg = 98, potassio_mg = 126, sodio_mg = coalesce(sodio_mg, 490), zinco_mg = coalesce(zinco_mg, 0.74), cobre_mcg = 101, manganes_mg = 0.536, selenio_mcg = 22, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.22, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.533), riboflavina_mg = coalesce(riboflavina_mg, 0.243), niacina_mg = coalesce(niacina_mg, 4.78), acido_pantotenico_mg = 0.536, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.087), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 14.6, vitamina_k_mcg = 0.2, folato_mcg = 171 where nome = 'Pão não especificado' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 144), ferro_mg = coalesce(ferro_mg, 3.61), magnesio_mg = 23, fosforo_mg = 98, potassio_mg = 126, sodio_mg = coalesce(sodio_mg, 490), zinco_mg = coalesce(zinco_mg, 0.74), cobre_mcg = 101, manganes_mg = 0.536, selenio_mcg = 22, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.22, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.533), riboflavina_mg = coalesce(riboflavina_mg, 0.243), niacina_mg = coalesce(niacina_mg, 4.78), acido_pantotenico_mg = 0.536, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.087), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 14.6, vitamina_k_mcg = 0.2, folato_mcg = 171 where nome = 'Pão diet (de forma industrializado)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 144), ferro_mg = coalesce(ferro_mg, 3.61), magnesio_mg = 23, fosforo_mg = 98, potassio_mg = 126, sodio_mg = coalesce(sodio_mg, 490), zinco_mg = coalesce(zinco_mg, 0.74), cobre_mcg = 101, manganes_mg = 0.536, selenio_mcg = 22, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.22, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.533), riboflavina_mg = coalesce(riboflavina_mg, 0.243), niacina_mg = coalesce(niacina_mg, 4.78), acido_pantotenico_mg = 0.536, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.087), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 14.6, vitamina_k_mcg = 0.2, folato_mcg = 171 where nome = 'Pão light (de forma industrializado)' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 119), ferro_mg = coalesce(ferro_mg, 3.33), magnesio_mg = 26, fosforo_mg = 103, potassio_mg = 131, sodio_mg = coalesce(sodio_mg, 537), zinco_mg = coalesce(zinco_mg, 0.68), cobre_mcg = 138, manganes_mg = 0.421, selenio_mcg = 31, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.24, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.415), riboflavina_mg = coalesce(riboflavina_mg, 0.337), niacina_mg = coalesce(niacina_mg, 3.926), acido_pantotenico_mg = 0.278, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.063), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0.02), colina_mg = 16, vitamina_k_mcg = 3.4, folato_mcg = 160 where nome = 'Torrada de qualquer pão' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 144), ferro_mg = coalesce(ferro_mg, 3.61), magnesio_mg = 23, fosforo_mg = 98, potassio_mg = 126, sodio_mg = coalesce(sodio_mg, 490), zinco_mg = coalesce(zinco_mg, 0.74), cobre_mcg = 101, manganes_mg = 0.536, selenio_mcg = 22, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.22, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.533), riboflavina_mg = coalesce(riboflavina_mg, 0.243), niacina_mg = coalesce(niacina_mg, 4.78), acido_pantotenico_mg = 0.536, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.087), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 14.6, vitamina_k_mcg = 0.2, folato_mcg = 171 where nome = 'Pão de hambúrguer' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 2), ferro_mg = coalesce(ferro_mg, 0.01), magnesio_mg = 3, fosforo_mg = 3, potassio_mg = 49, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 0.02), cobre_mcg = 2, manganes_mg = 0.023, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.01, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.014), riboflavina_mg = coalesce(riboflavina_mg, 0.076), niacina_mg = coalesce(niacina_mg, 0.191), acido_pantotenico_mg = 0.254, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.001), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 2.6, vitamina_k_mcg = 0.1, folato_mcg = 2 where nome = 'Café' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 2), ferro_mg = coalesce(ferro_mg, 0.13), magnesio_mg = 80, fosforo_mg = 7, potassio_mg = 115, sodio_mg = coalesce(sodio_mg, 14), zinco_mg = coalesce(zinco_mg, 0.05), cobre_mcg = 50, manganes_mg = 0.05, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.01, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0.2), tiamina_mg = coalesce(tiamina_mg, 0.001), riboflavina_mg = coalesce(riboflavina_mg, 0.177), niacina_mg = coalesce(niacina_mg, 5.207), acido_pantotenico_mg = 0.028, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.002), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 2.6, vitamina_k_mcg = 0.1, folato_mcg = 1 where nome = 'Café tipo expresso' and fonte = 'IBGE' and id_avaliador is null;
update public.tabela_alimentos set calcio_mg = coalesce(calcio_mg, 2), ferro_mg = coalesce(ferro_mg, 0.01), magnesio_mg = 3, fosforo_mg = 3, potassio_mg = 49, sodio_mg = coalesce(sodio_mg, 2), zinco_mg = coalesce(zinco_mg, 0.02), cobre_mcg = 2, manganes_mg = 0.023, selenio_mcg = 0, vitamina_a_mcg = coalesce(vitamina_a_mcg, 0), vitamina_e_mg = 0.01, vitamina_d_mcg = coalesce(vitamina_d_mcg, 0), vitamina_c_mg = coalesce(vitamina_c_mg, 0), tiamina_mg = coalesce(tiamina_mg, 0.014), riboflavina_mg = coalesce(riboflavina_mg, 0.076), niacina_mg = coalesce(niacina_mg, 0.191), acido_pantotenico_mg = 0.254, vitamina_b6_mg = coalesce(vitamina_b6_mg, 0.001), vitamina_b12_mcg = coalesce(vitamina_b12_mcg, 0), colina_mg = 2.6, vitamina_k_mcg = 0.1, folato_mcg = 2 where nome = 'Café da manha' and fonte = 'IBGE' and id_avaliador is null;
