-- Gerador de Orçamentos e Protocolos: nutricionista monta uma lista de
-- itens (serviço + valor), gera um PDF com marca própria + chave Pix, e
-- manda pro cliente via link do WhatsApp (envio manual, mesmo padrão do
-- Questionário — sem API automática, pra não sobrecarregar o zap do
-- nutri).
--
-- id_paciente é nullable de propósito: cobre tanto orçamento pra um
-- paciente já cadastrado quanto pra um lead novo/avulso (nome_lead +
-- telefone_lead), que ainda não tem registro em pacientes. Integração
-- mais profunda com uma lista de leads/CRM fica pra outra hora.
--
-- itens fica em jsonb (não vira tabela filha): são só linhas
-- descrição+valor, sem FK própria nem necessidade de serem consultadas
-- isoladamente — não há necessidade relacional real aqui.
--
-- link_pagamento é texto livre (não integração de API): o nutricionista
-- cola ali o link de checkout já gerado por fora (Mercado Pago, PagBank,
-- Stripe etc — cada gateway tem seu próprio link por transação/valor,
-- não dá pra generalizar num campo fixo por nutricionista como a chave
-- Pix). Fica nullable, exibido como botão "Pagar com Cartão" quando
-- presente.
--
-- mostrar_pix/mostrar_cartao: a chave Pix vem automática do perfil do
-- avaliador (não é campo por orçamento), então o único jeito de tirá-la
-- de UM orçamento específico é um liga/desliga próprio — mesma lógica
-- pro cartão, independente de link_pagamento estar preenchido ou não.
--
-- token_publico segue o mesmo padrão de exames_solicitacoes
-- (0033_exames_laboratoriais.sql): leitura pública pela tabela toda,
-- mas só quem tem o token aleatório acha a linha.
create table if not exists public.orcamentos (
  id              bigint generated by default as identity primary key,
  id_avaliador    uuid not null references auth.users(id) on delete cascade,
  id_paciente     bigint references public.pacientes(id) on delete set null,
  nome_lead       text,
  telefone_lead   text,
  titulo          text not null default 'Orçamento',
  itens           jsonb not null default '[]'::jsonb,
  desconto        numeric(10,2) not null default 0,
  valor_total     numeric(10,2) not null default 0,
  validade_dias   integer not null default 7,
  link_pagamento  text,
  mostrar_pix     boolean not null default true,
  mostrar_cartao  boolean not null default true,
  status          text not null default 'pendente' check (status in ('pendente', 'aceito', 'recusado')),
  token_publico   uuid not null default gen_random_uuid() unique,
  created_at      timestamptz not null default now()
);

create index if not exists idx_orcamentos_avaliador on public.orcamentos(id_avaliador);
create index if not exists idx_orcamentos_paciente on public.orcamentos(id_paciente);

alter table public.orcamentos enable row level security;

drop policy if exists "orcamentos_isolamento_avaliador" on public.orcamentos;
create policy "orcamentos_isolamento_avaliador" on public.orcamentos
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());

drop policy if exists "orcamentos_leitura_publica_via_token" on public.orcamentos;
create policy "orcamentos_leitura_publica_via_token" on public.orcamentos
  for select to anon using (true);
