-- CRM: funil visual de atendimento (Roadmap "CRM para Nutricionistas").
-- Tabela separada de pacientes, não uma coluna a mais nela — um lead ainda
-- frio não deve contar na cota de 7 pacientes do plano grátis
-- (Pacientes.jsx). Quando o nutricionista fecha negócio, converte o lead
-- num paciente de verdade (insert em pacientes + liga id_paciente aqui);
-- o card continua no funil até "Cliente Ativo" ou "Perdido".
--
-- Mesmo padrão de sempre (ver comentário completo em
-- 0001_prontuario_prescricao.sql): PK bigint identity, id_avaliador uuid
-- referenciando auth.users(id), RLS por comparação direta id_avaliador =
-- auth.uid() (mais barato que subquery em avaliadores).
create table public.leads_funil (
  id            bigint generated by default as identity primary key,
  id_avaliador  uuid not null references auth.users(id) on delete cascade,
  id_paciente   bigint references public.pacientes(id) on delete set null,
  nome          text not null,
  telefone      text,
  email         text,
  etapa         text not null default 'lead'
                  check (etapa in ('lead', 'agendado', 'realizado', 'ativo', 'perdido')),
  observacoes   text,
  created_at    timestamptz not null default now()
);

create index idx_leads_funil_avaliador on public.leads_funil(id_avaliador);

alter table public.leads_funil enable row level security;

create policy "leads_funil_isolamento_avaliador" on public.leads_funil
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());
