-- Diário Alimentar: o paciente registra o que realmente comeu, dia a dia,
-- refeição por refeição (mesma estrutura de refeições do Plano Alimentar
-- ativo dele) — sem ver meta/kcal/macro, só alimento e quantidade. O
-- nutricionista compara isso com o prescrito (calcularMacrosItem/
-- somarMacros, ver src/utils/calculoNutricional.js) num grid dia x refeição.
--
-- Uma linha por alimento registrado, no mesmo espírito de itens_refeicao.
-- nome_refeicao é copiado como texto (não FK pra refeicoes_prescritas) de
-- propósito: se o plano mudar depois, o registro antigo continua íntegro.
create table public.diario_alimentar_itens (
  id                  bigint generated by default as identity primary key,
  id_paciente         bigint not null references public.pacientes(id) on delete cascade,
  id_avaliador        uuid not null references auth.users(id) on delete cascade,
  data                date not null,
  nome_refeicao       text not null,
  id_alimento         bigint not null references public.tabela_alimentos(id),
  quantidade_g        numeric(8,2) not null,
  unidade_medida      text,
  quantidade_medida   numeric(8,2),
  created_at          timestamptz not null default now()
);

create index idx_diario_paciente_data on public.diario_alimentar_itens(id_paciente, data);

alter table public.diario_alimentar_itens enable row level security;

-- Nutricionista: só lê/gerencia os registros dos próprios pacientes.
create policy "diario_isolamento_avaliador" on public.diario_alimentar_itens
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());

-- Paciente (anônimo, via token já resolvido no client, mesmo padrão de
-- planos_alimentares/checkins_semanais_pacientes): registra e edita os
-- próprios, direto do Portal do Paciente.
create policy "diario_paciente_leitura" on public.diario_alimentar_itens
  for select to anon
  using (exists (select 1 from public.pacientes p where p.id = id_paciente));

-- with check cruza id_avaliador com o dono real do paciente (não confia
-- cegamente no valor que o client anônimo manda) — sem isso, um insert
-- anônimo poderia gravar um id_avaliador qualquer junto de um id_paciente
-- válido e o registro ficaria "órfão" (não aparece pro nutricionista
-- certo, nem some pra ninguém checar).
create policy "diario_paciente_escrita" on public.diario_alimentar_itens
  for insert to anon
  with check (
    exists (
      select 1 from public.pacientes p
      where p.id = id_paciente and p.id_avaliador = diario_alimentar_itens.id_avaliador
    )
  );

create policy "diario_paciente_exclusao" on public.diario_alimentar_itens
  for delete to anon
  using (exists (select 1 from public.pacientes p where p.id = id_paciente));
