-- Observação livre do paciente por refeição/dia no Diário Alimentar — ex:
-- "comi fora de hora", "sem fome hoje", "substitui sem querer". Separado de
-- diario_alimentar_itens (uma linha por alimento) porque é 1 texto por
-- refeição/dia, não por item; upsert por (id_paciente, data, nome_refeicao)
-- deixa salvar/atualizar sem precisar saber se já existe.
create table public.diario_alimentar_observacoes (
  id            bigint generated by default as identity primary key,
  id_paciente   bigint not null references public.pacientes(id) on delete cascade,
  id_avaliador  uuid not null references auth.users(id) on delete cascade,
  data          date not null,
  nome_refeicao text not null,
  observacao    text not null default '',
  updated_at    timestamptz not null default now(),
  unique (id_paciente, data, nome_refeicao)
);

create index idx_diario_obs_paciente_data on public.diario_alimentar_observacoes(id_paciente, data);

alter table public.diario_alimentar_observacoes enable row level security;

create policy "diario_obs_isolamento_avaliador" on public.diario_alimentar_observacoes
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());

create policy "diario_obs_paciente_leitura" on public.diario_alimentar_observacoes
  for select to anon
  using (exists (select 1 from public.pacientes p where p.id = id_paciente));

-- with check cruza id_avaliador com o dono real do paciente, mesmo padrão
-- de diario_paciente_escrita em 0116_diario_alimentar.sql.
create policy "diario_obs_paciente_escrita" on public.diario_alimentar_observacoes
  for insert to anon
  with check (
    exists (
      select 1 from public.pacientes p
      where p.id = id_paciente and p.id_avaliador = diario_alimentar_observacoes.id_avaliador
    )
  );

create policy "diario_obs_paciente_atualizacao" on public.diario_alimentar_observacoes
  for update to anon
  using (exists (select 1 from public.pacientes p where p.id = id_paciente))
  with check (
    exists (
      select 1 from public.pacientes p
      where p.id = id_paciente and p.id_avaliador = diario_alimentar_observacoes.id_avaliador
    )
  );
