-- Modelos de Grupo de Alimentos: listas de alimentos intercambiáveis
-- (equivalência calórica), reutilizáveis em qualquer Plano Alimentar. Ex:
-- "Carboidratos (refeições principais) — 150kcal" contendo Arroz cozido,
-- Batata doce, Macarrão etc., cada um calibrado pra ~150kcal.
--
-- Schema propositalmente adiado desde 0001_prontuario_prescricao.sql
-- ("Grupos de Alimentos ficam para quando a tela de cada um for construída")
-- — mesmo padrão de modelo pai + itens filho já usado em
-- modelos_refeicoes/modelos_refeicoes_itens (0014_modelos_refeicoes_planos.sql):
-- RLS via id_avaliador direto no pai, via join no filho.
--
-- Ao inserir um grupo numa refeição, o app NÃO grava uma referência nova em
-- itens_refeicao (id_alimento lá é not null em todas as migrations até hoje,
-- e mexer nisso obrigaria alterar as 3 cópias de calcularMacrosItem) — em vez
-- disso, o primeiro alimento do grupo vira o item normal e os demais entram
-- como substitutos_item dele, reaproveitando o recurso de substitutos que já
-- existe e já é calculado/exibido em todo lugar sem nenhuma mudança.

create table if not exists public.grupos_alimentos_modelo (
  id            bigint generated by default as identity primary key,
  id_avaliador  uuid not null references auth.users(id) on delete cascade,
  titulo        text not null default 'Grupo de Alimentos',
  kcal_alvo     numeric(10,2),
  created_at    timestamptz not null default now()
);

create index if not exists idx_grupos_alimentos_modelo_avaliador on public.grupos_alimentos_modelo(id_avaliador);

alter table public.grupos_alimentos_modelo enable row level security;

drop policy if exists "grupos_alimentos_modelo_isolamento_avaliador" on public.grupos_alimentos_modelo;
create policy "grupos_alimentos_modelo_isolamento_avaliador" on public.grupos_alimentos_modelo
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());


create table if not exists public.grupos_alimentos_modelo_itens (
  id                  bigint generated by default as identity primary key,
  id_grupo            bigint not null references public.grupos_alimentos_modelo(id) on delete cascade,
  id_alimento         bigint not null references public.tabela_alimentos(id) on delete restrict,
  quantidade_g        numeric(8,2) not null,
  -- Medida caseira digitada pelo nutri (ex: "5 colheres de sopa cheias") —
  -- só exibição, mesmo espírito de unidade_medida/quantidade_medida em
  -- itens_refeicao: quantidade_g continua sendo a única fonte usada no
  -- cálculo de macro.
  descricao_porcao    text,
  ordem               integer not null default 0
);

create index if not exists idx_grupos_alimentos_modelo_itens_grupo on public.grupos_alimentos_modelo_itens(id_grupo);
create index if not exists idx_grupos_alimentos_modelo_itens_alimento on public.grupos_alimentos_modelo_itens(id_alimento);

alter table public.grupos_alimentos_modelo_itens enable row level security;

-- Sem id_avaliador direto — dono verificado subindo item -> grupo, mesmo
-- padrão já usado em modelos_refeicoes_itens/itens_refeicao.
drop policy if exists "grupos_alimentos_modelo_itens_isolamento_via_grupo" on public.grupos_alimentos_modelo_itens;
create policy "grupos_alimentos_modelo_itens_isolamento_via_grupo" on public.grupos_alimentos_modelo_itens
  for all using (
    exists (
      select 1 from public.grupos_alimentos_modelo g
      where g.id = grupos_alimentos_modelo_itens.id_grupo
        and g.id_avaliador = auth.uid()
    )
  );
