-- Receitas culinárias vinculáveis ao Plano Alimentar (já citado como escopo
-- futuro em 0001_prontuario_prescricao.sql, agora construído).
--
-- id_avaliador é NULLABLE desde o início (lição do grupo de alimentos
-- padrão, migration 0122): receitas "de fábrica" entram com id_avaliador
-- null e ficam visíveis pra todo nutricionista, no mesmo padrão de
-- tabela_alimentos ("alimentos_leitura_oficial_ou_proprio"); receitas
-- criadas pela tela continuam privadas (id_avaliador = auth.uid()).
--
-- Os campos de nutriente (energia_kcal...vitamina_k_mcg) são os MESMOS de
-- tabela_alimentos, mas aqui guardam o TOTAL da receita inteira
-- (peso_final_g), não por 100g — o app converte na hora de sincronizar com
-- tabela_alimentos (ver Receitas.jsx).

create table if not exists public.receitas (
  id                          bigint generated by default as identity primary key,
  id_avaliador                uuid references auth.users(id) on delete cascade,
  nome                        text not null,
  descricao                   text,
  imagem_url                  text,
  modo_preparo                text,
  peso_final_g                numeric(8,2),
  rendimento_porcoes          numeric(8,2),
  tempo_preparo_min           integer,
  tags                        text[] not null default '{}',
  habilitado_planos           boolean not null default false,
  id_alimento_sincronizado    bigint references public.tabela_alimentos(id) on delete set null,
  energia_kcal numeric(10,3), proteina_g numeric(10,3), lipidios_g numeric(10,3),
  carboidrato_g numeric(10,3), fibra_g numeric(10,3), acucares_g numeric(10,3),
  gorduras_saturadas_g numeric(10,3), gorduras_trans_g numeric(10,3), colesterol_mg numeric(10,3),
  calcio_mg numeric(10,3), ferro_mg numeric(10,3), sodio_mg numeric(10,3), zinco_mg numeric(10,3),
  vitamina_a_mcg numeric(10,3), vitamina_c_mg numeric(10,3), vitamina_d_mcg numeric(10,3),
  tiamina_mg numeric(10,3), riboflavina_mg numeric(10,3), niacina_mg numeric(10,3),
  vitamina_b6_mg numeric(10,3), vitamina_b12_mcg numeric(10,3), magnesio_mg numeric(10,3),
  fosforo_mg numeric(10,3), potassio_mg numeric(10,3), cromo_mcg numeric(10,3),
  cobre_mcg numeric(10,3), iodo_mcg numeric(10,3), manganes_mg numeric(10,3),
  molibdenio_mcg numeric(10,3), selenio_mcg numeric(10,3), vitamina_e_mg numeric(10,3),
  acido_pantotenico_mg numeric(10,3), biotina_mcg numeric(10,3), folato_mcg numeric(10,3),
  colina_mg numeric(10,3), vitamina_k_mcg numeric(10,3),
  created_at                  timestamptz not null default now()
);

create index if not exists idx_receitas_avaliador on public.receitas(id_avaliador);

alter table public.receitas enable row level security;

create policy "receitas_leitura_oficial_ou_proprio" on public.receitas
  for select using (id_avaliador is null or id_avaliador = auth.uid());

create policy "receitas_escrita_somente_proprio" on public.receitas
  for insert with check (id_avaliador = auth.uid());

create policy "receitas_update_somente_proprio" on public.receitas
  for update using (id_avaliador = auth.uid()) with check (id_avaliador = auth.uid());

create policy "receitas_delete_somente_proprio" on public.receitas
  for delete using (id_avaliador = auth.uid());


create table if not exists public.receitas_ingredientes (
  id            bigint generated by default as identity primary key,
  id_receita    bigint not null references public.receitas(id) on delete cascade,
  id_alimento   bigint not null references public.tabela_alimentos(id) on delete restrict,
  quantidade_g  numeric(8,2) not null,
  ordem         integer not null default 0
);

create index if not exists idx_receitas_ingredientes_receita on public.receitas_ingredientes(id_receita);

alter table public.receitas_ingredientes enable row level security;

create policy "receitas_ingredientes_leitura_oficial_ou_proprio" on public.receitas_ingredientes
  for select using (
    exists (
      select 1 from public.receitas r
      where r.id = receitas_ingredientes.id_receita
        and (r.id_avaliador is null or r.id_avaliador = auth.uid())
    )
  );

create policy "receitas_ingredientes_escrita_via_receita_propria" on public.receitas_ingredientes
  for insert with check (
    exists (select 1 from public.receitas r where r.id = receitas_ingredientes.id_receita and r.id_avaliador = auth.uid())
  );

create policy "receitas_ingredientes_update_via_receita_propria" on public.receitas_ingredientes
  for update using (
    exists (select 1 from public.receitas r where r.id = receitas_ingredientes.id_receita and r.id_avaliador = auth.uid())
  );

create policy "receitas_ingredientes_delete_via_receita_propria" on public.receitas_ingredientes
  for delete using (
    exists (select 1 from public.receitas r where r.id = receitas_ingredientes.id_receita and r.id_avaliador = auth.uid())
  );


-- Alimento "sincronizado" de uma receita habilitada pra uso em planos: um
-- alimento normal em tabela_alimentos com nutrientes por 100g derivados do
-- total da receita, pra aparecer na busca de alimento (AdicionarItemForm)
-- e funcionar em qualquer refeição sem nenhuma mudança de cálculo.
alter table public.tabela_alimentos add column if not exists id_receita bigint references public.receitas(id) on delete set null;
create index if not exists idx_alimentos_receita on public.tabela_alimentos(id_receita);
