-- Vínculo receita <-> paciente: o nutricionista escolhe, dentro do perfil
-- de cada paciente, quais receitas do catálogo (Biblioteca > Receitas)
-- ficam visíveis pra ele no Portal do Paciente. Mesmo padrão de
-- checkins_semanais_pacientes/diario_alimentar_itens: tabela de junção com
-- id_avaliador (isolamento normal do nutri) + id_paciente. Existência da
-- linha = receita visível — sem coluna booleana extra, não precisa de um
-- estado "atribuída mas escondida".

create table if not exists public.receitas_pacientes (
  id            bigint generated by default as identity primary key,
  id_paciente   bigint not null references public.pacientes(id) on delete cascade,
  id_receita    bigint not null references public.receitas(id) on delete cascade,
  id_avaliador  uuid not null references auth.users(id) on delete cascade,
  created_at    timestamptz not null default now(),
  unique (id_paciente, id_receita)
);

create index if not exists idx_receitas_pacientes_paciente on public.receitas_pacientes(id_paciente);
create index if not exists idx_receitas_pacientes_receita on public.receitas_pacientes(id_receita);
create index if not exists idx_receitas_pacientes_avaliador on public.receitas_pacientes(id_avaliador);

alter table public.receitas_pacientes enable row level security;

create policy "receitas_pacientes_isolamento_avaliador" on public.receitas_pacientes
  for all using (id_avaliador = auth.uid())
  with check (id_avaliador = auth.uid());

-- Paciente (anônimo, via token já resolvido no client — mesmo padrão de
-- planos_alimentares/diario_alimentar_itens em 0018/0116).
create policy "receitas_pacientes_leitura_publica" on public.receitas_pacientes
  for select to anon using (
    exists (select 1 from public.pacientes p where p.id = receitas_pacientes.id_paciente)
  );

-- receitas/receitas_ingredientes (migration 0123) só tinham política de
-- leitura pro dono (auth.uid()) — precisam de uma política nova pro
-- 'anon', encadeada via receitas_pacientes, mesmo padrão de
-- exames_registros -> exames_registros_grupos/itens (0034).
create policy "receitas_leitura_publica_via_paciente" on public.receitas
  for select to anon using (
    exists (
      select 1 from public.receitas_pacientes rp
      join public.pacientes p on p.id = rp.id_paciente
      where rp.id_receita = receitas.id
    )
  );

create policy "receitas_ingredientes_leitura_publica_via_paciente" on public.receitas_ingredientes
  for select to anon using (
    exists (
      select 1 from public.receitas_pacientes rp
      join public.pacientes p on p.id = rp.id_paciente
      where rp.id_receita = receitas_ingredientes.id_receita
    )
  );
